"use client";
import { useId, useMemo, useState } from "react";
import { Button } from "@/app/components/algocore-ui";
import type { Locale } from "@/app/lib/paper3/catalog";
import { flynnScenarios, flynnTrace, riscCiscTrace, virtualMachineTrace, vmInitialState, vmScenarios, vmTransition, vmUsage, type HardwareScaleKind, type VmAction, type VmState } from "@/app/lib/paper3/hardware-scale-models";
import { StateControls, StateExplanation, StateHeading, StateTable } from "./Section15VisualPrimitives";
import { StateDigest } from "./ScaleVisualPrimitives";
import styles from "./ScaleWorkbench.module.css";

function RiscLab({locale}:{readonly locale:Locale}) {
  const id=useId(),[profile,setProfile]=useState<"risc"|"cisc">("risc"),[index,setIndex]=useState(0);const trace=useMemo(()=>riscCiscTrace("add-memory",profile),[profile]),step=trace.steps[index],state=step.after;
  return <div className={styles.workbench} data-hardware-scale-workbench="risc-cisc" data-profile={profile} data-step-id={step.id}>
    <div className={styles.setup}><div className={styles.field}><label htmlFor={id}>{locale==="vi"?"Mô hình tập lệnh":"Instruction profile"}</label><select id={id} data-risc-profile value={profile} onChange={e=>{setProfile(e.target.value as "risc"|"cisc");setIndex(0);}}><option value="risc">RISC · load/store</option><option value="cisc">CISC · ADDMEM</option></select></div></div>
    <StateControls steps={trace.steps} index={index} onChange={setIndex} locale={locale}/><div className={styles.body}><StateHeading step={step} index={index} count={trace.steps.length} locale={locale}/>
      <p className={styles.note}>{locale==="vi"?"Cùng nhiệm vụ Z=X+Y. Đây là hai tập lệnh minh họa; số bước và số lệnh không phải số chu kỳ hay kết luận tốc độ cho mọi CPU.":"Same task: Z=X+Y. These are symbolic instruction profiles; step and instruction counts are not clock counts or universal speed claims."}</p>
      <div className={styles.expression}>Z ← X + Y = 7 + 5</div>
      <div className={styles.grid}><section className={styles.card} data-active={state.activePath.includes("memory")}><h4>{locale==="vi"?"Bộ nhớ":"Memory"}</h4>{Object.entries(state.memory).map(([name,value])=><p className={styles.mono} data-memory={name} data-value={value} key={name}>{name} = {value}</p>)}</section><section className={styles.card} data-active={state.activePath.includes(profile==="risc"?"registers":"internal")}><h4>{profile==="risc"?locale==="vi"?"Thanh ghi":"Registers":locale==="vi"?"Toán hạng nội bộ":"Internal operands"}</h4>{profile==="risc"?Object.entries(state.registers).map(([name,value])=><p className={styles.mono} data-risc-register={name} data-value={value??"empty"} key={name}>{name} = {value??"—"}</p>):<p className={styles.mono} data-internal-operands>{state.operands?.join(" + ")??"—"}</p>}</section></div>
      <p className={styles.connection} data-active-path>{state.activePath.length?state.activePath.map(part=>({memory:locale==="vi"?"Bộ nhớ":"Memory",registers:locale==="vi"?"Thanh ghi":"Registers",internal:locale==="vi"?"Nội bộ":"Internal",alu:"ALU"}[part])).join(" → "):locale==="vi"?"Chưa chuyển dữ liệu":"No data transfer yet"}</p>
      <section className={styles.card} data-active={state.activePath.includes("alu")}><h4>ALU</h4><p className={styles.mono}>{profile==="risc"?state.registers.R3??"—":state.internalResult??"—"}</p></section>
      <div className={styles.facts}><span>{locale==="vi"?"Số lệnh trong chương trình":"Program instruction count"}: <strong data-instruction-count>{trace.instructions.length}</strong></span><span>{locale==="vi"?"Không gán số nhịp":"No clock counts assigned"}</span></div>
      <div className={styles.stack}>{trace.instructions.map((instruction,position)=><div className={styles.layer} key={instruction} data-program-instruction={position} data-active={state.activeInstruction===position}><span className={styles.mono}>{instruction}</span>{state.activeInstruction===position&&<span> · {locale==="vi"?"Đang xét":"Active"}</span>}</div>)}</div>
      <StateExplanation step={step} locale={locale}/></div><StateTable steps={trace.steps} selectedId={step.id} locale={locale} before={s=><StateDigest state={s.before} locale={locale}/>} after={s=><StateDigest state={s.after} locale={locale}/>}/>
  </div>;
}
function FlynnLab({locale}:{readonly locale:Locale}) {
  const id=useId(),[scenario,setScenario]=useState("sisd"),[index,setIndex]=useState(0);const trace=useMemo(()=>flynnTrace(scenario),[scenario]),step=trace.steps[index],state=step.after,mpp=scenario==="mpp-sum";
  return <div className={styles.workbench} data-hardware-scale-workbench="flynn-parallelism" data-flynn-scenario={scenario} data-step-id={step.id}><div className={styles.setup}><div className={styles.field}><label htmlFor={id}>{locale==="vi"?"Cấu trúc luồng":"Stream architecture"}</label><select id={id} data-flynn-select value={scenario} onChange={e=>{setScenario(e.target.value);setIndex(0);}}>{flynnScenarios.map(item=><option key={item.id} value={item.id}>{item.label[locale]}</option>)}</select></div></div><StateControls steps={trace.steps} index={index} onChange={setIndex} locale={locale}/><div className={styles.body}><StateHeading step={step} index={index} count={trace.steps.length} locale={locale}/>
    <p className={styles.note}>{mpp?locale==="vi"?"Bốn nhánh là sơ đồ nhỏ của ý tưởng có thể mở rộng; không khẳng định bốn bộ xử lý tạo thành massively parallel hoặc nhanh gấp bốn.":"Four lanes are a small diagram of a scalable idea; they do not establish massive parallelism or fourfold speed.":locale==="vi"?"Mỗi I là một luồng lệnh độc lập; mỗi D là một luồng dữ liệu. Nhiều nhánh có thể cùng nhận một luồng.":"Each I labels an independent instruction stream; each D labels a data stream. Several lanes can receive the same stream."}</p>
    {!mpp&&<div className={styles.facts}><span>{locale==="vi"?"Luồng lệnh":"Instruction streams"}: <strong data-instruction-streams>{state.instructionStreams}</strong></span><span>{locale==="vi"?"Luồng dữ liệu":"Data streams"}: <strong data-data-streams>{state.dataStreams}</strong></span></div>}
    <div className={styles.grid}>{state.lanes.map((lane,position)=><section className={styles.card} key={lane.id} data-flynn-lane={lane.id} data-output={lane.output??"pending"} data-active={state.dispatched}><h4>{lane.id}</h4><div className={styles.ports}><span>{mpp?locale==="vi"?"Phần dữ liệu":"Partition":`D${state.dataStreams===1?1:position+1}`} → [{lane.input.join(", ")}]</span><span>{mpp?"Σ":`I${state.instructionStreams===1?1:position+1}`} → {lane.operation==="add1"?"+1":lane.operation==="times2"?"×2":lane.operation==="times3"?"×3":"Σ"}</span></div><p className={styles.connection}>↓ {locale==="vi"?"xử lý":"compute"} ↓</p><p className={styles.mono}>{lane.output??"?"}</p>{state.partialsSent&&<p>{locale==="vi"?"Gửi tổng cục bộ tới khâu gộp":"Send partial sum to the combining stage"} →</p>}</section>)}</div>
    {mpp&&<div className={styles.expression} data-mpp-total>{state.lanes.map(lane=>lane.output??"?").join(" + ")} = {state.combined??"?"}</div>}{state.classificationVisible&&<p className={styles.feedback} data-flynn-classification>{scenario.toUpperCase()} · {trace.label[locale]}</p>}
    <StateExplanation step={step} locale={locale}/></div><StateTable steps={trace.steps} selectedId={step.id} locale={locale} before={s=><StateDigest state={s.before} locale={locale}/>} after={s=><StateDigest state={s.after} locale={locale}/>}/></div>;
}
function Resources({state,locale}:{readonly state:VmState;readonly locale:Locale}) {
  const usage=vmUsage(state);return <div data-vm-resources><div className={styles.memory} aria-hidden="true"><span data-part="reserve" style={{width:`${state.reserveGiB/state.capacityGiB*100}%`}}/>{state.guests.map(guest=><span key={guest.id} data-part={guest.id} style={{width:`${guest.ramGiB/state.capacityGiB*100}%`}}/>)}<span data-part="free" style={{width:`${usage.freeGiB/state.capacityGiB*100}%`}}/></div><div className={styles.facts}><span>{locale==="vi"?"Dự phòng":"Reserve"}: {state.reserveGiB} GiB</span><span>{locale==="vi"?"Đã giữ chỗ":"Reserved"}: <b data-vm-used>{usage.usedGiB}</b>/{state.capacityGiB} GiB</span><span>{locale==="vi"?"Còn trống":"Free"}: <b data-vm-free>{usage.freeGiB}</b> GiB</span></div><div className={styles.grid}>{state.guests.map(guest=><div key={guest.id} className={styles.card} data-vm-guest={guest.id} data-status={guest.status} data-ram={guest.ramGiB}><h4>VM {guest.id}</h4><p>{guest.ramGiB} GiB · {guest.status==="running"?locale==="vi"?"Đang chạy":"Running":locale==="vi"?"Đã dừng":"Stopped"}</p></div>)}</div></div>;
}
function VmLifecycle({locale}:{readonly locale:Locale}) {
  const id=useId(),[state,setState]=useState(vmInitialState),[type,setType]=useState<VmAction["type"]>("create"),[vm,setVm]=useState("C"),[ram,setRam]=useState(2),[result,setResult]=useState<ReturnType<typeof vmTransition>|null>(null);
  return <section className={styles.lab} data-vm-lifecycle><h4>{locale==="vi"?"Tự quản lý máy khách":"Manage the guests yourself"}</h4><p>{locale==="vi"?"Quy ước: máy mới bắt đầu ở trạng thái dừng. Dừng vẫn giữ RAM; chỉ đổi RAM khi đã dừng. Không overcommit và không trùng ID.":"Policy: new guests begin stopped. Stopping retains RAM; resize only while stopped. No overcommit or duplicate IDs."}</p><Resources state={state} locale={locale}/><div className={styles.form}><div className={styles.field}><label htmlFor={`${id}-action`}>{locale==="vi"?"Thao tác":"Action"}</label><select id={`${id}-action`} data-vm-action value={type} onChange={e=>{setType(e.target.value as VmAction["type"]);setResult(null);}}>{(["create","start","stop","resize"] as const).map(action=><option key={action} value={action}>{({create:locale==="vi"?"Tạo":"Create",start:locale==="vi"?"Chạy":"Start",stop:locale==="vi"?"Dừng":"Stop",resize:locale==="vi"?"Đổi RAM":"Resize RAM"})[action]}</option>)}</select></div><div className={styles.field}><label htmlFor={`${id}-guest`}>VM</label><select id={`${id}-guest`} data-vm-target value={vm} onChange={e=>{setVm(e.target.value);setResult(null);}}>{["A","B","C"].map(guest=><option key={guest}>{guest}</option>)}</select></div>{(type==="create"||type==="resize")&&<div className={styles.field}><label htmlFor={`${id}-ram`}>{locale==="vi"?"RAM mục tiêu (GiB)":"Target RAM (GiB)"}</label><select id={`${id}-ram`} data-vm-ram value={ram} onChange={e=>{setRam(Number(e.target.value));setResult(null);}}>{[2,4,6,10].map(value=><option key={value}>{value}</option>)}</select></div>}</div><div className={styles.actions}><Button data-vm-apply onClick={()=>{const action:VmAction=type==="create"||type==="resize"?{type,vm,ramGiB:ram}:{type,vm};const next=vmTransition(state,action);setState(next.after);setResult(next);}}>{locale==="vi"?"Áp dụng":"Apply action"}</Button><Button variant="secondary" data-vm-lifecycle-reset onClick={()=>{setState(vmInitialState());setType("create");setVm("C");setRam(2);setResult(null);}}>{locale==="vi"?"Đặt lại phòng thực hành":"Reset lab"}</Button></div><div className={styles.feedback} role="status" data-vm-action-result={result?result.allowed?"allowed":"denied":"unanswered"} data-valid={result?.allowed}>{result?result.feedback[locale]:locale==="vi"?"Chọn thao tác và áp dụng để kiểm tra ràng buộc.":"Choose and apply an action to check the constraints."}</div></section>;
}
function VmLab({locale}:{readonly locale:Locale}) {
  const id=useId(),[scenario,setScenario]=useState("guest-request"),[index,setIndex]=useState(0);const trace=useMemo(()=>virtualMachineTrace(scenario),[scenario]),step=trace.steps[index],state=step.after;
  const layers=[{id:"application",label:locale==="vi"?"Ứng dụng máy khách":"Guest application"},{id:"guest-os",label:locale==="vi"?"Hệ điều hành máy khách":"Guest OS"},{id:"hypervisor",label:locale==="vi"?"Lớp ảo hóa":"Virtualisation layer"},{id:"host-os",label:locale==="vi"?"Hệ điều hành máy chủ":"Host OS"},{id:"physical-resource",label:locale==="vi"?"Tài nguyên vật lý":"Physical resources"}];
  return <div className={styles.workbench} data-hardware-scale-workbench="virtual-machines" data-vm-scenario={scenario} data-step-id={step.id}><div className={styles.setup}><div className={styles.field}><label htmlFor={id}>{locale==="vi"?"Tình huống hosted VM":"Hosted VM scenario"}</label><select id={id} data-vm-scenario-select value={scenario} onChange={e=>{setScenario(e.target.value);setIndex(0);}}>{vmScenarios.map(item=><option key={item.id} value={item.id}>{item.label[locale]}</option>)}</select></div></div><StateControls steps={trace.steps} index={index} onChange={setIndex} locale={locale}/><div className={styles.body}><StateHeading step={step} index={index} count={trace.steps.length} locale={locale}/><p className={styles.note}>{locale==="vi"?"Mô hình hosted và chính sách tài nguyên được khai báo, không đại diện mọi hypervisor. Mẫu dự tính dung lượng bắt đầu lại từ A4+B4+dự phòng4; phòng thực hành bên dưới có trạng thái riêng.":"This is one declared hosted architecture and resource policy, not every hypervisor. Capacity estimates restart from A4+B4+reserve4; the interactive lab below has separate state."}</p><div className={styles.stack}>{layers.map(layer=><div className={styles.layer} key={layer.id} data-vm-layer={layer.id} data-active={state.activeLayer===layer.id}>{layer.label}{state.activeLayer===layer.id&&<strong> · {locale==="vi"?"Đang xử lý":"Active"}</strong>}</div>)}</div><Resources state={state.machine} locale={locale}/>{state.requestedUsedGiB!==null&&<p className={styles.feedback} data-vm-requested>{locale==="vi"?"Tổng yêu cầu":"Requested total"}: {state.requestedUsedGiB} GiB · {state.decision}</p>}<StateExplanation step={step} locale={locale}/><VmLifecycle locale={locale}/></div><StateTable steps={trace.steps} selectedId={step.id} locale={locale} before={s=><StateDigest state={s.before} locale={locale}/>} after={s=><StateDigest state={s.after} locale={locale}/>}/></div>;
}
export function HardwareScaleWorkbench({kind,locale}:{readonly kind:HardwareScaleKind;readonly locale:Locale}) {return kind==="risc-cisc"?<RiscLab locale={locale}/>:kind==="flynn-parallelism"?<FlynnLab locale={locale}/>:<VmLab locale={locale}/>;}
