"use client";
import { Fragment, useId, useMemo, useState } from "react";
import { Button } from "@/app/components/algocore-ui";
import type { Locale } from "@/app/lib/paper3/catalog";
import { adderTrace, booleanCircuit, flipFlopTrace, flipTransition, karnaughExamples, karnaughSolution, karnaughTrace, simplificationAttempt, simplificationChoices, simplificationExamples, simplificationTrace, validateKarnaughGroup, type AdderKind, type Bit, type FlipState, type LogicScaleKind } from "@/app/lib/paper3/logic-scale-models";
import { StateControls, StateExplanation, StateHeading, StateTable } from "./Section15VisualPrimitives";
import { BitControls, GateCard, ScaleGateSymbol, StateDigest, TruthTable } from "./ScaleVisualPrimitives";
import styles from "./ScaleWorkbench.module.css";

function AdderLab({locale}:{readonly locale:Locale}) {
  const id=useId(),[mode,setMode]=useState<AdderKind>("half"),[vector,setVector]=useState("11"),[index,setIndex]=useState(0);const trace=useMemo(()=>adderTrace(mode,vector),[mode,vector]),step=trace.steps[index],state=step.after;
  const nodes=[{id:"p",operation:"XOR",signals:["A","B"]},{id:"c1",operation:"AND",signals:["A","B"]},...(mode==="full"?[{id:"sum",operation:"XOR",signals:["p","Cin"]},{id:"c2",operation:"AND",signals:["p","Cin"]},{id:"carry",operation:"OR",signals:["c1","c2"]}]:[])];const known={...state.inputs,...state.known};
  return <div className={styles.workbench} data-logic-scale-workbench="adders" data-adder-kind={mode} data-input-row={vector} data-step-id={step.id}><div className={styles.setup}><div className={styles.field}><label htmlFor={id}>{locale==="vi"?"Loại bộ cộng":"Adder type"}</label><select id={id} data-adder-select value={mode} onChange={e=>{const next=e.target.value as AdderKind;setMode(next);setVector(next==="half"?"11":"101");setIndex(0);}}><option value="half">{locale==="vi"?"Half adder · không carry-in":"Half adder · no carry-in"}</option><option value="full">{locale==="vi"?"Full adder · có carry-in":"Full adder · with carry-in"}</option></select></div><BitControls names={mode==="half"?["A","B"]:["A","B","Cin"]} vector={vector} onChange={setVector} locale={locale}/></div><StateControls steps={trace.steps} index={index} onChange={setIndex} locale={locale}/><div className={styles.body}><StateHeading step={step} index={index} count={trace.steps.length} locale={locale}/><p className={styles.note}>{locale==="vi"?"Tín hiệu có tên nối đầu ra với đầu vào cổng sau. ? nghĩa chưa tính ở bước này; đây là thứ tự học, không phải mô phỏng độ trễ cổng.":"Named signals connect outputs to later gate inputs. ? means not yet evaluated at this step; this is a teaching order, not gate-delay simulation."}</p><div className={styles.grid}>{nodes.map(node=><GateCard key={node.id} id={node.id} operation={node.operation} inputs={node.signals.map(signal=>({signal,value:known[signal]}))} output={state.known[node.id]} active={state.active===node.id} locale={locale}/>)}</div>{mode==="half"&&<p className={styles.connection}>p → S · c1 → C</p>}<div className={styles.facts}><span>S = <b data-adder-sum>{state.known.sum??"?"}</b></span><span>{mode==="half"?"C":"Cout"} = <b data-adder-carry>{state.known.carry??"?"}</b></span></div>{state.verified&&<div className={styles.expression} data-adder-numeric-check>2 × {trace.result.carry} + {trace.result.sum} = {trace.result.total} = {trace.result.A} + {trace.result.B}{mode==="full"?` + ${trace.result.Cin}`:""}</div>}<TruthTable locale={locale} caption={locale==="vi"?"Đủ mọi tổ hợp; chọn hàng để đổi đầu vào.":"All combinations; choose a row to change inputs."} headers={mode==="half"?["AB","S","C","2C+S"]:["ABCin","p","c1","c2","S","Cout","2Cout+S"]} rows={trace.rows.map(row=>[<button className={styles.rowButton} key={row.vector} type="button" data-adder-row={row.vector} aria-pressed={row.vector===vector} onClick={()=>setVector(row.vector)}>{row.vector}</button>,...(mode==="half"?[row.sum,row.carry,row.total]:[row.p,row.c1,row.c2,row.sum,row.carry,row.total])])} current={parseInt(vector,2)}/><StateExplanation step={step} locale={locale}/></div><StateTable steps={trace.steps} selectedId={step.id} locale={locale} before={s=><StateDigest state={s.before} locale={locale}/>} after={s=><StateDigest state={s.after} locale={locale}/>}/></div>;
}

function StorageDiagram({state,locale}:{readonly state:FlipState;readonly locale:Locale}) {
  const sr=state.kind==="sr-nor",unknownLabel=state.status==="indeterminate"?(locale==="vi"?"Không xác định sau khi nhả trạng thái cấm":"Indeterminate after forbidden-state release"):undefined;return <div data-storage-diagram data-q={state.Q??"indeterminate"} data-qbar={state.Qbar??"indeterminate"} data-status={state.status}>
    {sr?<><div className={styles.grid}><GateCard id="Q" operation="NOR" inputs={[{signal:"R",value:state.input2},{signal:"Qbar (feedback)",value:state.Qbar}]} output={state.Q} locale={locale} unknownLabel={unknownLabel}/><GateCard id="Qbar" operation="NOR" inputs={[{signal:"S",value:state.input1},{signal:"Q (feedback)",value:state.Q}]} output={state.Qbar} locale={locale} unknownLabel={unknownLabel}/></div><svg viewBox="0 0 320 150" className={styles.crossCoupled} role="img" aria-label={locale==="vi"?"Hồi tiếp chéo: Q trở lại NOR tạo Qbar, Qbar trở lại NOR tạo Q":"Cross-coupling: Q feeds the Qbar NOR, Qbar feeds the Q NOR"} fill="none"><rect x="20" y="18" width="110" height="42" rx="5"/><rect x="190" y="90" width="110" height="42" rx="5"/><path data-sr-feedback="Q" d="M130 39H158V112H190M180 107L190 112L180 117"/><path data-sr-feedback="Qbar" d="M190 111H174V40H130M140 35L130 40L140 45"/><text x="40" y="46">Q = {state.Q??"?"}</text><text x="205" y="117">Q̅ = {state.Qbar??"?"}</text></svg><p className={styles.mono}>Q = NOT(R OR Qbar)<br/>Qbar = NOT(S OR Q)</p></>:<><div className={styles.grid}><section className={styles.card}><h4>{locale==="vi"?"Đầu vào + Q trước đó":"Inputs + previous Q"}</h4><div className={styles.ports}><span>J={state.input1}</span><span>K={state.input2}</span><span>Qprev={state.previousQ??"?"}</span></div></section><section className={styles.card} data-active={state.activeEdge}><h4>JK · ↑ CLK</h4><p>{state.activeEdge?locale==="vi"?"Có cạnh lên: cập nhật":"Rising edge: update":locale==="vi"?"Không có cạnh lên: giữ":"No rising edge: hold"}</p><p className={styles.mono}>Q = {state.Q??"?"} · Qbar = {state.Qbar??"?"}</p></section></div><p className={styles.connection}>Qprev → {locale==="vi"?"quy tắc JK tại cạnh lên":"JK rule at rising edge"} → Qnext → {locale==="vi"?"giá trị hồi tiếp cho sự kiện sau":"feedback value for the next event"}</p></>}
    <p className={styles.feedback} data-valid={state.status==="known"}>{state.status==="invalid"?locale==="vi"?"S=R=1: hai đầu ra đều0, không phải cặp bù hợp lệ.":"S=R=1: both outputs are0, not a valid complementary pair.":state.status==="indeterminate"?locale==="vi"?"Nhả11 về00: chưa xác định trạng thái nào thắng; cần set/reset để phục hồi.":"Releasing11 to00 leaves the winning state indeterminate; set/reset restores a known state.":locale==="vi"?"Hai đầu ra đang là một cặp bù hợp lệ.":"The outputs form a valid complementary pair."}</p>
  </div>;
}
function StoragePractice({kind,locale}:{readonly kind:"sr-nor"|"jk-edge";readonly locale:Locale}) {
  const [state,setState]=useState(()=>flipFlopTrace(kind).initial),[vector,setVector]=useState("00");return <section className={styles.lab} data-storage-practice><h4>{locale==="vi"?"Thử chuỗi đầu vào của bạn":"Try your own input sequence"}</h4><BitControls names={kind==="sr-nor"?["S","R"]:["J","K"]} vector={vector} onChange={setVector} locale={locale}/><div className={styles.actions}><Button data-storage-apply onClick={()=>setState(previous=>flipTransition(previous,Number(vector[0]) as Bit,Number(vector[1]) as Bit,kind==="jk-edge"))}>{kind==="sr-nor"?locale==="vi"?"Áp dụng S/R":"Apply S/R":locale==="vi"?"Tạo cạnh lên":"Apply rising edge"}</Button>{kind==="jk-edge"&&<Button variant="secondary" data-storage-no-edge onClick={()=>setState(previous=>flipTransition(previous,Number(vector[0]) as Bit,Number(vector[1]) as Bit,false))}>{locale==="vi"?"Đổi đầu vào, không tạo cạnh":"Change inputs, no edge"}</Button>}<Button variant="quiet" data-storage-reset onClick={()=>{setState(flipFlopTrace(kind).initial);setVector("00");}}>{locale==="vi"?"Đặt lại trạng thái":"Reset state"}</Button></div><StorageDiagram state={state} locale={locale}/></section>;
}
function FlipLab({locale}:{readonly locale:Locale}) {
  const id=useId(),[kind,setKind]=useState<"sr-nor"|"jk-edge">("sr-nor"),[index,setIndex]=useState(0);const trace=useMemo(()=>flipFlopTrace(kind),[kind]),step=trace.steps[index];return <div className={styles.workbench} data-logic-scale-workbench="sr-jk-flip-flops" data-storage-kind={kind} data-step-id={step.id}><div className={styles.setup}><div className={styles.field}><label htmlFor={id}>{locale==="vi"?"Quy ước lưu trạng thái":"Storage convention"}</label><select id={id} data-storage-select value={kind} onChange={e=>{setKind(e.target.value as typeof kind);setIndex(0);}}><option value="sr-nor">SR · active-high NOR</option><option value="jk-edge">JK · positive-edge</option></select></div></div><StateControls steps={trace.steps} index={index} onChange={setIndex} locale={locale}/><div className={styles.body}><StateHeading step={step} index={index} count={trace.steps.length} locale={locale}/><p className={styles.note}>{kind==="sr-nor"?locale==="vi"?"SR dùng hai cổng NOR hồi tiếp chéo, tích cực mức cao, không clock. Đây là các trạng thái ổn định hoặc không xác định; không mô phỏng độ trễ.":"SR uses active-high cross-coupled NOR gates without a clock. These are stable or indeterminate states, not a gate-delay simulation.":locale==="vi"?"JK là mô hình chức năng kích tại cạnh lên, gồm Q trước đó; không phải sơ đồ cổng thực hay mô phỏng race-around.":"JK is a rising-edge functional abstraction with previous-Q feedback, not a physical gate layout or race-around simulation."}</p><StorageDiagram state={step.after} locale={locale}/><StateExplanation step={step} locale={locale}/><StoragePractice key={kind} kind={kind} locale={locale}/></div><StateTable steps={trace.steps} selectedId={step.id} locale={locale} before={s=><StateDigest state={s.before} locale={locale}/>} after={s=><StateDigest state={s.after} locale={locale}/>}/></div>;
}

function ExpressionCircuit({source,vector,locale}:{readonly source:string;readonly vector:string;readonly locale:Locale}) {
  const circuit=booleanCircuit(source,{A:Number(vector[0]) as Bit,B:Number(vector[1]) as Bit});return <div data-expression-circuit><div className={styles.grid}>{circuit.nodes.map(node=><GateCard key={node.id} id={node.id} operation={node.operation} inputs={node.inputs} output={node.output} locale={locale}/>)}</div>{circuit.nodes.length===0&&<p className={styles.connection}>{circuit.output.signal} → Y</p>}<p className={styles.expression} data-expression-output>Y = {circuit.output.value} · {locale==="vi"?"Từ tín hiệu":"From signal"} {circuit.output.signal}</p></div>;
}
function SimplificationLab({locale}:{readonly locale:Locale}) {
  const id=useId(),[scenario,setScenario]=useState("factor-complements"),[index,setIndex]=useState(0),[vector,setVector]=useState("00"),[choice,setChoice]=useState("reviewed-law"),[attempt,setAttempt]=useState<ReturnType<typeof simplificationAttempt>|null>(null),[candidate,setCandidate]=useState("NOT A AND NOT B");
  const trace=useMemo(()=>simplificationTrace(scenario),[scenario]),step=trace.steps[index],choices=simplificationChoices(scenario,index),selected=choices.find(item=>item.id===choice)!;
  return <div className={styles.workbench} data-logic-scale-workbench="boolean-simplification" data-simplification-scenario={scenario} data-step-id={step.id}><div className={styles.setup}><div className={styles.field}><label htmlFor={id}>{locale==="vi"?"Chuỗi biến đổi":"Transformation chain"}</label><select id={id} data-simplification-select value={scenario} onChange={e=>{setScenario(e.target.value);setIndex(0);setChoice("reviewed-law");setAttempt(null);}}>{simplificationExamples.map(example=><option key={example.id} value={example.id}>{example.label[locale]}</option>)}</select></div><BitControls names={["A","B"]} vector={vector} onChange={setVector} locale={locale}/></div><StateControls steps={trace.steps} index={index} onChange={next=>{setIndex(next);setAttempt(null);}} locale={locale}/><div className={styles.body}><StateHeading step={step} index={index} count={trace.steps.length} locale={locale}/><p className={styles.note}>{locale==="vi"?"Mọi hàng chân trị phải trùng; một đầu vào đúng chưa đủ. Mạch bên dưới được dựng từ chính biểu thức ở bước đang chọn.":"Every truth row must agree; one matching input is insufficient. The circuit below is built from the expression at the selected step."}</p><div className={styles.expression} data-current-expression>{step.after.expression}</div><ExpressionCircuit source={step.after.expression} vector={vector} locale={locale}/><TruthTable locale={locale} caption={locale==="vi"?"So biểu thức gốc với bước hiện tại":"Original versus current expression"} headers={["AB",locale==="vi"?"Gốc":"Original",locale==="vi"?"Hiện tại":"Current"]} rows={step.after.rows.map(row=>[row.bits,row.original,row.candidate])} current={parseInt(vector,2)}/><StateExplanation step={step} locale={locale}/>
    <section className={styles.lab} data-law-practice><h4>{locale==="vi"?"Đề xuất luật cho bước tiếp":"Propose the next law"}</h4><div className={styles.field}><label htmlFor={`${id}-law`}>{locale==="vi"?"Luật / đề xuất":"Law / proposal"}</label><select id={`${id}-law`} data-law-choice value={choice} onChange={e=>{setChoice(e.target.value);setAttempt(null);}}>{choices.map(item=><option key={item.id} value={item.id}>{item.label[locale]}</option>)}</select></div><p className={styles.expression} data-law-proposal>{selected.expression}</p><Button data-law-apply onClick={()=>{const result=simplificationAttempt(step.after.expression,selected.expression,trace.variables);setAttempt(result);if(result.equivalent)setIndex(current=>Math.min(current+1,trace.steps.length-1));}}>{locale==="vi"?"Kiểm tra và áp dụng":"Check and apply"}</Button>{attempt&&<p className={styles.feedback} role="status" data-law-feedback data-valid={attempt.equivalent}>{attempt.feedback[locale]}</p>}</section>
    <section className={styles.lab} data-equivalence-practice><h4>{locale==="vi"?"Kiểm tra lỗi De Morgan":"Test a De Morgan mistake"}</h4><p className={styles.mono}>NOT (A AND B)</p><div className={styles.field}><label htmlFor={`${id}-candidate`}>{locale==="vi"?"Biểu thức đề xuất (A, B)":"Candidate expression (A, B)"}</label><input id={`${id}-candidate`} data-equivalence-input value={candidate} maxLength={256} onChange={e=>setCandidate(e.target.value)}/></div><EquivalenceCheck candidate={candidate} locale={locale}/></section>
  </div><StateTable steps={trace.steps} selectedId={step.id} locale={locale} before={s=><StateDigest state={s.before} locale={locale}/>} after={s=><StateDigest state={s.after} locale={locale}/>}/></div>;
}
function EquivalenceCheck({candidate,locale}:{readonly candidate:string;readonly locale:Locale}) {
  const [checked,setChecked]=useState<string|null>(null);const result=checked===candidate?simplificationAttempt("NOT (A AND B)",candidate,["A","B"]):null;return <><div className={styles.actions}><Button data-equivalence-check onClick={()=>setChecked(candidate)}>{locale==="vi"?"So mọi hàng chân trị":"Compare all truth rows"}</Button></div>{result&&<><p role="status" className={styles.feedback} data-equivalence-feedback data-valid={result.equivalent}>{result.feedback[locale]}</p>{result.validSyntax&&<TruthTable locale={locale} caption={locale==="vi"?"Mọi hàng, gồm phản ví dụ nếu có":"Every row, including any counterexample"} headers={["AB",locale==="vi"?"Gốc":"Original",locale==="vi"?"Đề xuất":"Candidate"]} rows={result.rows.map(row=>[row.bits,row.original,row.candidate])}/>}</>}</>;
}

function KmapLab({locale}:{readonly locale:Locale}) {
  const id=useId(),[exampleId,setExampleId]=useState("two-input-nand"),[index,setIndex]=useState(0),[selection,setSelection]=useState<number[]>([]),[groups,setGroups]=useState<number[][]>([]),[feedback,setFeedback]=useState<ReturnType<typeof validateKarnaughGroup>|null>(null);
  const trace=useMemo(()=>karnaughTrace(exampleId),[exampleId]),step=trace.steps[index],map=trace.map,solution=karnaughSolution(exampleId,groups);
  const renderMap=(chosen:readonly number[],covered:readonly number[],interactive:boolean,activeGroups:readonly (readonly number[])[])=><div className={styles.scroll} role="region" tabIndex={0} aria-label={locale==="vi"?"Bản đồ Karnaugh theo mã Gray":"Karnaugh map in Gray order"}><div className={styles.kmap} style={{gridTemplateColumns:`minmax(25px,.65fr) repeat(${map.columnLabels.length},minmax(44px,1fr))`}} data-kmap-grid={interactive?"practice":"guided"}><div className={styles.kmapAxis}>{map.rowVariables.join("")} ↓<br/>{map.columnVariables.join("")} →</div>{map.columnLabels.map(label=><div className={styles.kmapAxis} key={label}>{label}</div>)}{map.rowLabels.map((row,rowIndex)=><Fragment key={row}><div className={styles.kmapAxis}>{row}</div>{map.columnLabels.map((column,columnIndex)=>{const cell=map.cells.find(item=>item.row===rowIndex&&item.column===columnIndex)!;const memberships=activeGroups.flatMap((group,i)=>group.includes(cell.id)?[`G${i+1}`]:[]);return interactive?<button key={column} type="button" className={styles.cell} data-kmap-cell={cell.id} data-group-ids={memberships.join(" ")} data-covered={covered.includes(cell.id)} aria-pressed={chosen.includes(cell.id)} aria-label={`m${cell.id}, ${cell.bits}, ${cell.value}${covered.includes(cell.id)?locale==="vi"?", đã phủ":", covered":""}`} onClick={()=>{setSelection(current=>current.includes(cell.id)?current.filter(value=>value!==cell.id):[...current,cell.id]);setFeedback(null);}}><small>m{cell.id}</small><b>{cell.value}</b><small>{chosen.includes(cell.id)?"✓ ":""}{memberships.join(" ")}</small></button>:<div className={styles.cell} data-guided-minterm={cell.id} data-group-ids={memberships.join(" ")} data-covered={covered.includes(cell.id)} key={column}><small>m{cell.id}</small><b>{cell.value}</b><small>{chosen.includes(cell.id)?"✓ ":""}{memberships.join(" ")}</small></div>;})}</Fragment>)}</div></div>;
  return <div className={styles.workbench} data-logic-scale-workbench="karnaugh-map" data-kmap-example={exampleId} data-step-id={step.id}><div className={styles.setup}><div className={styles.field}><label htmlFor={id}>{locale==="vi"?"Bản đồ":"Map example"}</label><select id={id} data-kmap-select value={exampleId} onChange={e=>{setExampleId(e.target.value);setIndex(0);setSelection([]);setGroups([]);setFeedback(null);}}>{karnaughExamples.map(example=><option key={example.id} value={example.id}>{example.label[locale]}</option>)}</select></div></div><StateControls steps={trace.steps} index={index} onChange={setIndex} locale={locale}/><div className={styles.body}><StateHeading step={step} index={index} count={trace.steps.length} locale={locale}/><p className={styles.note}>{locale==="vi"?"Nhãn hàng/cột theo Gray; chỉ nhóm ô1, kích thước lũy thừa hai. Cạnh đối diện nối nhau, đường chéo không liền kề. Một ô có thể thuộc nhiều nhóm.":"Axes use Gray order. Group only1s in power-of-two rectangles. Opposite edges join; diagonal cells are not adjacent. A cell may belong to several groups."}</p><p className={styles.connection}>← {locale==="vi"?"Cạnh trái nối cạnh phải · cạnh trên nối cạnh dưới":"Left joins right · top joins bottom"} →</p>{renderMap(step.after.selected,step.after.groups.flat(),false,step.after.groups)}{step.after.term&&<p className={styles.expression} data-guided-term>{step.after.term}</p>}<div className={styles.groups}>{step.after.groups.map((group,position)=><div key={position}>G{position+1}: [{group.join(", ")}] → {validateKarnaughGroup(exampleId,group).term}</div>)}</div><StateExplanation step={step} locale={locale}/>
    <section className={styles.lab} data-kmap-practice><h4>{locale==="vi"?"Tự chọn và ghép nhóm":"Build your own groups"}</h4>{renderMap(selection,solution.covered,true,groups)}<p>{locale==="vi"?"Đang chọn":"Selected"}: <span data-kmap-selection>{selection.length?selection.map(value=>`m${value}`).join(", "):"—"}</span></p><div className={styles.actions}><Button data-kmap-add-group onClick={()=>{const result=validateKarnaughGroup(exampleId,selection);setFeedback(result);if(result.valid){setGroups(current=>[...current,[...selection]]);setSelection([]);}}}>{locale==="vi"?"Kiểm tra và thêm nhóm":"Validate and add group"}</Button><Button variant="secondary" data-kmap-clear-selection onClick={()=>{setSelection([]);setFeedback(null);}}>{locale==="vi"?"Bỏ chọn ô":"Clear selection"}</Button><Button variant="quiet" data-kmap-reset onClick={()=>{setSelection([]);setGroups([]);setFeedback(null);}}>{locale==="vi"?"Đặt lại nhóm":"Reset groups"}</Button></div>{feedback&&<p className={styles.feedback} role="status" data-kmap-feedback data-valid={feedback.valid} data-reason={feedback.reason}>{feedback.feedback[locale]}</p>}<div className={styles.groups}>{groups.map((group,position)=>{const checked=validateKarnaughGroup(exampleId,group);return <div key={position} data-user-group={position}>G{position+1}: [{group.join(", ")}] → <strong>{checked.term}</strong>{(checked.wrapsRows||checked.wrapsColumns)&&<p>{locale==="vi"?"Nối qua cạnh đối diện":"Wraps across opposite edges"}</p>}<Button variant="quiet" data-remove-group={position} onClick={()=>setGroups(current=>current.filter((_,i)=>i!==position))}>{locale==="vi"?"Xóa nhóm":"Remove group"}</Button></div>;})}</div><div className={styles.expression} data-kmap-expression>Y = {solution.expression}</div><p className={styles.feedback} data-kmap-complete={solution.complete}>{solution.complete?locale==="vi"?"Đã phủ mọi ô1; toàn bộ bảng chân trị tương đương.":"Every1 cell is covered; the full truth table is equivalent.":locale==="vi"?`Chưa hoàn tất; ô1 chưa phủ: ${solution.uncovered.map(value=>`m${value}`).join(", ")||"—"}. Nhóm hợp lệ chưa đồng nghĩa lời giải hoàn tất.`:`Not complete; uncovered1 cells: ${solution.uncovered.map(value=>`m${value}`).join(", ")||"—"}. A valid group is not a completed solution.`}</p><TruthTable locale={locale} caption={locale==="vi"?"Kiểm chứng SOP do bạn tạo với hàm gốc":"Verify your SOP against the original function"} headers={[map.variables.join(""),locale==="vi"?"Gốc":"Original","SOP"]} rows={solution.rows.map(row=>[row.bits,row.original,row.candidate])}/></section>
  </div><StateTable steps={trace.steps} selectedId={step.id} locale={locale} before={s=><StateDigest state={s.before} locale={locale}/>} after={s=><StateDigest state={s.after} locale={locale}/>}/></div>;
}
export function LogicScaleWorkbench({kind,locale}:{readonly kind:LogicScaleKind;readonly locale:Locale}) {return kind==="adders"?<AdderLab locale={locale}/>:kind==="sr-jk-flip-flops"?<FlipLab locale={locale}/>:kind==="boolean-simplification"?<SimplificationLab locale={locale}/>:<KmapLab locale={locale}/>;}
