"use client";
import type { ReactNode } from "react";
import type { Locale } from "@/app/lib/paper3/catalog";
import type { Bit } from "@/app/lib/paper3/logic-scale-models";
import styles from "./ScaleWorkbench.module.css";

export function BitControls({ names, vector, onChange, locale }: { readonly names: readonly string[]; readonly vector: string; readonly onChange: (vector: string) => void; readonly locale: Locale }) {
  return <fieldset className={styles.bits}><legend>{locale === "vi" ? "Đổi bit đầu vào" : "Toggle input bits"}</legend>{names.map((name,index) => <button key={name} type="button" data-scale-bit={name} aria-pressed={vector[index] === "1"} aria-label={`${name} = ${vector[index]}; ${locale === "vi" ? "đổi bit" : "toggle bit"}`} onClick={() => onChange(vector.slice(0,index)+(vector[index] === "1" ? "0" : "1")+vector.slice(index+1))}>{name} = {vector[index]}</button>)}</fieldset>;
}
export function ScaleGateSymbol({ operation, inputCount }: { readonly operation: string; readonly inputCount: number }) {
  const count=operation==="NOT"?1:inputCount, ys=count===1?[24]:Array.from({length:count},(_,i)=>11+i*26/(count-1));
  return <svg viewBox="0 0 84 48" aria-hidden="true" data-gate-symbol={operation} data-input-count={count} fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinejoin="round">
    {ys.map((y,index)=>{const t=(y-5)/38;return <line key={index} data-gate-input-wire={index+1} x1="2" y1={y} x2={operation==="NOT"?17:operation==="AND"?18:14+30*t*(1-t)} y2={y}/>;})}
    {operation==="NOT"?<><path d="M17 5L53 24L17 43Z"/><circle cx="58" cy="24" r="5"/><path d="M63 24H82"/></>:operation==="AND"?<><path d="M18 5H36C67 5 67 43 36 43H18Z"/><path d="M60 24H82"/></>:<><path d="M14 5Q45 3 65 24Q45 45 14 43Q29 24 14 5Z"/>{operation==="NOR"?<><circle cx="70" cy="24" r="5"/><path d="M75 24H82"/></>:<path d="M65 24H82"/>}{operation==="XOR"&&<path d="M8 5Q23 24 8 43"/>}</>}
  </svg>;
}
export function GateCard({ id, operation, inputs, output, active, locale, unknownLabel }: { readonly id:string; readonly operation:string; readonly inputs:readonly {readonly signal:string;readonly value:Bit|null}[];readonly output:Bit|null;readonly active?:boolean;readonly locale:Locale;readonly unknownLabel?:string }) {
  return <div className={styles.card} data-scale-gate={id} data-active={Boolean(active)} data-output={output??"unknown"}><div className={styles.gateTitle}><ScaleGateSymbol operation={operation} inputCount={inputs.length}/><strong>{id} · {operation}</strong></div><div className={styles.ports}>{inputs.map((input,index)=><span key={`${input.signal}-${index}`}>{input.signal} → {input.value??"?"}</span>)}</div><div className={styles.gateOutput}><span>{active?locale==="vi"?"Vừa tính":"Just evaluated":locale==="vi"?"Đầu ra":"Output"}: {id}</span><strong>{output??"?"}</strong></div>{output===null&&<p className={styles.muted} data-unknown-reason={unknownLabel?"indeterminate":"pending"}>{unknownLabel??(locale==="vi"?"Chưa tính ở bước này":"Not evaluated at this step")}</p>}</div>;
}
export function TruthTable({ rows, headers, caption, locale, current }: { readonly rows:readonly (readonly ReactNode[])[];readonly headers:readonly string[];readonly caption:string;readonly locale:Locale;readonly current?:number }) {
  return <div className={styles.scroll} role="region" tabIndex={0} aria-label={locale==="vi"?"Bảng dữ liệu minh họa":"Visual data table"}><table><caption>{caption}</caption><thead><tr>{headers.map((header,index)=><th scope="col" key={`${header}-${index}`}>{header}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index} data-current={index===current}>{row.map((value,i)=>i===0?<th scope="row" key={i}>{value}</th>:<td key={i}>{value}</td>)}</tr>)}</tbody></table></div>;
}
const labels:Record<string,[string,string]>={memory:["Memory","Bộ nhớ"],registers:["Registers","Thanh ghi"],operands:["Internal operands","Toán hạng nội bộ"],internalResult:["Internal result","Kết quả nội bộ"],activeInstruction:["Instruction index (0-based)","Chỉ số lệnh (từ0)"],activePath:["Active path","Đường đang xét"],instructionStreams:["Instruction streams","Luồng lệnh"],dataStreams:["Data streams","Luồng dữ liệu"],lanes:["Processing lanes","Nhánh xử lý"],input:["Input","Đầu vào"],output:["Output","Đầu ra"],combined:["Combined result","Kết quả gộp"],dispatched:["Dispatched","Đã phân phối"],partialsSent:["Partials sent","Đã gửi phần kết quả"],classificationVisible:["Classification shown","Hiện phân loại"],machine:["Host and guests","Máy chủ và máy khách"],guests:["Guests","Máy khách"],capacityGiB:["Capacity GiB","Dung lượng GiB"],reserveGiB:["Reserve GiB","Dự phòng GiB"],ramGiB:["RAM GiB","RAM GiB"],hostRunning:["Host running","Máy chủ đang chạy"],activeLayer:["Active layer","Lớp đang xét"],decision:["Decision","Quyết định"],requestedUsedGiB:["Requested total GiB","Tổng yêu cầu GiB"],completed:["Completed","Hoàn tất"],known:["Evaluated signals","Tín hiệu đã tính"],inputs:["Inputs","Đầu vào"],verified:["Verified","Đã kiểm chứng"],active:["Active signal","Tín hiệu đang xét"],previousQ:["Previous Q","Q trước đó"],activeEdge:["Rising edge","Cạnh lên"],expression:["Expression","Biểu thức"],selected:["Selected minterms","Minterm được chọn"],groups:["Groups","Các nhóm"],term:["Derived term","Tích suy ra"],status:["Status","Trạng thái"]};
export function StateDigest({state,locale}:{readonly state:unknown;readonly locale:Locale}) {
  const flatten=(value:unknown,path:string[]=[]):{path:string;value:string}[]=>{if(value===null||typeof value!=="object")return[{path:path.join(" / "),value:value===null?locale==="vi"?"chưa có":"not available":typeof value==="boolean"?value?locale==="vi"?"có":"yes":locale==="vi"?"không":"no":String(value)}];if("en"in value&&"vi"in value)return[{path:path.join(" / "),value:String((value as Record<string,unknown>)[locale])}];if(Array.isArray(value)&&value.length===0)return[{path:path.join(" / "),value:"—"}];return Object.entries(value).flatMap(([key,item])=>flatten(item,[...path,labels[key]?.[locale==="vi"?1:0]??key]));};
  return <dl>{flatten(state).map((item,index)=><div key={index}><dt><strong>{item.path}</strong></dt><dd>{item.value}</dd></div>)}</dl>;
}
