from __future__ import annotations


PATTERNS = ["MAIN_FLOW", "OUTPUT_FORMAT", "EVIDENCE_RUN"]


def bi(vi, en):
    return {"vi": vi, "en": en}


SPECS = {
    "MAIN_FLOW": {
        "pre": "The source fixes existing operations, call order, inputs/parameters, repetition, returned-state handoff and result branches; invoked algorithms remain dependencies.",
        "repr": "A call-and-state graph whose nodes are orchestration steps and whose edges carry parameters, return values, state versions and branch outcomes.",
        "conv": ["a dependency call is referenced rather than reimplemented", "call order follows preconditions and state versions", "each return is stored/used before dependent calls", "loop count and result branch remain source-bound"],
        "axes": ["call_order", "repetition", "input_plumbing", "result_branch"],
        "decision": bi("Dựng dependency/call-state graph trước; chỉ gọi operation khi input và state version mà nó cần đã sẵn sàng.", "Build the dependency/call-state graph first; call an operation only when its required inputs and state version are ready."),
        "inv": "After each orchestration event, every completed call has received the source-required arguments, its result/state version is owned once, and every pending call still has a satisfiable precondition.",
        "steps": [
            ("contract", ("Liệt kê calls có sẵn, input, parameter order, return/state mutation, repeat count, branch và required output/evidence handoff.", "List existing calls, inputs, parameter order, return/state mutation, repeat count, branches and required output/evidence handoffs."), ("Main flow ghép contracts; nó không tự định nghĩa lại thuật toán phụ thuộc.", "Main flow composes contracts rather than redefining dependency algorithms."), "Every requested orchestration action has one node and every data/state dependency has one directed edge.", "Before ordering calls.", "defines_flow_graph", ("Đánh dấu producer của từng argument/state version và consumer đầu tiên.", "Mark the producer of every argument/state version and its first consumer.")),
            ("schedule", ("Sắp call theo precondition: setup/read trước transform/search, rồi output/evidence sau state cần thiết.", "Schedule calls by precondition: setup/read before transform/search, then output/evidence after the required state exists."), ("Đổi order có thể dùng state rỗng/cũ dù từng call riêng đúng.", "Wrong order can consume empty/stale state even when each call is individually correct."), "A call fires only after all incoming dependency edges are satisfied by the latest state version.", "At each call boundary.", "orders_calls", ("Viết state version trước/sau từng call và phát hiện read-before-produce.", "Write the state version before/after every call and detect read-before-produce.")),
            ("handoff-branch", ("Đọc input đúng chỗ, truyền đúng argument, lưu/ dùng return, lặp đúng số lần và chọn branch theo result contract.", "Read input at the required point, pass exact arguments, store/use returns, repeat exactly and select branches under the result contract."), ("Bỏ return hoặc dùng result lần gọi trước phá state handoff.", "Dropping a return or using a previous call's result breaks state handoff."), "Within a repetition, parameters and result branch belong to that same iteration and no return is silently discarded.", "After a call produces a result and before dependent output/next call.", "advances_workflow", ("Theo dõi iteration id, arguments, returned value và chosen branch cùng một hàng.", "Track iteration id, arguments, returned value and chosen branch in one row.")),
            ("audit", ("Audit exact call count/order, state handoff, branch coverage và downstream output/evidence obligation mà không nhận điểm lại cho dependency.", "Audit exact call count/order, state handoff, branch coverage and downstream output/evidence obligations without reclaiming dependency marks."), ("Một workflow hoàn chỉnh phải đạt postcondition tích hợp, không chỉ từng call rời rạc.", "A complete workflow must meet the integrated postcondition rather than merely contain isolated calls."), "At completion, all requested calls and branches have the correct state lineage and each downstream obligation has its required input.", "After the final orchestration node.", "terminates_main_flow", ("So event sequence với QP/MS atoms được B8 sở hữu; dependency atoms giữ ở batch gốc.", "Compare the event sequence with B8-owned QP/MS atoms; dependency atoms stay in their original batches.")),
        ],
        "errors": [
            ("wrong-order-stale-state", "Gọi output/search/transform trước producer hoặc dùng state version cũ.", "Calling output/search/transform before its producer or using a stale state version.", "Call nhận state rỗng/cũ và workflow cho kết quả sai dù không lỗi cú pháp.", "A call consumes empty/stale state and the workflow is wrong without a syntax failure.", "Gắn version number vào state sau mỗi mutation và kiểm mọi call đọc latest producer.", "Attach a version number after every state mutation and verify every call reads the latest producer.", "Sắp lại topological order theo dependency edges; truyền trực tiếp latest result/state.", "Restore topological order from dependency edges and pass the latest result/state directly."),
            ("lost-result-iteration", "Không lưu return, trộn result giữa iterations hoặc lặp sai số lần.", "Failing to store a return, mixing results between iterations or repeating the wrong number of times.", "Branch/output không gắn với input đã tạo result hoặc thiếu/thừa call.", "A branch/output no longer belongs to the input that produced the result, or calls are missing/extra.", "Lập bảng iteration→input→call→return→branch và so row count với contract.", "Build an iteration→input→call→return→branch table and compare row count with the contract." , "Giữ result local cho mỗi iteration, commit branch trước khi tăng counter và khóa exact repeat bound.", "Keep the result local to each iteration, commit its branch before incrementing the counter and lock the exact repeat bound."),
        ],
        "cases": [("linear-pipeline", "setup/read, transform/search and output in dependency order"), ("repeated-call", "each iteration owns its input, return and branch"), ("before-after-observation", "output state before and after one mutating call without reimplementing it")],
        "visual": ("Call nào đang sở hữu state version nào, và return nào mở khóa event kế tiếp?", "Which call owns which state version, and which return unlocks the next event?", ["READ_WORKFLOW_INPUT", "CHECK_CALL_PRECONDITIONS", "INVOKE_DEPENDENCY_CALL", "RECEIVE_CALL_RESULT", "COMMIT_STATE_VERSION", "SELECT_RESULT_BRANCH", "HANDOFF_TO_OUTPUT_OR_EVIDENCE"]),
    },
    "OUTPUT_FORMAT": {
        "pre": "The source fixes which data is shown/returned, physical or logical order, labels/literals, separators, line/grid layout, range and result type.",
        "repr": "An output grammar plus an ordered sequence of source values transformed into labelled lines/cells or one returned formatted value.",
        "conv": ["exact source literals and labels are preserved when specified", "physical storage order is distinct from logical traversal/order", "range can include unused physical slots", "formatting does not mutate the underlying data structure"],
        "axes": ["grid_or_line", "physical_or_logical", "concatenation", "labels"],
        "decision": bi("Viết output grammar và iterator/range trước; mỗi output event phải khớp một record/cell trong đúng order và không đổi dữ liệu gốc.", "Write the output grammar and iterator/range first; each output event must match one record/cell in exact order without mutating source data."),
        "inv": "After k output events, the rendered prefix exactly matches the first k items of the source-selected sequence under the required labels, separators, line breaks and type contract.",
        "steps": [
            ("grammar", ("Chép exact literals/labels, field order, separator, newline/grid shape, return type và item range.", "Extract exact literals/labels, field order, separators, newline/grid shape, return type and item range."), ("Đúng values nhưng sai chữ, line hoặc range vẫn sai observable contract.", "Correct values with wrong text, lines or range still violate the observable contract."), "The output grammar determines one unambiguous rendering for each selected item sequence.", "Before choosing iteration/order.", "defines_output_grammar", ("Viết expected rendering cho hai item có giá trị phân biệt.", "Write the expected rendering for two items with distinct values.")),
            ("sequence", ("Chọn physical rows/slots hay logical order/traversal theo nguồn và khóa start/end bounds.", "Select physical rows/slots or logical order/traversal from the source and lock start/end bounds."), ("Backing-array order không tự động là logical order; đôi khi đề cố ý yêu cầu mọi slot vật lý.", "Backing-array order is not automatically logical order; some tasks explicitly require every physical slot."), "The iterator visits exactly the required items once and in the required order.", "Before formatting the first item.", "selects_output_sequence", ("Dùng state có physical order khác logical order và ghi expected first/last item.", "Use state whose physical order differs from logical order and state the expected first/last item.")),
            ("render", ("Lấy item hiện tại, convert/concatenate field theo grammar rồi emit đúng line/cell/return fragment.", "Take the current item, convert/concatenate fields under the grammar, then emit the exact line/cell/return fragment."), ("Tạo fragment hoàn chỉnh trước emit tránh thiếu label/separator và newline sai chỗ.", "Building a complete fragment before emission prevents missing labels/separators and misplaced newlines."), "Rendering changes only the output prefix; the source item and structure remain unchanged.", "For each selected item.", "advances_output_prefix", ("So fragment với grammar theo literal, field, separator và line position.", "Compare the fragment with the grammar by literal, field, separator and line position.")),
            ("audit", ("Kiểm exact text/order/range, item count, line/grid boundaries và underlying state unchanged.", "Check exact text/order/range, item count, line/grid boundaries and unchanged underlying state."), ("Format audit tách khỏi correctness của thuật toán tạo dữ liệu.", "Format audit is separate from correctness of the algorithm that produced the data."), "The complete rendering equals the source contract and contains no missing, extra or reordered item.", "After the final output event.", "terminates_output_format", ("Đếm outputs và diff expected/actual design character-by-character ở literals bắt buộc.", "Count outputs and design a character-level expected/actual diff for required literals.")),
        ],
        "errors": [
            ("right-data-wrong-shape", "Có đúng values nhưng thiếu label/separator/newline hoặc ghép sai field order.", "Having correct values but missing a label/separator/newline or concatenating fields in the wrong order.", "Observable text/return không khớp contract dù computation đúng.", "The observable text/return violates the contract even though computation is correct.", "Tách expected line thành token literal/field/separator và đối chiếu từng token cùng line break.", "Tokenise the expected line into literal/field/separator tokens and compare every token plus line break.", "Dựng fragment từ grammar cố định rồi thay field đúng vị trí; không tự paraphrase literal nguồn.", "Build the fragment from a fixed grammar and substitute fields in place; do not paraphrase source literals."),
            ("wrong-range-order", "In logical items khi đề cần physical slots, hoặc bỏ unused slot/đảo row-column.", "Printing logical items when physical slots are required, or omitting unused slots/swapping row-column order.", "Output thiếu/thừa/reordered item và không còn đại diện representation nguồn.", "Output has missing/extra/reordered items and no longer represents the source representation.", "Dùng item có index/value phân biệt, ghi visited-index sequence và so exact start/end/count.", "Use distinct index/value items, record the visited-index sequence and compare exact start/end/count.", "Khóa iterator/range bằng QP trước render; tách physical listing khỏi traversal/sorted sequence.", "Lock iterator/range from the QP before rendering; separate physical listing from traversal/sorted sequence."),
        ],
        "cases": [("labelled-lines", "one complete labelled record per line in source order"), ("physical-grid", "all specified rows/cells including unused slots"), ("returned-string", "concatenate exact fields/literals into the required return type")],
        "visual": ("Iterator chọn item nào tiếp theo, và grammar biến item đó thành exact line/cell/return fragment nào?", "Which item does the iterator select next, and how does the grammar turn it into the exact line/cell/return fragment?", ["SELECT_OUTPUT_RANGE", "READ_OUTPUT_ITEM", "BUILD_FORMAT_FRAGMENT", "EMIT_OUTPUT_FRAGMENT", "ADVANCE_OUTPUT_POSITION", "AUDIT_RENDERED_SEQUENCE"]),
    },
    "EVIDENCE_RUN": {
        "pre": "The source specifies tests/inputs, number of runs, expected visible outputs or file contents, screenshot/document destination and any filename visibility requirement.",
        "repr": "A Stage 5/6 evidence-capture plan linking each prescribed case to setup/reset, visible inputs, required output/file state and a named capture slot; no execution evidence exists yet.",
        "conv": ["Stage 4 designs evidence obligations but does not claim a run occurred", "official prescribed cases are distinguished from AlgoCore-added coverage", "each capture shows enough input/output/file identity to be attributable", "multiple runs have explicit reset/state lineage"],
        "axes": ["prescribed_inputs", "multiple_runs", "file_content", "filename_visibility"],
        "decision": bi("Lập evidence matrix case→setup→visible input→expected observable→capture slot; gắn nhãn official hoặc AlgoCore trước Stage 5/6.", "Build an evidence matrix case→setup→visible input→expected observable→capture slot, labelled official or AlgoCore before Stage 5/6."),
        "inv": "Every planned capture is attributable to exactly one test case and shows all source-required observable evidence, while no Stage 4 field states that execution, output or screenshot already exists.",
        "steps": [
            ("obligation", ("Trích prescribed inputs, số runs, expected output/file, filename visibility và vị trí evidence.doc từ QP/MS locator.", "Extract prescribed inputs, run count, expected output/file, filename visibility and evidence.doc destination from QP/MS locators."), ("Evidence mark thuộc observable được yêu cầu, không phải cài lại algorithm context.", "The evidence mark belongs to the required observable rather than reimplementing the contextual algorithm."), "Each official obligation is source-cited and separated from optional AlgoCore tests.", "Before planning setup or capture.", "defines_evidence_contract", ("Đánh dấu từng row `official_qp_ms` hoặc `AlgoCore_coverage`.", "Label every row `official_qp_ms` or `AlgoCore_coverage`.")),
            ("matrix", ("Cho mỗi case, ghi pre-state/reset, exact inputs/file seed, calls, expected observable và capture contents.", "For each case, record pre-state/reset, exact inputs/file seed, calls, expected observable and capture contents."), ("Nhiều runs dùng state khác nhau cần reset để ảnh không mơ hồ.", "Multiple runs using changing state need explicit reset so captures are not ambiguous."), "Every case has a reproducible setup and a unique expected capture specification without claiming execution.", "For each prescribed case.", "plans_test_case", ("Kiểm input nào phải hiện trên screen và file/filename nào phải nằm trong frame.", "Check which input must be visible and which file/filename must appear in frame.")),
            ("capture-plan", ("Định nghĩa planned events RUN_START, INPUT_SHOWN, OUTPUT/FILE_STATE_SHOWN, CAPTURE_SAVED với tên slot duy nhất.", "Define planned RUN_START, INPUT_SHOWN, OUTPUT/FILE_STATE_SHOWN and CAPTURE_SAVED events with a unique slot name."), ("Event model làm rõ evidence nào còn thiếu nhưng không biến plan thành run claim.", "The event model exposes missing evidence without turning the plan into a run claim."), "A capture may be considered complete in Stage 5/6 only after all required planned events are evidenced for the same case id.", "After the future run produces the required observable.", "specifies_capture_gate", ("Giữ status PENDING và prohibited claims cho đến khi artifact Stage 5/6 được review.", "Keep status PENDING and prohibited claims until a Stage 5/6 artifact is reviewed.")),
            ("review-handoff", ("Chuẩn bị checklist readability, uncropped inputs/outputs, filename/file contents, case id và official/AlgoCore label cho reviewer Stage 6.", "Prepare a Stage 6 reviewer checklist for readability, uncropped inputs/outputs, filename/file contents, case id and official/AlgoCore label."), ("Screenshot đẹp nhưng thiếu input hoặc attribution không chứng minh prescribed case.", "A clear screenshot missing input or attribution does not evidence the prescribed case."), "The handoff requests evidence verification but contains no assertion that tests ran or outputs passed.", "After the capture specification is complete.", "terminates_evidence_design", ("Tìm các từ run/pass/verified ở past tense và loại khỏi Stage 4 artifacts.", "Search for past-tense run/pass/verified claims and remove them from Stage 4 artifacts.")),
        ],
        "errors": [
            ("unattributed-capture", "Plan chỉ chụp output, thiếu prescribed input, case id, file contents hoặc filename bắt buộc.", "Planning an output-only capture that omits prescribed input, case id, file contents or a required filename.", "Ảnh tương lai không chứng minh observable thuộc đúng test case.", "The future image cannot establish that the observable belongs to the prescribed case.", "Đối chiếu capture contents với mọi cột input/output/file/filename của evidence matrix.", "Compare capture contents with every input/output/file/filename column in the evidence matrix.", "Mở rộng frame/capture set để hiển thị đủ attribution; đặt slot name chứa case id.", "Expand the frame/capture set to show full attribution and include the case id in the slot name."),
            ("premature-run-claim", "Viết rằng test đã chạy/pass hoặc gán expected output thành observed evidence ở Stage 4.", "Stating that a test ran/passed or treating expected output as observed evidence in Stage 4.", "Authority boundary bị phá và reviewer không phân biệt plan với bằng chứng thật.", "The authority boundary breaks and reviewers cannot distinguish a plan from real evidence.", "Quét mọi status/narrative để tìm past-tense execution claims và kiểm không có screenshot/runtime artifact được dẫn.", "Scan every status/narrative for past-tense execution claims and confirm no screenshot/runtime artifact is cited.", "Đổi sang planned/expected/PENDING_STAGE5_6 và giao capture verification cho Stage 5/6.", "Change wording to planned/expected/PENDING_STAGE5_6 and hand capture verification to Stage 5/6."),
        ],
        "cases": [("single-prescribed-run", "one official input/output capture with complete attribution"), ("multiple-reset-runs", "each official case has its own reset, state lineage and capture slot"), ("file-evidence", "capture required file contents and visible filename without asserting execution")],
        "visual": ("Mỗi planned capture phải hiển thị input, observable và attribution nào trước khi Stage 6 có thể review?", "Which input, observable and attribution must each planned capture show before Stage 6 can review it?", ["PLAN_CASE_SETUP", "PLAN_RUN_START", "PLAN_INPUT_VISIBLE", "PLAN_OUTPUT_VISIBLE", "PLAN_FILE_AND_FILENAME_VISIBLE", "PLAN_CAPTURE_SLOT", "PLAN_STAGE6_REVIEW"]),
    },
}


GLOBAL_INV_VI = {
    "MAIN_FLOW": "Sau mỗi event, call đã hoàn tất nhận đúng arguments và state version; result chỉ có một owner và call chờ vẫn còn precondition khả thi.",
    "OUTPUT_FORMAT": "Sau k output events, rendered prefix khớp chính xác k items đầu theo labels, separators, line breaks và type contract nguồn.",
    "EVIDENCE_RUN": "Mỗi planned capture gắn đúng một case và đủ observable bắt buộc; không field Stage 4 nào tuyên bố execution/output/screenshot đã tồn tại.",
}


STEP_META_VI = {
    "MAIN_FLOW": [
        ("Mỗi orchestration action có một node và mỗi data/state dependency có một edge.", "Trước khi order calls.", "định nghĩa flow graph"),
        ("Call chỉ fire khi incoming edges được thỏa bởi latest state version.", "Tại mỗi call boundary.", "sắp call"),
        ("Trong mỗi iteration, arguments/result/branch thuộc cùng iteration và không mất return.", "Sau call và trước consumer.", "tiến workflow"),
        ("Khi hoàn tất, calls/branches có đúng state lineage và downstream inputs.", "Sau orchestration node cuối.", "kết thúc main flow"),
    ],
    "OUTPUT_FORMAT": [
        ("Grammar xác định một rendering duy nhất cho selected sequence.", "Trước khi chọn order.", "định nghĩa output grammar"),
        ("Iterator visit đúng items một lần theo đúng order.", "Trước item đầu.", "chọn output sequence"),
        ("Render chỉ đổi output prefix, không đổi source state.", "Với mỗi selected item.", "tiến output prefix"),
        ("Rendering hoàn chỉnh khớp contract, không thiếu/thừa/reorder item.", "Sau output event cuối.", "kết thúc output format"),
    ],
    "EVIDENCE_RUN": [
        ("Official obligations có citation và tách khỏi AlgoCore tests.", "Trước setup/capture plan.", "định nghĩa evidence contract"),
        ("Mỗi case có reproducible setup và unique expected capture, chưa có execution claim.", "Với mỗi prescribed case.", "lập test-case plan"),
        ("Future capture chỉ complete khi đủ planned events cùng case id.", "Sau future observable ở Stage 5/6.", "định nghĩa capture gate"),
        ("Handoff yêu cầu verification nhưng không khẳng định run/pass.", "Sau khi capture spec đầy đủ.", "kết thúc evidence design"),
    ],
}


VISUAL_CASES = {
    "MAIN_FLOW": {
        "normal": bi("Pipeline Read→Sort→Output dùng state v0→v1→v2: mỗi call chỉ mở khi producer trước hoàn tất và Output nhận đúng v2.", "A Read→Sort→Output pipeline uses state v0→v1→v2: each call unlocks only after its producer completes, and Output receives v2."),
        "boundary": bi("So zero-iteration, one-iteration và failed-call result: không branch nào dùng stale result, không consumer nào chạy khi precondition chưa thỏa.", "Compare zero-iteration, one-iteration and failed-call results: no branch uses a stale result and no consumer runs with an unsatisfied precondition."),
    },
    "OUTPUT_FORMAT": {
        "normal": bi("Hai record có field phân biệt được render thành hai labelled lines; event sequence phải giữ exact literal, separator, order và source state unchanged.", "Render two records with distinct fields as two labelled lines; events must preserve exact literals, separators and order while leaving source state unchanged."),
        "boundary": bi("Dùng backing rows có physical order khác inorder và một empty/unused slot; chọn đúng physical hoặc logical range phải cho first/last/count khác nhau theo contract.", "Use backing rows whose physical order differs from inorder plus an empty/unused slot; selecting physical or logical range must produce the contract-specific first/last/count."),
    },
    "EVIDENCE_RUN": {
        "normal": bi("Thiết kế hai capture slots cho hai prescribed runs: mỗi slot liệt kê reset, visible input, expected output và case id; cả hai vẫn PENDING Stage 5/6.", "Design two capture slots for two prescribed runs: each lists reset, visible input, expected output and case id; both remain PENDING Stage 5/6."),
        "boundary": bi("File-evidence case yêu cầu filename và contents trong frame; một output-only crop phải bị capture gate từ chối và không được gọi là run/pass.", "A file-evidence case requires filename and contents in frame; an output-only crop must fail the capture gate and must not be described as a run/pass."),
    },
}
