import type { LocalText, ScenarioFixture, VisualFamilyDefinition, VisualKind } from "./types";

const t = (en: string, vi: string): LocalText => ({ en, vi });

type FamilySeed = Readonly<{
  id: VisualFamilyDefinition["id"];
  kind: VisualKind;
  name: LocalText;
  purpose: LocalText;
  lessons: readonly string[];
  fieldLabels: readonly [LocalText, LocalText, LocalText];
  values: Readonly<Record<"normal" | "boundary" | "failure", readonly [string, string, string]>>;
  action: LocalText;
  prediction: Readonly<Record<"normal" | "boundary" | "failure", LocalText>>;
  answers: readonly [LocalText, LocalText, LocalText];
  correct: Readonly<Record<"normal" | "boundary" | "failure", 0 | 1 | 2>>;
  code: readonly string[];
}>;

const scenario = (seed: FamilySeed, mode: "normal" | "boundary" | "failure"): ScenarioFixture => ({
  prompt: seed.prediction[mode],
  options: seed.answers,
  correctOption: seed.correct[mode],
  reveal: mode === "failure"
    ? t(`Rejected. ${seed.fieldLabels[2].en}: ${seed.values.failure[2]}.`, `Bị từ chối. ${seed.fieldLabels[2].vi}: ${seed.values.failure[2]}.`)
    : mode === "boundary"
      ? t(`Boundary result. ${seed.fieldLabels[2].en}: ${seed.values.boundary[2]}.`, `Kết quả tại biên. ${seed.fieldLabels[2].vi}: ${seed.values.boundary[2]}.`)
      : t(`${seed.action.en}. ${seed.fieldLabels[2].en}: ${seed.values.normal[2]}.`, `${seed.action.vi}. ${seed.fieldLabels[2].vi}: ${seed.values.normal[2]}.`),
  steps: [
    t("Read the current state", "Đọc trạng thái hiện tại"),
    seed.action,
    mode === "failure" ? t("Preserve state and report the reason", "Giữ nguyên trạng thái và nêu lý do") : t("Confirm the new invariant", "Kiểm tra điều kiện đúng sau thay đổi"),
  ],
  code: seed.code.slice(0, 3),
});

const make = (seed: FamilySeed): VisualFamilyDefinition => ({
  id: seed.id,
  kind: seed.kind,
  name: seed.name,
  purpose: seed.purpose,
  lessons: seed.lessons,
  fields: seed.fieldLabels.map((label, index) => ({
    label,
    values: {
      normal: seed.values.normal[index],
      boundary: seed.values.boundary[index],
      failure: seed.values.failure[index],
    },
  })),
  scenarios: {
    normal: scenario(seed, "normal"),
    boundary: scenario(seed, "boundary"),
    failure: scenario(seed, "failure"),
  },
});

const seeds: readonly FamilySeed[] = [
  { id: "VC-01", kind: "array", name: t("Array Ribbon", "Dải mảng"), purpose: t("See indices, capacity and the cell changed by an operation.", "Nhìn rõ chỉ số, sức chứa và ô bị thay đổi."), lessons: ["data-models", "text-processing", "search-collections", "sorting", "binary-search", "random-files"], fieldLabels: [t("capacity", "sức chứa"), t("count", "số phần tử"), t("next index", "chỉ số tiếp theo")], values: { normal: ["5", "3 → 4", "3"], boundary: ["5", "4 → 5", "4 (last slot)"], failure: ["5", "5", "no cell changes"] }, action: t("Place the value in the chosen cell", "Đặt giá trị vào ô đã chọn"), prediction: { normal: t("Which cell receives 28?", "Ô nào nhận giá trị 28?"), boundary: t("Which final cell is still available?", "Ô cuối cùng nào vẫn còn trống?"), failure: t("What changes when the array is full?", "Điều gì thay đổi khi mảng đã đầy?") }, answers: [t("index 2", "chỉ số 2"), t("index 3", "chỉ số 3"), t("no cell", "không ô nào")], correct: { normal: 1, boundary: 1, failure: 2 }, code: ["if count < capacity:", "    values[count] = item", "    count += 1"] },
  { id: "VC-02", kind: "record", name: t("Record / Object Card", "Thẻ bản ghi / đối tượng"), purpose: t("Connect named fields, types, values and validity.", "Liên kết tên trường, kiểu, giá trị và tính hợp lệ."), lessons: ["data-models", "validation-rules", "dictionary", "oop-model", "oop-state", "oop-aggregation"], fieldLabels: [t("name", "tên"), t("score", "điểm"), t("valid", "hợp lệ")], values: { normal: ["Binh", "81", "true"], boundary: ["An", "0", "true (minimum)"], failure: ["Binh", "121", "false; record unchanged"] }, action: t("Validate each named field", "Kiểm tra từng trường có tên"), prediction: { normal: t("Will this record be accepted?", "Bản ghi này có được nhận không?"), boundary: t("Is the minimum score valid?", "Điểm tối thiểu có hợp lệ không?"), failure: t("What happens to an invalid record?", "Bản ghi không hợp lệ sẽ thế nào?") }, answers: [t("accept", "chấp nhận"), t("reject", "từ chối"), t("change the name", "đổi tên")], correct: { normal: 0, boundary: 0, failure: 1 }, code: ["valid_name = name != ''", "valid_score = 0 <= score <= 100", "return valid_name and valid_score"] },
  { id: "VC-03", kind: "pipeline", name: t("Flow Pipeline", "Luồng xử lý"), purpose: t("Follow data through input, processing and output.", "Theo dõi dữ liệu qua nhập, xử lý và xuất."), lessons: ["procedural-design", "text-processing", "recursion", "oop-inheritance", "exceptions", "exam-workflow"], fieldLabels: [t("input", "đầu vào"), t("stage", "bước"), t("output", "đầu ra")], values: { normal: ["'  Ada  '", "clean_name", "'Ada'"], boundary: ["''", "clean_name", "''"], failure: ["None", "guard", "no output; report error"] }, action: t("Pass the value to the next named responsibility", "Chuyển giá trị tới trách nhiệm được đặt tên tiếp theo"), prediction: { normal: t("What leaves the cleaning stage?", "Giá trị nào ra khỏi bước làm sạch?"), boundary: t("What does an empty input produce?", "Đầu vào rỗng tạo ra gì?"), failure: t("Does invalid input reach processing?", "Đầu vào sai có tới bước xử lý không?") }, answers: [t("'Ada'", "'Ada'"), t("the original spaces", "giữ nguyên khoảng trắng"), t("stop before processing", "dừng trước xử lý")], correct: { normal: 0, boundary: 0, failure: 2 }, code: ["def clean_name(text):", "    if text is None: raise ValueError", "    return text.strip()"] },
  { id: "VC-04", kind: "predicate", name: t("Predicate Gate", "Cổng điều kiện"), purpose: t("See the tested condition, chosen branch and rejection reason.", "Nhìn rõ điều kiện, nhánh được chọn và lý do từ chối."), lessons: ["validation-rules"], fieldLabels: [t("value", "giá trị"), t("predicate", "điều kiện"), t("branch", "nhánh")], values: { normal: ["17", "0 <= age <= 120", "accept"], boundary: ["120", "0 <= age <= 120", "accept at upper limit"], failure: ["-1", "0 <= age <= 120", "reject; state unchanged"] }, action: t("Evaluate the condition once", "Đánh giá điều kiện một lần"), prediction: { normal: t("Which branch will 17 take?", "17 đi theo nhánh nào?"), boundary: t("Is 120 inside the inclusive range?", "120 có nằm trong khoảng bao gồm hai đầu không?"), failure: t("Which branch will -1 take?", "-1 đi theo nhánh nào?") }, answers: [t("accept", "chấp nhận"), t("reject", "từ chối"), t("skip the test", "bỏ qua kiểm tra")], correct: { normal: 0, boundary: 0, failure: 1 }, code: ["if 0 <= age <= 120:", "    accept(age)", "else: reject('range')"] },
  { id: "VC-05", kind: "tests", name: t("Test Matrix", "Ma trận kiểm thử"), purpose: t("Separate input, expected result, actual result and verdict.", "Tách đầu vào, kết quả mong đợi, thực tế và kết luận."), lessons: ["testing", "exam-workflow"], fieldLabels: [t("test", "ca kiểm thử"), t("expected", "mong đợi"), t("verdict", "kết luận")], values: { normal: ["middle value", "accepted", "pass"], boundary: ["minimum value", "accepted", "pass at boundary"], failure: ["invalid type", "rejected", "fail if accepted"] }, action: t("Run one test and compare exact results", "Chạy một ca và so sánh kết quả chính xác"), prediction: { normal: t("What verdict follows when results match?", "Kết luận nào khi kết quả trùng khớp?"), boundary: t("Why test the exact limit?", "Tại sao kiểm tra đúng giá trị giới hạn?"), failure: t("What if invalid data is accepted?", "Nếu dữ liệu sai lại được chấp nhận thì sao?") }, answers: [t("pass", "đạt"), t("fail", "không đạt"), t("cannot conclude", "chưa thể kết luận")], correct: { normal: 0, boundary: 0, failure: 1 }, code: ["actual = validate(test_input)", "passed = actual == expected", "print(test_input, expected, actual)"] },
  { id: "VC-06", kind: "search", name: t("Search Window", "Cửa sổ tìm kiếm"), purpose: t("Track low, middle, high and the retained interval.", "Theo dõi low, middle, high và khoảng được giữ lại."), lessons: ["search-collections", "binary-search", "performance"], fieldLabels: [t("low", "low"), t("middle", "middle"), t("high", "high")], values: { normal: ["0", "3", "6 → 2"], boundary: ["4", "4", "4 (one item)"], failure: ["0", "—", "6; stop: unsorted input"] }, action: t("Compare before changing one boundary", "So sánh trước khi đổi một biên"), prediction: { normal: t("Target 18 is below value 25. Which half remains?", "Mục tiêu 18 nhỏ hơn 25. Giữ lại nửa nào?"), boundary: t("How many values remain when low equals high?", "Còn bao nhiêu giá trị khi low bằng high?"), failure: t("Can binary search start on unsorted data?", "Tìm kiếm nhị phân có thể chạy trên dữ liệu chưa sắp xếp không?") }, answers: [t("left half", "nửa trái"), t("right half", "nửa phải"), t("stop: precondition fails", "dừng: sai điều kiện đầu")], correct: { normal: 0, boundary: 0, failure: 2 }, code: ["middle = (low + high) // 2", "if target < values[middle]:", "    high = middle - 1"] },
  { id: "VC-07", kind: "sort", name: t("Sort Track", "Đường sắp xếp"), purpose: t("See the compared pair, movement and proven sorted boundary.", "Nhìn cặp được so sánh, sự dịch chuyển và vùng đã đúng."), lessons: ["sorting", "performance"], fieldLabels: [t("pair", "cặp"), t("movement", "dịch chuyển"), t("invariant", "điều kiện đúng")], values: { normal: ["8, 3", "swap", "smaller value moves left"], boundary: ["3, 8", "no swap", "order already valid"], failure: ["index 4, 5", "blocked", "do not read beyond end"] }, action: t("Compare, then swap or keep", "So sánh rồi đổi chỗ hoặc giữ nguyên"), prediction: { normal: t("Will 8 and 3 swap?", "8 và 3 có đổi chỗ không?"), boundary: t("Will an ordered pair move?", "Cặp đã đúng thứ tự có di chuyển không?"), failure: t("What happens to an out-of-range comparison?", "So sánh vượt phạm vi sẽ thế nào?") }, answers: [t("swap", "đổi chỗ"), t("keep", "giữ nguyên"), t("reject the comparison", "từ chối so sánh")], correct: { normal: 0, boundary: 1, failure: 2 }, code: ["temp = values[i]", "values[i] = values[i + 1]", "values[i + 1] = temp"] },
  { id: "VC-08", kind: "stack", name: t("Stack Tower", "Tháp ngăn xếp"), purpose: t("See TOP, push, pop and unchanged rejection state.", "Nhìn TOP, push, pop và trạng thái không đổi khi bị từ chối."), lessons: ["stack", "recursion", "graphs"], fieldLabels: [t("TOP", "TOP"), t("operation", "thao tác"), t("result", "kết quả")], values: { normal: ["1 → 2", "push 9", "9 becomes top"], boundary: ["0 → -1", "pop", "stack becomes empty"], failure: ["2", "push 9", "overflow; TOP stays 2"] }, action: t("Move TOP only when the operation is valid", "Chỉ di chuyển TOP khi thao tác hợp lệ"), prediction: { normal: t("Where will TOP point after push 9?", "TOP trỏ tới đâu sau push 9?"), boundary: t("What is TOP after popping the final item?", "TOP là gì sau khi pop phần tử cuối?"), failure: t("Does TOP move on overflow?", "TOP có di chuyển khi tràn không?") }, answers: [t("move up", "tăng lên"), t("move down", "giảm xuống"), t("stay unchanged", "giữ nguyên")], correct: { normal: 0, boundary: 1, failure: 2 }, code: ["if top < capacity - 1:", "    top += 1", "    stack[top] = item"] },
  { id: "VC-09", kind: "queue", name: t("Queue Track / Ring", "Hàng đợi thẳng / vòng"), purpose: t("See front, rear, count and wrap-around without mixing conventions.", "Nhìn front, rear, count và vòng lại mà không trộn quy ước."), lessons: ["queue", "graphs"], fieldLabels: [t("front", "front"), t("rear", "rear"), t("count", "số phần tử")], values: { normal: ["1", "2 → 3", "2 → 3"], boundary: ["3", "3 → 0", "1 → 2 (wrap)"], failure: ["1", "3", "4; full, unchanged"] }, action: t("Write at rear, then update rear and count", "Ghi tại rear rồi cập nhật rear và count"), prediction: { normal: t("Which slot receives the next item?", "Ô nào nhận phần tử tiếp theo?"), boundary: t("Where does rear move after the final slot?", "rear đi đâu sau ô cuối?"), failure: t("What changes when the queue is full?", "Điều gì đổi khi hàng đợi đầy?") }, answers: [t("next physical slot", "ô vật lý tiếp theo"), t("wrap to slot 0", "vòng về ô 0"), t("nothing", "không gì")], correct: { normal: 0, boundary: 1, failure: 2 }, code: ["if count < capacity:", "    queue[rear] = item", "    rear = (rear + 1) % capacity"] },
  { id: "VC-10", kind: "nodes", name: t("Node-Link Canvas", "Mặt phẳng nút-liên kết"), purpose: t("See node identity, named links, null and safe rewiring order.", "Nhìn định danh nút, liên kết có tên, null và thứ tự nối an toàn."), lessons: ["linked-list", "binary-tree", "graphs"], fieldLabels: [t("current", "hiện tại"), t("link", "liên kết"), t("next target", "đích tiếp")], values: { normal: ["node 2", "next", "node 5"], boundary: ["node 5", "next", "null (tail)"], failure: ["node 2", "saved next", "absent target; links unchanged"] }, action: t("Read the link before rewiring it", "Đọc liên kết trước khi nối lại"), prediction: { normal: t("Which node is reached through next?", "Nút nào được tới qua next?"), boundary: t("What follows the tail node?", "Sau nút cuối là gì?"), failure: t("Should links change when the target is absent?", "Có đổi liên kết khi không tìm thấy đích không?") }, answers: [t("node 5", "nút 5"), t("null", "null"), t("keep every link", "giữ nguyên mọi liên kết")], correct: { normal: 0, boundary: 1, failure: 2 }, code: ["saved_next = nodes[current].next", "nodes[current].next = new_index", "nodes[new_index].next = saved_next"] },
  { id: "VC-11", kind: "hash", name: t("Hash Buckets", "Các bucket băm"), purpose: t("Follow key, hash result, collision probes and stop condition.", "Theo dõi khóa, kết quả băm, lần dò va chạm và điều kiện dừng."), lessons: ["dictionary", "hashing"], fieldLabels: [t("key", "khóa"), t("bucket", "bucket"), t("probe", "lần dò")], values: { normal: ["'Ada'", "2 → 3", "collision then free"], boundary: ["'Bo'", "4 → 0", "wrap to first bucket"], failure: ["'Cy'", "all", "full cycle; no insert"] }, action: t("Probe according to the declared collision rule", "Dò theo đúng quy tắc xử lý va chạm đã nêu"), prediction: { normal: t("Bucket 2 is occupied. Which probe is next?", "Bucket 2 đã có dữ liệu. Dò đâu tiếp?"), boundary: t("Where does a linear probe go after the last bucket?", "Dò tuyến tính đi đâu sau bucket cuối?"), failure: t("When must probing stop?", "Khi nào phải dừng dò?") }, answers: [t("next bucket", "bucket tiếp theo"), t("wrap to bucket 0", "vòng về bucket 0"), t("after a full cycle", "sau một vòng đầy đủ")], correct: { normal: 0, boundary: 1, failure: 2 }, code: ["index = hash_key(key) % size", "while table[index] is not None:", "    index = (index + 1) % size"] },
  { id: "VC-12", kind: "objects", name: t("Class / Object Map", "Bản đồ lớp / đối tượng"), purpose: t("Separate a class blueprint from instance identity, state and relationships.", "Tách bản thiết kế lớp khỏi định danh, trạng thái và quan hệ đối tượng."), lessons: ["oop-model", "oop-state", "oop-inheritance", "oop-aggregation", "object-files"], fieldLabels: [t("class", "lớp"), t("instance", "đối tượng"), t("change", "thay đổi")], values: { normal: ["Student", "s1", "score 70 → 81"], boundary: ["Student", "s2", "score remains 0"], failure: ["Student", "s1", "invalid update rejected"] }, action: t("Send a valid request through the public method", "Gửi yêu cầu hợp lệ qua phương thức công khai"), prediction: { normal: t("Which instance changes?", "Đối tượng nào thay đổi?"), boundary: t("Does changing s1 also change s2?", "Đổi s1 có làm s2 đổi theo không?"), failure: t("What happens to invalid state?", "Trạng thái sai sẽ thế nào?") }, answers: [t("s1 only", "chỉ s1"), t("both instances", "cả hai đối tượng"), t("reject and preserve state", "từ chối và giữ trạng thái")], correct: { normal: 0, boundary: 0, failure: 2 }, code: ["student = Student('Binh', 70)", "student.set_score(81)", "print(student.get_score())"] },
  { id: "VC-13", kind: "file", name: t("File Cursor", "Con trỏ tệp"), purpose: t("See mode, current record, cursor movement and EOF.", "Nhìn chế độ, bản ghi hiện tại, di chuyển con trỏ và EOF."), lessons: ["text-files", "object-files", "random-files"], fieldLabels: [t("mode", "chế độ"), t("cursor", "con trỏ"), t("record", "bản ghi")], values: { normal: ["read", "line 2 → 3", "'81' parsed"], boundary: ["read", "last line → EOF", "stop cleanly"], failure: ["read", "unchanged", "invalid data reported"] }, action: t("Read exactly one record, then advance", "Đọc đúng một bản ghi rồi tiến con trỏ"), prediction: { normal: t("Where is the cursor after one read?", "Con trỏ ở đâu sau một lần đọc?"), boundary: t("What follows the final line?", "Sau dòng cuối là gì?"), failure: t("Should invalid data be stored?", "Có lưu dữ liệu sai không?") }, answers: [t("next record", "bản ghi tiếp theo"), t("EOF", "EOF"), t("report and do not store", "báo lỗi và không lưu")], correct: { normal: 0, boundary: 1, failure: 2 }, code: ["with open(path, 'r') as file:", "    line = file.readline()", "    value = int(line.strip())"] },
  { id: "VC-14", kind: "exception", name: t("Exception Path", "Đường ngoại lệ"), purpose: t("See the exact raise point, matching handler and continuation.", "Nhìn điểm phát sinh lỗi, handler phù hợp và bước tiếp tục."), lessons: ["exceptions"], fieldLabels: [t("try step", "bước try"), t("error", "lỗi"), t("route", "đường đi")], values: { normal: ["int('42')", "none", "continue normally"], boundary: ["cleanup", "none", "finally still runs"], failure: ["int('x')", "ValueError", "matching handler"] }, action: t("Choose the route produced by the operation", "Chọn đường đi do thao tác tạo ra"), prediction: { normal: t("Which route follows a valid conversion?", "Đường nào sau chuyển đổi hợp lệ?"), boundary: t("Does finally run when there is no error?", "finally có chạy khi không lỗi không?"), failure: t("Which handler matches int('x')?", "Handler nào khớp int('x')?") }, answers: [t("normal continuation", "tiếp tục bình thường"), t("ValueError handler", "handler ValueError"), t("finally only", "chỉ finally")], correct: { normal: 0, boundary: 2, failure: 1 }, code: ["try: value = int(text)", "except ValueError: report_invalid()", "finally: close_resources()"] },
  { id: "VC-15", kind: "counter", name: t("Operation Counter", "Bộ đếm thao tác"), purpose: t("Name n, the counted operation, the case and exact small-input totals.", "Nêu n, thao tác được đếm, trường hợp và tổng chính xác với đầu vào nhỏ."), lessons: ["performance"], fieldLabels: [t("n", "n"), t("operation", "thao tác"), t("count", "số lần")], values: { normal: ["4", "comparison", "4"], boundary: ["1", "comparison", "1"], failure: ["4", "mixed operations", "claim rejected"] }, action: t("Increment only for the named operation", "Chỉ tăng với thao tác đã được nêu"), prediction: { normal: t("How many comparisons does a full scan of 4 items make?", "Quét đủ 4 phần tử có bao nhiêu phép so sánh?"), boundary: t("How many comparisons for one item?", "Một phần tử cần bao nhiêu phép so sánh?"), failure: t("Can unlike operations be compared as one count?", "Có thể gộp các thao tác khác loại thành một số đếm không?") }, answers: [t("4", "4"), t("1", "1"), t("reject the claim", "bác bỏ kết luận")], correct: { normal: 0, boundary: 1, failure: 2 }, code: ["count = 0", "for item in values:", "    count += 1  # comparison"] },
  { id: "VC-16", kind: "console", name: t("Output Console", "Bảng kết quả"), purpose: t("Show exact output, formatting, status and errors.", "Hiển thị chính xác đầu ra, định dạng, trạng thái và lỗi."), lessons: ["data-models", "procedural-design", "validation-rules", "testing", "text-processing", "search-collections", "sorting", "binary-search", "stack", "queue", "linked-list", "recursion", "binary-tree", "dictionary", "hashing", "oop-model", "oop-state", "oop-inheritance", "oop-aggregation", "text-files", "object-files", "random-files", "exceptions", "graphs", "exam-workflow"], fieldLabels: [t("status", "trạng thái"), t("line", "dòng"), t("output", "đầu ra")], values: { normal: ["success", "1", "Score: 81"], boundary: ["success", "1", "Score: 0"], failure: ["error", "1", "no fabricated result"] }, action: t("Emit the exact required text once", "Xuất đúng văn bản yêu cầu một lần"), prediction: { normal: t("What exact text is printed?", "Văn bản chính xác nào được in?"), boundary: t("Is zero printed or hidden?", "Số 0 được in hay bị ẩn?"), failure: t("Should an error invent an output value?", "Khi lỗi có nên tự tạo giá trị đầu ra không?") }, answers: [t("Score: 81", "Điểm: 81"), t("Score: 0", "Điểm: 0"), t("report error only", "chỉ báo lỗi")], correct: { normal: 0, boundary: 1, failure: 2 }, code: ["if valid:", "    print(f'Score: {score}')", "else: print('Invalid score')"] },
] as const;

export const visualFamilies: readonly VisualFamilyDefinition[] = seeds.map(make);

export function getVisualFamily(id: VisualFamilyDefinition["id"]): VisualFamilyDefinition {
  const family = visualFamilies.find((item) => item.id === id);
  if (!family) throw new Error(`Unknown visual family: ${id}`);
  return family;
}
