"""Manually curated, page-grounded source index; no source code is executed."""
import json
from pathlib import Path
from datetime import datetime, timezone

ROOT = Path(__file__).resolve().parents[1]
S1 = ROOT.parent / 'stage-1'
S2 = ROOT.parent / 'stage-2'
BOOK = json.loads((S1 / 'extracted/coursebook_watson_williams.json').read_text(encoding='utf-8'))
# id | chapter | section | subheading | printed pages | support level | patterns | supported actions | limitations
DATA = r'''
BOOK-01-RLE|1|1.3.1|Run-length encoding (RLE)|22-24|conceptual|RUN_LENGTH_ENCODE|Represent each adjacent run by a count and data-item code; distinguish adjacent repetition from frequency across the entire input.|No queue-based encoder, final-run flush, or examination output contract is supplied; derive these from QP/MS.
BOOK-06-VALIDATION|6|6.2|Validation|169-170|foundational|VALIDATE_INPUT,UNIQUE_SELECTION|Choose type, range, format, length, presence and existence checks suited to a field.|Validation does not prove factual correctness; uniqueness/consumed-answer state must come from the question.
BOOK-06-CHECK-DIGIT|6|6.2|Check digits|171-172|conceptual|CHECK_DIGIT|Apply weighted digit arithmetic, remainder and comparison to detect input errors.|Book demonstrates modulo-11 and mentions ISBN-13; do not replace a question's specified weights, modulo or exceptional digit with the book example.
BOOK-09-DECOMPOSE|9|9.1.1-9.1.2|Using abstraction; Using decomposition|218-219|foundational|MAIN_FLOW|Separate a problem into subproblems and retain relevant data and operations.|Does not specify the call sequence or global state of any corpus question.
BOOK-09-ALGORITHM|9|9.2.1-9.2.2|Writing algorithms; Writing simple algorithms using pseudocode|220-225|foundational|ALGORITHM_TRANSLATE,RULE_COMPUTE,MAIN_FLOW|Recognise input, output, assignment, selection and iteration; translate the intended construct into a programming language.|Preserve QP identifiers, bounds and required algorithm; these general examples are not authority to replace mandated pseudocode.
BOOK-09-ACCUMULATE|9|9.2.2|Average algorithm and input checks|227-229|foundational|COUNT_OCCURRENCES,GROUP_AGGREGATE,QUEUE_REDUCE,STACK_REDUCE,RULE_COMPUTE|Initialise an accumulator and counter, iterate over inputs and compute an aggregate; validate the requested quantity.|Does not cover grouping by a record key or destructive ADT consumption; those state transitions require the question's contract.
BOOK-09-REFINEMENT|9|9.2.3;9.2.5|Writing pseudocode from a structured English description; Stepwise refinement|229-231,233-235|foundational|RULE_COMPUTE,FILTER_RECORDS,MAIN_FLOW,VALIDATE_INPUT|Identify variables, inputs, outputs, processes and selection from a scenario; refine a high-level task into validated subtasks.|No corpus-specific predicate, scoring table or duplicate-selection algorithm is supplied.
BOOK-10-TYPES|10|10.1.1|Data types|239|foundational|DATA_STORAGE,DATA_RECORD,RULE_COMPUTE|Choose integer, real, Boolean, character/string and date representations; declare named data items.|Table10.1 prints False(2), a source defect; do not propagate numeric Boolean encoding from this table. Python declarations differ from pseudocode.
BOOK-10-RECORDS|10|10.1.2|Records|240-241|direct_concept|DATA_RECORD,FILE_READ_ARRAY|Define heterogeneous record fields, instantiate a record and access named fields.|A TYPE record may use a Python class substitute when permitted; an explicit OOP class task remains distinct. No full Python record-class listing here.
BOOK-10-ARRAYS|10|10.2.1-10.2.2|1D arrays; 2D arrays|241-243|direct_concept|DATA_STORAGE,ARRAY_APPEND,RANDOM_ARRAY,OUTPUT_FORMAT,HASH_SETUP,OOP_CAPACITY_ADD|Choose dimensions and bounds; initialise and access indexed elements; use a nested loop for a table and traverse contents for output.|Finite capacity, live length, safe 2D initialisation, append-full policy and random-number API are not specified here; obtain exact contracts from QP/MS.
BOOK-10-LINEAR-EXTENSION|10|10.2.3|Using a linear search; Extension Activity10B|243-244|activity_and_concept|LINEAR_SEARCH,COUNT_OCCURRENCES|Scan elements until found or exhausted; return an index when requested; extension asks for repeated items and their counts.|First-match search and full-scan frequency count are different exam patterns; the count extension has no completed solution.
BOOK-10-TEXT-FILES|10|10.3|Files|249-250|direct_concept|FILE_READ_ARRAY,FILE_READ_OBJECTS,FILE_WRITE|Open text files for read/write/append, process lines as strings, use end-of-file condition and close files.|Line grouping, delimiters, conversion, object construction, newline handling and exact file names need exam-specific evidence. Example pseudocode is not validated production code.
BOOK-10-ADT|10|10.4|Abstract data types (ADTs)|250-251|conceptual|STACK_SETUP,QUEUE_SETUP,LIST_SETUP,QUEUE_INSPECT,LIST_TRAVERSE|Explain data plus permitted operations; distinguish LIFO, FIFO and following node links.|Book's statements that linked-list insertions always occur at the start and queues always require circular management are contextual simplifications, not universal requirements.
BOOK-11-BASICS|11|11.1.1|Constants and variables; Example 11.1|265-269|foundational|RULE_COMPUTE,MAIN_FLOW,OUTPUT_FORMAT,OOP_UPDATE,ARRAY_APPEND|Use variables, assignment, arithmetic, input conversion, conditions and labelled output in a console program.|No exam-specific formatting, rounding, clamping, capacity or update rule is supplied; example code requires Stage5 validation.
BOOK-11-STRINGS|11|11.1.1|String manipulation; Example11.2; Table11.6|269-271|foundational|STRING_COMPARE,STRING_SPLIT,STRING_ROUTE,OUTPUT_FORMAT,FILTER_RECORDS,CHECK_DIGIT|Measure string length, inspect/slice characters and combine comparisons; distinguish case-sensitive data.|No complete lexical comparator, manual delimiter splitter or typed-field routing algorithm. Do not claim built-in split or sorting is permitted for a particular QP.
BOOK-11-LIBRARY|11|11.1.2|Library routines|271|foundational|RANDOM_ARRAY|Recognise standard library routines and investigate language-specific functions.|No random generator, randint call, inclusive endpoint rule or distribution appears in the reviewed book text; this is a deliberate book gap.
BOOK-11-CONSTRUCTS|11|11.2.1-11.2.2|CASE and IF; Loops|271-275|foundational|RULE_COMPUTE,FILTER_RECORDS,UNIQUE_SELECTION,VALIDATE_INPUT,STRING_ROUTE|Select by exact values/ranges, combine decisions and use pre/post-condition or count-controlled repetition.|Exam predicates, scoring bands, consumed-answer markers and termination sentinels remain question-specific.
BOOK-11-SUBROUTINES|11|11.3.1-11.3.2|Procedures; Functions|275-280|foundational|MAIN_FLOW,ALGORITHM_TRANSLATE,OOP_GET,OOP_SET,OOP_UPDATE,RULE_COMPUTE|Declare/call procedures and functions, pass parameters and return values; reason about local/global data.|Python argument passing must not be taught as literal BYREF syntax; exact signatures/return sentinels follow QP/MS.
BOOK-12-DESIGN|12|12.2.1|Purpose and use of structure charts|288-292|foundational|MAIN_FLOW,ALGORITHM_TRANSLATE|Decompose a program into interacting modules and convert the design to calls, procedures and functions.|No corpus question's main-program call order is supplied by this section.
BOOK-12-TESTING|12|12.3.1-12.3.3|Ways of avoiding and exposing faults in programs; Location, identification and correction of errors; Program testing|294-299|foundational|EVIDENCE_RUN|Identify syntax, logic and runtime errors; dry-run with a trace table; choose normal, abnormal and boundary data; compare expected and actual outcomes.|Paper4 evidence document placement, required screenshot contents, exact runs and submission names come from QP/MS, not this section. Maintenance subsection 12.3.4 begins later on printed 299 and is not the basis of this link.
BOOK-13-FILE-ORGANISATION|13|13.2.1|File organisation and file access|308-310|conceptual||Distinguish serial arrival order, sequential key order, random organisation, sequential access and direct access; choose for retrieval/update workload.|In-memory hash arrays do not demonstrate persistent random-file operations. Supporting theory outside19-20 is not an independent new core topic.
BOOK-13-HASH|13|13.2.2|Hashing algorithms|310-311|conceptual|HASH_SETUP,HASH_FUNCTION,HASH_INSERT,HASH_SEARCH|Calculate a location from a key, address/record size and modulo; detect collisions; compare keys during retrieval; understand next-free and overflow-area handling.|Book does not specify corpus100x10 buckets or Spare-array contracts. Preserve the question's collision policy; book terminology open/closed is source wording, not a universal naming rule.
BOOK-19-LINEAR|19|19.1.1|Understanding linear and binary searching methods: Linear search|451-454|direct_algorithm|LINEAR_SEARCH|Check each array element, terminate on found/exhausted and report a result; Python implementation and Activity19A are present.|Do not stop early for frequency-count tasks. Review pointer/bounds and return type against each question.
BOOK-19-BINARY|19|19.1.1|Binary search|454-457|direct_algorithm|BINARY_SEARCH|Require ordered input, compare midpoint and reduce the search interval; compare numbers of comparisons.|Printed455-457 pseudocode/language table has suspect equality-based termination; use as concept/source reference, not approved code. Recursive variants need recursion source plus QP/MS.
BOOK-19-BUBBLE|19|19.1.2|Understanding insertion and bubble sorting methods: Bubble sort|458-461|direct_algorithm|BUBBLE_SORT|Compare adjacent entries and swap to order them, repeat passes, recognise decreasing bound and swap flag.|Book/source code has known swap-flag placement risk also visible atprinted245; later code must be tested. Whole-row/multikey/direction variants come from QP/MS.
BOOK-19-INSERTION|19|19.1.2|Insertion sort|461-464|direct_algorithm|INSERTION_SORT,ORDERED_INSERT|Take the next value, shift larger predecessors and insert the saved value into its ordered position; interpret trace of array changes.|ORDERED_INSERT is a transfer from the inner insertion operation, not the full sort; fixed top-N retention and multi-field shifts require QP/MS. Check boundary guard order before implementation.
BOOK-19-STACK|19|19.1.3|Stacks|464-466|direct_algorithm|STACK_SETUP,STACK_PUSH,STACK_POP,STACK_PAIR,STACK_REDUCE|Represent a finite stack with array and pointers; initialise, check empty/full and push/pop; Python routines are present.|Book top points to last occupied slot(-1 when empty); corpus also uses next-free top. Pair rollback, operand order and reduction protocol are not supplied.
BOOK-19-QUEUE|19|19.1.3|Queues|466-469|direct_algorithm|QUEUE_SETUP,QUEUE_ENQUEUE,QUEUE_DEQUEUE,QUEUE_INSPECT,QUEUE_REDUCE|Represent a circular queue, maintain front/rear/count, wrap pointers and guard underflow/overflow; Python routines are present.|Do not force wraparound on linear-queue QPs. Live non-destructive inspection, terminal sentinels and reduction pipelines require QP/MS.
BOOK-19-LIST-SETUP|19|19.1.3|Linked lists|469-470|direct_algorithm|LIST_SETUP|Represent node data and next links in arrays, initialise a free list and identify start/null/free pointers.|Object-linked implementations and exact free-list conventions depend on the question; book uses parallel arrays.
BOOK-19-LIST-SEARCH|19|19.1.3|Linked lists: finding an item|470-474|direct_algorithm|LIST_TRAVERSE,LIST_REMOVE|Follow links from the start, compare current data and stop on match/null; Python find function and trace are present.|Directly supports linked-list search, a syllabus obligation even without its own Stage2 primary pattern. Full-list output is a transfer; deletion needs its separate source.
BOOK-19-LIST-INSERT|19|19.1.3|Inserting items into a linked list|474-477|direct_algorithm|LIST_INSERT|Take a free node, locate insertion position and relink live/free pointers; follow the diagrams and pseudocode.|This is ordered insertion; head/tail insertion variants and exact empty/full sentinels follow QP/MS. Python listing is not certified executable.
BOOK-19-LIST-REMOVE|19|19.1.3|Deleting items from a linked list|477-481|direct_algorithm|LIST_REMOVE|Find the target, bypass it in the live chain and return its slot to the free chain; distinguish first-node handling.|Do not copy book deletion code without testing null/not-found/head cases. Object-linked variants may have no array free list.
BOOK-19-TREE-SETUP|19|19.1.3|Binary trees|481-482|direct_concept|TREE_SETUP|Identify root, left/right child links, leaf and null pointers; model ordered binary tree nodes.|Binary-tree concepts are broader than BST ordering; exact duplicate policy and array/object representation are question contracts.
BOOK-19-TREE-SEARCH|19|19.1.3|Finding an item in a binary tree|482-484|direct_algorithm|TREE_SEARCH|Compare target with node data, follow a left/right link and terminate at match or null.|Array-based pseudocode is provided; guard an empty root and follow QP's return convention. Not the binary-search-in-array pattern.
BOOK-19-TREE-INSERT|19|19.1.3|Inserting items into a binary tree|484-487|direct_algorithm|TREE_INSERT|Allocate a free node and attach it at the correct left/right position, including empty-tree handling.|Printed487 says objects and recursion are required, but this must not override corpus iterative array implementations. Duplicate/capacity rules are question-specific.
BOOK-19-TREE-TRAVERSE|19|19.1.3;20.1.3|Extension Activity19B; Extension Activity20B|481,521|activity_only|TREE_TRAVERSE|Book asks learners to investigate tree traversal and implement pre-order/post-order output.|No completed in-order/pre-order/post-order algorithm on these pages. Build exact algorithms from QP/MS plus tree and recursion knowledge, explicitly as AlgoCore synthesis.
BOOK-19-GRAPH|19|19.1.3|Graphs|487|conceptual||Describe vertices/edges, directed/undirected graphs, weighted edges, paths and cycles using real networks.|Conceptual support only; syllabus no-graph-code boundary remains. Does not authorize graph algorithms as core Paper4 practice.
BOOK-19-ADT-COMPOSITION|19|19.1.4|Implementing one ADT from another ADT|488-489|conceptual|DATA_RECORD,LIST_SETUP,TREE_SETUP,QUEUE_SETUP,STACK_SETUP|Construct composite ADTs by referring to existing data types; represent linked records and dictionary keys/values.|Book declarations/examples are explanatory and include questionable syntax; do not present as validated Python implementations.
BOOK-19-DICTIONARY|19|19.1.4|Dictionary|488-490|conceptual||Use unique keys to retrieve values, permit duplicate values and compose the representation from other ADTs; Activity19P asks find/add/delete.|Do not equate corpus hash-table tasks with full dictionary add/find/delete coverage. Printed489 Java table includes a Python dict line; code is not validated.
BOOK-19-COMPLEXITY|19|19.1.5|Comparing algorithms|489-490|conceptual|LINEAR_SEARCH,BINARY_SEARCH,BUBBLE_SORT,INSERTION_SORT|Compare growth in worst-case time and space using BigO and the listed search/sort examples.|Contextual explanation and practical choice, not a new Paper4 essay pattern. Avoid blanket time complexity claims independent of implementation/assumptions.
BOOK-19-RECURSION|19|19.2.1|Understanding recursion|490-493|direct_algorithm|ALGORITHM_REWRITE,ALGORITHM_TRANSLATE,BINARY_SEARCH,TREE_TRAVERSE,TREE_INSERT,QUEUE_REDUCE,COUNT_OCCURRENCES,INSERTION_SORT|Identify base/general case, trace winding/unwinding and reason about recursive return values; factorial/Fibonacci/compound-interest examples are present.|No general proof that an arbitrary loop-to-recursion rewrite preserves outputs. Each corpus rewrite needs its own state and termination analysis.
BOOK-19-CALL-STACK|19|19.2.2|How a compiler implements recursion|494|conceptual|ALGORITHM_REWRITE,ALGORITHM_TRANSLATE,TREE_TRAVERSE,BINARY_SEARCH|Explain saved return addresses/local variables on recursive calls and restoration during unwinding.|This is recursion's execution model, not the same user-defined stack exercise; no low-level implementation lesson is added.
BOOK-20-PROCEDURAL|20|20.1.2|Imperative programming|500-501|conceptual|MAIN_FLOW,ALGORITHM_TRANSLATE,ALGORITHM_REWRITE|Distinguish sequential imperative instructions and procedural decomposition into subroutines/local/global variables.|Exclude low-level and declarative programming from core; this concept does not itself cover all AS11.3 subroutine objectives.
BOOK-20-CLASS|20|20.1.3|Class; Object; Encapsulation|501-504|direct_concept|OOP_CLASS,OOP_INSTANTIATE,FILE_READ_OBJECTS|Read a class diagram, define attributes/methods, create instances and encapsulate private data; Python example appears onprinted502-503.|Constructor/visibility requirements follow QP. Do not force privacy onto explicitly public Recordclass tasks or confuse TYPErecord substitutes with full OOP tasks.
BOOK-20-INHERITANCE|20|20.1.3|Inheritance|505-509|direct_concept|OOP_SUBCLASS|Define base/derived classes, inherit attributes/methods and initialise subclass state; Python example onprinted506.|Python double-underscore name mangling and superclass initialisation need implementation review; do not infer public/protected access from prose alone.
BOOK-20-POLYMORPHISM|20|20.1.3|Polymorphism and overloading: Example of polymorphism|509-513|direct_concept|OOP_OVERRIDE|Redefine a method in derived classes and invoke class-specific behaviour through objects.|QP formulas, caps and return contracts are additional assessed content. Python default-argument overloading example on513 is not a separate required pattern.
BOOK-20-CONTAINMENT|20|20.1.3|Containment|514-515|conceptual|OOP_CAPACITY_ADD,OOP_CLASS,FILE_READ_OBJECTS|Distinguish contains-a from is-a; model an object holding bounded arrays of other objects and a live count.|Book gives diagram and named operations but no complete capacity-checked append method; boundary checks are exam-derived.
BOOK-20-CONSTRUCTORS|20|20.1.3|Object methods: constructors and constructing an object|515-516|direct_concept|OOP_CLASS,OOP_INSTANTIATE|Initialise a new object's attributes and instantiate with constructor arguments.|Default array contents and parameter order follow QP/MS; book typesetting around Python underscores/spaces must not be copied literally.
BOOK-20-GETTERS|20|20.1.3|Object methods: Getter; Table 20.4|516|direct_concept|OOP_GET|Return the value of a stored object property through a method.|A computed formatted string is not automatically a getter; follow QP return type and scope.
BOOK-20-SETTERS|20|20.1.3|Object methods: Setter; Table 20.3|516|direct_concept|OOP_SET,OOP_UPDATE|Control changes to a private property through a method and parameter.|OOP_UPDATE with add/clamp/multiply rules is an exam transfer, not the plain replacement setter shown here.
BOOK-20-OBJECT-TREE|20|20.1.3|Writing a program for a binary tree; Tables20.6-20.9|517-521|direct_algorithm|TREE_SETUP,TREE_INSERT,TREE_SEARCH,OOP_CLASS|Represent node objects with child references, instantiate a root, insert recursively and search; connect objects and containment.|Printed520 Python search assigns a child reference into self.item rather than moving a node cursor; source code is unsuitable for direct reuse without later validation. Object/recursion approach is not compulsory for all QPs.
BOOK-20-FILE-RECORDS|20|20.2.1|Storing records in a serial or sequential file|526-528|direct_concept|FILE_READ_OBJECTS,FILE_READ_ARRAY,FILE_WRITE,DATA_RECORD|Define structured records, open a file, write/read successive records and close; Python example uses binary serialisation.|The binary pickle example is not interchangeable with supplied exam text files; preserve format contract. Arrays/record field indexing in source pseudocode require review.
BOOK-20-FILE-SEQUENTIAL|20|20.2.1|Adding a record to a sequential file|531-533|conceptual|FILE_WRITE|Copy records around a new record for ordered insertion, and distinguish append at end from insertion by key.|Printed532 loop/EOF logic is suspect and not certified; no new implementation is supplied here. Serial/sequential coverage must be distinguished from just loading text into memory.
BOOK-20-FILE-RANDOM|20|20.2.1|Adding a record to a random file; Finding a record in a random file|533-535|direct_concept||Compute an address from a key, SEEK, PUTRECORD/GETRECORD and close a random-access file.|Only pseudocode plus extension activities for these operations; exact Python storage layout and collision handling are not implemented. In-memory HASH tasks are not proof of this skill.
BOOK-20-EXCEPTIONS|20|20.2.2|Exception handling|535-537|direct_concept|FILE_READ_ARRAY,FILE_READ_OBJECTS,VALIDATE_INPUT|Recognise disrupted execution, trap division/input/file errors, recover or stop in an orderly way; extend file handling for missing file/unexpected EOF.|Book Python uses bare except; this is not a claim that every QP requires broad handling or that all validation is exception handling. Coverage must be evidenced separately.
'''

def expand(spec):
    out=[]
    for piece in spec.split(','):
        ends=piece.split('-');out.extend(range(int(ends[0]), int(ends[-1])+1))
    return out

sections=[]
for line in DATA.strip().splitlines():
    sid,ch,sec,heading,pages,level,patterns,support,limit=line.split('|')
    pp=expand(pages)
    sections.append(dict(section_id=sid,source_id=BOOK['source_id'],chapter=int(ch),section=sec,subheading=heading,
        printed_pages=pp,pdf_pages=[p+16 for p in pp],support_level=level,supported_knowledge_actions=support,
        limitations=[limit,'Knowledge locator only; no code execution, solution validation or syllabus-completion claim is made.'],
        suggested_pattern_ids=patterns.split(',') if patterns else [],review_status='SUBMITTED'))

VISUAL=[22,171,241,249,310,311,464,467,470,481,487,488,489,490,501,506,516,521,526,534,536,245,456,520]
for s in sections:
    s['visual_verified_printed_pages']=[p for p in s['printed_pages'] if p in VISUAL]
    s['visual_evidence']=[f'a2_renders/a2_contact_{VISUAL.index(p)//6+1}.png' for p in s['visual_verified_printed_pages']]

GAPS={
 'RANDOM_ARRAY':'Arrays and libraries are documented, but no random-number generator API or bounds convention was located by whole-book keyword search and relevant chapter review.',
 'STRING_COMPARE':'Character operations are documented; a manual lexicographic comparator and prefix rules must be derived from QP/MS.',
 'STRING_SPLIT':'String length/characters are documented; manual token extraction and final token handling are not given as a complete technique.',
 'STRING_ROUTE':'String primitives and selection are documented; parsing typed fields and routing to six colour arrays is a corpus-specific composition.',
 'RUN_LENGTH_ENCODE':'The compression concept is explicit atprinted22-24; queue consumption, final-run flush and exact output representation are corpus-specific.',
 'HASH_SETUP':'Hashing/collisions and arrays are explicit; the100x10bucket and main/Spare-array representations are exam variants.',
 'HASH_INSERT':'Hash and collision concepts are explicit; exact overflow-array/bucket-full policy is not the book algorithm.',
 'HASH_SEARCH':'Collision checking is conceptual; exact bucket/Spare probing termination and return sentinel need QP/MS.',
 'TREE_TRAVERSE':'Traversal appears as extension activities(481,521), not a complete textbook algorithm for all three orders.',
 'STACK_PAIR':'Push/pop are explicit; two-stack transactional pairing and restoring an unmatched item are QP-derived.',
 'STACK_REDUCE':'Stack operations and accumulation are separate sources; operand order and evaluation protocol are QP-derived.',
 'QUEUE_REDUCE':'Queue operations and accumulation are separate sources; consumption order, sentinel and recursive aggregate are QP-derived.',
 'QUEUE_INSPECT':'FIFO and pointers are explicit; a non-destructive live-queue view excluding stale slots is a QP-specific composition.',
 'GROUP_AGGREGATE':'Accumulator and record/array foundations exist; find-or-add by group key is a QP-specific composition.',
 'FILTER_RECORDS':'Arrays, predicates and strings are foundations; the complete multi-condition object filter comes from QP/MS.',
 'UNIQUE_SELECTION':'Validation/selection/array state are foundations; used-position or consumed-answer handling is QP-specific.',
 'EVIDENCE_RUN':'Testing knowledge is explicit; screenshot content, evidence file and prescribed test runs are QP/MS authorities.',
 'OOP_CAPACITY_ADD':'Containment diagram and arrays are explicit; success/failure result and bounded insertion invariant are QP-specific.',
 'ORDERED_INSERT':'Inner insertion operation is supported by insertion sort; fixed-capacity top-N list and multi-field shifts remain QP-derived.'}

cat=json.loads((S2/'EXAM_PATTERN_CATALOG.json').read_text(encoding='utf-8'))
ids={x['pattern_id'] for x in cat['patterns']}
mapped={p for s in sections for p in s['suggested_pattern_ids']}
assert not mapped-ids, mapped-ids
assert not ids-mapped, ids-mapped
for s in sections:
    assert all(0<p<=560 for p in s['printed_pages'])
    for pdf,printed in zip(s['pdf_pages'],s['printed_pages']):
        text=BOOK['pages'][pdf-1]['text'];assert str(printed) in text[:30],(s['section_id'],pdf)

result=dict(schema_version='1.0',status='SUBMITTED',created_utc=datetime.now(timezone.utc).isoformat(),
 source={'source_id':BOOK['source_id'],'source_path':BOOK['source_path'],'sha256':BOOK['sha256'],'pdf_page_count':BOOK['page_count'],
 'title':'Cambridge International AS & A Level Computer Science','authors':['David Watson','Helen Williams'],'publisher':'Hodder Education','year':2019},
 locator_policy='One-based PDF pages; Arabic printed body pages use PDF=printed+16. Each cited printed marker was checked in extracted text;24anchor pages were additionally viewed in original-PDF render contact sheets.',
 authority_boundary='The book supplies knowledge and examples, not final exam instructions or syllabus authority. Suggested patterns include foundational transfer; they do not mean the exact exam technique is printed in the book.',
 count=len(sections),sections=sections,pattern_book_gaps=[{'pattern_id':p,'gap':g,'disposition':'Use cited foundations plus source QP/MS; mark AlgoCore synthesis explicitly in Stage4, validate code in Stage5.'} for p,g in GAPS.items()],
 syllabus_not_corpus_obligations=[
 {'knowledge':'Dictionary ADT find/add/delete and construction from other ADTs','section_ids':['BOOK-19-DICTIONARY','BOOK-19-ADT-COMPOSITION'],'caution':'No Stage2pattern assigned solely to manufacture exam incidence.'},
 {'knowledge':'Linked-list search','section_ids':['BOOK-19-LIST-SEARCH'],'caution':'Related traversal/deletion patterns do not prove a separately assessed linked-search function.'},
 {'knowledge':'Graph characteristics','section_ids':['BOOK-19-GRAPH'],'caution':'Concept only, no graph code.'},
 {'knowledge':'Time/space complexity','section_ids':['BOOK-19-COMPLEXITY'],'caution':'Supporting understanding, no invented exam essay pattern.'},
 {'knowledge':'Serial/sequential record processing and random file access','section_ids':['BOOK-13-FILE-ORGANISATION','BOOK-20-FILE-RECORDS','BOOK-20-FILE-SEQUENTIAL','BOOK-20-FILE-RANDOM'],'caution':'Text loading or in-memory hash tables are insufficient to prove whole objective coverage.'},
 {'knowledge':'Exceptions','section_ids':['BOOK-20-EXCEPTIONS'],'caution':'Validate explicit exception requirements separately from input-range checks.'}],
 excluded_core_sections=[{'section':'20.1.1','reason':'Low-level programming excluded from core Paper4 scope'},{'section':'20.1.4','reason':'Declarative programming excluded from core Paper4 scope'}],
 self_checks={'unique_section_ids':len({s['section_id'] for s in sections})==len(sections),'all_58_patterns_have_at_least_foundational_link':len(mapped)==58,'all_cited_printed_markers_checked':True,'visual_anchor_page_count':len(VISUAL),'source_mutated':False,'code_executed':False})
(ROOT/'evidence').mkdir(exist_ok=True)
(ROOT/'evidence/A2_BOOK_SECTION_INDEX.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'sections':len(sections),'mapped_patterns':len(mapped),'gaps':len(GAPS),'status':'SUBMITTED'}))
