"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Button, CodePanel, Feedback, Textarea } from "@/app/components/algocore-ui";
import type { PerformanceLearnerProjection } from "./learnerProjection";
import { learnerText } from "./learnerProjection";
import {
  PERFORMANCE_PRACTICE_KEY,
  PERFORMANCE_PRACTICE_SCHEMA,
  PERFORMANCE_PROJECTION_SHA256,
  PERFORMANCE_PROGRESS_KEY,
  createInitialPerformanceProgress,
  isPerformanceComplete,
  performanceCheckpointId,
  performanceRows,
  performanceStep,
  performanceSupport,
  restorePerformanceProgress,
  type PerformanceTraceProgress,
} from "./performanceProjectionAdapter";
import type { LearningLocale } from "./types";
import styles from "./LessonLearningPage.module.css";

const labels = {
  en: { caption:"Static search evidence", algorithm:"Algorithm", result:"Result index", probes:"Inspected positions", precondition:"Required condition", hidden:"Predict before reveal", setup:"Setup outside the probe count", prediction:"Your justification", placeholder:"Write one justified sentence before revealing…", record:"Record prediction", recorded:"Prediction recorded. Compare it with the controlled evidence.", code:"Focused Python", decision:"Decision", previous:"Previous", next:"Next", support:"Boundary and blocked-precondition support", empty:"Valid empty boundary", blocked:"Binary precondition blocked", linear:"Linear", binary:"Binary", notRun:"Not run", invariant:"Fair comparison rule", practice:"Practice item", of:"of", answer:"Your explanation", attempt:"Record attempt", attempted:"Attempt recorded. Support is now available.", hint:"Hint", model:"Model answer", check:"Success check", previousPractice:"Previous practice", nextPractice:"Next practice" },
  vi: { caption:"Bằng chứng search tĩnh", algorithm:"Thuật toán", result:"Result index", probes:"Vị trí được kiểm tra", precondition:"Điều kiện bắt buộc", hidden:"Dự đoán trước khi mở", setup:"Setup nằm ngoài probe count", prediction:"Lập luận của bạn", placeholder:"Viết một câu có lý do trước khi mở…", record:"Ghi nhận dự đoán", recorded:"Đã ghi nhận. Hãy đối chiếu với bằng chứng có kiểm soát.", code:"Python đang xét", decision:"Quyết định", previous:"Trước", next:"Tiếp", support:"Hỗ trợ boundary và precondition bị chặn", empty:"Boundary rỗng hợp lệ", blocked:"Binary bị chặn bởi precondition", linear:"Linear", binary:"Binary", notRun:"Không chạy", invariant:"Quy tắc so sánh công bằng", practice:"Bài luyện", of:"trên", answer:"Giải thích của bạn", attempt:"Ghi nhận lần làm", attempted:"Đã ghi nhận. Phần hỗ trợ đã được mở.", hint:"Gợi ý", model:"Đáp án mẫu", check:"Điểm tự kiểm", previousPractice:"Bài luyện trước", nextPractice:"Bài luyện tiếp" },
} as const;

function persist(progress: PerformanceTraceProgress) { try { sessionStorage.setItem(PERFORMANCE_PROGRESS_KEY, JSON.stringify(progress)); } catch { /* unavailable */ } }

export function PerformanceEvidenceTable({ projection, locale, onLearnerProgress }: Readonly<{ projection: PerformanceLearnerProjection; locale: LearningLocale; onLearnerProgress: (complete:boolean)=>void }>) {
  const t=labels[locale]; const [progress,setProgress]=useState<PerformanceTraceProgress>(createInitialPerformanceProgress); const [restored,setRestored]=useState(false);
  const rows=useMemo(()=>performanceRows(projection),[projection]); const support=useMemo(()=>performanceSupport(projection),[projection]); const id=performanceCheckpointId(progress.checkpoint_index); const step=performanceStep(projection,progress.checkpoint_index); const draft=progress.drafts[id]??""; const revealed=progress.revealed_checkpoint_ids.includes(id); const complete=isPerformanceComplete(progress);
  useEffect(()=>{const candidate=restorePerformanceProgress(sessionStorage.getItem(PERFORMANCE_PROGRESS_KEY));if(candidate)setProgress(candidate);setRestored(true);},[]);
  useEffect(()=>{if(restored)onLearnerProgress(complete);},[complete,onLearnerProgress,restored]);
  const commit=(next:PerformanceTraceProgress)=>{persist(next);setProgress(next);}; const setDraft=(value:string)=>commit({...progress,phase:"predict",drafts:{...progress.drafts,[id]:value}}); const reveal=()=>{if(!draft.trim())return;const revealedIds=progress.revealed_checkpoint_ids.includes(id)?progress.revealed_checkpoint_ids:[...progress.revealed_checkpoint_ids,id];commit({...progress,phase:"revealed",revealed_checkpoint_ids:revealedIds});};
  const move=(checkpoint_index:0|1|2)=>{const nextId=performanceCheckpointId(checkpoint_index);commit({...progress,checkpoint_index,phase:progress.revealed_checkpoint_ids.includes(nextId)?"revealed":"predict"});requestAnimationFrame(()=>document.getElementById("performance-trace-prediction")?.focus());};
  const conditionVisible=progress.checkpoint_index>1||progress.revealed_checkpoint_ids.includes("comparison:1"); const evidenceVisible=progress.checkpoint_index===2&&revealed; const setupVisible=progress.revealed_checkpoint_ids.includes("comparison:1");
  return <section className={styles.performanceEvidence} data-testid="paper4-performance-evidence-table" data-scene="performance-static-comparison" data-case-kind="normal-comparison" data-checkpoint-index={progress.checkpoint_index} data-phase={revealed?"revealed":"predict"} data-comparison-complete={complete?"true":"false"}>
    <p className={styles.performanceInput}><strong>[1, 3, 5, 7, 9, 11, 13]</strong><span>target = 11</span></p>
    <div className={styles.performanceEvidencePanels}>
      <section className={styles.performanceTablePanel} data-trace-panel="probe-table">
        <table className={styles.performanceTable}><caption>{t.caption}: {learnerText(projection.stages.trace.scenario.label,locale)}</caption><thead><tr><th scope="col">{t.algorithm}</th><th scope="col">{t.result}</th><th scope="col">{t.probes}</th><th scope="col">{t.precondition}</th></tr></thead><tbody>{rows.map((row,index)=><tr key={row.algorithm} data-probe-row={index===0?"linear":"binary"}><th scope="row">{row.algorithm}</th><td data-label={t.result}>{evidenceVisible?<strong>{row.result_index}</strong>:<span>{t.hidden}</span>}</td><td data-label={t.probes} data-probe-metric="inspected-positions">{evidenceVisible?<strong>{row.inspected_positions}</strong>:<span>{t.hidden}</span>}</td><td data-label={t.precondition}>{conditionVisible?<strong>{learnerText(row.required_precondition,locale)}</strong>:<span>{t.hidden}</span>}</td></tr>)}</tbody></table>
        {setupVisible&&<aside className={styles.performanceSetup} data-setup-disclosure><strong>{t.setup}</strong><p>{learnerText(projection.stages.trace.scenario.setup_disclosure,locale)}</p></aside>}
        <div data-focused-code><CodePanel title={t.code} caption={`${t.decision} ${progress.checkpoint_index+1} / 3`} lines={step.code_focus.map((text,index)=>({number:index+1,text,active:true}))}/></div>
      </section>
      <section className={styles.performancePredictionPanel} data-trace-panel="prediction" data-trace-prediction><p>{learnerText(projection.stages.trace.scenario.metric,locale)}</p><Textarea id="performance-trace-prediction" label={learnerText(step.prediction,locale)} placeholder={t.placeholder} rows={4} value={draft} onChange={(event)=>setDraft(event.target.value)}/><Button data-action="record-prediction" disabled={!draft.trim()} onClick={reveal}>{t.record}</Button>{revealed&&<div className={styles.traceAnswer} data-answer-revealed="true"><Feedback status="info" title={t.recorded}>{learnerText(step.answer,locale)}</Feedback><p className={styles.invariantResult}><strong>{t.invariant}:</strong> {learnerText(projection.stages.trace.invariant_check,locale)}</p></div>}</section>
    </div>
    <nav className={styles.traceStepNav} aria-label={projection.stages.trace.name[locale]}><Button variant="secondary" data-action="previous" disabled={progress.checkpoint_index===0} onClick={()=>move((progress.checkpoint_index-1) as 0|1|2)}>← {t.previous}</Button><Button variant="secondary" data-action="next" disabled={!revealed||progress.checkpoint_index===2} onClick={()=>move((progress.checkpoint_index+1) as 0|1|2)}>{t.next} →</Button></nav>
    {complete&&<section className={styles.performanceSupport} aria-labelledby="performance-support-title"><h3 id="performance-support-title">{t.support}</h3><div>{support.map((variant)=><article key={variant.kind} data-support-case={variant.kind} data-case-kind={variant.kind==="valid_empty_boundary"?"valid-empty-boundary":"binary-precondition-blocked"}><h4>{variant.kind==="valid_empty_boundary"?t.empty:t.blocked}</h4>{variant.kind==="valid_empty_boundary"?<dl><div><dt>{t.linear}</dt><dd>-1 · 0 probes</dd></div><div><dt>{t.binary}</dt><dd>-1 · 0 probes</dd></div></dl>:<dl><div><dt>{t.linear}</dt><dd>index 2 · 3 probes</dd></div><div><dt>{t.binary}</dt><dd>{t.notRun} · UNSORTED</dd></div></dl>}<p>{learnerText(variant.explanation,locale)}</p></article>)}</div></section>}
  </section>;
}

type PracticeStage=PerformanceLearnerProjection["stages"]["practise"];
export function PerformancePractice({stage,locale,onAttemptChange}:Readonly<{stage:PracticeStage;locale:LearningLocale;onAttemptChange?:(attempted:boolean)=>void}>) {
  const t=labels[locale]; const inputRef=useRef<HTMLTextAreaElement>(null); const [index,setIndex]=useState(0); const [drafts,setDrafts]=useState<Record<number,string>>({}); const [attempted,setAttempted]=useState<ReadonlySet<number>>(new Set()); const [restored,setRestored]=useState(false); const item=stage.items[index]; const draft=drafts[index]??""; const hasAttempt=attempted.has(index); const marker=["fairness","order","growth","space"][index];
  useEffect(()=>{try{const value=JSON.parse(sessionStorage.getItem(PERFORMANCE_PRACTICE_KEY)??"null") as {schema_version?:unknown;projection_sha256?:unknown;index?:unknown;drafts?:unknown;attempted?:unknown}|null;if(value&&typeof value==="object"&&value.schema_version===PERFORMANCE_PRACTICE_SCHEMA&&value.projection_sha256===PERFORMANCE_PROJECTION_SHA256&&typeof value.index==="number"&&Number.isInteger(value.index)&&value.index>=0&&value.index<4&&value.drafts&&typeof value.drafts==="object"&&!Array.isArray(value.drafts)&&Array.isArray(value.attempted)){const entries=Object.entries(value.drafts),valid=entries.every(([key,val])=>/^[0-3]$/.test(key)&&typeof val==="string"),attempts=value.attempted.every((val)=>typeof val==="number"&&Number.isInteger(val)&&val>=0&&val<4);if(valid&&attempts){setIndex(value.index);setDrafts(Object.fromEntries(entries));setAttempted(new Set(value.attempted as number[]));}}}catch{/* stale */}setRestored(true);},[]);
  const persistPractice=(nextIndex:number,nextDrafts:Record<number,string>,nextAttempted:ReadonlySet<number>)=>{try{sessionStorage.setItem(PERFORMANCE_PRACTICE_KEY,JSON.stringify({schema_version:PERFORMANCE_PRACTICE_SCHEMA,projection_sha256:PERFORMANCE_PROJECTION_SHA256,index:nextIndex,drafts:nextDrafts,attempted:[...nextAttempted]}));}catch{/* unavailable */}};
  useEffect(()=>{if(restored)persistPractice(index,drafts,attempted);},[attempted,drafts,index,restored]); useEffect(()=>onAttemptChange?.(attempted.size>0),[attempted,onAttemptChange]); if(!item)return null;
  const record=()=>{if(!draft.trim())return;const next=new Set([...attempted,index]);persistPractice(index,drafts,next);setAttempted(next);}; const move=(nextIndex:number)=>{persistPractice(nextIndex,drafts,attempted);setIndex(nextIndex);requestAnimationFrame(()=>inputRef.current?.focus());};
  return <div className={`${styles.practiceJourney} ${styles.performancePractice}`} data-practice-gate="attempt-before-reveal" data-practice-index={index}><p>{learnerText(stage.attempt_rule,locale)}</p><article className={styles.learnerCard} data-transfer-card={marker}><header className={styles.cardHeader}><div><span>{learnerText(item.level,locale)}</span><h3>{learnerText(item.title,locale)}</h3></div><strong>{t.practice} {index+1} {t.of} 4</strong></header><p>{learnerText(item.prompt,locale)}</p><label className={styles.responseField}><span>{t.answer}</span><textarea ref={inputRef} value={draft} onChange={(event)=>{const next={...drafts,[index]:event.target.value};persistPractice(index,next,attempted);setDrafts(next);}} rows={5}/></label><button className={styles.learningButton} type="button" data-action="record-practice" disabled={!draft.trim()} onClick={record}>{t.attempt}</button><p className={styles.statusText} aria-live="polite">{hasAttempt?t.attempted:""}</p>{hasAttempt&&<div className={styles.afterAttempt} data-answer-revealed="true"><details><summary>{t.hint}</summary><p>{learnerText(item.hint,locale)}</p></details><details><summary>{t.model}</summary><p>{learnerText(item.model_answer,locale)}</p></details><p><strong>{t.check}: </strong>{learnerText(item.success_check,locale)}</p></div>}</article><nav className={styles.itemNav} aria-label={stage.name[locale]}><button type="button" data-action="previous-practice" disabled={index===0} onClick={()=>move(Math.max(0,index-1))}>← {t.previousPractice}</button><button type="button" data-action="next-practice" disabled={index>=3||!hasAttempt} onClick={()=>move(Math.min(3,index+1))}>{t.nextPractice} →</button></nav></div>;
}
