"use client";

import { useEffect,useMemo,useRef,useState } from "react";
import { Button,CodePanel,Feedback,Textarea } from "@/app/components/algocore-ui";
import type { StackLearnerProjection } from "./learnerProjection";
import { learnerText } from "./learnerProjection";
import { STACK_PRACTICE_KEY,STACK_PRACTICE_SCHEMA,STACK_PROGRESS_KEY,STACK_PROJECTION_SHA256,createInitialStackProgress,isStackComplete,restoreStackProgress,stackCheckpointId,stackStep,stackVariants,type StackTraceProgress } from "./stackProjectionAdapter";
import type { LearningLocale } from "./types";
import styles from "./LessonLearningPage.module.css";

const copy={
 en:{free:"free",top:"top",operation:"Pending operation",outcome:"Outcome",hidden:"Predict before reveal",prediction:"Your prediction",placeholder:"State the guard, pointer and live stack…",record:"Record prediction",recorded:"Prediction recorded",previous:"Previous",next:"Next",support:"Rejected operations: state stays unchanged",empty:"Empty pop",rejected:"Overflow and underflow",before:"Before",after:"After",practice:"Practice item",of:"of",answer:"Your answer",attempt:"Record attempt",attempted:"Attempt recorded. Support is now available.",hint:"Hint",model:"Model answer",check:"Success check",previousPractice:"Previous practice",nextPractice:"Next practice",currentTop:"Current top",nextFree:"Next free",rule:"Rule"},
 vi:{free:"trống",top:"top",operation:"Operation sắp chạy",outcome:"Outcome",hidden:"Dự đoán trước khi mở",prediction:"Dự đoán của bạn",placeholder:"Nêu guard, pointer và live stack…",record:"Ghi nhận dự đoán",recorded:"Đã ghi nhận dự đoán",previous:"Trước",next:"Tiếp",support:"Operation bị từ chối: state giữ nguyên",empty:"Pop khi rỗng",rejected:"Overflow và underflow",before:"Trước",after:"Sau",practice:"Bài luyện",of:"trên",answer:"Câu trả lời",attempt:"Ghi nhận lần làm",attempted:"Đã ghi nhận. Phần hỗ trợ đã được mở.",hint:"Gợi ý",model:"Đáp án mẫu",check:"Điểm tự kiểm",previousPractice:"Bài luyện trước",nextPractice:"Bài luyện tiếp",currentTop:"Current top",nextFree:"Next free",rule:"Quy tắc"}
} as const;

function save(p:StackTraceProgress){try{sessionStorage.setItem(STACK_PROGRESS_KEY,JSON.stringify(p));}catch{/* unavailable */}}
export function StackTrace({projection,locale,onLearnerProgress}:Readonly<{projection:StackLearnerProjection;locale:LearningLocale;onLearnerProgress:(complete:boolean)=>void}>){
 const t=copy[locale],[progress,setProgress]=useState<StackTraceProgress>(createInitialStackProgress),[restored,setRestored]=useState(false);const id=stackCheckpointId(progress.checkpoint_index),step=stackStep(projection,progress.checkpoint_index),draft=progress.drafts[id]??"",revealed=progress.revealed_checkpoint_ids.includes(id),complete=isStackComplete(progress),variants=useMemo(()=>stackVariants(projection),[projection]);
 useEffect(()=>{const p=restoreStackProgress(sessionStorage.getItem(STACK_PROGRESS_KEY));if(p)setProgress(p);setRestored(true)},[]);useEffect(()=>{if(restored)onLearnerProgress(complete)},[complete,onLearnerProgress,restored]);
 const commit=(p:StackTraceProgress)=>{save(p);setProgress(p)},setDraft=(value:string)=>commit({...progress,phase:"predict",drafts:{...progress.drafts,[id]:value}}),reveal=()=>{if(!draft.trim())return;commit({...progress,phase:"revealed",revealed_checkpoint_ids:[...new Set([...progress.revealed_checkpoint_ids,id])]})},move=(i:0|1|2|3)=>{const next=stackCheckpointId(i);commit({...progress,checkpoint_index:i,phase:progress.revealed_checkpoint_ids.includes(next)?"revealed":"predict"});requestAnimationFrame(()=>document.getElementById("stack-trace-prediction")?.focus())};
 const before=progress.checkpoint_index===0?{items:projection.stages.trace.scenario.initial_items,live:[] as number[],top:-1}:projection.stages.trace.steps[progress.checkpoint_index-1].expected,shown=revealed?step.expected:before,operation=step.operation.join(" ");
 return <section className={styles.stackTrace} data-testid="paper4-stack-trace" data-scene="current-top" data-case-kind="normal-current-top" data-checkpoint-index={progress.checkpoint_index} data-phase={revealed?"revealed":"predict"} data-stack-complete={complete?"true":"false"}>
  <div className={styles.stackPanels}>
   <section className={styles.stackVisual} data-trace-panel="stack-state"><div className={styles.stackOperation} data-stack-operation><strong>{t.operation}</strong><span>{operation}</span></div><div className={styles.stackSlots}>{shown.items.map((value,index)=><div key={index} data-stack-slot-index={index} data-stack-slot-state={index<=shown.top?"live":"free"}><small>index {index}</small><strong>{index<=shown.top?value:t.free}</strong>{index===shown.top&&<span data-stack-top>← {t.top} = {shown.top}</span>}</div>)}</div><div className={styles.stackOutcome} data-stack-outcome>{revealed?<><strong>{t.outcome}</strong><span>{String(step.expected.outcome)}</span></>:<span>{t.hidden}</span>}</div><div data-code-panel="stack-focus"><CodePanel title="Focused Python" caption={`${t.operation}: ${operation}`} lines={step.code_focus.map((text,index)=>({number:index+1,text,active:true}))}/></div></section>
   <section className={styles.stackPrediction} data-trace-panel="prediction" data-trace-prediction><Textarea id="stack-trace-prediction" label={learnerText(step.prediction,locale)} placeholder={t.placeholder} rows={4} value={draft} onChange={e=>setDraft(e.target.value)}/><Button data-action="record-prediction" disabled={!draft.trim()} onClick={reveal}>{t.record}</Button>{revealed&&<div data-answer-revealed="true"><Feedback status="info" title={t.recorded}>{learnerText(step.answer,locale)}</Feedback></div>}</section>
  </div>
  <nav className={styles.traceStepNav} aria-label={projection.stages.trace.name[locale]}><Button variant="secondary" data-action="previous" disabled={progress.checkpoint_index===0} onClick={()=>move((progress.checkpoint_index-1) as 0|1|2|3)}>← {t.previous}</Button><Button variant="secondary" data-action="next" disabled={!revealed||progress.checkpoint_index===3} onClick={()=>move((progress.checkpoint_index+1) as 0|1|2|3)}>{t.next} →</Button></nav>
  {complete&&<section className={styles.stackSupport}><h3>{t.support}</h3><div>{variants.map((variant,index)=><article key={variant.kind} data-support-case={variant.kind} data-case-kind={index===0?"boundary-empty-pop":"rejected-operations"}><h4>{index===0?t.empty:t.rejected}</h4>{index===0?<div className={styles.stackBeforeAfter} data-rejection="underflow-empty"><div><strong>{t.before}</strong><p>items [empty] · live [] · top -1</p></div><div><strong>{t.after}</strong><p>None · items [empty] · live [] · top -1</p></div></div>:<div className={styles.stackRejectionPairs}><section data-rejection="overflow-full"><h5>push(3) · overflow</h5><div className={styles.stackBeforeAfter}><div><strong>{t.before}</strong><p>items [1, 2] · live [1, 2] · top 1</p></div><div><strong>{t.after}</strong><p>False · items [1, 2] · live [1, 2] · top 1</p></div></div></section><section data-rejection="underflow-empty"><h5>pop() · underflow</h5><div className={styles.stackBeforeAfter}><div><strong>{t.before}</strong><p>items [empty, empty] · live [] · top -1</p></div><div><strong>{t.after}</strong><p>None · items [empty, empty] · live [] · top -1</p></div></div></section><p><strong>runner OK</strong> — {locale==="en"?"the run completed; the rejected operations did not mutate the stack.":"runner đã hoàn tất; các operation bị từ chối không làm thay đổi stack."}</p></div>}<p>{learnerText(variant.explanation,locale)}</p></article>)}</div></section>}
 </section>
}

type PracticeStage=StackLearnerProjection["stages"]["practise"];
export function StackPractice({stage,locale,onAttemptChange}:Readonly<{stage:PracticeStage;locale:LearningLocale;onAttemptChange?:(attempted:boolean)=>void}>){const t=copy[locale],input=useRef<HTMLTextAreaElement>(null),[index,setIndex]=useState(0),[drafts,setDrafts]=useState<Record<number,string>>({}),[attempted,setAttempted]=useState<ReadonlySet<number>>(new Set),[restored,setRestored]=useState(false),item=stage.items[index],draft=drafts[index]??"",done=attempted.has(index),marker=["push","pop","rejection","next-free","rebuild"][index];
 useEffect(()=>{try{const v=JSON.parse(sessionStorage.getItem(STACK_PRACTICE_KEY)??"null") as Record<string,unknown>|null;if(v?.schema_version===STACK_PRACTICE_SCHEMA&&v.projection_sha256===STACK_PROJECTION_SHA256&&Number.isInteger(v.index)&&(v.index as number)>=0&&(v.index as number)<5&&v.drafts&&typeof v.drafts==="object"&&!Array.isArray(v.drafts)&&Array.isArray(v.attempted)){const e=Object.entries(v.drafts as object),a=v.attempted as unknown[];if(e.every(([k,x])=>/^[0-4]$/.test(k)&&typeof x==="string")&&a.every(x=>Number.isInteger(x)&&(x as number)>=0&&(x as number)<5)){setIndex(v.index as number);setDrafts(Object.fromEntries(e));setAttempted(new Set(a as number[]))}}}catch{/* stale */}setRestored(true)},[]);
 const persist=(i:number,d:Record<number,string>,a:ReadonlySet<number>)=>{try{sessionStorage.setItem(STACK_PRACTICE_KEY,JSON.stringify({schema_version:STACK_PRACTICE_SCHEMA,projection_sha256:STACK_PROJECTION_SHA256,index:i,drafts:d,attempted:[...a]}))}catch{/* unavailable */}};useEffect(()=>{if(restored)persist(index,drafts,attempted)},[attempted,drafts,index,restored]);useEffect(()=>onAttemptChange?.(attempted.size>0),[attempted,onAttemptChange]);if(!item)return null;const record=()=>{if(!draft.trim())return;const a=new Set([...attempted,index]);persist(index,drafts,a);setAttempted(a)},move=(i:number)=>{persist(i,drafts,attempted);setIndex(i);requestAnimationFrame(()=>input.current?.focus())};
 return <div className={`${styles.practiceJourney} ${styles.stackPractice}`} data-practice-gate="attempt-before-reveal" data-practice-index={index}><p>{learnerText(stage.attempt_rule,locale)}</p><article className={styles.learnerCard} data-transfer-card={marker}><header className={styles.cardHeader}><div><span>{learnerText(item.level,locale)}</span><h3>{learnerText(item.title,locale)}</h3></div><strong>{t.practice} {index+1} {t.of} 5</strong></header><p>{learnerText(item.prompt,locale)}</p><label className={styles.responseField}><span>{t.answer}</span><textarea ref={input} rows={5} value={draft} onChange={e=>{const d={...drafts,[index]:e.target.value};persist(index,d,attempted);setDrafts(d)}}/></label><button className={styles.learningButton} data-action="record-practice" disabled={!draft.trim()} onClick={record}>{t.attempt}</button><p className={styles.statusText} aria-live="polite">{done?t.attempted:""}</p>{done&&<div className={styles.afterAttempt} data-answer-revealed="true">{index===3&&<table className={styles.stackTransferTable} data-next-free-transfer><caption>{t.nextFree}</caption><thead><tr><th>{t.rule}</th><th>{t.currentTop}</th><th>{t.nextFree}</th></tr></thead><tbody><tr><th>Empty</th><td>-1</td><td>0</td></tr><tr><th>Full</th><td>capacity - 1</td><td>capacity</td></tr><tr><th>Push</th><td>increment, then write</td><td>write, then increment</td></tr><tr><th>Pop item</th><td>items[top]</td><td>items[pointer - 1]</td></tr><tr><th>Translation</th><td>current_top = next_free - 1</td><td>next_free = current_top + 1</td></tr></tbody></table>}<details><summary>{t.hint}</summary><p>{learnerText(item.hint,locale)}</p></details><details><summary>{t.model}</summary><p>{learnerText(item.model_answer,locale)}</p></details><p><strong>{t.check}: </strong>{learnerText(item.success_check,locale)}</p></div>}</article><nav className={styles.itemNav} aria-label={stage.name[locale]}><button data-action="previous-practice" disabled={index===0} onClick={()=>move(index-1)}>← {t.previousPractice}</button><button data-action="next-practice" disabled={index===4||!done} onClick={()=>move(index+1)}>{t.nextPractice} →</button></nav></div>}
