import type { Paper3Lesson } from "./lesson-types";

// Server-side, per-topic imports keep the course map independent of lesson payloads.
const loaders: Record<string, () => Promise<{ default: unknown }>> = {
  "user-defined-and-enumerated-types": () => import("@/content/paper3/lessons/user-defined-and-enumerated-types.json"),
  "pointers-and-referenced-data": () => import("@/content/paper3/lessons/pointers-and-referenced-data.json"),
  "sets": () => import("@/content/paper3/lessons/sets.json"),
  "records-and-composite-models": () => import("@/content/paper3/lessons/records-and-composite-models.json"),
  "organisation-versus-access": () => import("@/content/paper3/lessons/organisation-versus-access.json"),
  "hashing-to-locate-records": () => import("@/content/paper3/lessons/hashing-to-locate-records.json"),
  "collisions-and-retrieval": () => import("@/content/paper3/lessons/collisions-and-retrieval.json"),
  "signed-floating-point-conversion": () => import("@/content/paper3/lessons/signed-floating-point-conversion.json"),
  "normalisation": () => import("@/content/paper3/lessons/normalisation.json"),
  "precision-range-and-limits": () => import("@/content/paper3/lessons/precision-range-and-limits.json"),
  "approximation-rounding-and-range-errors": () => import("@/content/paper3/lessons/approximation-rounding-and-range-errors.json"),
  "tcp-ip-stack-and-message-journey": () => import("@/content/paper3/lessons/tcp-ip-stack-and-message-journey.json"),
  "application-protocol-selection": () => import("@/content/paper3/lessons/application-protocol-selection.json"),
  "bittorrent-and-peer-to-peer-transfer": () => import("@/content/paper3/lessons/bittorrent-and-peer-to-peer-transfer.json"),
  "packet-journey-and-routers": () => import("@/content/paper3/lessons/packet-journey-and-routers.json"),
  "choosing-a-switching-method": () => import("@/content/paper3/lessons/choosing-a-switching-method.json"),
  "risc-and-cisc": () => import("@/content/paper3/lessons/risc-and-cisc.json"),
  "pipelines-registers-and-interrupts": () => import("@/content/paper3/lessons/pipelines-registers-and-interrupts.json"),
  "flynn-architectures-and-massive-parallelism": () => import("@/content/paper3/lessons/flynn-architectures-and-massive-parallelism.json"),
  "virtual-machines": () => import("@/content/paper3/lessons/virtual-machines.json"),
  "circuit-truth-table-and-expression": () => import("@/content/paper3/lessons/circuit-truth-table-and-expression.json"),
  "half-full-adders": () => import("@/content/paper3/lessons/half-full-adders.json"),
  "sr-and-jk-flip-flops": () => import("@/content/paper3/lessons/sr-and-jk-flip-flops.json"),
  "boolean-simplification": () => import("@/content/paper3/lessons/boolean-simplification.json"),
  "karnaugh-maps": () => import("@/content/paper3/lessons/karnaugh-maps.json"),
  "scheduling-choices": () => import("@/content/paper3/lessons/scheduling-choices.json"),
  "rpn-and-the-stack": () => import("@/content/paper3/lessons/rpn-and-the-stack.json"),
  "resources-processes-and-states": () => import("@/content/paper3/lessons/resources-processes-and-states.json"),
  "kernel-interrupts-and-scheduling": () => import("@/content/paper3/lessons/kernel-interrupts-and-scheduling.json"),
  "paging-segmentation-and-virtual-memory": () => import("@/content/paper3/lessons/paging-segmentation-and-virtual-memory.json"),
  "replacement-and-thrashing": () => import("@/content/paper3/lessons/replacement-and-thrashing.json"),
  "interpreter-versus-compiler": () => import("@/content/paper3/lessons/interpreter-versus-compiler.json"),
  "compilation-stages": () => import("@/content/paper3/lessons/compilation-stages.json"),
  "bnf-and-syntax-diagrams": () => import("@/content/paper3/lessons/bnf-and-syntax-diagrams.json"),
  "confidentiality-and-key-choice": () => import("@/content/paper3/lessons/confidentiality-and-key-choice.json"),
  "quantum-cryptography": () => import("@/content/paper3/lessons/quantum-cryptography.json"),
  "ssl-tls-communication": () => import("@/content/paper3/lessons/ssl-tls-communication.json"),
  "certificates-and-signatures": () => import("@/content/paper3/lessons/certificates-and-signatures.json"),
  "graphs-and-dijkstra": () => import("@/content/paper3/lessons/graphs-and-dijkstra.json"),
  "a-star-and-heuristic-search": () => import("@/content/paper3/lessons/a-star-and-heuristic-search.json"),
  "learning-categories": () => import("@/content/paper3/lessons/learning-categories.json"),
  "neural-networks-and-deep-learning": () => import("@/content/paper3/lessons/neural-networks-and-deep-learning.json"),
  "backpropagation": () => import("@/content/paper3/lessons/backpropagation.json"),
  "regression": () => import("@/content/paper3/lessons/regression.json"),
  "linear-search": () => import("@/content/paper3/lessons/linear-search.json"),
  "binary-search": () => import("@/content/paper3/lessons/binary-search.json"),
  "bubble-sort": () => import("@/content/paper3/lessons/bubble-sort.json"),
  "insertion-sort": () => import("@/content/paper3/lessons/insertion-sort.json"),
  "stack": () => import("@/content/paper3/lessons/stack.json"),
  "queue": () => import("@/content/paper3/lessons/queue.json"),
  "linked-list": () => import("@/content/paper3/lessons/linked-list.json"),
  "binary-tree": () => import("@/content/paper3/lessons/binary-tree.json"),
  "dictionary": () => import("@/content/paper3/lessons/dictionary.json"),
  "implementing-one-adt-with-another": () => import("@/content/paper3/lessons/implementing-one-adt-with-another.json"),
  "time-and-space-complexity": () => import("@/content/paper3/lessons/time-and-space-complexity.json"),
  "designing-and-tracing-recursion": () => import("@/content/paper3/lessons/designing-and-tracing-recursion.json"),
  "call-stacks-and-unwinding": () => import("@/content/paper3/lessons/call-stacks-and-unwinding.json"),
  "paradigms-and-procedural-design": () => import("@/content/paper3/lessons/paradigms-and-procedural-design.json"),
  "five-addressing-modes": () => import("@/content/paper3/lessons/five-addressing-modes.json"),
  "assembly-execution-and-construction": () => import("@/content/paper3/lessons/assembly-execution-and-construction.json"),
  "class-object-design-and-encapsulation": () => import("@/content/paper3/lessons/class-object-design-and-encapsulation.json"),
  "inheritance-polymorphism-and-aggregation": () => import("@/content/paper3/lessons/inheritance-polymorphism-and-aggregation.json"),
  "declarative-facts-rules-and-goals": () => import("@/content/paper3/lessons/declarative-facts-rules-and-goals.json"),
  "serial-sequential-text-file-workflows": () => import("@/content/paper3/lessons/serial-sequential-text-file-workflows.json"),
  "random-file-record-operations": () => import("@/content/paper3/lessons/random-file-record-operations.json"),
  "exceptions-and-controlled-recovery": () => import("@/content/paper3/lessons/exceptions-and-controlled-recovery.json"),
};

export async function getLesson(slug: string): Promise<Paper3Lesson | undefined> {
  const load = loaders[slug];
  return load ? (await load()).default as Paper3Lesson : undefined;
}

export const implementedLessonSlugs = Object.keys(loaders);
