import type { Localized } from "./catalog";
export type SystemSoftwareKind="process-states"|"cpu-scheduling"|"kernel-interrupts"|"memory-addressing"|"page-replacement";
export interface SystemStep<S>{readonly id:string;readonly title:Localized;readonly action:Localized;readonly why:Localized;readonly outcome:Localized;readonly before:S;readonly after:S}
const L=(en:string,vi:string):Localized=>({en,vi});
function freeze<T>(value:T):T{if(value!==null&&typeof value==="object"&&!Object.isFrozen(value)){Object.values(value).forEach(freeze);Object.freeze(value);}return value;}
export type SchedulingAlgorithm="fcfs"|"rr"|"sjf"|"srt";
export interface ProcessSpec{readonly id:string;readonly arrival:number;readonly burst:number}
export const schedulingProcesses:readonly ProcessSpec[]=freeze([{id:"P1",arrival:0,burst:7},{id:"P2",arrival:2,burst:4},{id:"P3",arrival:4,burst:1},{id:"P4",arrival:5,burst:3}]);
export const schedulingAlgorithms=freeze([{id:"fcfs",label:L("FCFS · first come, first served","FCFS · đến trước phục vụ trước")},{id:"rr",label:L("Round robin · quantum","Round robin · lát thời gian")},{id:"sjf",label:L("SJF · non-preemptive","SJF · không cưỡng đoạt")},{id:"srt",label:L("SRT · shortest remaining time","SRT · thời gian còn lại ngắn nhất")} ] as const);
export interface SchedulingMetric{readonly id:string;readonly arrival:number;readonly burst:number;readonly start:number|null;readonly completion:number|null;readonly waiting:number|null;readonly turnaround:number|null;readonly response:number|null}
export interface SchedulingState{readonly intervalStart:number;readonly intervalEnd:number;readonly cpu:string|null;readonly readyAtStart:readonly string[];readonly remainingAfter:Readonly<Record<string,number>>;readonly completed:readonly string[];readonly arrivals:readonly string[];readonly events:readonly Localized[];readonly timeline:readonly {readonly start:number;readonly end:number;readonly process:string|null}[];readonly metrics:readonly SchedulingMetric[]}
export function schedulingTrace(algorithm:SchedulingAlgorithm,processes:readonly ProcessSpec[]=schedulingProcesses,quantum=2){
 if(!schedulingAlgorithms.some(item=>item.id===algorithm))throw new RangeError("Unknown scheduling algorithm");
 if(processes.length<1||processes.length>6||new Set(processes.map(p=>p.id)).size!==processes.length||processes.some(p=>!/^P[1-9]$/.test(p.id)||!Number.isInteger(p.arrival)||p.arrival<0||p.arrival>32||!Number.isInteger(p.burst)||p.burst<1||p.burst>16)||processes.reduce((n,p)=>n+p.burst,0)>64)throw new RangeError("Use1–6 distinct P1–P9 processes, arrivals0–32 and bursts1–16; total burst at most64");
 if(!Number.isInteger(quantum)||quantum<1||quantum>8)throw new RangeError("Quantum must be1–8");
 const specs=[...processes].sort((a,b)=>a.arrival-b.arrival||a.id.localeCompare(b.id));const remaining:Record<string,number>=Object.fromEntries(specs.map(p=>[p.id,p.burst]));const starts:Record<string,number>={},ends:Record<string,number>={};let ready:string[]=[],running:string|null=null,slice=0,time=0;
 const timeline:{start:number;end:number;process:string|null}[]=[],steps:SystemStep<SchedulingState>[]=[];
 const metrics=():SchedulingMetric[]=>specs.map(p=>({id:p.id,arrival:p.arrival,burst:p.burst,start:starts[p.id]??null,completion:ends[p.id]??null,waiting:ends[p.id]===undefined?null:ends[p.id]-p.arrival-p.burst,turnaround:ends[p.id]===undefined?null:ends[p.id]-p.arrival,response:starts[p.id]===undefined?null:starts[p.id]-p.arrival}));
 let state:SchedulingState=freeze({intervalStart:0,intervalEnd:0,cpu:null,readyAtStart:[],remainingAfter:{...remaining},completed:[],arrivals:[],events:[],timeline:[],metrics:metrics()});const initial=state;
 steps.push(freeze({id:"ready",title:L("Inspect the process task","Quan sát bài toán tiến trình"),action:L("Use one CPU and the stated arrivals and CPU bursts.","Dùng một CPU cùng thời điểm đến và CPU burst đã cho."),why:L("No I/O or switching overhead is included. Arrivals and quantum expiry are processed at the declared boundaries.","Không có I/O hay chi phí chuyển ngữ cảnh. Lượt đến và hết quantum được xử lý tại ranh giới đã khai báo."),outcome:L("No CPU time has been consumed.","Chưa dùng thời gian CPU."),before:state,after:state}));
 const rank=(a:string,b:string)=>remaining[a]-remaining[b]||specs.find(p=>p.id===a)!.arrival-specs.find(p=>p.id===b)!.arrival||a.localeCompare(b);
 while(Object.keys(ends).length<specs.length){const before=state;const arrivals=specs.filter(p=>p.arrival===time).map(p=>p.id);const events:Localized[]=[];ready.push(...arrivals);if(arrivals.length)events.push(L(`Admit ${arrivals.join(", ")} to ready.`,`Đưa ${arrivals.join(", ")} vào ready.`));
  if(algorithm==="rr"&&running&&slice===quantum){ready.push(running);events.push(L(`Quantum expires: ${running} returns to ready after new arrivals.`,`Hết quantum: ${running} trở lại ready sau các tiến trình mới đến.`));running=null;slice=0;}
  if(algorithm==="srt"&&running&&ready.length){const candidate=[...ready].sort(rank)[0];if(remaining[candidate]<remaining[running]){events.push(L(`Preempt ${running}: ${candidate} has strictly less remaining time.`, `Cưỡng đoạt ${running}: ${candidate} có thời gian còn lại ngắn hơn nghiêm ngặt.`));ready.push(running);running=null;slice=0;}}
  if(!running&&ready.length){if(algorithm==="sjf"||algorithm==="srt"){const candidate=[...ready].sort(rank)[0];running=ready.splice(ready.indexOf(candidate),1)[0];}else running=ready.shift()!;slice=0;if(starts[running]===undefined)starts[running]=time;events.push(L(`Dispatch ${running}.`,`Cấp CPU cho ${running}.`));}
  const cpu=running,readyAtStart=[...ready];timeline.push({start:time,end:time+1,process:cpu});if(cpu){remaining[cpu]--;slice++;if(remaining[cpu]===0){ends[cpu]=time+1;events.push(L(`${cpu} completes at ${time+1}.`,`${cpu} hoàn tất lúc ${time+1}.`));running=null;slice=0;}}else events.push(L("CPU is idle; no quantum is consumed.","CPU rảnh; không tiêu thụ quantum."));
  state=freeze({intervalStart:time,intervalEnd:time+1,cpu,readyAtStart,remainingAfter:{...remaining},completed:Object.keys(ends),arrivals,events,timeline:[...timeline],metrics:metrics()});
  steps.push(freeze({id:`interval-${time}`,title:L(`Time ${time} → ${time+1}`,`Thời gian ${time} → ${time+1}`),action:L(cpu?`Run ${cpu} for one time unit.`:"Leave the CPU idle for this interval.",cpu?`Chạy ${cpu} trong một đơn vị thời gian.`:"CPU rảnh trong khoảng này."),why:algorithm==="rr"?L(`Quantum=${quantum}; completions happen first, then arrivals, then requeue an unfinished expired process.`,`Quantum=${quantum}; hoàn tất trước, rồi nhận lượt đến, sau đó đưa tiến trình chưa xong hết quantum về hàng đợi.`):algorithm==="srt"?L("Compare remaining CPU time, not original burst. Equal remaining time keeps the current process.","So thời gian CPU còn lại, không so burst gốc. Bằng nhau thì giữ tiến trình đang chạy."):algorithm==="sjf"?L("Choose the shortest ready burst only when the CPU becomes free; do not preempt the running process.","Chọn burst ngắn nhất trong ready khi CPU rảnh; không cưỡng đoạt tiến trình đang chạy."):L("Choose ready processes by arrival, then process ID; run each to completion.","Chọn tiến trình ready theo lượt đến rồi ID; chạy mỗi tiến trình đến khi hoàn tất."),outcome:L(cpu?`${cpu} has ${remaining[cpu]} CPU time units left.`:"No process ran in this interval.",cpu?`${cpu} còn ${remaining[cpu]} đơn vị CPU.`:"Không tiến trình nào chạy trong khoảng này."),before,after:state}));time++;if(time>96)throw new Error("Scheduling bound exceeded");
 }
 const finalMetrics=metrics(),average=(key:"waiting"|"turnaround"|"response")=>({numerator:finalMetrics.reduce((sum,m)=>sum+m[key]!,0),denominator:finalMetrics.length});
 return freeze({algorithm,processes:specs,quantum,initial,steps,metrics:finalMetrics,averages:{waiting:average("waiting"),turnaround:average("turnaround"),response:average("response")},finishedAt:time});
}
export type ProcessEvent="dispatch-p1"|"io-request"|"dispatch-p2"|"io-complete"|"timer-preempt"|"resume-p1";
export interface ProcessState{readonly cpu:"P1"|"P2"|null;readonly ready:readonly string[];readonly blocked:readonly string[];readonly states:Readonly<Record<string,"ready"|"running"|"blocked">>}
export const processEvents=freeze([{id:"dispatch-p1",label:L("Dispatch P1","Cấp CPU cho P1")},{id:"io-request",label:L("P1 requests I/O","P1 yêu cầu I/O")},{id:"dispatch-p2",label:L("Dispatch P2","Cấp CPU cho P2")},{id:"io-complete",label:L("P1 I/O completes","I/O của P1 hoàn tất")},{id:"timer-preempt",label:L("Preempt P2 on timer","Cưỡng đoạt P2 khi hết lượt")},{id:"resume-p1",label:L("Dispatch P1 again","Cấp CPU lại cho P1")}] as const);
export const initialProcessState:ProcessState=freeze({cpu:null,ready:["P1","P2"],blocked:[],states:{P1:"ready",P2:"ready"}});
export function processTransition(before:ProcessState,event:ProcessEvent){const states={...before.states};let cpu=before.cpu,ready=[...before.ready],blocked=[...before.blocked],valid=true;let action:Localized,why:Localized;
 if(event==="dispatch-p1"||event==="resume-p1"||event==="dispatch-p2"){const id=event==="dispatch-p2"?"P2":"P1";valid=cpu===null&&states[id]==="ready";action=L(`Dispatch ${id} from ready to running.`,`Chuyển ${id} từ ready sang running.`);why=L("Only a ready process can be dispatched onto a free CPU; a blocked process must first become ready.","Chỉ tiến trình ready được cấp CPU đang rảnh; tiến trình blocked phải trở về ready trước.");if(valid){cpu=id;ready=ready.filter(x=>x!==id);states[id]="running";}}
 else if(event==="io-request"){valid=cpu==="P1";action=L("P1 waits for I/O: running → blocked.","P1 chờ I/O: running → blocked.");why=L("P1 cannot continue until its requested I/O completes; the CPU becomes available.","P1 chưa thể tiếp tục cho đến khi I/O hoàn tất; CPU được nhường lại.");if(valid){cpu=null;states.P1="blocked";blocked.push("P1");}}
 else if(event==="io-complete"){valid=states.P1==="blocked";action=L("Move P1 from blocked to ready; keep the current running process.","Đưa P1 từ blocked về ready; giữ tiến trình đang chạy.");why=L("I/O completion makes P1 eligible for CPU time; it does not dispatch P1 directly.","I/O hoàn tất giúp P1 đủ điều kiện nhận CPU; không chuyển thẳng P1 sang running.");if(valid){blocked=blocked.filter(x=>x!=="P1");ready.push("P1");states.P1="ready";}}
 else{valid=cpu==="P2";action=L("Preempt P2: running → ready.","Cưỡng đoạt P2: running → ready.");why=L("A timer expiry removes CPU ownership, not eligibility; P2 is ready, not blocked.","Hết lượt làm P2 mất CPU nhưng vẫn đủ điều kiện chạy; P2 về ready, không về blocked.");if(valid){cpu=null;ready.push("P2");states.P2="ready";}}
 const after=valid?freeze({cpu,ready,blocked,states}):before;return freeze({valid,after,title:processEvents.find(x=>x.id===event)!.label,action:valid?action:L("Reject this transition; retain the state.","Từ chối chuyển trạng thái; giữ nguyên hiện tại."),why,outcome:valid?L(`CPU=${cpu??"idle"}; ready=${ready.join(", ")||"empty"}; blocked=${blocked.join(", ")||"empty"}.`,`CPU=${cpu??"rảnh"}; ready=${ready.join(", ")||"trống"}; blocked=${blocked.join(", ")||"trống"}.`):L("The event's precondition is not satisfied. No process state changes.","Điều kiện của sự kiện chưa thỏa. Không đổi trạng thái tiến trình.")});
}
export function processTrace(){let state=initialProcessState;const steps:SystemStep<ProcessState>[]=[{id:"ready",title:L("Two processes are ready","Hai tiến trình ready"),action:L("Inspect P1 and P2 waiting for a CPU.","Quan sát P1 và P2 đang chờ CPU."),why:L("Ready means able to run once selected by the scheduler.","Ready nghĩa là có thể chạy khi được bộ lập lịch chọn."),outcome:L("CPU idle; P1 and P2 ready.","CPU rảnh; P1 và P2 ready."),before:state,after:state}];for(const event of processEvents){const before=state,result=processTransition(state,event.id);state=result.after;steps.push({id:event.id,title:result.title,action:result.action,why:result.why,outcome:result.outcome,before,after:state});}return freeze({initial:initialProcessState,steps});}
export interface InterruptState{readonly phase:string;readonly running:string|null;readonly cpu:{readonly PC:number;readonly R1:number}|null;readonly saved:Readonly<Record<string,{readonly PC:number;readonly R1:number}>>;readonly ready:readonly string[];readonly blocked:readonly string[];readonly selected:string|null}
export function interruptTrace(kind:"timer"|"io"){let state:InterruptState=freeze({phase:"application",running:"P1",cpu:{PC:120,R1:7},saved:{P2:{PC:240,R1:3}},ready:kind==="timer"?["P2"]:[],blocked:kind==="io"?["P2"]:[],selected:null});const initial=state,steps:SystemStep<InterruptState>[]=[];const emit=(id:string,title:Localized,action:Localized,why:Localized,next:InterruptState)=>{const before=state;state=freeze(next);steps.push(freeze({id,title,action,why,outcome:L(`Phase=${state.phase}; selected=${state.selected??"none"}; ready=${state.ready.join(", ")||"empty"}.`,`Pha=${state.phase}; chọn=${state.selected??"chưa có"}; ready=${state.ready.join(", ")||"trống"}.`),before,after:state}));};
 emit("ready",L("Application is running","Ứng dụng đang chạy"),L("P1 owns the CPU with PC=120 and R1=7.","P1 giữ CPU với PC=120 và R1=7."),L("These finite register values illustrate saved context, not a real instruction address space.","Các giá trị thanh ghi hữu hạn minh họa ngữ cảnh, không mô tả không gian lệnh thật."),state);
 emit("save-context",L("Save the interrupted context","Lưu ngữ cảnh bị ngắt"),L("Save P1 PC and register values before running the handler.","Lưu PC và các thanh ghi P1 trước khi chạy trình xử lý."),L("P1 must be able to resume from its saved state.","P1 cần có thể tiếp tục từ trạng thái đã lưu."),{...state,phase:"save",running:null,cpu:null,saved:{...state.saved,P1:{PC:120,R1:7}}});
 emit("handle-interrupt",L("Run the interrupt handler","Chạy trình xử lý ngắt"),kind==="timer"?L("Handle the timer interrupt.","Xử lý ngắt bộ định thời."):L("Acknowledge completion of P2's I/O.","Ghi nhận I/O của P2 đã hoàn tất."),L("Servicing an interrupt and choosing the next process are separate responsibilities.","Xử lý ngắt và chọn tiến trình tiếp theo là hai trách nhiệm riêng."),{...state,phase:"handler"});
 emit("update-ready",L("Update process queues","Cập nhật hàng đợi"),kind==="timer"?L("P1's turn ends; append P1 to ready.","Lượt P1 kết thúc; đưa P1 vào ready."):L("Move P2 from blocked to ready.","Đưa P2 từ blocked sang ready."),kind==="timer"?L("Preemption returns a runnable process to ready, not blocked.","Cưỡng đoạt đưa tiến trình còn chạy được về ready, không về blocked."):L("The I/O event removes P2's reason for waiting.","Sự kiện I/O loại bỏ lý do P2 phải chờ."),{...state,phase:"queues",ready:kind==="timer"?["P2","P1"]:["P2"],blocked:[]});
 const selected=kind==="timer"?"P2":"P1";
 emit("select-process",L("Apply the scheduling decision","Áp dụng quyết định lập lịch"),L(`Select ${selected}.`,`Chọn ${selected}.`),kind==="timer"?L("This scenario switches to ready P2.","Tình huống này chuyển sang P2 đang ready."):L("This scenario resumes P1. An interrupt does not always require a process switch.","Tình huống này tiếp tục P1. Ngắt không luôn buộc chuyển tiến trình."),{...state,phase:"select",selected,ready:state.ready.filter(x=>x!==selected)});
 emit("restore-context",L("Restore the selected context","Khôi phục ngữ cảnh được chọn"),L(`Restore ${selected}'s saved PC and R1.`,`Khôi phục PC và R1 đã lưu của ${selected}.`),L("The CPU uses the selected process's values, not the previous process's values.","CPU dùng giá trị của tiến trình được chọn, không dùng nhầm giá trị tiến trình trước."),{...state,phase:"restore",cpu:state.saved[selected]});
 emit("resume",L("Resume execution","Tiếp tục thực thi"),L(`${selected} continues with its restored context.`,`${selected} tiếp tục với ngữ cảnh đã khôi phục.`),L("Context restoration completes the transition back to application execution.","Khôi phục ngữ cảnh hoàn tất việc trở lại thực thi ứng dụng."),{...state,phase:"application",running:selected});return freeze({kind,initial,steps});}
export const memoryPageSize=16;
export const memorySegments=freeze([{segment:0,base:100,limit:20},{segment:1,base:300,limit:12}]);
export interface MemoryState{readonly mode:"paging"|"segmentation";readonly logical:number;readonly page:number|null;readonly segment:number|null;readonly offset:number|null;readonly frame:number|null;readonly base:number|null;readonly limit:number|null;readonly physical:number|null;readonly pageTable:readonly {readonly page:number;readonly frame:number|null;readonly present:boolean}[];readonly status:"ready"|"lookup"|"fault"|"loaded"|"translated"|"bounds-error"}
export function memoryTrace(mode:"paging"|"segmentation",address=35,segment=1){if(!Number.isInteger(address)||address<0||address>63||!Number.isInteger(segment)||segment<0||segment>1)throw new RangeError("Address0–63; segment0–1");let state:MemoryState=freeze({mode,logical:address,page:null,segment:mode==="segmentation"?segment:null,offset:null,frame:null,base:null,limit:null,physical:null,pageTable:[{page:0,frame:1,present:true},{page:1,frame:4,present:true},{page:2,frame:5,present:true},{page:3,frame:null,present:false}],status:"ready"});const initial=state,steps:SystemStep<MemoryState>[]=[];const emit=(id:string,title:Localized,action:Localized,why:Localized,outcome:Localized,patch:Partial<MemoryState>)=>{const before=state;state=freeze({...state,...patch});steps.push(freeze({id,title,action,why,outcome,before,after:state}));};
 emit("ready",L("Inspect the logical address","Quan sát địa chỉ logic"),mode==="paging"?L(`Logical address=${address}; page size=16.`,`Địa chỉ logic=${address}; kích thước trang=16.`):L(`Segment=${segment}; offset=${address}.`,`Segment=${segment}; offset=${address}.`),L("Translate through the mapping; a logical number is not already a physical address.","Dịch qua bảng ánh xạ; số logic chưa phải địa chỉ vật lý."),L("No physical address yet.","Chưa có địa chỉ vật lý."),{});
 if(mode==="paging"){const page=Math.floor(address/16),offset=address%16;emit("split-address",L("Split page and offset","Tách số trang và offset"),L(`${address} DIV16=${page}; ${address} MOD16=${offset}.`,`${address} DIV16=${page}; ${address} MOD16=${offset}.`),L("Fixed-size pages use quotient for page number and remainder for offset.","Trang kích thước cố định dùng thương làm số trang, số dư làm offset."),L(`Page=${page}, offset=${offset}.`,`Trang=${page}, offset=${offset}.`),{page,offset,status:"lookup"});let frame=state.pageTable[page].frame;emit("lookup",L("Look up the page table","Tra bảng trang"),L(`Read entry ${page} and its present bit.`,`Đọc mục ${page} và bit present.`),L("Only a present mapping can supply a physical frame.","Chỉ ánh xạ hiện diện mới cung cấp frame vật lý."),L(frame===null?"Present=0; no valid frame yet.":`Present=1; frame=${frame}.`,frame===null?"Present=0; chưa có frame hợp lệ.":`Present=1; frame=${frame}.`),{frame});if(frame===null){emit("page-fault",L("Page fault","Lỗi trang"),L("Request the missing page from backing store.","Yêu cầu trang thiếu từ backing store."),L("The requested page is not currently in RAM. Do not calculate a physical address yet.","Trang yêu cầu chưa ở RAM. Chưa tính địa chỉ vật lý."),L("Execution waits for the page; a free frame is available.","Thực thi chờ trang; đang có frame trống."),{status:"fault"});frame=2;emit("load-page",L("Load into the free frame","Nạp vào frame trống"),L("Load page3 into free frame2 and update the page table.","Nạp trang3 vào frame2 trống rồi cập nhật bảng trang."),L("A page fault does not require eviction when a free frame is available.","Lỗi trang không cần thay trang khi có frame trống."),L("Present=1; frame2 now maps page3.","Present=1; frame2 nay chứa trang3."),{frame,pageTable:state.pageTable.map(p=>p.page===3?{...p,frame:2,present:true}:p),status:"loaded"});emit("retry",L("Retry the logical access","Thử lại truy cập logic"),L(`Read page${page}'s updated mapping.`,`Đọc ánh xạ mới của trang${page}.`),L("The offset is unchanged by loading the page.","Offset không đổi khi nạp trang."),L(`Frame=${frame}; offset=${offset}.`,`Frame=${frame}; offset=${offset}.`),{status:"lookup"});}emit("translate",L("Construct the physical address","Tạo địa chỉ vật lý"),L(`${frame} ×16 + ${offset} = ${frame*16+offset}.`,`${frame} ×16 + ${offset} = ${frame*16+offset}.`),L("Use frame base plus offset, not page number plus offset.","Dùng đầu frame cộng offset, không dùng số trang cộng offset."),L(`Physical address=${frame*16+offset}.`,`Địa chỉ vật lý=${frame*16+offset}.`),{physical:frame*16+offset,status:"translated"});}
 else{const {base,limit}=memorySegments[segment];emit("lookup-segment",L("Read segment base and limit","Đọc base và limit của segment"),L(`Segment${segment}: base=${base}, limit=${limit}.`,`Segment${segment}: base=${base}, limit=${limit}.`),L("The segment number selects an entry; it is not the base address.","Số segment chọn một mục; nó không phải địa chỉ base."),L(`Check 0 ≤ ${address} < ${limit}.`,`Kiểm tra 0 ≤ ${address} < ${limit}.`),{base,limit,offset:address,status:"lookup"});if(address>=limit)emit("bounds-error",L("Reject the out-of-bounds offset","Từ chối offset ngoài giới hạn"),L(`${address} is not below limit${limit}.`,`${address} không nhỏ hơn limit${limit}.`),L("The limit is a size; offset equal to the limit is invalid.","Limit là kích thước; offset bằng limit là không hợp lệ."),L("No physical address is produced.","Không tạo địa chỉ vật lý."),{status:"bounds-error"});else emit("translate",L("Add base and offset","Cộng base và offset"),L(`${base} + ${address} = ${base+address}.`,`${base} + ${address} = ${base+address}.`),L("The validated offset is relative to the segment base.","Offset đã hợp lệ được tính từ base segment."),L(`Physical address=${base+address}.`,`Địa chỉ vật lý=${base+address}.`),{physical:base+address,status:"translated"});}return freeze({mode,initial,steps});}
export type ReplacementPolicy="fifo"|"lru";
export const replacementExamples=freeze([{id:"comparison",references:[1,2,3,1,4,2,5],label:L("Compare FIFO and LRU","So sánh FIFO và LRU")},{id:"locality",references:[1,2,3,1,2,3,1,2,3],label:L("Three-page working set","Tập làm việc ba trang")}]);
export interface ReplacementState{readonly referenceIndex:number;readonly page:number|null;readonly frames:readonly (number|null)[];readonly loadOrder:readonly number[];readonly recentOrder:readonly number[];readonly faults:number;readonly hits:number;readonly victim:number|null;readonly result:"ready"|"checking"|"hit"|"fault";readonly resolved:boolean}
export function replacementTrace(policy:ReplacementPolicy,frameCount=3,references:readonly number[]=replacementExamples[0].references){if(!["fifo","lru"].includes(policy)||!Number.isInteger(frameCount)||frameCount<2||frameCount>3||!references.length||references.length>16||references.some(p=>!Number.isInteger(p)||p<1||p>9))throw new RangeError("FIFO/LRU,2–3frames,1–16references in1–9");let state:ReplacementState=freeze({referenceIndex:-1,page:null,frames:Array(frameCount).fill(null),loadOrder:[],recentOrder:[],faults:0,hits:0,victim:null,result:"ready",resolved:true});const initial=state,steps:SystemStep<ReplacementState>[]=[];const emit=(id:string,title:Localized,action:Localized,why:Localized,outcome:Localized,patch:Partial<ReplacementState>)=>{const before=state;state=freeze({...state,...patch});steps.push(freeze({id,title,action,why,outcome,before,after:state}));};emit("ready",L("Begin with empty frames","Bắt đầu với các frame trống"),L(`Use ${frameCount} frames and ${policy.toUpperCase()}.`,`Dùng ${frameCount} frame và ${policy.toUpperCase()}.`),L("This trace counts references and faults, not measured time or a universal thrashing threshold.","Chuỗi bước đếm truy cập và lỗi trang, không đo thời gian hay ngưỡng thrashing phổ quát."),L("Faults=0; hits=0.","Lỗi trang=0; hit=0."),{});
 references.forEach((page,i)=>{emit(`reference-${i}-check`,L(`Reference ${i+1}: page${page}`,`Truy cập ${i+1}: trang${page}`),L(`Check whether page${page} is resident.`,`Kiểm tra trang${page} có trong RAM chưa.`),L("A hit reuses the resident page; a miss requires a page load.","Hit dùng lại trang đang có; miss cần nạp trang."),L("No counter changes until the reference is resolved.","Chưa đổi bộ đếm cho đến khi xử lý truy cập."),{referenceIndex:i,page,victim:null,result:"checking",resolved:false});const hit=state.frames.includes(page);if(hit){emit(`reference-${i}-hit`,L("Page hit","Trúng trang"),L(`Reuse page${page}; mark it most recently used.`,`Dùng lại trang${page}; đánh dấu vừa được dùng gần nhất.`),L("FIFO load order is unchanged by a hit; LRU recency changes.","Hit không đổi thứ tự nạp FIFO; độ gần đây LRU thay đổi."),L(`Hits=${state.hits+1}; faults=${state.faults}.`,`Hit=${state.hits+1}; lỗi trang=${state.faults}.`),{hits:state.hits+1,recentOrder:[...state.recentOrder.filter(x=>x!==page),page],result:"hit",resolved:true});}else{const frames=[...state.frames],free=frames.indexOf(null),victim=free<0?(policy==="fifo"?state.loadOrder[0]:state.recentOrder[0]):null,position=free>=0?free:frames.indexOf(victim);frames[position]=page;emit(`reference-${i}-fault`,L("Page fault and load","Lỗi trang và nạp trang"),victim===null?L(`Load page${page} into free frame${position}.`,`Nạp trang${page} vào frame${position} trống.`):L(`Replace page${victim} with page${page} in frame${position}.`,`Thay trang${victim} bằng trang${page} tại frame${position}.`),victim===null?L("No eviction is needed because a frame is free.","Không cần loại trang vì có frame trống."):policy==="fifo"?L(`Page${victim} entered RAM earliest. A previous hit did not refresh its FIFO position.`,`Trang${victim} vào RAM sớm nhất. Hit trước đó không làm mới vị trí FIFO.`):L(`Page${victim} was used least recently.`,`Trang${victim} được dùng cách đây lâu nhất.`),L(`Faults=${state.faults+1}; hits=${state.hits}.`,`Lỗi trang=${state.faults+1}; hit=${state.hits}.`),{frames,loadOrder:[...state.loadOrder.filter(x=>x!==victim),page],recentOrder:[...state.recentOrder.filter(x=>x!==victim),page],faults:state.faults+1,victim,result:"fault",resolved:true});}});return freeze({policy,frameCount,references:[...references],initial,steps,faults:state.faults,hits:state.hits});}
