import type { Localized } from "./catalog";
export type TranslationKind="translation-workflows"|"compilation-pipeline"|"bnf-explorer"|"rpn-stack";
export interface TranslationStep<S>{readonly id:string;readonly title:Localized;readonly action:Localized;readonly why:Localized;readonly outcome:Localized;readonly before:S;readonly after:S}
const L=(en:string,vi:string):Localized=>({en,vi});
function freeze<T>(value:T):T{if(value!==null&&typeof value==="object"&&!Object.isFrozen(value)){Object.values(value).forEach(freeze);Object.freeze(value);}return value;}
type Operator="+"|"-"|"*"|"/";
export interface RpnValue{readonly numerator:string;readonly denominator:string;readonly text:string;readonly expression:string}
export interface RpnState{readonly tokenIndex:number;readonly token:string|null;readonly stack:readonly RpnValue[];readonly right:RpnValue|null;readonly left:RpnValue|null;readonly result:RpnValue|null;readonly equation:string|null;readonly status:"ready"|"running"|"complete"|"error";readonly error:string|null;readonly untouchedOnError:boolean}
function gcd(a:bigint,b:bigint):bigint{a=a<0n?-a:a;b=b<0n?-b:b;while(b){const next=a%b;a=b;b=next;}return a||1n;}
function fraction(n:bigint,d:bigint,expression:string):RpnValue{if(d===0n)throw new RangeError("division-by-zero");if(d<0n){n=-n;d=-d;}const factor=gcd(n,d);n/=factor;d/=factor;return freeze({numerator:n.toString(),denominator:d.toString(),text:d===1n?n.toString():`${n}/${d}`,expression});}
function calculate(left:RpnValue,right:RpnValue,operator:Operator):RpnValue{const a=BigInt(left.numerator),b=BigInt(left.denominator),c=BigInt(right.numerator),d=BigInt(right.denominator),expression=`(${left.expression} ${operator} ${right.expression})`;return operator==="+"?fraction(a*d+c*b,b*d,expression):operator==="-"?fraction(a*d-c*b,b*d,expression):operator==="*"?fraction(a*c,b*d,expression):fraction(a*d,b*c,expression);}
export const rpnExamples=freeze([{id:"main",source:"9 4 - 6 2 + * 5 /",label:L("Main: two subexpressions and division","Ví dụ chính: hai biểu thức con và phép chia")},{id:"subtract",source:"8 3 -",label:L("Operand order: subtraction","Thứ tự toán hạng: phép trừ")},{id:"divide",source:"12 3 /",label:L("Operand order: division","Thứ tự toán hạng: phép chia")},{id:"fraction",source:"5 2 /",label:L("Exact fractional result","Kết quả phân số chính xác")},{id:"underflow",source:"4 +",label:L("Missing operand","Thiếu toán hạng")},{id:"leftover",source:"4 5",label:L("Leftover values","Còn nhiều giá trị")},{id:"zero",source:"8 0 /",label:L("Division by zero","Chia cho không")},{id:"token",source:"2 # +",label:L("Unknown token","Token không hợp lệ")}]);
export function rpnTrace(source:string){const tokens=source.trim()?source.trim().split(/\s+/):[];let state:RpnState=freeze({tokenIndex:-1,token:null,stack:[],right:null,left:null,result:null,equation:null,status:"ready",error:null,untouchedOnError:false});const initial=state,steps:TranslationStep<RpnState>[]=[];
 const emit=(id:string,title:Localized,action:Localized,why:Localized,outcome:Localized,next:RpnState)=>{const before=state;state=freeze(next);steps.push(freeze({id,title,action,why,outcome,before,after:state}));};
 emit("ready",L("Inspect the token sequence","Quan sát chuỗi token"),L("Read tokens left to right; the stack is shown bottom to top.","Đọc token từ trái sang phải; stack hiển thị từ đáy lên đỉnh."),L("Binary operators need two operands; the first popped value is the right operand.","Toán tử hai ngôi cần hai toán hạng; giá trị pop đầu tiên là toán hạng phải."),L("The stack is empty.","Stack đang trống."),state);
 const fail=(id:string,code:string,title:Localized,detail:Localized,next:Partial<RpnState>={})=>emit(id,title,detail,L("An invalid operation leaves the value stack unchanged; do not invent a result.","Thao tác không hợp lệ giữ nguyên stack giá trị; không tạo kết quả giả."),L(`Stopped: ${code}.`,`Dừng: ${code}.`),{...state,...next,status:"error",error:code,untouchedOnError:true});
 if(!tokens.length)fail("empty-input","empty-input",L("Enter an expression","Nhập biểu thức"),L("The expression has no tokens.","Biểu thức không có token."));else if(source.length>240||tokens.length>24)fail("input-limit","input-limit",L("Expression exceeds this tool's bounds","Biểu thức vượt giới hạn minh họa"),L("Use at most24 tokens and240 characters.","Dùng tối đa24 token và240 ký tự."));
 for(let index=0;index<tokens.length&&state.status!=="error";index++){const token=tokens[index];emit(`token-${index}-read`,L(`Read token ${index+1}: ${token}`,`Đọc token ${index+1}: ${token}`),L(`Inspect ${token}.`,`Xét ${token}.`),L("An operand is pushed; an operator combines the top two values.","Toán hạng được push; toán tử kết hợp hai giá trị ở đỉnh."),L("The value stack is unchanged by reading.","Đọc token chưa thay đổi stack giá trị."),{...state,tokenIndex:index,token,right:null,left:null,result:null,equation:null,status:"running",untouchedOnError:false});
  if(/^-?\d{1,9}$/.test(token)){const value=fraction(BigInt(token),1n,token);emit(`token-${index}-push`,L("Push the operand","Push toán hạng"),L(`Push ${token} onto the top.`,`Push ${token} lên đỉnh.`),L("Operands wait on the stack until an operator uses them.","Toán hạng chờ trên stack đến khi toán tử dùng chúng."),L(`Stack depth=${state.stack.length+1}.`,`Độ sâu stack=${state.stack.length+1}.`),{...state,stack:[...state.stack,value]});continue;}
  if(!["+","-","*","/"].includes(token)){fail(`token-${index}-unknown`,"unknown-token",L("Unknown token","Token không hợp lệ"),L(`${token} is not a signed integer or binary +,-,*,/. A signed integer is one token; exponent operators are outside this bounded tool.`,`${token} không phải số nguyên có dấu hay toán tử hai ngôi +,-,*,/. Số nguyên có dấu là một token; minh họa không hỗ trợ toán tử lũy thừa.`));break;}
  if(state.stack.length<2){fail(`token-${index}-underflow`,"stack-underflow",L("Two operands are required","Cần hai toán hạng"),L(`Operator ${token} found only ${state.stack.length} value(s).`,`Toán tử ${token} chỉ gặp ${state.stack.length} giá trị.`));break;}
  const right=state.stack.at(-1)!,left=state.stack.at(-2)!;
  if(token==="/"&&BigInt(right.numerator)===0n){fail(`token-${index}-zero`,"division-by-zero",L("Reject division by zero","Từ chối chia cho không"),L("The right operand is zero. Neither operand is popped.","Toán hạng phải bằng không. Không pop toán hạng nào."),{right,left});break;}
  emit(`token-${index}-pop-right`,L("Pop the right operand first","Pop toán hạng phải trước"),L(`RIGHT ← ${right.text}.`,`PHẢI ← ${right.text}.`),L("The most recently pushed value is the operator's right operand.","Giá trị push gần nhất là toán hạng phải của toán tử."),L(`RIGHT=${right.text}.`,`PHẢI=${right.text}.`),{...state,right,stack:state.stack.slice(0,-1)});
  emit(`token-${index}-pop-left`,L("Pop the left operand second","Pop toán hạng trái sau"),L(`LEFT ← ${left.text}.`,`TRÁI ← ${left.text}.`),L("Preserve LEFT operator RIGHT, especially for subtraction and division.","Giữ thứ tự TRÁI toán tử PHẢI, đặc biệt khi trừ hoặc chia."),L(`LEFT=${left.text}; RIGHT=${right.text}.`,`TRÁI=${left.text}; PHẢI=${right.text}.`),{...state,left,stack:state.stack.slice(0,-1)});
  const result=calculate(left,right,token as Operator),equation=`${left.text} ${token} ${right.text} = ${result.text}`;
  emit(`token-${index}-calculate`,L("Calculate LEFT op RIGHT","Tính TRÁI op PHẢI"),L(equation,equation),L("Use exact rational arithmetic; no rounding is introduced.","Dùng số hữu tỉ chính xác; không làm tròn."),L(`Result=${result.text}.`,`Kết quả=${result.text}.`),{...state,result,equation});
  emit(`token-${index}-push-result`,L("Push the result","Push kết quả"),L(`Push ${result.text}.`,`Push ${result.text}.`),L("The result can be an operand for a later operator.","Kết quả có thể là toán hạng của toán tử về sau."),L(`Stack depth=${state.stack.length+1}.`,`Độ sâu stack=${state.stack.length+1}.`),{...state,stack:[...state.stack,result]});
 }
 if(state.status!=="error"){if(state.stack.length!==1)fail("leftover-operands","leftover-operands",L("Final stack must contain one value","Stack cuối phải chứa một giá trị"),L(`${state.stack.length} values remain; the token sequence is not a complete binary expression.`,`Còn ${state.stack.length} giá trị; chuỗi token chưa tạo biểu thức hai ngôi hoàn chỉnh.`));else emit("complete",L("One final result","Một kết quả cuối"),L(`Result ${state.stack[0].text}; infix ${state.stack[0].expression}.`,`Kết quả ${state.stack[0].text}; dạng trung tố ${state.stack[0].expression}.`),L("Exactly one stack value remains after all tokens.","Sau mọi token, stack còn đúng một giá trị."),L("The expression is valid.","Biểu thức hợp lệ."),{...state,status:"complete",result:state.stack[0]});}
 return freeze({source,tokens,initial,steps,status:state.status,result:state.status==="complete"?state.result:null,error:state.error});
}
export interface InfixState{readonly tokenIndex:number;readonly token:string|null;readonly operators:readonly string[];readonly output:readonly string[];readonly status:"ready"|"running"|"complete"|"error";readonly error:string|null}
export function infixTrace(source:string){const tokens=source.match(/\d+|\S/g)??[];let state:InfixState=freeze({tokenIndex:-1,token:null,operators:[],output:[],status:"ready",error:null});const initial=state,steps:TranslationStep<InfixState>[]=[];let expectsOperand=true;
 const emit=(id:string,title:Localized,action:Localized,why:Localized,next:InfixState)=>{const before=state;state=freeze(next);steps.push(freeze({id,title,action,why,outcome:L(`Output: ${state.output.join(" ")||"empty"}; operator stack: ${state.operators.join(" ")||"empty"}.`,`Đầu ra: ${state.output.join(" ")||"trống"}; stack toán tử: ${state.operators.join(" ")||"trống"}.`),before,after:state}));};
 emit("ready",L("Convert infix to RPN","Chuyển trung tố sang RPN"),L("Start with empty output and operator stack.","Bắt đầu với đầu ra và stack toán tử trống."),L("* and / precede + and -; equal precedence is left-associative.","* và / ưu tiên hơn + và -; cùng mức ưu tiên thì kết hợp trái."),state);
 const error=(code:string,tokenIndex=state.tokenIndex,token=state.token)=>emit(`error-${steps.length}`,L("Reject the infix expression","Từ chối biểu thức trung tố"),L("Check operator/operand order and matching brackets; no unary minus is supported.","Kiểm tra thứ tự toán tử/toán hạng và ngoặc khớp; không hỗ trợ dấu trừ một ngôi."),L(code,code),{...state,tokenIndex,token,status:"error",error:code});
 if(!tokens.length||tokens.length>32||source.length>240)error("input-limit-or-empty");
 for(let i=0;i<tokens.length&&state.status!=="error";i++){const token=tokens[i],operators=[...state.operators],output=[...state.output];let action:Localized;
  if(/^\d{1,9}$/.test(token)&&expectsOperand){output.push(token);expectsOperand=false;action=L(`Append operand ${token} to output.`,`Thêm toán hạng ${token} vào đầu ra.`);}
  else if(token==="("&&expectsOperand){operators.push(token);action=L("Push the opening bracket.","Push ngoặc mở.");}
  else if(token===")"&&!expectsOperand){while(operators.length&&operators.at(-1)!=="(")output.push(operators.pop()!);if(operators.pop()!=="("){error("unmatched-closing-bracket",i,token);break;}action=L("Output operators up to the opening bracket, then discard both brackets.","Xuất toán tử tới ngoặc mở, rồi bỏ cả hai ngoặc.");}
  else if(["+","-","*","/"].includes(token)&&!expectsOperand){const precedence=(operator:string)=>operator==="+"||operator==="-"?1:operator==="*"||operator==="/"?2:0;while(operators.length&&operators.at(-1)!=="("&&precedence(operators.at(-1)!)>=precedence(token))output.push(operators.pop()!);operators.push(token);expectsOperand=true;action=L(`Output higher/equal-precedence operators before pushing ${token}.`,`Xuất toán tử ưu tiên cao hơn/bằng trước khi push ${token}.`);}
  else{error("invalid-token-or-order",i,token);break;}
  emit(`token-${i}`,L(`Read ${token}`,`Đọc ${token}`),action,L("Operators wait until their operands and precedence allow them to enter the output.","Toán tử chờ cho đến khi toán hạng và mức ưu tiên cho phép đưa chúng vào đầu ra."),{tokenIndex:i,token,operators,output,status:"running",error:null});
 }
 if(state.status!=="error"){if(expectsOperand)error("missing-final-operand");else if(state.operators.includes("("))error("unmatched-opening-bracket");else emit("complete",L("Drain the operator stack","Xuất hết stack toán tử"),L("Append remaining operators from top to bottom.","Thêm các toán tử còn lại từ đỉnh xuống đáy."),L("All brackets were matched; the output is the corresponding RPN sequence.","Mọi ngoặc đã khớp; đầu ra là chuỗi RPN tương ứng."),{...state,operators:[],output:[...state.output,...[...state.operators].reverse()],status:"complete"});}
 return freeze({source,tokens,initial,steps,status:state.status,output:state.status==="complete"?state.output.join(" "):null,error:state.error});
}
export interface WorkflowState{readonly method:"interpreter"|"compiler";readonly phase:string;readonly activeStatement:number|null;readonly variable:number|null;readonly outputs:readonly number[];readonly artifact:boolean;readonly diagnostic:string|null;readonly statements:readonly string[]}
export function translationTrace(method:"interpreter"|"compiler",scenario:"valid"|"syntax-error"="valid"){const statements=["x ← 2 + 3","OUTPUT x",scenario==="valid"?"OUTPUT x * 2":"OUTPUT x +"];let state:WorkflowState=freeze({method,phase:"source",activeStatement:null,variable:null,outputs:[],artifact:false,diagnostic:null,statements});const initial=state,steps:TranslationStep<WorkflowState>[]=[];const emit=(id:string,title:Localized,action:Localized,why:Localized,patch:Partial<WorkflowState>)=>{const before=state;state=freeze({...state,...patch});steps.push(freeze({id,title,action,why,outcome:L(`Output=[${state.outputs.join(", ")}]; executable=${state.artifact?"available":"not available"}${state.diagnostic?`; diagnostic=${state.diagnostic}`:""}.`,`Đầu ra=[${state.outputs.join(", ")}]; chương trình thực thi=${state.artifact?"có":"chưa có"}${state.diagnostic?`; chẩn đoán=${state.diagnostic}`:""}.`),before,after:state}));};emit("ready",L("Inspect the same source program","Quan sát cùng chương trình nguồn"),L("Compare translation and execution as separate activities.","Phân biệt hoạt động dịch và hoạt động thực thi."),L("This bounded example illustrates workflows; it is not a speed benchmark.","Ví dụ hữu hạn minh họa quy trình; không phải phép đo tốc độ."),{});
 if(method==="interpreter"){emit("execute-1",L("Execute the assignment","Thực thi phép gán"),L("Evaluate 2+3, then assign x=5.","Tính 2+3 rồi gán x=5."),L("This interpreter handles and executes statements sequentially.","Trình thông dịch này xử lý và thực thi các câu lệnh lần lượt."),{phase:"execute",activeStatement:0,variable:5});emit("execute-2",L("Produce the first output","Tạo đầu ra đầu tiên"),L("Execute OUTPUT x, producing5.","Thực thi OUTPUT x, tạo giá trị5."),L("Output is a runtime effect, not a translation artifact.","Đầu ra là hiệu ứng khi chạy, không phải sản phẩm dịch."),{activeStatement:1,outputs:[5]});if(scenario==="syntax-error")emit("diagnostic",L("Stop at the malformed statement","Dừng tại câu lệnh sai"),L("The third statement has no right operand after +.","Câu lệnh thứ ba thiếu toán hạng phải sau +."),L("The prior output5 has already occurred in this sequential example.","Đầu ra5 trước đó đã được tạo trong ví dụ tuần tự này."),{phase:"error",activeStatement:2,diagnostic:"missing-operand"});else emit("execute-3",L("Produce the second output","Tạo đầu ra thứ hai"),L("Execute OUTPUT x*2, producing10.","Thực thi OUTPUT x*2, tạo giá trị10."),L("The interpreter does not produce a standalone executable in this model.","Trong mô hình này, trình thông dịch không tạo chương trình thực thi độc lập."),{activeStatement:2,outputs:[5,10],phase:"complete"});}
 else{emit("analyse",L("Analyse the complete source","Phân tích toàn bộ mã nguồn"),L("Check the source before generating an executable artifact.","Kiểm tra mã nguồn trước khi tạo sản phẩm thực thi."),L("Compilation does not execute OUTPUT statements.","Biên dịch không thực thi các lệnh OUTPUT."),{phase:"analyse"});if(scenario==="syntax-error")emit("diagnostic",L("Report a compile-time diagnostic","Báo chẩn đoán khi biên dịch"),L("Reject the missing operand in statement3.","Từ chối toán hạng bị thiếu ở câu lệnh3."),L("No successful executable is published and no program output has run.","Không tạo chương trình thực thi thành công và chưa chạy lệnh xuất nào."),{phase:"error",activeStatement:2,diagnostic:"missing-operand"});else{emit("generate",L("Generate target code","Sinh mã đích"),L("Translate the checked program into target code.","Dịch chương trình đã kiểm tra thành mã đích."),L("Target-code creation remains separate from execution.","Tạo mã đích vẫn là hoạt động riêng với thực thi."),{phase:"generate"});emit("object-ready",L("The compiled artifact is ready","Sản phẩm biên dịch sẵn sàng"),L("Keep the artifact for a later run.","Giữ sản phẩm để chạy sau."),L("A ready artifact has not yet executed the program's OUTPUT statements.","Sản phẩm sẵn sàng chưa thực thi các lệnh OUTPUT của chương trình."),{phase:"artifact",artifact:true});emit("run",L("Run the compiled program","Chạy chương trình đã biên dịch"),L("Execute the assignment and outputs:5, then10.","Thực thi phép gán và các lệnh xuất:5 rồi10."),L("The valid program has the same observable output in both workflows.","Chương trình hợp lệ có cùng đầu ra quan sát được ở cả hai quy trình."),{phase:"complete",variable:5,outputs:[5,10]});}}return freeze({method,scenario,initial,steps});}
export interface CompilationState{readonly phase:string;readonly source:string;readonly tokens:readonly {readonly text:string;readonly category:string}[];readonly symbols:readonly {readonly name:string;readonly type:string}[];readonly ast:string|null;readonly code:readonly string[];readonly output:readonly number[];readonly diagnostic:string|null;readonly optimized:boolean}
export function compilationTrace(scenario:"valid"|"lexical-error"|"syntax-error"="valid",optimize=true){const source=scenario==="lexical-error"?"DECLARE total : INTEGER; total ← 2 @ 3; OUTPUT total":scenario==="syntax-error"?"DECLARE total : INTEGER; total ← 2 +; OUTPUT total":"DECLARE total : INTEGER; total ← 2 + 3; OUTPUT total";let state:CompilationState=freeze({phase:"source",source,tokens:[],symbols:[],ast:null,code:[],output:[],diagnostic:null,optimized:false});const initial=state,steps:TranslationStep<CompilationState>[]=[];const emit=(id:string,title:Localized,action:Localized,why:Localized,outcome:Localized,patch:Partial<CompilationState>)=>{const before=state;state=freeze({...state,...patch});steps.push(freeze({id,title,action,why,outcome,before,after:state}));};emit("ready",L("Source program","Chương trình nguồn"),L("Inspect the declaration, assignment and output.","Quan sát khai báo, phép gán và lệnh xuất."),L("The next stages build different representations of the same program.","Các giai đoạn tiếp theo tạo các dạng biểu diễn của cùng chương trình."),L("No target code or runtime output yet.","Chưa có mã đích hay đầu ra khi chạy."),{});
 const words=source.match(/[A-Za-z]+|\d+|←|[^\s]/g)??[],tokens=words.map(text=>({text,category:["DECLARE","INTEGER","OUTPUT"].includes(text)?"keyword":/^\d+$/.test(text)?"integer-literal":text==="total"?"identifier":text==="←"?"assignment":text==="+"?"addition":[":",";"].includes(text)?"punctuation":"invalid"}));
 emit("lexical",L("Lexical analysis","Phân tích từ vựng"),L("Convert character sequences into tokens and identify lexical errors.","Chuyển chuỗi ký tự thành token và phát hiện lỗi từ vựng."),L("Token classes distinguish names, keywords, literals and operators.","Lớp token phân biệt tên, từ khóa, hằng và toán tử."),scenario==="lexical-error"?L("@ is not a token in this bounded source language; stop.","@ không phải token trong ngôn ngữ nguồn hữu hạn này; dừng."):L("The source is tokenized.","Mã nguồn đã được tách token."),{phase:scenario==="lexical-error"?"error":"lexical",tokens,diagnostic:scenario==="lexical-error"?"unknown-character-@":null});if(scenario==="lexical-error")return freeze({scenario,optimize,initial,steps});
 emit("syntax",L("Syntax analysis","Phân tích cú pháp"),L("Check token order against the grammar and build a parse structure.","Kiểm tra thứ tự token theo văn phạm và dựng cấu trúc phân tích."),L("Known tokens alone do not guarantee a valid expression.","Các token hợp lệ riêng lẻ chưa đảm bảo một biểu thức đúng."),scenario==="syntax-error"?L("The addition has no right operand; stop.","Phép cộng thiếu toán hạng phải; dừng."):L("Assignment expression: add(integer2, integer3).","Biểu thức gán: add(integer2, integer3)."),{phase:scenario==="syntax-error"?"error":"syntax",ast:scenario==="syntax-error"?null:"assign(total, add(2, 3))",diagnostic:scenario==="syntax-error"?"missing-right-operand":null});if(scenario==="syntax-error")return freeze({scenario,optimize,initial,steps});
 emit("semantic",L("Semantic checks and symbol information","Kiểm tra ngữ nghĩa và thông tin ký hiệu"),L("Record total:INTEGER and check that integer addition can be assigned to it.","Ghi total:INTEGER và kiểm tra kết quả cộng số nguyên có thể gán vào biến này."),L("The symbol table supports declaration and type checks; syntax alone does not establish types.","Bảng ký hiệu hỗ trợ kiểm tra khai báo và kiểu; cú pháp riêng lẻ chưa xác lập kiểu."),L("total has typeINTEGER; the assignment is compatible.","total có kiểuINTEGER; phép gán tương thích."),{phase:"semantic",symbols:[{name:"total",type:"INTEGER"}]});
 emit("generate",L("Generate target instructions","Sinh lệnh đích"),L("Emit LOAD2, ADD3, STORE total, OUTPUT total.","Sinh LOAD2, ADD3, STORE total, OUTPUT total."),L("These symbolic instructions illustrate code generation, not a real processor ISA.","Các lệnh ký hiệu minh họa sinh mã, không phải ISA của bộ xử lý thật."),L("The target code preserves the program's operations.","Mã đích giữ các thao tác của chương trình."),{phase:"generate",code:["LOAD 2","ADD 3","STORE total","OUTPUT total"]});
 if(optimize)emit("optimize",L("Fold the constant expression","Gấp biểu thức hằng"),L("Replace LOAD2;ADD3 with LOAD5; retain STORE and OUTPUT.","Thay LOAD2;ADD3 bằng LOAD5; giữ STORE và OUTPUT."),L("An optimization must preserve observable output, types and error behaviour; removing required OUTPUT is invalid.","Tối ưu phải giữ đầu ra quan sát được, kiểu và hành vi lỗi; xóa OUTPUT cần thiết là sai."),L("The valid constant fold reduces this symbolic instruction sequence.","Gấp hằng hợp lệ rút gọn chuỗi lệnh ký hiệu này."),{phase:"optimize",code:["LOAD 5","STORE total","OUTPUT total"],optimized:true});
 emit("run-check",L("Check observable behaviour","Kiểm tra hành vi quan sát được"),L("Run the resulting symbolic code: output5.","Chạy mã ký hiệu thu được: xuất5."),L("The before and after programs both output5 for this fixed example.","Chương trình trước và sau cùng xuất5 trong ví dụ cố định này."),L("Observed output=[5].","Đầu ra quan sát=[5]."),{phase:"complete",output:[5]});return freeze({scenario,optimize,initial,steps});}
export const bnfGrammar=freeze(["<name> ::= <letter><tail>","<letter> ::= A | B","<tail> ::= <digit><tail> | ε","<digit> ::= 0 | 1 | 2"]);
export const bnfExamples=freeze(["A","B20","A012","","0A","AB","A3","A01B"]);
export interface BnfState{readonly input:string;readonly cursor:number;readonly consumed:string;readonly remaining:string;readonly derivation:string;readonly production:string|null;readonly expected:readonly string[];readonly status:"ready"|"deriving"|"accepted"|"rejected"|"unsupported";readonly reason:string|null}
export function bnfTrace(input:string){let state:BnfState=freeze({input,cursor:0,consumed:"",remaining:input,derivation:"<name>",production:null,expected:["A","B"],status:"ready",reason:null});const initial=state,steps:TranslationStep<BnfState>[]=[];const emit=(id:string,title:Localized,action:Localized,why:Localized,outcome:Localized,patch:Partial<BnfState>)=>{const before=state;state=freeze({...state,...patch});steps.push(freeze({id,title,action,why,outcome,before,after:state}));};emit("ready",L("Start with <name>","Bắt đầu từ <name>"),L("Derive one letter followed by zero or more digits.","Sinh một chữ cái theo sau bởi không hoặc nhiều chữ số."),L("Adjacent nonterminals concatenate; | means choice; ε means the empty string.","Các ký hiệu không kết thúc đứng cạnh nhau là nối tiếp; | là lựa chọn; ε là chuỗi rỗng."),L("The entire input must be consumed.","Phải dùng hết toàn bộ chuỗi đầu vào."),{});
 const reject=(reason:string,detail:Localized)=>emit(`reject-${state.cursor}`,L("Reject this string","Từ chối chuỗi này"),detail,L("A valid prefix is insufficient; every character must match a production.","Tiền tố hợp lệ chưa đủ; mọi ký tự phải khớp một luật sinh."),L("The string is not in this example grammar.","Chuỗi không thuộc văn phạm ví dụ này."),{status:"rejected",reason});if(input.length>12){emit("input-limit",L("Explorer input limit","Giới hạn đầu vào công cụ"),L("Use at most12 characters in this explorer.","Dùng tối đa12 ký tự trong công cụ này."),L("The recursive grammar can generate longer strings; this is a tool boundary, not a grammar rule.","Văn phạm đệ quy có thể sinh chuỗi dài hơn; đây là giới hạn công cụ, không phải luật văn phạm."),L("No grammar-membership verdict is produced.","Chưa đưa ra kết luận về việc chuỗi thuộc văn phạm."),{status:"unsupported",reason:"input-limit"});return freeze({input,initial,steps,accepted:null});}
 emit("expand-name",L("Expand the name production","Khai triển luật name"),L("<name> → <letter><tail>.","<name> → <letter><tail>."),L("The letter and tail are concatenated, not alternatives.","Letter và tail được nối tiếp, không phải hai lựa chọn thay thế."),L("A letter must come first.","Chữ cái phải đứng đầu."),{derivation:"<letter><tail>",production:bnfGrammar[0],status:"deriving"});if(!["A","B"].includes(input[0])){reject("expected-letter",L("The first character must be A or B; the empty string is invalid.","Ký tự đầu phải là A hoặc B; chuỗi rỗng không hợp lệ."));return freeze({input,initial,steps,accepted:false});}
 emit("choose-letter",L("Choose the first letter","Chọn chữ cái đầu"),L(`<letter> → ${input[0]}.`,`<letter> → ${input[0]}.`),L("Only A and B are terminal choices for <letter>.","Chỉ A và B là các lựa chọn kết thúc của <letter>."),L(`Consumed ${input[0]}.`,`Đã nhận ${input[0]}.`),{cursor:1,consumed:input[0],remaining:input.slice(1),derivation:`${input[0]}<tail>`,production:`<letter> ::= ${input[0]}`,expected:["0","1","2","ε"]});
 for(let i=1;i<input.length;i++){if(!["0","1","2"].includes(input[i])){reject("expected-digit",L(`Character${i+1} must be0,1 or2; ${input[i]} is not allowed.`,`Ký tự${i+1} phải là0,1 hoặc2; ${input[i]} không được phép.`));return freeze({input,initial,steps,accepted:false});}emit(`digit-${i}`,L(`Derive digit ${input[i]}`,`Sinh chữ số ${input[i]}`),L(`<tail> → <digit><tail>; <digit> → ${input[i]}.`,`<tail> → <digit><tail>; <digit> → ${input[i]}.`),L("The recursive tail permits another digit while retaining the option to finish.","Tail đệ quy cho phép thêm chữ số đồng thời vẫn giữ khả năng kết thúc."),L(`Consumed ${input.slice(0,i+1)}.`,`Đã nhận ${input.slice(0,i+1)}.`),{cursor:i+1,consumed:input.slice(0,i+1),remaining:input.slice(i+1),derivation:`${input.slice(0,i+1)}<tail>`,production:`<tail> ::= <digit><tail>; <digit> ::= ${input[i]}`});}
 emit("choose-empty",L("Finish with ε","Kết thúc bằng ε"),L("<tail> → ε; ε contributes no character.","<tail> → ε; ε không thêm ký tự nào."),L("The input has ended, so the recursive tail takes its empty alternative.","Đầu vào đã hết nên tail đệ quy chọn nhánh rỗng."),L(`Derived ${input}; no input remains.`,`Đã sinh ${input}; không còn đầu vào.`),{derivation:input,production:"<tail> ::= ε",expected:[]});emit("accept",L("Accept the whole string","Chấp nhận toàn bộ chuỗi"),L("Confirm that the derivation matches all input characters.","Xác nhận phép dẫn xuất khớp mọi ký tự đầu vào."),L("There are no unmatched suffix characters.","Không còn hậu tố chưa khớp."),L("Accepted by this grammar.","Được văn phạm này chấp nhận."),{status:"accepted"});return freeze({input,initial,steps,accepted:true});}
