import Link from "next/link";
import { ArrowLeft, ArrowRight, BookOpen, CircleDashed, Map, Target } from "lucide-react";
import { getSectionTopics, paper2Href, type Locale, type StudyMapCatalog, type Topic } from "@/app/lib/paper2/catalog";
import { Paper2LocaleBoundary } from "./Paper2LocaleBoundary";
import { learningModes, SectionIcon, topicStatusLabel, TopicRow } from "./shared";
import styles from "./Paper2Learning.module.css";

const journey = [
  { en: "Recognise", vi: "Nhận diện", enText: "Read the task and choose a suitable method.", viText: "Đọc yêu cầu và chọn phương pháp phù hợp." },
  { en: "Understand", vi: "Hiểu", enText: "Connect the idea with a clear visual explanation.", viText: "Kết nối khái niệm với minh họa rõ ràng." },
  { en: "Worked Example", vi: "Giải mẫu", enText: "Follow the working and the reason for each step.", viText: "Theo dõi lời giải và lý do của từng bước." },
  { en: "Practise", vi: "Tự luyện", enText: "Try another task with the solution available.", viText: "Luyện tình huống khác với lời giải sẵn có." },
  { en: "Avoid Lost Marks", vi: "Tránh mất điểm", enText: "Check common mistakes and missing details.", viText: "Kiểm tra lỗi thường gặp và chi tiết dễ bỏ sót." },
  { en: "Remember", vi: "Gợi nhớ", enText: "Review the key ideas and make connections.", viText: "Ôn các ý chính và liên hệ kiến thức." },
];

export function TopicPreview({ catalog, topic, locale }: { readonly catalog: StudyMapCatalog; readonly topic: Topic; readonly locale: Locale }) {
  const section = catalog.sections.find(item => item.id === topic.sectionId);
  if (!section) return null;
  const prerequisites = topic.prerequisites.flatMap(id => { const entry = catalog.topics.find(item => item.id === id); return entry ? [entry] : []; });
  const siblings = getSectionTopics(catalog, section.id).filter(item => item.id !== topic.id);
  const next = catalog.topics[catalog.topics.findIndex(item => item.id === topic.id) + 1];
  return <div className={styles.page} lang={locale} data-paper2-topic-preview data-topic-id={topic.id}>
    <Paper2LocaleBoundary locale={locale} />
    <nav className={styles.breadcrumb} aria-label={locale === "vi" ? "Vị trí trong khóa học" : "Breadcrumb"}><Link href={paper2Href(`/paper-2?section=${section.id}`, locale)}><Map size={16} aria-hidden="true" />{locale === "vi" ? "Bản đồ học tập" : "Study map"}</Link><span aria-hidden="true">/</span><Link href={paper2Href(`/paper-2/sections/${section.id}`, locale)}>{section.id} · {section.title[locale]}</Link><span aria-hidden="true">/</span><span aria-current="page">{topic.id}</span></nav>
    <header className={styles.topicHero}><div className={styles.eyebrow}><SectionIcon id={section.id} size={19} />PAPER 2 · {topic.id} · {locale === "vi" ? "PHẦN" : "SECTION"} {section.id}</div><h1>{topic.title[locale]}</h1><p>{topic.summary[locale]}</p><span className={styles.modePill}><BookOpen size={16} aria-hidden="true" />{learningModes[topic.learningMode][locale]}</span></header>
    <section className={styles.preparationPanel} aria-labelledby="paper2-preview-status"><div className={styles.preparationSymbol}><CircleDashed size={32} aria-hidden="true" /></div><div><span className={styles.kicker}>{locale === "vi" ? "TỔNG QUAN CHỦ ĐỀ" : "TOPIC OVERVIEW"}</span><h2 id="paper2-preview-status">{locale === "vi" ? "Bài chi tiết đang được biên soạn" : "The full lesson is in preparation"}</h2><p>{locale === "vi" ? "Bạn có thể xem mục tiêu học và các kiến thức liên quan ngay dưới đây. Phần giảng giải, minh họa từng bước, bài mẫu và bài luyện chưa mở trong phiên bản này." : "Explore the learning objectives and connected ideas below. Detailed teaching, step-by-step visuals, worked examples and practice are not yet available in this version."}</p><Link className={styles.primaryLink} href={paper2Href(`/paper-2/sections/${section.id}`, locale)}><ArrowLeft size={17} aria-hidden="true" />{locale === "vi" ? "Khám phá phần này" : "Explore this section"}</Link></div></section>
    <section className={`${styles.objectivePanel} ${styles.sectionRoute}`} aria-labelledby="paper2-topic-objectives"><div className={styles.blockHeading}><h2 id="paper2-topic-objectives">{locale === "vi" ? "Mục tiêu học của chủ đề" : "Topic learning objectives"}</h2><Target size={24} aria-hidden="true" /></div><ul className={styles.objectiveList}>{topic.learningObjectives.map((objective, index) => <li key={index}><span aria-hidden="true">{String(index + 1).padStart(2, "0")}</span><p>{objective[locale]}</p></li>)}</ul></section>
    <section className={styles.sectionRoute} aria-labelledby="paper2-prerequisites"><div className={styles.blockHeading}><h2 id="paper2-prerequisites">{locale === "vi" ? "Kiến thức nên ôn trước" : "Useful prior knowledge"}</h2></div><p className={styles.mapHint}>{prerequisites.length ? (locale === "vi" ? "Các chủ đề này giúp bạn đọc mục tiêu và chuẩn bị cho bài học. Đây là gợi ý, không phải điều kiện khóa bài." : "These topics help you understand the objectives and prepare for the lesson. They are suggestions, not access requirements.") : (locale === "vi" ? "Chủ đề này không yêu cầu kiến thức nền riêng trong lộ trình. Bạn có thể bắt đầu từ các mục tiêu phía trên." : "This topic has no specific prerequisite in the course map. Start with the objectives above.")}</p>{prerequisites.length > 0 && <div className={styles.topicList}>{prerequisites.map(item => <TopicRow key={item.id} topic={item} locale={locale} />)}</div>}</section>
    <section className={styles.journeyPreview} aria-labelledby="paper2-journey-title"><div className={styles.blockHeading}><div><span className={styles.kicker}>{locale === "vi" ? "CẤU TRÚC BÀI CHI TIẾT DỰ KIẾN" : "PLANNED FULL LESSON STRUCTURE"}</span><h2 id="paper2-journey-title">{locale === "vi" ? "Từ nhận diện đến tự giải" : "From recognition to application"}</h2></div></div><ol className={`${styles.journeySteps} ${styles.paper2Journey}`}>{journey.map((step, index) => <li key={step.en}><span className={styles.journeyNumber}>{String(index + 1).padStart(2, "0")}</span><h3>{locale === "vi" ? step.vi : step.en}</h3><p>{locale === "vi" ? step.viText : step.enText}</p></li>)}</ol><p className={styles.journeyNote}>{locale === "vi" ? "Khi bài chi tiết được mở, hướng dẫn và lời giải sẽ có sẵn ngay; bạn có thể chọn tự luyện mà không phải mở khóa nội dung." : "When the full lesson is available, all guidance and solutions will be immediately readable. Self-practice will be optional, with no content unlocking."}</p></section>
    {siblings.length > 0 && <section className={styles.sectionRoute} aria-labelledby="paper2-siblings"><div className={styles.blockHeading}><h2 id="paper2-siblings">{locale === "vi" ? "Các chủ đề cùng phần" : "Other topics in this section"}</h2></div><div className={styles.topicList}>{siblings.map(item => <TopicRow key={item.id} topic={item} locale={locale} />)}</div></section>}
    <nav className={styles.pageNavigation} aria-label={locale === "vi" ? "Khám phá thêm" : "Explore more"}><Link href={paper2Href(`/paper-2?section=${section.id}`, locale)}><ArrowLeft size={18} aria-hidden="true" /><span>{locale === "vi" ? "Về bản đồ học tập" : "Back to the study map"}</span></Link>{next && <Link href={paper2Href(`/paper-2/topics/${next.slug}`, locale)}><span><small>{locale === "vi" ? "Chủ đề tiếp theo" : "Next topic"} · {topicStatusLabel(next, locale)}</small>{next.title[locale]}</span><ArrowRight size={18} aria-hidden="true" /></Link>}</nav>
  </div>;
}
