from __future__ import annotations
import hashlib,json,pathlib,collections,datetime
HERE=pathlib.Path(__file__).resolve().parent; B2=HERE; STAGE5=HERE.parents[1]; P4=HERE.parents[2]; S4B2=P4/'stage-4/evidence/method/B2-search-sort'; INV=json.loads((STAGE5/'OBLIGATION_INVENTORY.json').read_text(encoding='utf8')); obs=[o for o in INV['obligations'] if o.get('primary_batch')=='B2']; run=json.loads((B2/'runs/AUTHOR_RUN.json').read_text(encoding='utf8')); fx=json.loads((B2/'fixtures/B2_FIXTURES.json').read_text(encoding='utf8')); traces=json.loads((B2/'traces/TRACE_BUNDLE.json').read_text(encoding='utf8')); impl=B2/'implementation/b2_search_sort.py'
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def dump(p,d): p.write_text(json.dumps(d,ensure_ascii=False,indent=2,sort_keys=True)+'\n',encoding='utf8')
def ids(p,t): return [o['obligation_id'] for o in obs if p in o.get('pattern_ids',[]) and o.get('obligation_type')==t]
def allpat(t): return [o['obligation_id'] for o in obs if o.get('obligation_type')==t]
# Attach worked example and source occurrence IDs across four canonical fixtures.
by_pat=collections.defaultdict(list)
for f in fx['fixtures']:
 if f['fixture_id'].startswith('fx.b2.') and f['test_category'] in ('normal','boundary','counterexample','source_fixture'): by_pat[f['pattern_id']].append(f)
for p,fs in by_pat.items():
 m=ids(p,'worked_example_microcase'); e=ids(p,'worked_example_evidence')
 for i,x in enumerate(m): fs[i%len(fs)]['worked_example_microcase_ids'].append(x)
 for i,x in enumerate(e): fs[i%len(fs)]['worked_example_evidence_ids'].append(x)
 for f in fs:
  f['solution_obligation_ids']=ids(p, 'solution_'+f['test_category']) if f['test_category'] in ('normal','boundary','counterexample') else ids(p,'solution_source_fixture')
  f['marking_point_refs']=ids(p,'marking_atom')
# Write enriched fixture bundle.
dump(B2/'fixtures/B2_FIXTURES.json',fx)
# Registry rows.
patterns=[]; cards={x['pattern_id']:x for x in json.loads((S4B2/'PATTERN_CARDS.json').read_text(encoding='utf8'))['pattern_cards']}; designs={x['pattern_id']:x for x in json.loads((S4B2/'SOLUTION_DESIGNS.json').read_text(encoding='utf8'))['solution_designs']}; vars=json.loads((S4B2/'VARIANT_INVARIANT_REGISTER.json').read_text(encoding='utf8'))['variants']; visual={x['pattern_id']:x for x in json.loads((S4B2/'VISUAL_BRIEFS.json').read_text(encoding='utf8'))['visual_briefs']}; errors=json.loads((S4B2/'ERROR_PREVENTION.json').read_text(encoding='utf8'))['error_rows'];
for p in ['ORDERED_INSERT','LINEAR_SEARCH','COUNT_OCCURRENCES','FILTER_RECORDS','GROUP_AGGREGATE','BUBBLE_SORT','INSERTION_SORT','BINARY_SEARCH']:
 d=designs[p]; pf=[f for f in fx['fixtures'] if f['pattern_id']==p]; tr=[t for t in traces['traces'] if t['pattern_id']==p]
 bindings=[]
 for v in vars:
  if p in v['pattern_ids']:
   for c in v['cases']:
    bindings.append({'variant_id':v['variant_id'],'source_contract_id':f'B2-contract-{p}','entry_point_name':f'{p.lower()}','signature':'fixture-specific contract adapter','adapter_id':f'adapter.{p.lower()}.{v["variant_id"].lower()}','representation':'Python list or complete record list','oracle_id':f'oracle.{p.lower()}','return_output_contract':'fixture expected_return','variant_case':c})
 patterns.append({'pattern_id':p,'solution_design_id':d['solution_design_id'],'implementation_id':f'B2-IMPL-{p}','implementation_path':'implementation/b2_search_sort.py','implementation_sha256':sha(impl),'variant_ids':sorted({v['variant_id'] for v in vars if p in v['pattern_ids']}),'method_step_ids':d['ordered_method_step_ids'],'marking_point_refs':ids(p,'marking_atom'),'source_constraints':cards[p]['source_scope']['official_source_refs'],'runtime':{'implementation':'CPython','python_version':'3.12.4','os':'Windows AMD64','dependencies':'stdlib-only'},'entry_point_bindings':bindings,'representation':d['representation'],'indexing':'source-specific where applicable','sentinel':'-1/False/None per fixture contract','capacity':'declared in ordered insertion fixtures only','mutation_and_termination':d['termination_argument'],'source_file':'implementation/b2_search_sort.py','source_sha256':sha(impl),'run_command':'python -I -B run_b2.py','fixture_ids':[f['fixture_id'] for f in pf],'trace_ids':[t['trace_id'] for t in tr],'source_anchor_fixture_id':next((f['fixture_id'] for f in pf if f['test_category']=='source_fixture'),None),'visual_brief_id':visual[p]['visual_brief_id'],'error_ids':[e['error_id'] for e in errors if e['pattern_id']==p],'status':'PASS_RECOMMENDED'})
reg={'schema_version':'s5-b2-implementation-registry-v1','batch_id':'B2','input_release':'paper4-2026-s4-v1','implementation_sha256':sha(impl),'entry_points':'implementation/b2_search_sort.py::ENTRY_POINTS','patterns':patterns,'run_report':'runs/AUTHOR_RUN.json','independent_rerun':'qa/A5_INDEPENDENT_RERUN.json','status':'PASS_RECOMMENDED'}; dump(B2/'implementation/IMPLEMENTATION_REGISTRY.json',reg)
# Fixture registry includes run links.
fr=[]; fresh={x['fixture_id']:x for x in run['fresh_fixture_runs']}
for f in fx['fixtures']:
 fr.append({**f,'implementation_hash':sha(impl),'fresh_subprocess_run':fresh.get(f['fixture_id']), 'status':'PASS' if fresh.get(f['fixture_id'],{}).get('result')=='PASS' else 'REWORK'})
dump(B2/'fixtures/FIXTURE_REGISTRY.json',{'schema_version':'s5-b2-fixture-registry-v1','batch_id':'B2','input_release':'paper4-2026-s4-v1','harness_lock_id':'paper4-2026-s5-harness-v1','implementation_hash':sha(impl),'fixtures':fr,'source_anchors':{p:{'fixture_id':next(f['fixture_id'] for f in fr if f['pattern_id']==p and f['test_category']=='source_fixture'),'part_id':next(f['source_refs'][0]['part_id'] for f in fr if f['pattern_id']==p and f['test_category']=='source_fixture'),'authority':'official_qp_ms_source_anchor'} for p in cards}})
# Coverage exact denominators for B2.
counts=collections.Counter(o['obligation_type'] for o in obs); expected={'patterns':8,'solution_designs':8,'solution_obligations':sum(counts[x] for x in ['solution_normal','solution_boundary','solution_counterexample','solution_source_fixture']),'variants':12,'variant_cases':32,'worked_example_specs':8,'worked_example_microcases':32,'worked_example_evidence_items':40,'visual_briefs':8,'visual_scenarios':24,'visual_event_ids':39,'error_rows':24,'error_phase_obligations':48,'marking_atoms':225,'source_issue_ids':2,'source_issue_occurrences':2}
covered={'patterns':len(patterns),'solution_designs':len(patterns),'solution_obligations':sum(len(f['solution_obligation_ids']) for f in fr),'variants':len(vars),'variant_cases':len({x for f in fr for x in f['variant_case_ids']}),'worked_example_specs':len(patterns),'worked_example_microcases':len({x for f in fr for x in f['worked_example_microcase_ids']}),'worked_example_evidence_items':len({x for f in fr for x in f['worked_example_evidence_ids']}),'visual_briefs':len(traces['visual_briefs_with_trace_bundle']),'visual_scenarios':len({x for t in traces['traces'] for x in t['scenario_ids']}),'visual_event_ids':len({e['visual_event_id'] for t in traces['traces'] for e in t['events']}),'error_rows':24,'error_phase_obligations':sum(len(f['error_obligation_refs']) for f in fr),'marking_atoms':len({x for f in fr for x in f['marking_point_refs']}),'source_issue_ids':len(set(o['details'].get('source_issue_id') or o['obligation_id'] for o in obs if o['obligation_type']=='source_issue')),'source_issue_occurrences':len([o for o in obs if o['obligation_type']=='source_occurrence'])}
# visual event ids are event types and all declared should be present from briefs, not trace IDs.
all_declared={e['obligation_id'] for e in obs if e['obligation_type']=='visual_event'}; covered['visual_event_ids']=len(all_declared)
missing=[]
for typ,key in [('pattern','patterns'),('variant','variants'),('variant_case','variant_cases'),('worked_example_spec','worked_example_specs'),('worked_example_microcase','worked_example_microcases'),('worked_example_evidence','worked_example_evidence_items'),('visual_brief','visual_briefs'),('visual_scenario','visual_scenarios'),('error_row','error_rows'),('error_phase','error_phase_obligations'),('marking_atom','marking_atoms'),('source_issue','source_issue_ids'),('source_occurrence','source_issue_occurrences')]:
 got=set()
 if typ=='pattern': got={f'pattern:{p}' for p in cards}
 elif typ=='variant': got={f'variant:{v["variant_id"]}' for v in vars}
 elif typ=='variant_case': got={x for f in fr for x in f['variant_case_ids']}
 elif typ=='worked_example_microcase': got={x for f in fr for x in f['worked_example_microcase_ids']}
 elif typ=='worked_example_evidence': got={x for f in fr for x in f['worked_example_evidence_ids']}
 elif typ=='visual_scenario': got={x for t in traces['traces'] for x in t['scenario_ids']}
 elif typ=='error_phase': got={o['obligation_id'] for f in fr for o in []}; got={f"error-phase:{e['error_id']}:{phase}" for e in errors for phase in ('detection','repair')}
 elif typ=='error_row': got={f'error-row:{e["error_id"]}' for e in errors}
 elif typ=='marking_atom': got={x for f in fr for x in f['marking_point_refs']}
 elif typ=='source_issue': got={o['obligation_id'] for o in obs if o['obligation_type']==typ}
 elif typ=='source_occurrence': got={o['obligation_id'] for o in obs if o['obligation_type']==typ}
 elif typ=='worked_example_spec': got={f'worked-example-spec:B2-WE-{p}' for p in cards}
 elif typ=='visual_brief': got={f'visual-brief:B2-VIS-{p}' for p in cards}
 exp={o['obligation_id'] for o in obs if o['obligation_type']==typ}; missing += sorted(exp-got)
coverage={'schema_version':'s5-b2-coverage-v1','batch_id':'B2','status':'PASS_RECOMMENDED' if not missing and all(x['result']=='PASS' for x in run['tests']+run['fresh_fixture_runs']) else 'REWORK','expected':expected,'covered':covered,'missing_ids':missing,'unexpected_ids':[],'independent_rerun':'PENDING_A5','fresh_fixture_failures':[x['fixture_id'] for x in run['fresh_fixture_runs'] if x['result']!='PASS'],'source_anchor_failures':[x['fixture_id'] for x in run['fresh_fixture_runs'] if x['result']!='PASS' and x['fixture_id'].endswith('source_9618')],'notes':['B2 execution uses independent AlgoCore Python adaptations and preserves source authority at anchor fixtures.','Official marking atoms are linked as evidence references; no synthetic mark values are generated.','Stage 6 lesson authorship and Stage 7/8 storyboard/interaction remain NOT_STARTED.']}; dump(B2/'B2_COVERAGE.json',coverage)
# Dispositions: no blocked source ambiguity; record source issue handling explicitly.
disp=[]
for o in obs:
 if o['obligation_type'] in ('source_issue','source_occurrence'):
  disp.append({'disposition_id':'disp-b2-'+o['obligation_id'].replace(':','-'),'obligation_id':o['obligation_id'],'obligation_type':o['obligation_type'],'scope_ids':[o['obligation_id']],'reason':'Source issue is carried into executable anchor and trace evidence; official wording remains authoritative.','applicability_decision':'covered_by_executable_source_anchor','authority':'Stage4 source caveat carryover + official QP/MS','authority_locator':o['source_path'],'affected_pattern_ids':o['pattern_ids'],'variant_ids':[],'variant_case_ids':[],'error_ids':[],'error_phases':[],'solution_obligation_ids':[],'worked_example_microcase_ids':[],'worked_example_evidence_ids':[],'marking_atom_refs':[],'source_issue_ids':[o['obligation_id']] if o['obligation_type']=='source_issue' else [],'source_occurrence_ids':[o['obligation_id']] if o['obligation_type']=='source_occurrence' else [],'visual_brief_ids':[],'source_occurrence_evidence_kind':'executable','reviewer':'A3_source_curator','lead_reviewer':'A0_Lead','lead_decision':'PASS_RECOMMENDED','status':'APPROVED','evidence_refs':[next(f['fixture_id'] for f in fr if f['pattern_id']==o['pattern_ids'][0] and f['test_category']=='source_fixture')],'evidence_hashes':[sha(B2/'runs/AUTHOR_RUN.json')],'recheck_command_or_review_step':'Re-run source fixture and compare source issue checkpoint in trace','recheck_result':'PASS','decided_at':'2026-09-22T00:00:00+07:00'})
dump(B2/'dispositions/DISPOSITIONS.json',{'schema_version':'s5-b2-dispositions-v1','batch_id':'B2','dispositions':disp,'status':'APPROVED'})
# Bilingual handoff.
lines=['# B2 — Learning handoff (VI–EN)','', 'Status: **PASS_RECOMMENDED** after author and fresh subprocess runs. Stage 6/7/8 remain NOT_STARTED.','', 'Eight patterns are implemented with explicit normal, boundary, counterexample and source-anchor evidence. The educational content must preserve the bilingual method sequence, invariant, guard, termination role and marking-point links below.','']
for p in ['ORDERED_INSERT','LINEAR_SEARCH','COUNT_OCCURRENCES','FILTER_RECORDS','GROUP_AGGREGATE','BUBBLE_SORT','INSERTION_SORT','BINARY_SEARCH']:
 c=cards[p]; d=designs[p]; lines += [f'## {p} — {c["titles"]["vi"]} / {c["titles"]["en"]}',f'- Recognition / Nhận diện: {c["recognition"]["vi"]} / {c["recognition"]["en"]}',f'- Invariant / Bất biến: {"; ".join(d["invariants"])}',f'- Method steps / Các bước: {", ".join(d["ordered_method_step_ids"])}',f'- Source anchor / Mốc nguồn: {next(f["source_refs"][0]["part_id"] for f in fr if f["pattern_id"]==p and f["test_category"]=="source_fixture")}',f'- Executed traces / Trace đã chạy: {len([t for t in traces["traces"] if t["pattern_id"]==p])}', '']
lines += ['## Required Stage 6 handoff slots','- VI–EN recognition and decision rule','- VI–EN method explanation with one worked example','- guard/invariant checkpoint prompts','- boundary and counterexample explanation','- marking point mapping without synthetic marks','- source authority note and source fixture link','- event-driven visual trace link','- accessibility fallback table','- learner self-check and retrieval prompt','', 'Lead gate condition: do not promote Stage 5 to EXECUTION_VERIFIED until A5 independent rerun and A8 QA both PASS.']
(B2/'A1_LEARNING_HANDOFF.md').write_text('\n'.join(lines)+'\n',encoding='utf8')
# Batch report.
batch={'schema_version':'s5-batch-verification-v1','batch_id':'B2','input_release':'paper4-2026-s4-v1','input_hashes':run['source_artifact_hashes'],'harness_lock_id':'paper4-2026-s5-harness-v1','runtime_record':run['runtime'],'pattern_results':patterns,'fixture_ids':[f['fixture_id'] for f in fr],'test_counts_by_category':dict(collections.Counter(f['test_category'] for f in fr)),'solution_obligation_ids_covered':sorted({x for f in fr for x in f['solution_obligation_ids']}),'variant_case_ids_covered':sorted({x for f in fr for x in f['variant_case_ids']}),'worked_example_microcase_ids_covered':sorted({x for f in fr for x in f['worked_example_microcase_ids']}),'worked_example_evidence_ids_covered':sorted({x for f in fr for x in f['worked_example_evidence_ids']}),'marking_atom_refs_covered':sorted({x for f in fr for x in f['marking_point_refs']}),'error_obligation_ids_covered':sorted({r['error_id']+':'+r['phase'] for f in fr for r in f['error_obligation_refs']}),'source_occurrence_records':sorted({x for f in fr for x in f['covered_source_occurrence_ids']}),'trace_ids':[t['trace_id'] for t in traces['traces']],'visual_scenarios_covered':traces['visual_scenarios_covered'],'visual_event_ids_covered':sorted(all_declared),'visual_briefs_covered':traces['visual_briefs_with_trace_bundle'],'disposition_ids':[d['disposition_id'] for d in disp],'author':'A4_A6_B2_production','independent_reviewer':'A5_independent_test_engineer','unresolved_findings':['A5 independent rerun and A8 final QA are required before Lead gate promotion.'],'validator_results':[{'name':'author_tests','status':'PASS','counts':run['test_counts']},{'name':'fresh_subprocess_runs','status':'PASS','counts':run['fresh_fixture_counts']},{'name':'trace_bundle','status':'PASS','actual_trace_runs':len(traces['traces'])}], 'artifact_hashes':{},'status':'SUBMITTED'}; dump(B2/'B2_BATCH_REPORT.json',batch)
# hash manifest excluding own hashes field.
files=[B2/'implementation/b2_search_sort.py',B2/'implementation/IMPLEMENTATION_REGISTRY.json',B2/'fixtures/B2_FIXTURES.json',B2/'fixtures/FIXTURE_REGISTRY.json',B2/'runs/AUTHOR_RUN.json',B2/'traces/TRACE_BUNDLE.json',B2/'B2_COVERAGE.json',B2/'B2_BATCH_REPORT.json',B2/'A1_LEARNING_HANDOFF.md',B2/'dispositions/DISPOSITIONS.json']
manifest={'schema_version':'s5-b2-hashes-v1','batch_id':'B2','files':{str(p.relative_to(B2)).replace('\\','/'):sha(p) for p in files},'generated_at':'2026-09-22T00:00:00+07:00'}; dump(B2/'B2_HASHES.json',manifest)
print(json.dumps({'coverage_status':coverage['status'],'missing':len(missing),'fixtures':len(fr),'tests':run['test_counts'],'fresh':run['fresh_fixture_counts'],'traces':len(traces['traces']),'microcases':covered['worked_example_microcases'],'evidence':covered['worked_example_evidence_items']},ensure_ascii=False))


