/* This file is generated by scripts/build-paper4-v2-app-registry.mjs. */
/* Do not edit it directly. */

export const paper4V2LessonLoaders = {
  "data-models": () => import("./lessons/data-models.json").then((module) => module.default),
  "procedural-design": () => import("./lessons/procedural-design.json").then((module) => module.default),
  "validation-rules": () => import("./lessons/validation-rules.json").then((module) => module.default),
  "testing": () => import("./lessons/testing.json").then((module) => module.default),
  "text-processing": () => import("./lessons/text-processing.json").then((module) => module.default),
  "search-collections": () => import("./lessons/search-collections.json").then((module) => module.default),
  "sorting": () => import("./lessons/sorting.json").then((module) => module.default),
  "binary-search": () => import("./lessons/binary-search.json").then((module) => module.default),
  "stack": () => import("./lessons/stack.json").then((module) => module.default),
  "queue": () => import("./lessons/queue.json").then((module) => module.default),
  "linked-list": () => import("./lessons/linked-list.json").then((module) => module.default),
  "recursion": () => import("./lessons/recursion.json").then((module) => module.default),
  "binary-tree": () => import("./lessons/binary-tree.json").then((module) => module.default),
  "dictionary": () => import("./lessons/dictionary.json").then((module) => module.default),
  "hashing": () => import("./lessons/hashing.json").then((module) => module.default),
  "oop-model": () => import("./lessons/oop-model.json").then((module) => module.default),
  "oop-state": () => import("./lessons/oop-state.json").then((module) => module.default),
  "oop-inheritance": () => import("./lessons/oop-inheritance.json").then((module) => module.default),
  "oop-aggregation": () => import("./lessons/oop-aggregation.json").then((module) => module.default),
  "text-files": () => import("./lessons/text-files.json").then((module) => module.default),
  "object-files": () => import("./lessons/object-files.json").then((module) => module.default),
  "random-files": () => import("./lessons/random-files.json").then((module) => module.default),
  "exceptions": () => import("./lessons/exceptions.json").then((module) => module.default),
  "performance": () => import("./lessons/performance.json").then((module) => module.default),
  "graphs": () => import("./lessons/graphs.json").then((module) => module.default),
  "exam-workflow": () => import("./lessons/exam-workflow.json").then((module) => module.default),
} as const;

export type Paper4V2LessonSlug = keyof typeof paper4V2LessonLoaders;

