# Each row is a manual semantic classification after QP/MS reading.
# part|primary|additional assessed|context|task mode|variants|mark-scheme distinguishing requirement
MAP={
's21_41': '''
1(a)|DATA_RECORD||LIST_SETUP|declare_initialize|record_role=node;fields=data:int,nextNode:int;oop_constructor_role=record_substitute|The named record and its two integer fields are assessed; a Python class here substitutes for a record, not an encapsulated business object.
1(b)|LIST_SETUP||DATA_RECORD|declare_initialize|head_start=0;free_start=5;initial_data=supplied_ten_node_table|The array of node records, all supplied field values and both initial pointers are assessed.
1(c)(i)|LIST_TRAVERSE||LIST_SETUP|implement|order=logical_nextNode_links;termination=null_-1;algorithm_source=authored|Marks distinguish following nextNode, outputting node data and advancing the pointer until -1 from printing physical array positions.
1(c)(ii)|EVIDENCE_RUN||MAIN_FLOW,LIST_TRAVERSE|test_evidence|required_run=call_outputNodes;expected_evidence=linked_list_output|The mark is for the screenshot of the traversal output; calling the existing procedure does not newly implement traversal.
1(d)(i)|LIST_INSERT||LIST_SETUP,DATA_RECORD|implement|insert_position=tail;allocation=free_list;result=Boolean;algorithm_source=authored|The function inputs a value, checks full storage, allocates a free node, finds the list end, updates links/free pointer and reports success.
1(d)(ii)|MAIN_FLOW||LIST_INSERT,LIST_TRAVERSE|integrate|call_order=outputNodes,addNode,outputNodes;result_handling=success_or_full_message|Marks require addNode with appropriate parameters/result handling and traversal calls before and after; the insertion code was assessed in the previous part.
1(d)(iii)|EVIDENCE_RUN||MAIN_FLOW,LIST_INSERT,LIST_TRAVERSE|test_evidence|test_input=5;expected_evidence=before_and_after_insertion|The screenshot must show the prior list, insertion input/result and list with the new item at the end.
2(a)|DATA_STORAGE|||declare_initialize|dimensions=1D;capacity=10;initialization=supplied_integer_sequence|Marks require the array identifier and the ten given integer values.
2(b)(i)|LINEAR_SEARCH||DATA_STORAGE|implement|return=Boolean_existence;match_goal=first_or_any_match;algorithm_source=authored|The function accepts the search value, examines array elements and returns true when found or false when absent; it does not count occurrences.
2(b)(ii)|MAIN_FLOW||LINEAR_SEARCH|integrate|input=integer;result_handling=found_or_not_found_message|Input/casting, passing the value, using the Boolean result and reporting it are assessed; no new search implementation or repeat-until-valid loop is required.
2(b)(iii)|EVIDENCE_RUN||MAIN_FLOW,LINEAR_SEARCH|test_evidence|tests=one_present_and_one_absent;expected_evidence=two_search_results|Separate screenshot evidence is required for found and not-found tests.
2(c)|BUBBLE_SORT||DATA_STORAGE|complete_pseudocode|direction=descending;dimensions=1D;algorithm_source=supplied_five_incomplete_statements|MS distinguishes loop limits, comparison direction, swap assignments and preserving the supplied bubble-sort logic; general translation is not a separate algorithm pattern.
3(a)|OOP_CLASS|||declare_initialize|class=TreasureChest;attributes=private_question_answer_points;constructor=shown_in_MS_example_not_separately_named_in_QP;python_declarations=comments|The class identity and private typed attributes are assessed; this is the encapsulated TreasureChest context, not the record substitute in1(a).
3(b)|FILE_READ_OBJECTS|OOP_INSTANTIATE,DATA_STORAGE|OOP_CLASS|implement|source_file=TreasureChestData.txt;record_lines=3;object_count=5;missing_file=exception_and_message|Read question/answer/points groups, construct TreasureChest objects and store them in arrayTreasure; array declaration and object creation are explicit criteria alongside file handling.
3(c)(i)|OOP_GET||OOP_CLASS|implement|method=getQuestion;return=stored_question;parameters=none_besides_self|Return the stored question attribute; no derived score or predicate is computed.
3(c)(ii)|RULE_COMPUTE||OOP_CLASS|implement|method=checkAnswer;rule=compare_supplied_answer_with_stored_answer;return=Boolean|The method accepts an answer, compares it with the object's answer and returns the correctness predicate; its name does not make it a stored-attribute accessor.
3(c)(iii)|RULE_COMPUTE||OOP_CLASS|implement|method=getPoints;rule=attempt_bands_1_2_3to4_other;division=integer;return=points|Marks distinguish each attempt-count scoring band and integer division; the computed score is not a direct getter.
3(c)(iv)|MAIN_FLOW|VALIDATE_INPUT|FILE_READ_OBJECTS,OOP_GET,RULE_COMPUTE|integrate|question_choice=1_to_5;loop=repeat_answer_until_correct;state=attempt_counter;result=awarded_points|Main orchestration selects/validates a question, repeats answer checking, counts attempts and outputs computed points using existing methods.
3(c)(v)|EVIDENCE_RUN||MAIN_FLOW,RULE_COMPUTE,FILE_READ_OBJECTS|test_evidence|tests=question1_correct_first_attempt_and_question5_correct_second_attempt|Two prescribed input/output test histories are assessed, not new implementations of answer checking or scoring.
''',
's22_41': '''
1(a)|DATA_STORAGE|||declare_initialize|dimensions=one_or_more_arrays;capacity=11;fields=player_name_and_score|Global array structure(s), appropriate field types and eleven-element capacity are required.
1(b)|FILE_READ_ARRAY||DATA_STORAGE|implement|source_file=HighScore.txt;records=10;record_lines=2;order=player_then_score|The procedure opens/reads the file, stores each name-score pair, closes the file and may gain the stated file-handling criteria; no ordering algorithm is implemented here.
1(c)|OUTPUT_FORMAT||DATA_STORAGE|output|output=player_name_space_score;layout=one_player_per_line;range=stored_array_elements|The procedure loops through storage and emits each name/score pair together on its own line.
1(d)(i)|MAIN_FLOW||FILE_READ_ARRAY,OUTPUT_FORMAT|integrate|call_order=ReadHighScores_then_OutputHighScores|Marks require the two existing procedure calls in the correct order.
1(d)(ii)|EVIDENCE_RUN||MAIN_FLOW,FILE_READ_ARRAY,OUTPUT_FORMAT|test_evidence|expected_evidence=ten_loaded_names_and_scores_optional_extra_blank|The screenshot of loaded high scores is assessed; file reading and formatted output are under test.
1(e)(i)|VALIDATE_INPUT|||adapt|constraints=name_length3_score_integer_1to100000;retry=until_valid|Marks distinguish obtaining inputs, ensuring a three-character name and validating the integer score range.
1(e)(ii)|ORDERED_INSERT||DATA_STORAGE,FILE_READ_ARRAY|implement|key=score;direction=descending;retained_records=top10;insertion=conditional_on_qualifying_score;named_algorithm_restriction=none_in_QP|Find the insertion position and store existing/incoming name-score pairs correctly while retaining a top-ten list; QP does not name insertion sort or mandate a named sorting algorithm.
1(e)(iii)|MAIN_FLOW||ORDERED_INSERT,OUTPUT_FORMAT,VALIDATE_INPUT|integrate|call_order=display_before_insert_display_after;parameters=player_name_and_score|The assessed work calls the insertion procedure and the existing display procedure before/after; no new sort or formatting procedure is written.
1(e)(iv)|EVIDENCE_RUN||MAIN_FLOW,ORDERED_INSERT,OUTPUT_FORMAT|test_evidence|test_input=JKL_9999;expected_evidence=before_after_with_new_second_place|The screenshot must demonstrate insertion of the prescribed player/score and its resulting position.
1(f)|FILE_WRITE||DATA_STORAGE,ORDERED_INSERT|implement|target_file=NewHighScore.txt;target_role=student_created_output;records=10;record_order=name_then_score;mode=write|The procedure opens the new output file, writes the top ten in the stated field order and closes it; it does not read a missing input file.
2(a)|OOP_CLASS|||declare_initialize|class=Balloon;attributes=private;constructor_parameters=defence_item_colour;health_initial=100|The class and private typed attributes, two constructor parameters, parameter assignments and default health100 are assessed.
2(b)|OOP_GET||OOP_CLASS|implement|method=GetDefenceItem;return=stored_defence_item|The accessor takes no business parameter and returns the stored defence item.
2(c)|OOP_UPDATE||OOP_CLASS|implement|method=ChangeHealth;update=add_integer_parameter_to_health|The parameter is added to existing health; this is a relative update, not replacement by a setter.
2(d)|RULE_COMPUTE||OOP_CLASS|implement|method=CheckHealth;predicate=health_le0;return=Boolean|The method computes a Boolean from the health threshold and returns both outcomes; it is not a stored-attribute getter.
2(e)|OOP_INSTANTIATE||OOP_CLASS|integrate|input=defence_item_and_colour;object_identifier=Balloon1|Input strings and construction of Balloon1 with those values are explicitly assessed.
2(f)|MAIN_FLOW||OOP_UPDATE,OOP_GET,RULE_COMPUTE|implement|scope=function_Defend;parameter=Balloon_object;workflow=input_strength_change_health_output_defence_check_health_return_object|The function coordinates existing methods, passes negative strength, uses their results and returns the amended object; it does not implement the object's ChangeHealth method again.
2(g)(i)|MAIN_FLOW||MAIN_FLOW,OOP_INSTANTIATE|integrate|call=Defend;return_handling=store_returned_Balloon_object|The assessed call supplies Balloon1 and retains the returned object; the body of Defend was assessed previously.
2(g)(ii)|EVIDENCE_RUN||MAIN_FLOW,OOP_UPDATE,RULE_COMPUTE|test_evidence|test_input=Shield_Red_50;expected_evidence=defence_item_and_remaining_health_status|The screenshot demonstrates the specified balloon/opponent interaction using already-written methods.
3(a)|QUEUE_SETUP|||declare_initialize|queue_model=circular;capacity=10;element_type=string;head_initial=0;tail_initial=0;count_initial=0;tail_role=next_free|The ten-element string queue and all three zero-initialised state variables are required.
3(b)|QUEUE_ENQUEUE||QUEUE_SETUP|complete_pseudocode|queue_model=circular;full_test=item_count_equals_capacity;wrap=tail_after_slot9_to0;result=Boolean;algorithm_source=supplied_five_gaps|MS assesses completed queue indices/full return/count update plus function structure and reference-state handling, preserving circular wrap.
3(c)|QUEUE_DEQUEUE||QUEUE_SETUP|implement|queue_model=circular;empty_test=item_count_zero;empty_result=QP_string_FALSE;remove_from=head;wrap=head_after9_to0|The function handles empty state, retrieves at head, updates head with wrap and decrements count; published example inconsistencies are not silently treated as correct variants.
3(d)(i)|MAIN_FLOW||QUEUE_ENQUEUE,QUEUE_DEQUEUE|integrate|calls=eleven_enqueue_then_two_dequeue;result_handling=per_enqueue_success_and_each_dequeue_value|The main program loops over eleven inputs, calls existing operations, reports success and displays two returned items.
3(d)(ii)|EVIDENCE_RUN||MAIN_FLOW,QUEUE_ENQUEUE,QUEUE_DEQUEUE|test_evidence|test_inputs=A_through_K;expected_evidence=ten_success_one_full_then_A_B|The screenshot demonstrates the prescribed full-capacity test and two removals; queue algorithms are context.
''',
's22_42': '''
1(a)|STACK_SETUP|||declare_initialize|capacity=10;element_type=integer;pointer_role=next_free;pointer_initial=0|Global StackData with ten integer slots and zero-initialised StackPointer are explicitly assessed.
1(b)|OUTPUT_FORMAT||STACK_SETUP|output|range=all10_physical_array_elements;include=StackPointer|Output all ten physical slots and the pointer, including unused/popped slots where present; no stack traversal/pop is implemented.
1(c)|STACK_PUSH||STACK_SETUP|implement|pointer_role=next_free;full=pointer10;success_result=Boolean;algorithm_source=authored|Check capacity, store at the next-free pointer, advance it and return success; this row implements Push rather than merely calling it.
1(d)(i)|MAIN_FLOW||STACK_PUSH,OUTPUT_FORMAT|integrate|calls=eleven_push_attempts_then_output;result_handling=success_or_full_per_attempt|The main program obtains eleven values, calls Push and reports its Boolean result before calling the existing display procedure.
1(d)(ii)|EVIDENCE_RUN||MAIN_FLOW,STACK_PUSH,OUTPUT_FORMAT|test_evidence|test_inputs=11_through21;expected_evidence=ten_stored_one_rejected_and_array|Screenshot evidence of all eleven inputs, capacity messages and the stored array is assessed.
1(e)(i)|STACK_POP||STACK_SETUP|implement|pointer_role=next_free;read_index=pointer_minus1;empty=pointer0;empty_result=integer_-1|MS distinguishes empty sentinel, access to the current top, pointer decrement and returned removed item.
1(e)(ii)|EVIDENCE_RUN||MAIN_FLOW,STACK_POP,OUTPUT_FORMAT|test_evidence|calls=two_pop_after_existing_eleven_push_test;output=stack_contents_after_two_pops;storage_display=MS_accepts_retained_cleared_or_shortened_slots|The marks are for before/after output screenshots. Two calls to the existing Pop function do not constitute a new Pop implementation.
2(a)|RANDOM_ARRAY|DATA_STORAGE||declare_initialize|dimensions=10x10;scope=main_local;element_type=integer;random_bounds=1_to100|MS separately requires the local2D array and random initialisation of every cell; those separable requirements support both tags.
2(b)(i)|BUBBLE_SORT||RANDOM_ARRAY,DATA_STORAGE|translate_pseudocode|dimensions=2D;order=ascending_within_each_row;algorithm_source=complete_supplied_pseudocode;built_in_sort=prohibited|The nested dimension/pass/comparison loops and adjacent swap implement the supplied row-wise sort; no general unnamed-algorithm tag is added.
2(b)(ii)|OUTPUT_FORMAT|MAIN_FLOW|BUBBLE_SORT|mixed|layout=10x10_grid;calls=before_and_after_sort|Writing the grid-output procedure and placing calls before/after the sort are separate assessed actions; sorting is invoked context.
2(b)(iii)|EVIDENCE_RUN||OUTPUT_FORMAT,MAIN_FLOW,BUBBLE_SORT|test_evidence|expected_evidence=unsorted_and_sorted_2D_data|The screenshot is assessed for showing the array before and after sorting.
2(c)(i)|BINARY_SEARCH||BUBBLE_SORT|complete_pseudocode|search_space=first_array_row;implementation=recursive;return=found_index_or_minus1;algorithm_source=supplied_six_gaps;source_caveat=midpoint_and_guard_require_Stage5_verification|Six completed statements, function parameters/recursive calls and the supplied integer-division logic are assessed; source defects are preserved, not endorsed.
2(c)(ii)|EVIDENCE_RUN||MAIN_FLOW,BINARY_SEARCH|test_evidence|tests=present_first_row_value_and_absent_value;expected_evidence=index_and_minus1|Screenshot output is required for one successful first-row search and one absent value; no new search code is assessed.
3(a)|OOP_CLASS|||declare_initialize|class=Card;attributes=private_Number_Colour;constructor_parameters=number_colour|The private typed attributes and two-parameter constructor belong to an encapsulated Card class.
3(b)|OOP_GET||OOP_CLASS|implement|methods=GetNumber_GetColour;return=stored_attributes|The two methods return stored attributes; neither computes a new rule-based value.
3(c)|FILE_READ_OBJECTS|OOP_INSTANTIATE,DATA_STORAGE|OOP_CLASS|implement|source_file=CardValues.txt;object_count=30;record_lines=2;record_order=number_colour|The30-element object array, per-record object construction and file reading/storage are explicit marking requirements.
3(d)|UNIQUE_SELECTION|VALIDATE_INPUT|DATA_STORAGE|implement|candidate_input=1_to30;bookkeeping=chosen_indices;retry=out_of_range_or_already_selected;return=available_index|The function validates range, rejects already selected cards, records a newly taken card and returns its index; checking availability differs from an ordinary key search.
3(e)(i)|MAIN_FLOW|DATA_STORAGE,OUTPUT_FORMAT|UNIQUE_SELECTION,OOP_GET,FILE_READ_OBJECTS|integrate|target=Player1_Card_array;selection_count=4;objects=references_to_existing_cards;output=number_and_colour_of_each_selected_card|The row declares Player1 storage, calls selection four times, stores existing Card objects and outputs their attributes; it does not construct four new Card instances.
3(e)(ii)|EVIDENCE_RUN||MAIN_FLOW,UNIQUE_SELECTION,VALIDATE_INPUT,OUTPUT_FORMAT|test_evidence|tests=1_5_9_10_and_2_2_3_4_4_5;expected_evidence=both_selection_tests|The single mark covers both prescribed tests, including rejection of repeated choices.
''',
'w21_41': '''
1(a)|ALGORITHM_TRANSLATE|||translate_pseudocode|algorithm=Unknown;implementation=recursive;parameters=X_Y;branches=XltY_XeqY_XgtY;division=integer|The named function, correct integer division and preservation of the supplied recursive pseudocode are assessed; no named search/sort/ADT operation fits.
1(b)(i)|MAIN_FLOW||ALGORITHM_TRANSLATE|integrate|calls=Unknown_10_15_10_10_15_10;output=parameters_and_return_values|The main program identifies the parameters, makes all three prescribed calls and outputs their return values.
1(b)(ii)|EVIDENCE_RUN||MAIN_FLOW,ALGORITHM_TRANSLATE|test_evidence|tests=XltY_XeqY_XgtY;expected_evidence=all_three_recursive_runs|The marks concern screenshots for all three parameter pairs and their recursive outputs/returns.
1(c)|ALGORITHM_REWRITE||ALGORITHM_TRANSLATE|transform|direction=recursive_to_iterative;algorithm=Unknown;preserve=intermediate_outputs_and_return;initial_accumulator=1|MS requires iterative control with two parameters, the correct accumulator/updates, intermediate outputs and final return, preserving both branches and the base case.
1(d)(i)|MAIN_FLOW||ALGORITHM_REWRITE|integrate|calls=IterativeUnknown_same_three_pairs;output=parameters_and_return_values|The row calls the already-written iterative function with the same three pairs and outputs each result.
1(d)(ii)|EVIDENCE_RUN||MAIN_FLOW,ALGORITHM_TRANSLATE,ALGORITHM_REWRITE|test_evidence|expected_evidence=both_function_forms_all_three_pairs|Screenshots compare both implemented forms on the prescribed parameter pairs; transformation was assessed in1(c).
2(a)|OOP_CLASS|||declare_initialize|class=Picture;attributes=private_description_width_height_frameColour;constructor_parameters=all4|The class, four typed private attributes, four-parameter constructor and assignments are assessed.
2(b)|OOP_GET||OOP_CLASS|implement|methods=description_width_height_frame_colour;return=stored_attributes|Four direct attribute getters are requested; these are not the later multi-condition search.
2(c)|OOP_SET||OOP_CLASS|implement|method=SetDescription;update=replace_description_with_parameter|The setter takes a new description and assigns it directly, with no relative arithmetic or computed value.
2(d)|DATA_STORAGE||OOP_CLASS|declare_initialize|element_type=Picture;capacity=100;operation=declare_object_array|The only required mark is array declaration with100 Picture elements; constructing business-data instances is not independently required by this row.
2(e)|FILE_READ_OBJECTS|OOP_INSTANTIATE|DATA_STORAGE,OOP_CLASS|implement|source_file=Pictures.txt;record_lines=4;record_order=description_width_height_colour;termination=end_of_file;return=record_count;missing_file=exception|Read records, create/store one Picture per record, handle the file and count/return objects; array declaration is prior context, not newly assessed storage setup.
2(f)|MAIN_FLOW||FILE_READ_OBJECTS|integrate|call=ReadData;result_handling=retain_number_of_loaded_pictures|Call the existing loader and store/use its returned object count; the file algorithm is context.
2(g)|FILTER_RECORDS||FILE_READ_OBJECTS,OOP_GET|adapt|match=frame_colour_and_width_le_max_and_height_le_max;case=insensitive_colour;result=all_matching_pictures;scan_limit=loaded_count|Input three constraints, check all three against each loaded object through getters and output every match; this is conjunctive filtering, not one-key existence search.
2(h)|EVIDENCE_RUN||FILTER_RECORDS,OOP_GET|test_evidence|tests=BLACK_100_100_and_silver_25_25;expected_evidence=matching_set_and_empty_set|Two screenshots show all matches for the first constraints and no matches for the second.
3(a)|TREE_SETUP|||declare_initialize|capacity=20;representation=2D_array_20x3;fields=left_data_right;root_initial=-1;free_initial=0|null-root/free-pointer initialisation and correctly shaped integer node storage are required; physical rows are not a traversal.
3(b)|TREE_INSERT||TREE_SETUP|complete_pseudocode|algorithm_source=supplied_six_gaps;input=user_integer;equal_key_branch=right;allocation=sequential_FreeNode;empty_tree=root0;full=FreeNode_gt19|The six completions and remaining pseudocode must correctly place a binary-search-tree node and propagate amended array/root/free state.
3(c)|OUTPUT_FORMAT||TREE_SETUP|output|range=all20_physical_rows;layout=left_pointer_data_right_pointer_per_row|The procedure prints every stored node row in physical array order with field order/spacing; it does not follow tree links or sort node data.
3(d)(i)|MAIN_FLOW||TREE_INSERT,OUTPUT_FORMAT|integrate|calls=ten_AddNode_then_PrintAll|Ten calls to the existing insertion procedure followed by the existing physical-array printer are assessed.
3(d)(ii)|EVIDENCE_RUN||MAIN_FLOW,TREE_INSERT,OUTPUT_FORMAT|test_evidence|test_input=10_5_15_8_12_6_20_11_9_4;expected_evidence=physical_node_table|The screenshot must show the resulting node array from the prescribed insertion sequence.
3(e)(i)|TREE_TRAVERSE||TREE_SETUP,TREE_INSERT|implement|order=inorder_left_root_right;implementation=recursive;termination=null_child_-1;algorithm_source=authored_from_traversal_definition|MS distinguishes child checks, recursive calls and root output in left-root-right order; physical array printing is a different task.
3(e)(ii)|EVIDENCE_RUN||TREE_TRAVERSE,TREE_INSERT|test_evidence|input=same_ten_insertions_as3dii;expected_evidence=inorder_data_output|The mark is for the traversal screenshot using the existing tree, not another traversal implementation.
''',
'w22_41': '''
1(a)|DATA_STORAGE|||declare_initialize|capacity=100;dimensions=1D;element_type=integer;scope=global|The global100-integer DataArray declaration is assessed.
1(b)|FILE_READ_ARRAY||DATA_STORAGE|implement|source_file=IntegerData.txt;records=100;record_lines=1;exceptions=required|The procedure reads100 integer values into existing storage and handles file exceptions; it does not search or sort.
1(c)|COUNT_OCCURRENCES|VALIDATE_INPUT|DATA_STORAGE|implement|input=integer_1to100;retry=until_in_range;result=count_all_matches;scan=100_elements|MS requires input range/type validation, scanning all100 entries, incrementing a count for each match and returning the total; FindValues is not an existence-only search.
1(d)(i)|MAIN_FLOW||FILE_READ_ARRAY,COUNT_OCCURRENCES,VALIDATE_INPUT|integrate|call_order=ReadFile_FindValues;output=returned_frequency_with_message|Call the existing loader and frequency function and output its result; counting is not implemented again.
1(d)(ii)|EVIDENCE_RUN||MAIN_FLOW,COUNT_OCCURRENCES|test_evidence|test_input=61;expected_evidence=frequency2|The screenshot records the prescribed input and its frequency result.
1(e)|BUBBLE_SORT|OUTPUT_FORMAT,MAIN_FLOW|DATA_STORAGE,FILE_READ_ARRAY|implement|algorithm_source=authored;comparison=adjacent;direction=QP_unspecified_MS_examples_ascending;output=sorted_array;call=from_main|The row writes bubble-sort loops/swaps, outputs the sorted contents and calls the new procedure from main; sorting is the concrete primary operation.
2(a)(i)|OOP_CLASS|||declare_initialize|class=Card;attributes=private_Number_Colour;constructor_parameters=2|The Card class and private typed fields with two constructor parameters/assignments are required.
2(a)(ii)|OOP_GET||OOP_CLASS|implement|methods=GetNumber_GetColour;return=stored_attributes|Both direct accessors return their associated stored attributes.
2(a)(iii)|OOP_INSTANTIATE||OOP_CLASS|declare_initialize|objects=15_named_Card_values;numbers=1_to5;colours=red_blue_yellow|Instantiate all fifteen specified number-colour Card objects; this is construction, not only declaring array capacity.
2(b)(i)|OOP_CLASS||OOP_CLASS|declare_initialize|class=Hand;composition=private_Card_array_capacity10;constructor_parameters=5_Card_objects;initial=FirstCard0_NumberCards5|The Hand class includes a private Card collection and pointers/count, accepts five objects and stores them; composition is not inheritance or a new Card constructor.
2(b)(ii)|OOP_GET||OOP_CLASS|implement|method=GetCard;parameter=index;return=stored_Card_at_index|Return an indexed stored member of the Hand collection; it is an accessor rather than a search.
2(b)(iii)|OOP_INSTANTIATE||OOP_CLASS,OOP_INSTANTIATE|declare_initialize|objects=two_Hand_instances;arguments=specified_five_existing_Cards_each|Construct two Hand objects by passing the specified existing Card objects; parent Card data creation remains context.
2(c)(i)|RULE_COMPUTE||OOP_GET,OOP_CLASS|implement|aggregation=one_hand_total;cards=5;colour_bonus=red5_blue10_yellow15;include=each_card_number;return=score|Loop over five cards through existing accessors, add the stated colour bonuses and numbers, and return one score; no grouping by repeated keys is requested.
2(c)(ii)|MAIN_FLOW||RULE_COMPUTE,OOP_INSTANTIATE|adapt|calls=CalculateValue_for_two_hands;comparison=highest_score_wins;tie=draw|Call the existing score function for both hands, compare its returns and report winner or draw. This result handling does not implement CalculateValue again.
2(c)(iii)|EVIDENCE_RUN||MAIN_FLOW,RULE_COMPUTE|test_evidence|expected_evidence=winning_player_from_supplied_hands|The screenshot demonstrates the final comparison outcome for the supplied hands.
3(a)|TREE_SETUP|||declare_initialize|capacity=20;representation=2D_array_20x3;fields=left_data_right;initialization=all_minus1|Create tree-node storage and initialise all60 integer cells to -1.
3(b)|TREE_SETUP|||adapt|initialization=supplied_six_node_table;root_initial=0;free_initial=6|MS requires copying the supplied node values and initialising root/free pointers; no insertion algorithm is written.
3(c)|TREE_SEARCH||TREE_SETUP|complete_pseudocode|implementation=recursive;return=matching_node_index_or_minus1;algorithm_source=supplied_four_gaps;selection=left_or_right_child_from_data_comparison|Complete the recursive tree-search returns and child choices; no midpoint or array-interval binary search is involved.
3(d)|TREE_TRAVERSE||TREE_SETUP|implement|order=postorder_left_right_root;implementation=recursive;argument=root_node_or_index_consistent_with_implementation|MS requires null-child checks, recursive child visits and data output in left-right-root order; it allows the root representation to match the implementation.
3(e)(i)|MAIN_FLOW||TREE_SEARCH,TREE_TRAVERSE|integrate|search_input=15;calls=SearchValue_then_PostOrder;result=found_index_or_message|The main program supplies the search value/root, handles its return and invokes the existing postorder traversal.
3(e)(ii)|EVIDENCE_RUN||MAIN_FLOW,TREE_SEARCH,TREE_TRAVERSE|test_evidence|expected_evidence=index_for15_and_postorder_sequence|The screenshot is assessed for the combined tree-search and traversal output.
''',
'w22_42': '''
1(a)|DATA_STORAGE|||declare_initialize|dimensions=100x2;fields=job_number_priority;element_type=integer;count=NumberOfJobs_global|The two-dimensional integer job table and global item count are declared; priority does not turn this into a queue ADT.
1(b)|DATA_STORAGE|||implement|procedure=Initialise;initialization=all_slots_minus1_and_count0|The procedure loops through both dimensions, writes -1 and initialises the count; no job is appended yet.
1(c)|ARRAY_APPEND||DATA_STORAGE|implement|capacity=100;append_position=next_free_row;fields=job_number_priority;result=Added_or_Not_added|The procedure checks capacity, stores a job at the next available row and increments count; it neither inserts into sorted position nor changes queue head/tail pointers.
1(d)|MAIN_FLOW||DATA_STORAGE,ARRAY_APPEND|integrate|call_order=Initialise_then_five_AddJob;test_pairs=12_10__526_9__33_8__12_9__78_1|Call the existing initialiser and append routine with the five given pairs in order.
1(e)|INSERTION_SORT||DATA_STORAGE|implement|key=priority_column;direction=ascending_numeric;priority_meaning=1_highest_10_lowest;move=whole_job_priority_pair;algorithm_source=authored|The procedure grows the ordered prefix by comparing priorities and shifting/inserting the complete job pair; this differs from appending a job and from sorting job numbers.
1(f)|OUTPUT_FORMAT||DATA_STORAGE|output|range=NumberOfJobs_live_rows;layout=job_number_priority_label_priority_value_one_per_line|The procedure emits each active job and its priority on the same line with the word priority between them.
1(g)(i)|MAIN_FLOW||INSERTION_SORT,OUTPUT_FORMAT|integrate|call_order=InsertionSort_then_PrintArray|The two existing subroutines are called in order; no new sorting or formatting logic is required.
1(g)(ii)|EVIDENCE_RUN||MAIN_FLOW,INSERTION_SORT,OUTPUT_FORMAT|test_evidence|expected_evidence=five_added_messages_and_priority_sorted_jobs;equal_priority=526_and12_either_order_accepted|The screenshot shows added jobs and their sorted order; MS explicitly permits either order for the equal-priority pair.
2(a)|OOP_CLASS|||declare_initialize|class=Character;attributes=private_name_x_y;constructor_parameters=3|Declare the private typed attributes and assign all three constructor parameters; published spelling defects are not endorsed as required identifiers.
2(b)|OOP_GET||OOP_CLASS|implement|methods=GetName_GetX_GetY;return=stored_attributes|The three methods return their respective stored attributes.
2(c)|OOP_UPDATE||OOP_CLASS|implement|method=ChangePosition;update=add_XChange_and_YChange|Both coordinate deltas are added to existing state, distinguishing relative movement from direct setters.
2(d)|FILE_READ_OBJECTS|OOP_INSTANTIATE,DATA_STORAGE|OOP_CLASS|adapt|source_file=Characters.txt;object_count=10;record_lines=3;record_order=name_x_y|The row declares object-array storage, reads each record, constructs Character objects and stores all ten; constructor definition is earlier context.
2(e)|LINEAR_SEARCH|VALIDATE_INPUT|OOP_GET,FILE_READ_OBJECTS|adapt|key=character_name;case=normalised_comparison;retry=until_name_exists;return_state=store_found_index|MS distinguishes searching names through GetName, handling case, repeating failed user choices and retaining the matched position.
2(f)|MAIN_FLOW|VALIDATE_INPUT|OOP_UPDATE,LINEAR_SEARCH|adapt|allowed_inputs=A_W_S_D;retry=until_allowed;directions=A_left_W_up_S_down_D_right;method=existing_ChangePosition|Validate a new movement choice and dispatch the corresponding deltas to ChangePosition; the coordinate-update method itself is invoked context.
2(g)(i)|OUTPUT_FORMAT||OOP_GET,MAIN_FLOW|adapt|layout=name_has_changed_coordinates_to_X_equals_value_and_Y_equals_value|The row builds the specified message with name/x/y values obtained through getters; no new coordinate change or getter implementation is assessed.
2(g)(ii)|EVIDENCE_RUN||MAIN_FLOW,LINEAR_SEARCH,VALIDATE_INPUT,OOP_UPDATE,OUTPUT_FORMAT|test_evidence|test_inputs=THOMAS_qui_X_A;expected_evidence=retry_invalid_name_and_move_then_updated_coordinates|The screenshot must reflect both invalid-input retries and the accepted left move.
3(a)|QUEUE_SETUP|||declare_initialize|queue_model=linear;capacity=100;element_type=integer;head_role=first_stored_item;tail_role=next_free;initial_pointers=appropriate_values_MS_example_head_minus1_tail0|QP requires appropriate initial pointers; MS gives head=-1/tail=0 as an example. No circular wrap or item counter is specified.
3(b)|QUEUE_ENQUEUE||QUEUE_SETUP|implement|queue_model=linear;full=tail_at_capacity;first_item=initialise_head;result=Boolean;wrap=none|MS distinguishes tail capacity, append/advance, success return and initial head update; circular wrapping is not part of this operation.
3(c)|MAIN_FLOW||QUEUE_ENQUEUE|adapt|values=1_to20_ascending;result=all_success_or_unsuccessful|The main loop invokes Enqueue for all20 values and reports overall success; it does not implement enqueue again.
3(d)|QUEUE_REDUCE|ALGORITHM_REWRITE|QUEUE_SETUP|transform|direction=iterative_to_recursive;aggregation=sum;destructive=false;iteration_order=backward_from_Start_minus1_to_head;recursion=backward_index|Rewrite the supplied iterative queue-total computation recursively, with base case, recurrence and returned sum; queue removal is not required.
3(e)(i)|MAIN_FLOW||QUEUE_REDUCE,ALGORITHM_REWRITE|adapt|call=recursive_total;result=output_return_value|Call the previously written recursive total function with the appropriate starting position and output its return.
3(e)(ii)|EVIDENCE_RUN||MAIN_FLOW,QUEUE_REDUCE,ALGORITHM_REWRITE|test_evidence|expected_evidence=total210|The screenshot showing the sum210 is assessed; no new recursion or queue operation is written.
'''
}
