import Link from "next/link";
import { AlertTriangle, ArrowLeft, ArrowRight, BookOpen, CheckCircle2, Clock3, Eye, Goal, Lightbulb, Map, Route } from "lucide-react";
import type { Locale, StudyMapCatalog } from "@/app/lib/paper2/catalog";
import type { LessonSource, Paper2Lesson, TheoryBlock } from "@/app/lib/paper2/lesson-types";
import type { Paper2VisualSelection } from "@/app/lib/paper2/visual-types";
import { parsePaper2AnswerTable } from "@/app/lib/paper2/structured-answer";
import { paper2Href } from "@/app/lib/paper2/catalog";
import { Paper2LocaleBoundary } from "../Paper2LocaleBoundary";
import { topicStatusLabel } from "../shared";
import { LessonProgress } from "./LessonProgress";
import { LessonSectionActions } from "./LessonSectionActions";
import { Paper2VisualExplorer } from "./Paper2VisualExplorer";
import learnerVisualStyles from "./Paper2LearnerVisual.module.css";
import styles from "./Paper2Lesson.module.css";

function Theory({ block, locale, sources }: { readonly block: TheoryBlock; readonly locale: Locale; readonly sources: readonly LessonSource[] }) {
  return <section className={styles.theoryBlock} id={block.id}><h3>{block.title[locale]}</h3>{block.paragraphs.map((paragraph, index) => <p key={index}>{paragraph[locale]}</p>)}{block.bullets && <ul>{block.bullets.map((bullet, index) => <li key={index}>{bullet[locale]}</li>)}</ul>}{block.table && <div className={styles.tableScroll} role="region" tabIndex={0} aria-label={block.title[locale]}><table><thead><tr>{block.table.headers.map((header, index) => <th key={index} scope="col">{header[locale]}</th>)}</tr></thead><tbody>{block.table.rows.map((row, rowIndex) => <tr key={rowIndex}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell[locale]}</td>)}</tr>)}</tbody></table></div>}<InlineSources sourceIds={block.sourceIds} sources={sources} locale={locale} /></section>;
}

function InlineSources({ sourceIds, sources, locale }: { readonly sourceIds: readonly string[]; readonly sources: readonly LessonSource[]; readonly locale: Locale }) {
  const resolved = sourceIds.map((sourceId) => sources.find((source) => source.id === sourceId)).filter((source): source is LessonSource => Boolean(source));
  if (!resolved.length) return null;
  return <details className={styles.inlineSources}><summary>{locale === "vi" ? `Nguồn tham khảo (${resolved.length})` : `Reference sources (${resolved.length})`}</summary><ul>{resolved.map((source) => <li key={source.id}><strong>{source.kind === "teacher-authored" ? (locale === "vi" ? "AlgoCore tự biên soạn" : "AlgoCore-authored") : source.title}</strong><span>{source.locator}</span></li>)}</ul></details>;
}

function StructuredAnswer({ value, caption }: { readonly value: string; readonly caption: string }) {
  const parsed = parsePaper2AnswerTable(value);
  if (!parsed && value.includes("\n")) return <pre className={styles.answerCode} tabIndex={0} aria-label={caption}><code>{value}</code></pre>;
  if (!parsed) return <p>{value}</p>;
  return <div className={styles.tableScroll} role="region" tabIndex={0} aria-label={caption}>
    <table>
      <caption className={styles.srOnly}>{caption}</caption>
      <thead><tr>{parsed.headers.map((header, index) => <th key={index} scope="col">{header}</th>)}</tr></thead>
      <tbody>{parsed.rows.map((row, rowIndex) => <tr key={rowIndex}>{row.map((cell, cellIndex) => <td key={cellIndex}>{cell}</td>)}</tr>)}</tbody>
    </table>
  </div>;
}

export function Paper2LessonPage({ lesson, catalog, locale, visualSelection, candidate = false }: { readonly lesson: Paper2Lesson; readonly catalog: StudyMapCatalog; readonly locale: Locale; readonly visualSelection: Paper2VisualSelection; readonly candidate?: boolean }) {
  const topic = catalog.topics.find((entry) => entry.id === lesson.topicId);
  const section = catalog.sections.find((entry) => entry.id === lesson.sectionId);
  const currentIndex = catalog.topics.findIndex((entry) => entry.id === lesson.topicId);
  const previous = currentIndex > 0 ? catalog.topics[currentIndex - 1] : undefined;
  const next = currentIndex >= 0 ? catalog.topics[currentIndex + 1] : undefined;
  return <article className={styles.lesson} lang={locale} data-paper2-lesson={lesson.topicId} data-candidate={candidate ? "true" : "false"} data-paper2-candidate={candidate ? lesson.version : undefined} data-lesson-revision={lesson.version}>
    <Paper2LocaleBoundary locale={locale} />
    <nav className={styles.breadcrumb} aria-label={locale === "vi" ? "Vị trí bài học" : "Breadcrumb"}><Link href={paper2Href("/paper-2", locale)}><Map size={16} aria-hidden="true" />{locale === "vi" ? "Bản đồ học" : "Study map"}</Link><span>/</span><Link href={paper2Href(`/paper-2/sections/${lesson.sectionId}`, locale)}>{lesson.sectionId} · {section?.title[locale]}</Link><span>/</span><span aria-current="page">{lesson.topicId}</span></nav>
    {candidate && <div className={styles.candidateBanner} role="status">{locale === "vi" ? "Bản nháp cục bộ — chưa công bố cho học sinh" : "Local candidate — not yet published to learners"}</div>}
    <header className={styles.hero}><div className={styles.eyebrow}>PAPER 2 · {lesson.topicId} · {locale === "vi" ? "PHẦN" : "SECTION"} {lesson.sectionId}</div><h1>{lesson.title[locale]}</h1>{lesson.estimatedMinutes && <p className={styles.meta}><Clock3 size={17} aria-hidden="true" />{locale === "vi" ? `Thời gian dự kiến: ${lesson.estimatedMinutes} phút` : `Estimated time: ${lesson.estimatedMinutes} minutes`}</p>}<p className={styles.question}>{lesson.question[locale]}</p><p>{lesson.opening[locale]}</p></header>
    <div className={styles.lessonGrid}>
      <LessonProgress topicId={lesson.topicId} version={lesson.version} locale={locale} writable={!candidate} />
      <div className={styles.lessonContent}>
    <div className={styles.objectiveGrid}><section><h2><Goal size={21} aria-hidden="true" />{locale === "vi" ? "Sau bài này, bạn có thể" : "By the end, you can"}</h2><ul>{lesson.objectives.map((objective, index) => <li key={index}>{objective[locale]}</li>)}</ul></section><section><h2><Route size={21} aria-hidden="true" />{locale === "vi" ? "Kiến thức nên có" : "Useful prior knowledge"}</h2>{lesson.prerequisites.length ? <ul>{lesson.prerequisites.map((item, index) => <li key={index}><strong>{item.title[locale]}</strong><span>{item.reason[locale]}</span></li>)}</ul> : <p>{locale === "vi" ? "Không cần kiến thức nền riêng; hãy bắt đầu từ mục tiêu của bài." : "No specific prerequisite; start with the lesson objectives."}</p>}</section></div>

    <section className={styles.chapter} id="recognise" aria-labelledby="recognise-title"><div className={styles.heading}><span>01</span><div><p>{locale === "vi" ? "DẤU HIỆU ĐỀ BÀI" : "QUESTION CUES"}</p><h2 id="recognise-title" tabIndex={-1}>{locale === "vi" ? "Nhận diện dạng bài" : "Recognise the task"}</h2></div></div><div className={styles.recognitionGrid}><div><h3>{locale === "vi" ? "Dấu hiệu phù hợp" : "Positive cues"}</h3><ul>{lesson.recognition.cues.map((cue, index) => <li key={index}>{cue[locale]}</li>)}</ul></div><div><h3>{locale === "vi" ? "Dấu hiệu dễ nhầm" : "Misleading cues"}</h3><ul>{lesson.recognition.misleadingCues.map((cue, index) => <li key={index}>{cue[locale]}</li>)}</ul></div></div><div className={styles.answerProduct}><strong>{locale === "vi" ? "Sản phẩm cần trả lời" : "Required answer product"}</strong><p>{lesson.recognition.answerProduct[locale]}</p><ol>{lesson.recognition.method.map((step, index) => <li key={index}>{step[locale]}</li>)}</ol></div>{lesson.patternLinks.length > 0 && <p className={styles.patterns}>{locale === "vi" ? "Dạng bài liên quan: " : "Related patterns: "}{lesson.patternLinks.map((pattern) => `${pattern.id} · ${pattern.title[locale]}`).join("; ")}</p>}<LessonSectionActions anchor="recognise" nextAnchor="understand" topicId={lesson.topicId} version={lesson.version} locale={locale} writable={!candidate} /></section>

    <section className={styles.chapter} id="understand" aria-labelledby="understand-title"><div className={styles.heading}><span><Eye size={20} aria-hidden="true" /></span><div><p>{locale === "vi" ? "MÔ HÌNH VÀ CƠ CHẾ" : "MODEL AND MECHANISM"}</p><h2 id="understand-title" tabIndex={-1}>{locale === "vi" ? "Hiểu bằng giải thích trực quan" : "Understand through a visual explanation"}</h2></div></div>{lesson.theory.map((block) => <Theory key={block.id} block={block} locale={locale} sources={lesson.sources} />)}<div className={styles.visualIntro}><h3>{lesson.visual.title[locale]}</h3><p>{lesson.visual.introduction[locale]}</p><p><strong>{locale === "vi" ? "Nhiệm vụ quan sát: " : "Observation task: "}</strong>{lesson.visual.task[locale]}</p><InlineSources sourceIds={lesson.visual.sourceIds} sources={lesson.sources} locale={locale} /></div><div className={learnerVisualStyles.learnerVisual}><Paper2VisualExplorer selection={visualSelection} locale={locale} /></div><ul className={styles.conventions}>{lesson.visual.conventions.map((item, index) => <li key={index}>{item[locale]}</li>)}</ul><LessonSectionActions anchor="understand" nextAnchor="worked-example" topicId={lesson.topicId} version={lesson.version} locale={locale} writable={!candidate} /></section>

    <section className={styles.chapter} id="worked-example" aria-labelledby="worked-title"><div className={styles.heading}><span><BookOpen size={20} aria-hidden="true" /></span><div><p>{locale === "vi" ? "LỜI GIẢI MỞ NGAY" : "FULL WORKING VISIBLE"}</p><h2 id="worked-title" tabIndex={-1}>{locale === "vi" ? "Ví dụ giải từng bước" : "Worked examples"}</h2></div></div>{lesson.workedExamples.map((example) => <article className={styles.worked} key={example.id}><header><span>{example.origin === "algocore-authored" ? (locale === "vi" ? "Tự biên soạn" : "AlgoCore-authored") : (locale === "vi" ? "Chuyển thể từ nguồn" : "Adapted from source")}</span><h3>{example.title[locale]}</h3><p>{example.prompt[locale]}</p><InlineSources sourceIds={example.sourceIds} sources={lesson.sources} locale={locale} /></header><ol>{example.steps.map((step, index) => <li key={step.id}><span>{String(index + 1).padStart(2, "0")}</span><div><h4>{step.action[locale]}</h4><p><strong>{locale === "vi" ? "Vì sao: " : "Why: "}</strong>{step.why[locale]}</p><p><strong>{locale === "vi" ? "Kết quả: " : "Result: "}</strong>{step.result[locale]}</p>{step.check && <p><strong>{locale === "vi" ? "Kiểm: " : "Check: "}</strong>{step.check[locale]}</p>}</div></li>)}</ol><div className={styles.solution}><strong>{locale === "vi" ? "Đáp án" : "Answer"}</strong><StructuredAnswer value={example.answer[locale]} caption={`${example.title[locale]} — ${locale === "vi" ? "bảng đáp án" : "answer table"}`} /><small>{example.selfCheck[locale]}</small></div></article>)}<LessonSectionActions anchor="worked-example" nextAnchor="practise" topicId={lesson.topicId} version={lesson.version} locale={locale} writable={!candidate} /></section>

    <section className={styles.chapter} id="practise" aria-labelledby="practise-title"><div className={styles.heading}><span><CheckCircle2 size={20} aria-hidden="true" /></span><div><p>{locale === "vi" ? "ĐÁP ÁN LUÔN HIỂN THỊ" : "ANSWERS ALWAYS AVAILABLE"}</p><h2 id="practise-title" tabIndex={-1}>{locale === "vi" ? "Tự luyện có hướng dẫn" : "Guided practice"}</h2></div></div><div className={styles.practiceGrid}>{lesson.practices.map((task, taskIndex) => <article className={styles.practice} key={task.id}><span>{locale === "vi" ? `Bài ${taskIndex + 1}` : `Task ${taskIndex + 1}`}</span><h3>{task.title[locale]}</h3><p>{task.prompt[locale]}</p><InlineSources sourceIds={task.sourceIds} sources={lesson.sources} locale={locale} /><h4>{locale === "vi" ? "Cách làm" : "Working"}</h4><ol>{task.working.map((step, index) => <li key={index}>{step[locale]}</li>)}</ol><div className={styles.solution}><strong>{locale === "vi" ? "Đáp án" : "Answer"}</strong><StructuredAnswer value={task.answer[locale]} caption={`${task.title[locale]} — ${locale === "vi" ? "bảng đáp án" : "answer table"}`} /></div><h4>{locale === "vi" ? "Hướng dẫn chấm tự biên soạn" : "Teacher-authored mark guidance"}</h4><ul>{task.markGuidance.map((point, index) => <li key={index}>{point[locale]}</li>)}</ul><h4>{locale === "vi" ? "Lỗi thường gặp" : "Common mistakes"}</h4><ul>{task.commonMistakes.map((point, index) => <li key={index}>{point[locale]}</li>)}</ul><p className={styles.selfCheck}><strong>{locale === "vi" ? "Tự kiểm tra:" : "Self-check:"}</strong> {task.selfCheck[locale]}</p></article>)}</div><LessonSectionActions anchor="practise" nextAnchor="avoid-lost-marks" topicId={lesson.topicId} version={lesson.version} locale={locale} writable={!candidate} /></section>

    <section className={styles.chapter} id="avoid-lost-marks" aria-labelledby="avoid-title"><div className={styles.heading}><span><AlertTriangle size={20} aria-hidden="true" /></span><div><p>{locale === "vi" ? "KIỂM TRA TRƯỚC KHI NỘP" : "CHECK BEFORE SUBMITTING"}</p><h2 id="avoid-title" tabIndex={-1}>{locale === "vi" ? "Tránh mất điểm" : "Avoid lost marks"}</h2></div></div><div className={styles.mistakeGrid}>{lesson.misconceptions.map((item, index) => <article key={index}><h3>{item.mistake[locale]}</h3><p>{item.correction[locale]}</p><small>{item.selfCheck[locale]}</small></article>)}</div><LessonSectionActions anchor="avoid-lost-marks" nextAnchor="remember" topicId={lesson.topicId} version={lesson.version} locale={locale} writable={!candidate} /></section>

    <section className={styles.chapter} id="remember" aria-labelledby="remember-title"><div className={styles.heading}><span><Lightbulb size={20} aria-hidden="true" /></span><div><p>{locale === "vi" ? "GỢI NHỚ" : "RETRIEVAL"}</p><h2 id="remember-title" tabIndex={-1}>{locale === "vi" ? "Nhớ và kết nối" : "Remember and connect"}</h2></div></div><div className={styles.recall}><h3>{lesson.recall.prompt[locale]}</h3><ul>{lesson.recall.answerPoints.map((point, index) => <li key={index}>{point[locale]}</li>)}</ul></div><ul className={styles.takeaways}>{lesson.takeaways.map((point, index) => <li key={index}>{point[locale]}</li>)}</ul><div className={styles.glossary}><h3>{locale === "vi" ? "Thuật ngữ" : "Glossary"}</h3><dl>{lesson.glossary.map((item) => <div key={item.term}><dt>{item.term}</dt><dd>{item.meaning[locale]}</dd></div>)}</dl></div><LessonSectionActions anchor="remember" topicId={lesson.topicId} version={lesson.version} locale={locale} writable={!candidate} completionHref={paper2Href(`/paper-2/sections/${lesson.sectionId}`, locale)} /></section>

    <section className={styles.sources} aria-labelledby="sources-title"><h2 id="sources-title">{locale === "vi" ? "Nguồn dùng cho bài học này" : "Sources used in this lesson"}</h2><details><summary>{locale === "vi" ? `Xem chi tiết nguồn tham khảo (${lesson.sources.length})` : `Reference details (${lesson.sources.length})`}</summary><ul>{lesson.sources.map((source) => <li key={source.id}><strong>{source.title}</strong><span>{source.locator}</span>{source.kind === "teacher-authored" && <small>{locale === "vi" ? "Bài luyện do AlgoCore biên soạn; không phải thang điểm chính thức của Cambridge." : "AlgoCore-authored practice; not an official Cambridge mark allocation."}</small>}</li>)}</ul></details></section>
    <nav className={styles.pageNavigation} aria-label={locale === "vi" ? "Bài liền kề" : "Adjacent lessons"}>{previous ? <Link href={paper2Href(`/paper-2/topics/${previous.slug}`, locale)}><ArrowLeft size={18} aria-hidden="true" /><span><small>{locale === "vi" ? "Chủ đề trước" : "Previous topic"} · {topicStatusLabel(previous, locale)}</small>{previous.title[locale]}</span></Link> : <Link href={paper2Href("/paper-2", locale)}><ArrowLeft size={18} aria-hidden="true" />{locale === "vi" ? "Bản đồ học" : "Study map"}</Link>}{next && <Link href={paper2Href(`/paper-2/topics/${next.slug}`, locale)}><span><small>{locale === "vi" ? "Chủ đề tiếp theo" : "Next topic"} · {topicStatusLabel(next, locale)}</small>{next.title[locale]}</span><ArrowRight size={18} aria-hidden="true" /></Link>}</nav>
      </div>
    </div>
  </article>;
}

