"use client";
import {classroomRequest} from "@/lib/classroom-content";
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {ArrowRight,BookOpen,GraduationCap,Presentation,KeyRound,LogOut} from 'lucide-react';
import StudyWorkspace from './study-workspace';
export default function Classroom(){
 const[role,setRole]=useState('student'),[code,setCode]=useState(''),[session,setSession]=useState<{role:string}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{classroomRequest('/api/auth').then(r=>r.json() as Promise<{session?:{role:string}}>).then(d=>setSession(d.session||null)).catch(()=>{});},[]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await classroomRequest('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role,code})});const d=await r.json() as {error?:string;session:{role:string}};if(!r.ok)throw Error(d.error||'Please try again.');setSession(d.session);setCode('');}catch(e){setError((e as Error).message);}finally{setBusy(false)}}
 if(session)return <StudyWorkspace role={session.role} onSignOut={async()=>{const r=await classroomRequest('/api/auth',{method:'DELETE'});if(r.ok)setSession(null);else setError('Sign out failed. Please try again.')}}/>;
 return <main className="entry"><section className="entry-intro"><div className="brand"><span className="brand-mark">13</span> AlgoCore <span>/ Chapter lab</span></div><div><p className="eyebrow">A LEVEL COMPUTER SCIENCE · PAPER 3</p><h1>Understand it.<br/>Try it.<br/><em>Explain it.</em></h1><p className="entry-summary">Your study space for data types, files, floating-point numbers and past-paper skills.</p><div className="topic-strip"><span>13.1 Data types</span><span>13.2 Files</span><span>13.3 Numbers</span><span>13.4 Exam skills</span></div></div><p className="entry-foot">CHAPTER 13 / DATA REPRESENTATION</p></section><section className="entry-form"><div className="entry-card"><KeyRound className="login-icon" size={28}/><h2>Join your classroom</h2><p>Choose your role, then enter your class code.</p><Tabs value={role} onValueChange={v=>{setRole(v);setError('')}}><TabsList className="role-tabs"><TabsTrigger value="student"><GraduationCap size={20}/> Student</TabsTrigger><TabsTrigger value="teacher"><Presentation size={20}/> Teacher</TabsTrigger></TabsList></Tabs><form onSubmit={login}><label htmlFor="class-code">Class code</label><Input id="class-code" type="password" inputMode="numeric" autoComplete="off" pattern="[0-9]{4}" maxLength={4} required value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="Enter 4 digits"/><p className="form-error" role="alert">{error}</p><Button className="join-button" type="submit" disabled={busy}>{busy?'Checking…':`Continue as ${role}`}<ArrowRight size={18}/></Button></form><p className="entry-help"><BookOpen size={17}/> Ask your teacher for your class code.</p></div></section></main>
}
