"""Objective-specific assessment requirements, not authored exercises or solutions."""
import hashlib
import importlib.util
import json
from pathlib import Path

HERE=Path(__file__).resolve().parent
S3=HERE.parent
COURSE='ac-9618-p4-2026-python'
inventory=json.loads((HERE/'A3_OBJECTIVE_INVENTORY.json').read_text(encoding='utf-8-sig'))
blueprint=json.loads((HERE/'A1_LESSON_BLUEPRINT.json').read_text(encoding='utf-8-sig'))
spec=importlib.util.spec_from_file_location('lead_objective_links',S3/'scripts/lead_objective_links.py')
module=importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)
links=module.get_links()

# ID | concrete VI brief | concrete EN brief | capability-specific acceptance checks
ROWS='''
SYL-19.1-01|Lập nhiệm vụ tìm tuyến tính trên dữ liệu mới, có phần tử đầu/cuối, khóa lặp và khóa không tồn tại.|Plan a linear-search task on unfamiliar data with first/last items, repeated keys and an absent key.|Checks positions sequentially under the declared contract;Returns the specified found or missing result without a premature stop
SYL-19.1-02|Lập nhiệm vụ tìm nhị phân với mảng đã sắp, thử biên một phần tử và khoảng rỗng; chọn biến thể lặp hoặc đệ quy rõ ràng.|Plan binary search on sorted data with singleton and empty-interval cases; state whether the required variant is iterative or recursive.|Midpoint and bound updates shrink the interval;Found and absent cases terminate;Recursive variant propagates return values when selected
SYL-19.1-03|Đưa các bộ dữ liệu và chiều so sánh khác nhau để học sinh quyết định có được dùng tìm nhị phân ngay hay không.|Present datasets and comparator directions and ask whether binary search can be applied immediately.|Identifies the ordering precondition;Explains comparator consistency;Does not claim binary search works on arbitrary unsorted data
SYL-19.1-04|Yêu cầu dự đoán số lần thu hẹp khoảng khi kích thước mảng tăng, rồi giải thích từ trace tìm nhị phân.|Ask learners to predict interval reductions as array size grows and justify them from binary-search traces.|Uses a consistent counted operation and case;Relates interval halving to logarithmic growth rather than claiming elapsed time proves Big O
SYL-19.1-05|Lập bài insertion sort cho bản ghi theo khóa mới, gồm dữ liệu đã sắp, đảo ngược và khóa bằng nhau.|Plan insertion sort of records by a new key, including sorted, reversed and equal-key data.|Preserves a sorted prefix;Shifts complete records without loss;Inserts the saved item at the correct boundary
SYL-19.1-06|Lập bài bubble sort có trace từng lượt và trường hợp không cần đổi chỗ.|Plan bubble sort with pass-by-pass tracing and an input requiring no swaps.|Compares adjacent items with the required direction;Uses correct pass bounds;Terminates correctly under the specified stopping rule
SYL-19.1-07|Cho cùng kích thước nhưng khác thứ tự đầu vào để so sánh chi phí của một bản bubble/insertion sort đã xác định.|Compare equal-size inputs with different initial orders for a specified bubble/insertion implementation.|Separates input order from input size;Counts comparisons or shifts consistently;Accounts for whether early exit is present
SYL-19.1-08|Cho các kích thước tăng dần với kiểu thứ tự cố định để so sánh số bước sắp xếp.|Compare increasing input sizes while holding the ordering pattern constant.|Keeps implementation and case comparable;Explains growth in counted operations;Does not confuse one measured runtime with a complexity proof
SYL-19.1-09|Lập bài tìm khóa theo link của linked list có ô mảng vật lý không theo thứ tự, gồm rỗng và không tìm thấy.|Plan linked-list search with nonconsecutive physical slots, including empty and absent-key cases.|Follows links from the head;Stops at the declared null sentinel;Returns the correct node/result without changing links
SYL-19.1-10|Lập bài tìm trong BST với khóa ở root, nhánh sâu và nhánh thiếu.|Plan BST search for a root key, a deep key and a key leading to a missing child.|Chooses the child using the declared ordering rule;Handles a null subtree;Preserves the tree and returns the requested result
SYL-19.1-11|Lập bài push theo một quy ước top được cho, gồm rỗng, còn một chỗ và đầy.|Plan push under a supplied top-pointer convention with empty, one-free-slot and full states.|Uses the supplied pointer convention;Writes and updates in a valid order;Reports full without corrupting stored state
SYL-19.1-12|Lập bài enqueue theo kiểu tuyến tính hoặc vòng được chỉ định, có trường hợp đầy và vòng chỉ số nếu áp dụng.|Plan enqueue for a specified linear or circular queue, including full and applicable wraparound states.|Preserves FIFO order;Updates tail/count under the chosen convention;Handles full and applicable wraparound correctly
SYL-19.1-13|Lập bài chèn linked list cần lấy node từ free list và cập nhật liên kết đầu/cuối theo yêu cầu.|Plan linked-list insertion requiring free-list allocation and the specified head/tail link changes.|Allocates only a free node;Preserves existing live links;Updates free and used chains without loss or cycles
SYL-19.1-14|Lập bài chèn vào BST rỗng và có sẵn node, nêu rõ quy tắc với khóa trùng.|Plan insertion into empty and populated BSTs with an explicit duplicate-key policy.|Attaches at the correct empty child;Preserves ordering and existing nodes;Applies the declared duplicate and capacity policy
SYL-19.1-15|Lập bài pop với nhiều phần tử, một phần tử và stack rỗng theo quy ước top cụ thể.|Plan pop from multiple-item, single-item and empty stacks using a stated top convention.|Returns the most recently pushed item;Updates top correctly;Leaves an empty stack unchanged when reporting failure
SYL-19.1-16|Lập bài dequeue qua chuỗi thêm/lấy, gồm phần tử cuối và điểm vòng nếu có.|Plan dequeue across enqueue/dequeue sequences, including the last item and any wrap point.|Returns the oldest live item;Updates head/count consistently;Handles empty without returning a stale slot
SYL-19.1-17|Lập bài xóa node đầu/giữa/cuối và khóa vắng, có yêu cầu trả node về free list.|Plan deletion of head/interior/tail nodes and an absent key, with node recycling to a free list.|Repairs the predecessor or head link;Recycles only the removed node when required;Preserves both chains and the not-found state
SYL-19.1-18|Thiết kế kiểm tra trên sơ đồ đồ thị để nhận đỉnh, cạnh, hướng và trọng số; không yêu cầu viết code.|Plan a diagram-based check identifying graph vertices, edges, direction and weights without coding.|Labels graph features correctly;Distinguishes the displayed graph variants;Uses diagram or prose evidence rather than requiring an algorithm implementation
SYL-19.1-19|Cho một tình huống quan hệ nhiều-nhiều và yêu cầu giải thích vì sao dùng graph phù hợp.|Present a many-to-many relationship scenario and ask why a graph is suitable.|Maps entities to vertices and relationships to edges;Justifies relevant direction or weight choices;Does not invent a graph-coding requirement
SYL-19.1-21|Yêu cầu biểu diễn stack bằng kiểu cho phép, ghi ý nghĩa từng ô/con trỏ rồi thực hiện chuỗi thao tác ngắn.|Ask learners to represent a stack using permitted types, explain cells/pointers and perform a short operation sequence.|Storage and pointer convention are explicit;State transitions implement LIFO;Empty/full conditions agree with the representation
SYL-19.1-22|Yêu cầu biểu diễn queue, nêu head/tail/count và chứng minh FIFO qua chuỗi thao tác.|Ask learners to represent a queue, define head/tail/count and demonstrate FIFO through an operation sequence.|Separates physical storage from live items;State matches the chosen linear/circular convention;Order and empty/full states are consistent
SYL-19.1-23|Yêu cầu biểu diễn linked list và free list trong mảng, vẽ link trước/sau một thay đổi.|Ask learners to represent linked and free lists in arrays and draw links before and after a change.|Distinguishes physical indices from logical order;Head/null/free meanings are explicit;Every allocated node belongs to the appropriate chain
SYL-19.1-24|Lập bài dictionary với hợp đồng khóa duy nhất và chuỗi thêm/tìm/cập nhật/xóa do AlgoCore chọn để kiểm tra giao diện.|Plan a dictionary task with unique-key semantics and an AlgoCore-selected add/find/update/delete sequence to demonstrate the interface.|Separates key-value contract from storage;Handles duplicate and missing keys according to specification;Demonstrates the chosen operations without claiming they are separate official syllabus bullets
SYL-19.1-25|Yêu cầu biểu diễn cùng cây bằng một cấu trúc hợp lệ, chỉ rõ root, con trái/phải và ô chưa dùng.|Ask learners to represent a tree using a permitted structure and identify root, child links and unused storage.|Representation preserves the intended shape;Null and root conventions are unambiguous;Does not require OOP for an array-backed representation
SYL-19.1-26|Cho hai thuật toán giải cùng nhiệm vụ và yêu cầu so sánh thời gian theo mô hình bước, với giả thiết đầu vào rõ.|Present two algorithms solving the same task and compare time using an explicit operation model and input assumptions.|Compares equivalent tasks and cases;Identifies the dominant repeated work;States assumptions such as sorted input or tree shape
SYL-19.1-27|Yêu cầu so sánh bộ nhớ của hai cách giải, tính cả dữ liệu phụ và các frame đệ quy.|Ask learners to compare storage use of two solutions, including auxiliary data and recursive frames.|Distinguishes input storage from auxiliary space;Includes simultaneous call frames where applicable;States how space changes with input size
SYL-19.1-28|Lập kiểm tra suy ra Big O thời gian từ các cấu trúc lặp và thu hẹp khoảng, có nêu n và trường hợp xét.|Plan a check deriving time Big O from loops and interval reduction, with input size and case stated.|Defines n and counted work;Derives the dominant growth term;Avoids treating constants or a single runtime as the growth class
SYL-19.1-29|Lập kiểm tra suy ra Big O không gian từ biến tạm, mảng phụ và độ sâu call stack.|Plan a check deriving space Big O from temporary variables, auxiliary arrays and call depth.|Counts simultaneously live storage;Includes recursive depth rather than total calls;States whether the answer is auxiliary or total space
SYL-19.1-30|Lập bài dictionary dùng ADT linked list chứa cặp khóa–giá trị và gọi giao diện của ADT thành phần.|Plan a dictionary backed by a linked-list ADT of key-value pairs, invoking the component ADT interface.|Names both the outer dictionary and inner linked-list ADT;Provides executable interface composition and call-trace evidence;Built-in arrays alone or a comparison diagram do not satisfy this requirement
SYL-19.2-01|Cho ví dụ đệ quy đúng/sai để xác định base case, recursive case và bước tiến tới dừng.|Present valid and flawed recursive examples and identify base case, recursive case and progress.|Identifies all three obligations;Explains a nontermination fault;Preserves them when comparing with an iterative form
SYL-19.2-02|Yêu cầu diễn đạt một thuật toán đệ quy đã mô tả bằng Python, giữ đúng tham số và giá trị trả về.|Ask learners to express a described recursive algorithm in Python while preserving arguments and returned values.|Uses recursive calls for the required subproblem;Implements the base result;Propagates results without replacing return with print
SYL-19.2-03|Cho bài toán mới có cấu trúc giảm dần, yêu cầu tự thiết kế base case và bước đệ quy trước khi triển khai.|Present an unfamiliar reducible problem and require independent base-case and recursive-step design before implementation.|Defines a valid smaller subproblem;Every allowed input progresses to a stopping condition;Result composition matches the problem specification
SYL-19.2-04|Yêu cầu tự trace lời gọi, biến cục bộ, công việc chờ và giá trị trả về trước khi chạy một ví dụ đệ quy.|Require an independent trace of calls, local state, pending work and returns before executing a recursive example.|Records frame-local values in call order;Shows unwind and returned values in the correct order;Final console output alone is insufficient evidence
SYL-19.2-05|Cho bài toán cây hoặc phân rã lặp lại để học sinh giải thích lợi ích và chi phí của đệ quy.|Use a tree or repeated-decomposition problem to explain recursion benefits and costs.|Connects recursive structure to the problem;Explains clarity or natural decomposition;Acknowledges stack/termination costs rather than claiming recursion is always faster
SYL-19.2-06|Yêu cầu chú thích sơ đồ call stack cho lời gọi lồng nhau, chỉ dữ liệu cần giữ để tiếp tục sau return.|Ask learners to annotate a nested-call stack and identify information needed to resume after return.|Includes return location and frame-local state;Explains LIFO support for nested calls;Does not require implementing a compiler
SYL-19.2-07|Cho trạng thái tại base case và yêu cầu dựng chuỗi unwind cùng các phép tính còn chờ.|Provide the state at a base case and ask for the unwind sequence and pending computations.|Pops frames in reverse call order;Uses the correct local values at each return;Produces the final result through visible intermediate returns
SYL-20.1-01|Cho hai thiết kế cùng bài toán theo thủ tục và OOP, yêu cầu đối chiếu cách tổ chức dữ liệu/trách nhiệm.|Present procedural and OOP designs for the same problem and compare how data and responsibilities are organised.|Explains the paradigm distinction;Identifies procedures versus stateful objects/methods;Stays within procedural/OOP scope
SYL-20.1-03|Lập bài khai báo và sử dụng biến/mảng theo yêu cầu dữ liệu mới, kiểm tra trạng thái đầu và các thay đổi.|Plan declaration and use of variables/arrays for unfamiliar data requirements, checking initial and updated state.|Types, scope and dimensions fit the data;Initial values are deliberate;Updates do not exceed bounds or leak unintended shared state
SYL-20.1-04|Lập nhóm nhiệm vụ chuyển giao dùng rẽ nhánh/lặp để đếm, lọc, phân nhóm hoặc xử lý trạng thái; chọn bối cảnh từ các block đã nối.|Plan transfer tasks using selection and iteration for counting, filtering, grouping or state processing, selecting contexts from the linked blocks.|Conditions implement the stated rule;Loops visit the intended data and terminate;Normal and boundary cases show correct state/results without assuming all corpus techniques are named syllabus requirements
SYL-20.1-05|Yêu cầu tách một luồng xử lý thành procedures rồi ghép lời gọi có tham số đúng thứ tự.|Ask learners to split a processing flow into procedures and compose correctly ordered calls with parameters.|Each procedure has a clear responsibility;Arguments and state flow match interfaces;Composition calls existing routines rather than duplicating their algorithms
SYL-20.1-06|Yêu cầu viết function trả kết quả để dùng trong biểu thức hoặc điều kiện, phân biệt với chỉ in ra.|Ask learners to write a function whose result is used in an expression or condition, distinguishing it from printing.|Parameters describe the required inputs;All relevant paths return the specified value;Caller uses the returned value correctly
SYL-20.1-07|Tạo nhiệm vụ với hai object cùng class và yêu cầu dự đoán trạng thái riêng sau một thao tác.|Plan a task with two objects of one class and predict their separate states after an operation.|Distinguishes class from object identity;Tracks instance-specific state;An update to one object affects another only through specified sharing
SYL-20.1-08|Yêu cầu chọn và khởi tạo các attribute với giá trị lấy từ tham số hoặc mặc định được mô tả.|Ask learners to choose and initialise attributes from supplied parameters or stated defaults.|Attribute names/types/roles fit the contract;Constructor initialises required fields;Parameters are not mistaken for persistent instance fields
SYL-20.1-09|Yêu cầu cài phương thức thực hiện trách nhiệm của object và một lời gọi tới object thành phần khi phù hợp.|Ask learners to implement object responsibilities as methods, including delegation to a contained object where appropriate.|Method uses the correct instance state;Return values and side effects match the contract;Delegation addresses the intended contained instance
SYL-20.1-10|Cho mô tả dữ liệu và hành vi của một loại thực thể, yêu cầu khai báo class thể hiện đúng cấu trúc đó.|Provide data and behaviour requirements for an entity type and ask for its class definition.|Class groups the required attributes and methods;Definition is distinguished from construction of an instance;Constructor and method signatures match the specification
SYL-20.1-11|Lập bài subclass có thêm trạng thái và cần khởi tạo phần được kế thừa.|Plan a subclass with additional state that must initialise its inherited part.|Uses an appropriate is-a relation;Initialises inherited and new attributes;Reuses the base interface without duplicating inconsistent state
SYL-20.1-12|Lập bài gọi cùng phương thức trên các object khác subclass và dự đoán hành vi được chọn.|Plan shared method calls on objects of different subclasses and predict the selected behaviour.|Overrides a common method contract;Calls resolve to the appropriate instance behaviour;Demonstrates polymorphic use rather than only defining two unrelated methods
SYL-20.1-13|Lập bài object chứa tập object khác, có truy cập thành phần và thêm theo giới hạn nếu được yêu cầu.|Plan an object containing other objects, with component access and capacity-limited addition where specified.|Models a has-a relation;Stores/retrieves the intended object references;Count/capacity and component method calls follow the stated contract
SYL-20.1-14|Yêu cầu thiết kế truy cập trạng thái qua phương thức và giải thích mức đóng gói thực tế của cách viết Python.|Ask learners to mediate state access through methods and explain the actual encapsulation offered by their Python approach.|State access follows the intended interface;Explains conventions or name mangling accurately;Does not describe Python naming as absolute security
SYL-20.1-15|Lập bài getter trả đúng attribute được yêu cầu, thử trước và sau thay đổi trạng thái.|Plan a getter returning the requested stored attribute, tested before and after a state change.|Returns the correct instance field;Does not change state;Distinguishes retrieving a stored value from formatting or recomputing an unrelated result
SYL-20.1-16|Lập bài setter nhận giá trị mới và thay thế attribute, đối chiếu với một phương thức cộng dồn.|Plan a setter replacing an attribute from a new input value and contrast it with an incremental-update method.|Assigns the supplied value to the intended field;Does not accidentally add or clamp unless specified;Subsequent access observes the replacement
SYL-20.1-17|Yêu cầu tạo nhiều instance với tham số khác nhau và xác định object nào được từng biến tham chiếu.|Ask learners to construct several instances with different arguments and identify the object referenced by each variable.|Calls constructors with correct argument order;Distinguishes separate instances from two references to one object;Initial state matches each construction
SYL-20.1-18|Cho tình huống chưa kèm class diagram để học sinh tự đề xuất class, attribute, method và quan hệ rồi giải thích lựa chọn.|Present an unfamiliar scenario without a supplied class diagram and require independent classes, attributes, methods and relationships with justification.|Derives responsibilities from requirements;Specifies coherent attribute types and method contracts;Justifies relationships before code rather than copying a given class skeleton
SYL-20.1-19|Lập nhiệm vụ tích hợp tạo object và gọi các phương thức để giải quyết yêu cầu mới, có thể dùng record tệp đã xác minh.|Plan an integrated task constructing objects and invoking methods for new requirements, optionally using verified file records.|Executable behaviour is organised through object state and methods;Instances and calls fit their contracts;Tests cover the required interaction rather than only successful construction
SYL-20.2-01|Lập nhiệm vụ mở đúng tệp để đọc mà không làm thay đổi dữ liệu sẵn có.|Plan opening the specified file for reading without altering existing data.|Selects read access and the correct path/name;Reads only through a valid open resource;Original file content remains unchanged
SYL-20.2-02|Lập nhiệm vụ ghi lại tệp có sẵn và yêu cầu dự đoán phần dữ liệu cũ còn hay mất.|Plan rewriting an existing file and ask learners to predict which previous data remains.|Uses overwrite mode when required;Result contains exactly the intended new content;Explains the effect on pre-existing data
SYL-20.2-03|Lập nhiệm vụ thêm record vào tệp có sẵn rồi kiểm tra cả record cũ và mới.|Plan appending records to an existing file and verify both old and new records.|Uses append semantics;Preserves existing content;Record delimiters prevent old/new records from merging
SYL-20.2-04|Lập nhiệm vụ theo dõi trạng thái tài nguyên qua đường thành công và đường lỗi có thể xảy ra.|Plan resource-state checks across successful processing and an applicable failure path.|The opened file is closed when processing ends;Chosen cleanup approach covers relevant paths;Does not claim finally or context-manager syntax is itself a named syllabus requirement
SYL-20.2-05|Lập bài đọc record nhiều trường hoặc nhiều dòng, chuyển kiểu và đưa vào đúng record/object đích.|Plan reading multi-field or multi-line records, converting types and populating the correct record/object.|Respects record boundaries;Converts fields under the stated layout;Handles end-of-file without inventing an extra record or updating the wrong object
SYL-20.2-06|Lập bài ghi record theo layout xác định rồi đọc lại để đối chiếu dữ liệu.|Plan writing records in a specified layout and reading them back for comparison.|Field order and separators are recoverable;Mode and newline behaviour match the requirement;Round-trip values retain the intended types/meaning
SYL-20.2-07|Lập bài xử lý tệp serial theo thứ tự nhận record và kiểm tra thứ tự sau khi thêm dữ liệu.|Plan processing a serial file in arrival order and checking the order after adding records.|Preserves the defined arrival order;Does not relabel unsorted serial organisation as key-sorted sequential organisation;Processes complete records
SYL-20.2-08|Lập bài xử lý tệp sequential theo khóa và cập nhật mà vẫn giữ thứ tự đã quy định.|Plan processing a key-ordered sequential file and updating it while preserving the stated order.|Recognises key order as an organisation property;Update preserves that order and complete records;Does not confuse sequential reading with file organisation
SYL-20.2-09|Lập fixture tự biên soạn cho chọn địa chỉ record rồi đọc/ghi/sửa tệp thật, kiểm tra record khác giữ nguyên.|Plan an original fixture for selecting a record address and reading/writing/updating a real file while checking other records remain unchanged.|Uses persistent file operations rather than only an in-memory table;Address/layout convention is explicit and tested;Target and non-target records verify direct-update behaviour
SYL-20.2-10|Cho tình huống thiếu tệp, lỗi chuyển kiểu và dữ liệu ngoài miền để phân biệt ngoại lệ với lỗi dữ liệu thông thường.|Present missing-file, conversion-failure and out-of-range-input scenarios to distinguish exceptions from ordinary invalid-domain data.|Explains disruption of normal execution;Identifies why recovery or reporting is needed;Does not treat every failed validation as an exception
SYL-20.2-11|Cho các ranh giới xử lý lỗi khác nhau để chọn chỗ bắt ngoại lệ và cách phục hồi phù hợp.|Present alternative handling boundaries and ask learners to choose where to catch an exception and how to recover.|Matches the handler to a plausible operation failure;Selects retry/report/propagation deliberately;Does not mask unrelated programming faults with an indiscriminate catch
SYL-20.2-12|Lập bài code xử lý một lỗi tệp hoặc chuyển kiểu, thử cả đường bình thường và đường lỗi.|Plan code handling a file or conversion failure, testing normal and exceptional paths.|Catches the intended exception;Produces the specified recovery state/message;Normal execution remains correct and relevant resources are handled
SYL-9.1-01|Cho mô tả dài có chi tiết thừa và yêu cầu chọn dữ liệu/đầu ra thiết yếu cho nhiệm vụ lập trình.|Present a verbose scenario with irrelevant detail and select essential data and outputs for programming.|Retains information needed by the required behaviour;Excludes irrelevant detail with a reason;Produces a usable model rather than a prose copy
SYL-9.1-02|Yêu cầu chia một nhiệm vụ nhỏ thành routines với đầu vào/đầu ra và trách nhiệm riêng.|Ask learners to split a small task into routines with distinct responsibilities and inputs/outputs.|Responsibilities are coherent and nonduplicated;Interfaces support the overall task;The decomposition can be followed to completion
SYL-9.2-01|Cho các bước thuật toán chưa rõ và yêu cầu diễn đạt lại thành chuỗi bước xác định có thể trace.|Present imprecise algorithm steps and rewrite them as a definite traceable sequence.|Each step has an unambiguous effect;Order and conditions are explicit;A sample input produces a determinate trace
SYL-9.2-02|Yêu cầu lập bảng tên biến, ý nghĩa, kiểu và vai trò cho một bài có mảng/con trỏ.|Ask for an identifier table listing meaning, type and role in an array/pointer task.|Identifiers distinguish different roles;Types and scope fit the values;Pointer/index names are not confused with the data they locate
SYL-9.2-03|Cho đặc tả input-process-output rồi yêu cầu viết thuật toán đáp ứng đúng dữ liệu vào và kết quả ra.|Provide an input-process-output specification and ask for an algorithm matching its inputs and outputs.|Inputs are consumed as specified;Processing steps connect inputs to outputs;Output form and returned values match the contract
SYL-9.2-04|Cho một bước còn quá lớn và yêu cầu refinement đến các thao tác có thể triển khai/kiểm tra.|Give an oversized step and refine it into implementable, checkable operations.|Each refined step has a clear action and data;The substeps preserve the parent requirement;No unexplained operation remains at the intended coding level
SYL-9.2-05|Lập bài viết predicate cho nhiều điều kiện, gồm trường hợp biên và kết hợp AND/OR.|Plan predicates combining several conditions, including boundaries and AND/OR alternatives.|Boolean structure matches the rule;Boundary equality is handled correctly;Tests distinguish incorrect operator combinations
SYL-10.1-01|Cho các trường dữ liệu và phép toán cần dùng để học sinh chọn kiểu phù hợp, giải thích trường hợp dễ nhầm.|Provide data fields and required operations and select suitable types, explaining ambiguous cases.|Chosen types represent all allowed values;Operations are compatible with the types;Numeric-looking identifiers are not converted without justification
SYL-10.1-02|Yêu cầu khai báo record chứa các trường khác kiểu và phân biệt record với bảng các record.|Ask learners to declare a record with heterogeneous fields and distinguish it from a collection of records.|Each named field has the required type/role;One record represents one entity;A Python class substitute is not automatically treated as a full OOP design
SYL-10.1-03|Lập nhiệm vụ đọc và sửa một trường record mà giữ các trường khác không đổi.|Plan reading and modifying one record field while preserving the others.|Accesses the correct record and field;New value satisfies the field contract;Unrelated fields retain their values
SYL-10.2-01|Cho mảng với giới hạn được mô tả và yêu cầu truy cập các vị trí đầu/cuối, phát hiện chỉ số vượt biên.|Provide an array with stated bounds and access first/last positions while identifying out-of-range indices.|Translates stated bounds consistently to Python;Uses valid index ranges;Distinguishes an index from a stored value
SYL-10.2-02|Cho hai tình huống dữ liệu để chọn mảng 1D/2D rồi xử lý hàng/cột cần thiết.|Present two data situations, select 1D/2D arrays and process the required rows/columns.|Dimensions match the data relationships;Nested indexing and iteration are correct;Updates target the intended cell without unintended row aliasing
SYL-10.3-01|Lập bài lưu các dòng văn bản, kết thúc chương trình rồi đọc lại để chứng minh lưu trữ bền vững.|Plan storing text lines, ending execution and reading them in a later run to demonstrate persistence.|Data survives beyond one program run;Line boundaries are preserved;Opening/reading/closing follows the selected file contract
SYL-10.4-01|Yêu cầu mô tả một ADT bằng dữ liệu cùng thao tác cho phép, rồi phân biệt với một cách biểu diễn.|Ask learners to describe an ADT through its data and permitted operations, then distinguish an implementation.|States the behaviour of operations;Separates logical contract from storage;Does not equate every array with the same ADT
SYL-10.4-02|Cho ảnh chụp mảng/con trỏ của stack, queue hoặc list để dựng thứ tự dữ liệu logic.|Provide array/pointer snapshots of a stack, queue or list and reconstruct logical data order.|Interprets the relevant pointers/links;Distinguishes live from unused storage;Logical order matches the selected ADT behaviour
SYL-11.1-01|Yêu cầu khởi tạo constants và variables theo một nhiệm vụ rồi chỉ ra giá trị nào được thay đổi.|Ask learners to initialise constants and variables for a task and identify which values may change.|Initial values fit the specification;Constant intent and variable updates are distinguished;Scope does not hide or overwrite required state
SYL-11.1-02|Lập trace assignment, biểu thức số học và logic có chia nguyên/làm tròn được quy định rõ.|Plan a trace of assignments and arithmetic/logical expressions with explicitly specified division/rounding.|Uses the required operator semantics;Assignment changes the correct target;Intermediate and final values follow evaluation order
SYL-11.1-03|Lập bài nhận dữ liệu console, chuyển kiểu và xuất nhãn/kết quả theo yêu cầu.|Plan console input, conversion and labelled output under a stated format.|Input is read at the required point;Conversions fit expected types;Output preserves required labels/order and does not substitute print for a required return
SYL-11.1-04|Cho nhiệm vụ chuỗi và giới hạn về built-ins để học sinh chọn hàm được phép hoặc thao tác tự triển khai.|Provide a string task and explicit built-in restrictions, asking learners to select permitted functions or manual operations.|Library calls are appropriate and permitted;Arguments/return values are used correctly;No prohibited shortcut bypasses the assessed algorithm
SYL-11.2-01|Lập bài lựa chọn nhiều nhánh, gồm điều kiện lồng nhau và dạng tương đương CASE.|Plan multi-branch selection with nested conditions and a CASE-equivalent decision.|Branches cover the stated alternatives;Priority and nesting implement the intended rule;Boundary cases select the correct branch
SYL-11.2-02|Lập bài xử lý đúng số phần tử đã biết trước và kiểm tra số lần lặp bằng trace.|Plan processing a known number of items and verify the iteration count by tracing.|Iteration count matches the requirement;First/last positions are valid;No extra or skipped item appears at the loop boundary
SYL-11.2-03|Lập bài vòng lặp kiểm tra điều kiện trước, gồm trường hợp không chạy lần nào.|Plan a pre-condition loop including a case with zero iterations.|Tests the condition before the body;Allows zero iterations when appropriate;Loop state progresses toward termination
SYL-11.2-04|Cho tình huống cần lặp để học sinh chọn và giải thích vòng lặp đếm, kiểm tra trước hoặc kiểm tra sau; với tình huống ít nhất một lần, yêu cầu biểu diễn tương đương hợp lệ bằng Python.|Present repetition scenarios requiring learners to choose and justify counted, pre-condition or post-condition loops; for the at-least-once scenario, require a valid Python equivalent.|Justifies the loop choice from whether the count is known and whether zero iterations are allowed;Explains why a post-condition loop fits the selected scenario better than counted or pre-condition alternatives;Body executes once before the stopping decision;Condition polarity matches the intended repeat-until/while contract;Does not invent a native Python post-condition-loop keyword
SYL-11.3-01|Yêu cầu định nghĩa procedure có giao diện rõ và gọi với các bộ arguments khác nhau.|Ask learners to define a procedure with a clear interface and invoke it with different arguments.|Header and parameters match the responsibility;Calls supply compatible arguments;The intended observable effect occurs without hidden dependencies
SYL-11.3-02|Lập trace sửa list trong hàm và gán lại tham số, gồm truyền scalar rồi gán lại tham số cục bộ để đối chiếu trạng thái caller.|Plan traces of list mutation and parameter rebinding, including passing a scalar then rebinding the local parameter to compare caller state.|Predicts caller-visible mutation versus local rebinding accurately;Explains shared object references without claiming selectable by-reference syntax;Uses value/reference concepts without falsely labelling Python as simply either
SYL-11.3-03|Yêu cầu dùng giá trị function trả về trong phép tính hoặc điều kiện khác, gồm nhiều đường return.|Ask learners to use a function return value in another expression or condition, including multiple return paths.|Every relevant path returns the required type/value;Caller uses the result rather than relying on printed output;Arguments and local state remain within the contract
SYL-11.3-04|Cho một định nghĩa và lời gọi rồi yêu cầu gắn nhãn header, interface, parameter, argument và return.|Provide a definition and call and label header, interface, parameter, argument and return.|Distinguishes formal parameters from actual arguments;Identifies returned values separately from displayed output;Terminology is applied to the concrete example
SYL-11.3-05|Cho hai cách phân chia thuật toán và yêu cầu chọn cách rõ ràng, tránh công việc lặp thừa mà giữ kết quả.|Present two structured designs and choose a clear approach that avoids unnecessary repeated work while preserving results.|Explains module and interface choices;Identifies a relevant efficiency improvement;Checks preserved behaviour instead of assuming shorter code is always better
SYL-12.2-01|Yêu cầu dựng sơ đồ module và trace dữ liệu được truyền qua một chuỗi lời gọi.|Ask for a module diagram and a trace of data passed through a call sequence.|Module responsibilities are clear;Each arrow identifies the transferred data;Arguments and return directions match the actual interfaces
SYL-12.3-01|Chuẩn bị một ví dụ tự biên soạn có lỗi cú pháp và yêu cầu định vị, phân loại trước khi sửa.|Prepare an original example with a syntax fault and require localisation and classification before repair.|Identifies the offending syntax;Uses the error location as evidence rather than guessing from final output;Repair makes the code syntactically valid
SYL-12.3-02|Chuẩn bị chương trình chạy được nhưng sai một trường hợp biên để học sinh tìm lỗi logic qua trace.|Prepare a runnable program failing a boundary case and locate the logic fault through a trace.|Shows the first divergence from expected state;Distinguishes a logic fault from a syntax failure;Proposes a change tied to the faulty condition/update
SYL-12.3-03|Chuẩn bị ví dụ phát sinh lỗi runtime có dữ liệu kích hoạt rõ để học sinh xác định nguyên nhân.|Prepare a runtime-failure example with a reproducible triggering input and identify the cause.|Reproduces the failure;Connects the failing operation to the triggering state;Distinguishes handling an expected failure from concealing a programming defect
SYL-12.3-04|Yêu cầu sửa một lỗi đã xác định rồi chạy lại ca gây lỗi cùng các ca không bị ảnh hưởng.|Ask learners to repair an identified fault and rerun the failing case plus unaffected cases.|Change addresses the root cause;Previously failing behaviour meets the specification;Regression checks preserve unaffected results
SYL-12.3-05|Yêu cầu dry run các biến quan trọng trước khi chạy thật, rồi so sánh expected/actual để giải thích khác biệt.|Require a dry run of selected state before execution, then compare expected and actual results to explain discrepancies.|Trace records relevant state transitions;Expected results are written before observation;Differences are investigated with a focused hypothesis
SYL-12.3-06|Yêu cầu lập test plan ghi input, trạng thái đầu, expected output/state và mục đích từng ca.|Ask for a test plan listing inputs, initial state, expected output/state and each case purpose.|Expected outcomes are explicit and checkable;State reset or retained state is specified;Tests link to requirements rather than merely collecting screenshots
SYL-12.3-07|Cho miền dữ liệu và giới hạn lưu trữ để học sinh chọn ca thường, bất thường và biên có lý do.|Provide data domains and capacity limits and select justified normal, abnormal and boundary cases.|Includes values at and around meaningful boundaries;Abnormal cases violate a stated input contract;Each case has a justified expected outcome
SYL-12.3-08|Yêu cầu thêm một hành vi nhỏ vào chương trình hiện có mà giữ giao diện và các kết quả cũ cần thiết.|Ask learners to add a small behaviour to an existing program while preserving required interfaces and previous results.|New behaviour meets the enhancement specification;Existing required behaviour remains correct;Tests cover the change and relevant regressions
SYL-13.2-01|Cho ba sơ đồ lưu record để phân loại serial, sequential và random, tách cách tổ chức khỏi thao tác đọc.|Present three record-storage diagrams and classify serial, sequential and random organisation separately from reading operations.|Identifies arrival order, key order and address-based organisation appropriately;Does not infer organisation solely from a loop;Uses the distinction to support file-processing choices
SYL-13.2-02|Cho cùng yêu cầu tìm record để so sánh quét tuần tự với truy cập theo địa chỉ.|Use the same record-retrieval requirement to compare sequential scanning with address-based access.|Describes records visited by each method;States the address information needed for direct access;Does not call an in-memory index lookup a completed file read
SYL-13.2-03|Yêu cầu giải thích hàm băm ánh xạ khóa sang địa chỉ, vì sao có va chạm và vì sao cùng khóa cho cùng địa chỉ khi giữ nguyên hàm; sau đó tính địa chỉ rồi chèn/tìm theo cách xử lý va chạm đã cho.|Require an explanation of how hashing maps keys to addresses, why collisions occur and why the same key gives the same address under an unchanged function; then compute addresses and insert/retrieve using a supplied collision scheme.|Explains the key-to-address mapping rather than only calculating a value;Explains that distinct keys can map to the same address and identifies this as a collision;States that an unchanged deterministic hash function maps the same key consistently to the same address;Address falls within the prescribed range;Collision and not-found behaviour follow the chosen bucket/Spare contract;Does not generalise one collision scheme to all hash tables
SYL-13.2-04|Lập phần mở rộng tự biên soạn nối khóa qua hàm băm tới địa chỉ record trong tệp thật rồi đọc/ghi theo layout đã chọn.|Plan an original extension mapping a key through hashing to a real file-record address and reading/writing the chosen layout.|Connects key, address and persistent file operation;States collision/address/layout policy;Array-only hashing or a binary fixture labelled official without provenance is insufficient
'''

manual={}
for row in ROWS.strip().splitlines():
    oid,vi,en,checks=row.split('|')
    assert oid not in manual,oid
    manual[oid]={'task_brief':{'vi':vi,'en':en},'acceptance_checks':checks.split(';')}

assessments={a['assessment_id']:a for a in blueprint['planned_assessment_destinations']}
blocks={b['block_id']:b for l in blueprint['lessons'] for b in l['blocks']}
special={
 'SYL-19.1-09':'linked-list-search', 'SYL-19.1-18':'graph-characteristics', 'SYL-19.1-19':'graph-characteristics',
 'SYL-19.1-24':'dictionary-operations', 'SYL-19.1-30':'adt-abstraction',
 'SYL-19.2-03':'recursive-design-trace', 'SYL-19.2-04':'recursive-design-trace',
 'SYL-20.1-12':'polymorphic-use', 'SYL-20.2-07':'serial-sequential-processing', 'SYL-20.2-08':'serial-sequential-processing',
 'SYL-20.2-09':'random-file-processing', 'SYL-20.2-10':'exception-recovery', 'SYL-20.2-11':'exception-recovery', 'SYL-20.2-12':'exception-recovery',
 'SYL-11.3-02':'parameter-effects', 'SYL-13.2-01':'serial-sequential-processing', 'SYL-13.2-02':'random-file-processing', 'SYL-13.2-04':'random-file-processing',
}
for n in [4,7,8,26,27,28,29]:special[f'SYL-19.1-{n:02}']='algorithm-cost'
nonexcluded=[o for o in inventory['objectives'] if o['scope']!='excluded']
assert len(nonexcluded)==107
assert set(manual)=={o['objective_id'] for o in nonexcluded},(set(manual)-{o['objective_id'] for o in nonexcluded},{o['objective_id'] for o in nonexcluded}-set(manual))
requirements=[]
for objective in nonexcluded:
    oid=objective['objective_id']
    keys=links[oid]['block_keys']
    bids=[f'{COURSE}.lesson.{key.replace("/", ".knowledge.")}' for key in keys]
    assert set(bids)<=set(blocks),oid
    lesson_ids=list(dict.fromkeys(bid.split('.knowledge.')[0] for bid in bids))
    grouping=f'{COURSE}.assessment.gap.{special[oid]}' if oid in special else f'{lesson_ids[0]}.assessment.progression'
    assert grouping in assessments,grouping
    support=[f'{lid}.assessment.progression' for lid in lesson_ids if f'{lid}.assessment.progression'!=grouping]
    assert all(aid in assessments for aid in support),oid
    requirements.append({
      'requirement_id':f'{COURSE}.assessment-requirement.{oid.lower()}',
      'objective_id':oid,'capability':{'vi':objective['capability_vi'],'en':objective['capability_en']},
      'scope':objective['scope'],'corpus_coverage':objective['corpus_coverage'],
      'knowledge_block_ids':bids,'suggested_assessment_id':grouping,'supporting_assessment_ids':support,
      **manual[oid],
      'status':'PLANNED_NOT_AUTHORED','origin':'AlgoCore original','official_marks':None,
      'authority_note':'Original assessment requirement; not a Cambridge question, official rubric or official marking allocation.',
      'source_objective_ref':'A3_OBJECTIVE_INVENTORY.json#'+oid,
      'mapping_authority':'Lead manual objective-to-block mapping in scripts/lead_objective_links.py',
      'knowledge_link_semantics':'Exact curriculum destinations for this capability; several blocks may be alternative application contexts. They do not require a single exercise to assess every context simultaneously.',
    })

result={
 'schema_version':'1.0.0','status':'SUBMITTED_FOR_LEAD_AND_A8_REVIEW','course_id':COURSE,
 'purpose':'Capability-specific original assessment requirements grouped into existing planned assessments. These are not 107 authored exercises, solutions, datasets or marking schemes.',
 'authoring_boundary':'No question prompts, solutions, code, fixtures or marks have been authored. Acceptance checks are design requirements for later authoring and independent review.',
 'language_policy':'Task briefs and capability labels are VI/EN. Acceptance checks are reviewer-facing English requirements; learner-facing rubrics derived from them require full VI/EN parity when authored.',
 'input_provenance':[{'path':str(p.relative_to(S3)).replace('\\','/'),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in [HERE/'A3_OBJECTIVE_INVENTORY.json',HERE/'A1_LESSON_BLUEPRINT.json',S3/'scripts/lead_objective_links.py']],
 'requirements':requirements,
 'excluded_objective_ids':[o['objective_id'] for o in inventory['objectives'] if o['scope']=='excluded'],
 'self_checks':{'objective_inventory_count':len(inventory['objectives']),'nonexcluded_objective_requirements':len(requirements),'missing_nonexcluded_objectives':[],'duplicate_requirement_ids':[],'all_exact_block_ids_resolve':True,'all_suggested_group_ids_resolve':True,'acceptance_check_count':sum(len(r['acceptance_checks']) for r in requirements),'assessment_group_count_available':len(assessments),'assessment_groups_used':len({r['suggested_assessment_id'] for r in requirements}),'official_marks_allocated':False,'exercises_authored':False},
}
assert all(len(r['acceptance_checks'])>=2 for r in requirements)
assert len({r['requirement_id'] for r in requirements})==107
(HERE/'A1_OBJECTIVE_ASSESSMENT_REQUIREMENTS.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps(result['self_checks'],ensure_ascii=False))
