import json, re, hashlib
from pathlib import Path
from collections import Counter
BASE=Path(__file__).resolve().parents[2]
OUT=Path(__file__).resolve().parent
syll=json.loads((BASE/'stage-1/extracted/syllabus_2026_v2.json').read_text(encoding='utf-8'))
pages={p['pdf_page']:p for p in syll['pages']}
catalog=json.loads((BASE/'stage-2/EXAM_PATTERN_CATALOG.json').read_text(encoding='utf-8'))
patterns={p['pattern_id']:p for p in catalog['patterns']}
qmap=json.loads((BASE/'stage-2/QUESTION_PATTERN_MAP.json').read_text(encoding='utf-8'))
rows=qmap['rows']
OBJECTIVES=[]
HEADINGS={'19.1':'Algorithms','19.2':'Recursion','20.1':'Programming Paradigms','20.2':'File Processing and Exception Handling','9.1':'Computational Thinking Skills','9.2':'Algorithms','10.1':'Data Types and Records','10.2':'Arrays','10.3':'Files','10.4':'Introduction to Abstract Data Types (ADT)','11.1':'Programming Basics','11.2':'Constructs','11.3':'Structured Programming','12.2':'Program Design','12.3':'Program Testing and Maintenance','13.2':'File organisation and access'}
def add(section,page,scope,en,vi,anchor,locator,links='',coverage='observed',brief='',deps=''):
    i=1+sum(o['section']==section for o in OBJECTIVES)
    oid=f'SYL-{section}-{i:02d}'
    text=pages[page]['text']; normalized=' '.join(text.split()).replace('built- in','built-in'); assert anchor in normalized,(oid,anchor)
    linked=[]
    for token in links.split():
        pat,role=token.split(':'); assert pat in patterns
        examples=[] # Filled only by the manual semantic evidence audit after all objectives exist.
        linked.append({'pattern_id':pat,'role':role,'basis':'Stage 2 capability boundary; occurrence alone does not establish every variant of this objective.','example_parts':[{'part_id':r['part_id'],'qp_basis':r['qp_basis'],'ms_basis':r['ms_basis']} for r in examples]})
    rationale={'core_practical':'Practical capability named within sections 19–20, retained even when absent from the historical corpus.','supporting_understanding':'Understanding named in 19–20 supports practical choices and traces; not promoted to a separate mandatory Paper 4 theory essay.','prerequisite':'Selected AS bridge used by practical code; not a claim that all AS objectives are independently assessed in Paper 4.','corpus_support':'Outside core 19–20; linked only to explain a corpus task or named file-processing capability.','excluded':'Explicit Paper 4 or graph-code boundary; no required practical lesson or assessment.'}[scope]
    OBJECTIVES.append({'objective_id':oid,'section':section,'scope':scope,'capability_en':en,'capability_vi':vi,'source':{'source_id':'syllabus_2026_v2','pdf_page':page,'printed_page':str(page),'heading':HEADINGS[section],'bullet_locator':locator,'anchor_text':anchor,'verification':'Natural text and rendered original page visually checked; page number matches PDF index.'},'rationale':rationale,'candidate_pattern_links':linked,'corpus_coverage':coverage,'coverage_limit':'Candidate links are capability mappings, not counts or guarantees of complete historical coverage.','gap':{'status':'not_applicable' if scope=='excluded' else ('authored_assessment_needed' if coverage in ['absent','partial','support_only'] else 'variant_completeness_check_needed'),'recommended_assessment_brief':brief or ('Author one small independent transfer check with changed data and boundary cases; do not reproduce a historical question.' if scope!='excluded' else '')},'prerequisite_objective_ids':deps.split()})
# Atomic capabilities from core source; list position is local, not an official Cambridge code.
C='core_practical';U='supporting_understanding';X='excluded';P='prerequisite';S='corpus_support'
add('19.1',37,C,'Implement linear search','Cài đặt tìm kiếm tuyến tính','Write an algorithm to implement a linear search','Search note 1','LINEAR_SEARCH:direct')
add('19.1',37,C,'Implement binary search','Cài đặt tìm kiếm nhị phân','Write an algorithm to implement a binary search','Search note 2','BINARY_SEARCH:direct')
add('19.1',37,U,'Explain binary-search preconditions','Giải thích điều kiện dùng tìm kiếm nhị phân','The conditions necessary for the use of a binary search','Search note 3','BINARY_SEARCH:support','support_only','Check whether a proposed search input satisfies its ordering contract, then justify the decision.')
add('19.1',37,U,'Relate binary-search performance to data size','Liên hệ hiệu năng tìm kiếm nhị phân với kích thước dữ liệu','How the performance of a binary search varies according to the number of data items','Search note 4','BINARY_SEARCH:support','support_only','Compare decision counts on increasing sorted inputs; explain the trend without predicting exam frequency.')
add('19.1',37,C,'Implement insertion sort','Cài đặt sắp xếp chèn','Write an algorithm to implement an insertion sort','Sorting note 1','INSERTION_SORT:direct')
add('19.1',37,C,'Implement bubble sort','Cài đặt sắp xếp nổi bọt','Write an algorithm to implement a bubble sort','Sorting note 2','BUBBLE_SORT:direct')
add('19.1',37,U,'Explain effects of initial order on sorting performance','Giải thích ảnh hưởng của thứ tự ban đầu tới hiệu năng sắp xếp','Performance of a sorting routine may depend on the initial order of the data and the number of data items','Sorting note 3, initial-order facet','BUBBLE_SORT:support INSERTION_SORT:support','support_only','Compare already sorted, reversed and mixed inputs for a fixed implementation; identify comparison and movement differences.')
add('19.1',37,U,'Explain effects of data size on sorting performance','Giải thích ảnh hưởng của lượng dữ liệu tới hiệu năng sắp xếp','Performance of a sorting routine may depend on the initial order of the data and the number of data items','Sorting note 3, size facet','BUBBLE_SORT:support INSERTION_SORT:support','support_only','Hold input-order family fixed while changing size and compare the number of operations.')
add('19.1',37,C,'Find an item in a linked list','Tìm một phần tử trong danh sách liên kết','Write algorithms to find an item in each of the following: linked list, binary tree','ADT find list, linked-list facet','LIST_REMOVE:partial LIST_TRAVERSE:support','partial','Write a standalone linked-list search returning a specified result for present, absent and empty cases; preserving links is part of the contract.')
add('19.1',37,C,'Find an item in a binary tree','Tìm một phần tử trong cây nhị phân','Write algorithms to find an item in each of the following: linked list, binary tree','ADT find list, binary-tree facet','TREE_SEARCH:direct')
for struct,vi,pat in [('stack','ngăn xếp','STACK_PUSH'),('queue','hàng đợi','QUEUE_ENQUEUE'),('linked list','danh sách liên kết','LIST_INSERT'),('binary tree','cây nhị phân','TREE_INSERT')]:add('19.1',37,C,'Insert an item into a '+struct,'Chèn phần tử vào '+vi,'Write algorithms to insert an item into each of the following: stack, queue, linked list, binary tree','ADT insert list, '+struct+' facet',pat+':direct')
for struct,vi,pat in [('stack','ngăn xếp','STACK_POP'),('queue','hàng đợi','QUEUE_DEQUEUE'),('linked list','danh sách liên kết','LIST_REMOVE')]:add('19.1',37,C,'Delete an item from a '+struct,'Xóa phần tử khỏi '+vi,'Write algorithms to delete an item from each of the following: stack, queue, linked list','ADT delete list, '+struct+' facet',pat+':direct')
add('19.1',37,U,'Describe graph ADT features','Mô tả đặc điểm ADT đồ thị','Describe the key features of a graph and justify its use for a given situation.','Graph note, features facet','','absent','Identify vertices and edges in a small scenario and explain which information the graph represents.')
add('19.1',37,U,'Justify a graph for a situation','Giải thích khi nào nên dùng đồ thị','Describe the key features of a graph and justify its use for a given situation.','Graph note, use facet','','absent','Choose a graph representation conceptually for a relationship scenario and justify it; no graph algorithm code.')
add('19.1',37,X,'Graph-structure code is not required','Không yêu cầu viết mã cấu trúc đồ thị','Candidates will not be required to write code for a graph structure','Graph note, explicit code exclusion','','excluded')
for struct,vi,pat in [('stack','ngăn xếp','STACK_SETUP'),('queue','hàng đợi','QUEUE_SETUP'),('linked list','danh sách liên kết','LIST_SETUP'),('dictionary','từ điển',''),('binary tree','cây nhị phân','TREE_SETUP')]:
 add('19.1',37,C,'Describe and implement '+struct+' using built-in types or another ADT','Mô tả và cài đặt '+vi+' bằng kiểu có sẵn hoặc ADT khác','Describe the following ADTs and demonstrate how they can be implemented from appropriate built-in types or other ADTs: stack, queue, linked list, dictionary, binary tree','ADT implementation list, '+struct+' facet',pat+':direct' if pat else 'HASH_SETUP:support HASH_INSERT:support HASH_SEARCH:support','observed' if pat else 'absent','Demonstrate a key-value dictionary interface with retrieval, insertion/update and a specified missing-key policy; these operation choices are an authored demonstration, not a verbatim syllabus operation list.' if not pat else '')
add('19.1',37,U,'Compare algorithms using time','So sánh thuật toán theo thời gian','criteria (e.g. time taken to complete the task and memory used)','Comparison criterion, time facet','BINARY_SEARCH:support LINEAR_SEARCH:support','support_only','Compare algorithms solving the same task on the same input and explain the time measure used.')
add('19.1',37,U,'Compare algorithms using memory','So sánh thuật toán theo bộ nhớ','criteria (e.g. time taken to complete the task and memory used)','Comparison criterion, memory facet','ALGORITHM_REWRITE:support','support_only','Compare explicit working storage and recursive call frames for two equivalent solutions.')
add('19.1',37,U,'Use Big O for time complexity','Dùng Big O mô tả độ phức tạp thời gian','Including use of Big O notation to specify time and space complexity','Comparison note, time complexity','BINARY_SEARCH:support BUBBLE_SORT:support','support_only','Relate counted operations to a suitable Big O time category for a specified implementation.')
add('19.1',37,U,'Use Big O for space complexity','Dùng Big O mô tả độ phức tạp không gian','Including use of Big O notation to specify time and space complexity','Comparison note, space complexity','ALGORITHM_REWRITE:support','support_only','Identify input storage versus auxiliary storage and include recursive stack depth in a small example.')
add('19.1',37,C,'Implement one ADT using another ADT','Cài đặt một ADT bằng ADT khác','Show how it is possible for ADTs to be implemented from another ADT','Separate ADT-from-ADT objective; not satisfied by choosing only built-in arrays','','absent','Demonstrate an ADT with its public operations implemented using another named ADT, for example a queue using two stack ADTs; test interface behaviour and explain the representation. This is an authored transfer demonstration, not an observed required exam pattern.')
add('19.2',37,U,'Identify essential recursion features','Nhận biết đặc điểm thiết yếu của đệ quy','Essential features of recursion','Recursion note 1','ALGORITHM_TRANSLATE:support ALGORITHM_REWRITE:support','support_only','Identify terminating case and progress toward it in a short recursive routine.')
add('19.2',37,C,'Express recursion in a programming language','Biểu diễn đệ quy bằng ngôn ngữ lập trình','How recursion is expressed in a programming language','Recursion note 2','BINARY_SEARCH:partial TREE_TRAVERSE:partial ALGORITHM_REWRITE:partial QUEUE_REDUCE:partial INSERTION_SORT:partial')
add('19.2',37,C,'Write a recursive algorithm','Viết thuật toán đệ quy','Write and trace recursive algorithms','Recursion note 3, writing facet','BINARY_SEARCH:partial TREE_SEARCH:partial TREE_TRAVERSE:partial ALGORITHM_TRANSLATE:partial ALGORITHM_REWRITE:partial QUEUE_REDUCE:partial INSERTION_SORT:partial')
add('19.2',37,C,'Trace a recursive algorithm','Theo vết thuật toán đệ quy','Write and trace recursive algorithms','Recursion note 3, tracing facet','EVIDENCE_RUN:support','absent','Trace calls, local values, returns and outputs for a short recursion with at least two pending frames; running a screenshot test alone does not evidence a trace.')
add('19.2',37,U,'Explain when recursion is beneficial','Giải thích trường hợp đệ quy có lợi','When the use of recursion is beneficial','Recursion note 4','TREE_TRAVERSE:support ALGORITHM_REWRITE:support','support_only','Compare recursive decomposition with an iterative alternative on a tree or shrinking interval.')
add('19.2',37,U,'Explain stack support for recursive translation','Giải thích ngăn xếp hỗ trợ lời gọi đệ quy','Use of stacks and unwinding','Compiler-awareness note, stack facet','STACK_SETUP:support','support_only','Represent each recursive activation with parameters, local state and return location; no compiler implementation.')
add('19.2',37,U,'Explain unwinding and pending returns','Giải thích tháo ngăn xếp và trả kết quả','Use of stacks and unwinding','Compiler-awareness note, unwinding facet','TREE_TRAVERSE:support ALGORITHM_REWRITE:support','support_only','Complete a call-and-return trace showing how pending results combine during unwinding.')
add('20.1',38,U,'Explain a programming paradigm and procedural/OOP characteristics','Giải thích mô hình lập trình và đặc trưng thủ tục/OOP','Understanding what is meant by a programming paradigm','Opening objective and paradigm characteristic umbrella','MAIN_FLOW:support OOP_CLASS:support','support_only','Compare how a procedural routine and an object organise the same small responsibility.')
add('20.1',38,X,'Low-level code and addressing modes excluded from Paper 4','Loại mã mức thấp và các chế độ địa chỉ khỏi Paper 4','low-level code that uses various addressing modes: immediate, direct, indirect, indexed and relative','Low-level note; P4 exclusion on pp11,40','','excluded')
for facet,vi,links in [('variables','biến','DATA_STORAGE:direct'),('constructs','cấu trúc điều khiển','RULE_COMPUTE:direct MAIN_FLOW:direct'),('procedures','thủ tục','FILE_READ_ARRAY:direct MAIN_FLOW:partial'),('functions','hàm','LINEAR_SEARCH:direct RULE_COMPUTE:partial')]:add('20.1',38,C,'Write procedural code using '+facet,'Viết mã thủ tục sử dụng '+vi,'programming code that uses variables, constructs, procedures and functions.','Imperative note 2, '+facet+' facet',links)
for facet,vi,links in [('objects','đối tượng','OOP_INSTANTIATE:direct'),('attributes','thuộc tính','OOP_CLASS:direct'),('methods','phương thức','OOP_CLASS:direct OOP_UPDATE:direct'),('classes','lớp','OOP_CLASS:direct'),('inheritance','kế thừa','OOP_SUBCLASS:direct'),('polymorphism','đa hình','OOP_OVERRIDE:direct'),('containment/aggregation','chứa đối tượng/tổng hợp','OOP_CAPACITY_ADD:direct OOP_CLASS:partial'),('encapsulation','đóng gói','OOP_CLASS:partial OOP_GET:partial OOP_SET:partial'),('getters','phương thức đọc thuộc tính','OOP_GET:direct'),('setters','phương thức đặt thuộc tính','OOP_SET:direct'),('instances','thể hiện của lớp','OOP_INSTANTIATE:direct')]:add('20.1',38,C,'Understand and demonstrate OOP '+facet,'Hiểu và thể hiện OOP: '+vi,'understanding of the terminology associated with OOP','OOP terminology note, '+facet+' facet',links)
add('20.1',38,C,'Design appropriate classes for a problem','Thiết kế lớp phù hợp với bài toán','understanding of how to solve a problem by designing appropriate classes','OOP note 2','OOP_CLASS:partial OOP_SUBCLASS:partial','partial','Given a small unfamiliar scenario without a supplied class diagram, propose classes, state, interfaces and containment/inheritance choices before coding.')
add('20.1',38,C,'Write code demonstrating OOP','Viết chương trình thể hiện OOP','understanding of and ability to write code that demonstrates the use of OOP','OOP note 3','OOP_CLASS:direct OOP_INSTANTIATE:direct OOP_OVERRIDE:direct')
add('20.1',38,X,'Declarative facts and rules excluded from Paper 4','Loại sự kiện và luật lập trình khai báo khỏi Paper 4','writing appropriate facts and rules based on supplied information','Declarative note 1; P4 exclusion on pp11,40','','excluded')
add('20.1',38,X,'Declarative goal satisfaction excluded from Paper 4','Loại giải mục tiêu bằng sự kiện và luật khỏi Paper 4','can satisfy a goal using facts and rules','Declarative note 2; P4 exclusion on pp11,40','','excluded')
for mode,vi,links in [('read','đọc','FILE_READ_ARRAY:direct FILE_READ_OBJECTS:direct'),('write','ghi','FILE_WRITE:partial'),('append','ghi nối','FILE_WRITE:partial')]:add('20.2',38,C,'Open a file in '+mode+' mode','Mở tệp ở chế độ '+vi,'Open (in read, write, append mode) and close a file','File note 1, '+mode+' facet',links)
add('20.2',38,C,'Close a file','Đóng tệp','Open (in read, write, append mode) and close a file','File note 1, close facet','FILE_READ_ARRAY:partial FILE_READ_OBJECTS:partial FILE_WRITE:partial')
add('20.2',38,C,'Read a record from a file','Đọc bản ghi từ tệp','Read a record from a file and write a record to a file','File note 2, read facet','FILE_READ_ARRAY:direct FILE_READ_OBJECTS:direct')
add('20.2',38,C,'Write a record to a file','Ghi bản ghi vào tệp','Read a record from a file and write a record to a file','File note 2, write facet','FILE_WRITE:direct')
add('20.2',38,C,'Process serial files','Xử lý tệp tổ chức nối tiếp không theo khóa','Perform file-processing operations on serial, sequential, random files','File note 3, serial facet','FILE_READ_ARRAY:partial FILE_READ_OBJECTS:partial FILE_WRITE:partial','partial','Process records in arrival order; distinguish this organisation from simply using sequential access.')
add('20.2',38,C,'Process sequential files','Xử lý tệp tổ chức tuần tự theo khóa','Perform file-processing operations on serial, sequential, random files','File note 3, sequential facet','FILE_READ_ARRAY:partial FILE_WRITE:partial','partial','Maintain a small file ordered by an explicit record key and demonstrate processing consistent with that organisation; a loop reading lines alone is insufficient.')
add('20.2',38,C,'Process random files','Xử lý tệp truy cập ngẫu nhiên theo khóa','Perform file-processing operations on serial, sequential, random files','File note 3, random facet','HASH_FUNCTION:support HASH_INSERT:support HASH_SEARCH:support','absent','Create a small learner-authored record file with a specified key-to-location scheme; retrieve and update by location. Supplied exam files contain no binary files; this does not delete the random-file objective.')
add('20.2',38,U,'Explain exceptions and why handling matters','Giải thích ngoại lệ và ý nghĩa xử lý ngoại lệ','Show understanding of an exception and the importance of exception handling','Exception objective','FILE_READ_ARRAY:partial FILE_WRITE:partial','partial','Explain the difference between an invalid input value handled by ordinary validation and an exceptional file operation failure.')
add('20.2',38,C,'Choose appropriate exception handling','Chọn nơi xử lý ngoại lệ phù hợp','Know when it is appropriate to use exception handling','Exception note 1','FILE_READ_ARRAY:partial FILE_READ_OBJECTS:partial FILE_WRITE:partial','partial','Select a narrow handling boundary and useful response for a missing/unreadable file without hiding unrelated programming faults.')
add('20.2',38,C,'Write exception-handling code','Viết mã xử lý ngoại lệ','Write program code to use exception handling','Exception note 2','FILE_READ_ARRAY:partial FILE_READ_OBJECTS:partial FILE_WRITE:partial')

# Focused prerequisite bridges. These are selected capabilities, not an exhaustive Paper 2 course.
add('9.1',27,P,'Model essential information through abstraction','Mô hình hóa thông tin thiết yếu bằng trừu tượng hóa','Produce an abstract model of a system by only including essential details','Abstraction guidance','DATA_RECORD:support OOP_CLASS:support')
add('9.1',27,P,'Decompose a task into procedures/functions','Phân rã bài toán thành thủ tục/hàm','Describe and use decomposition','Decomposition objective','MAIN_FLOW:support')
add('9.2',27,P,'Read and express a definite sequence of algorithm steps','Đọc và biểu diễn các bước thuật toán xác định','an algorithm is a solution to a problem expressed as a sequence of defined steps','Opening objective','ALGORITHM_TRANSLATE:direct')
add('9.2',27,P,'Choose suitable identifiers and record their roles','Chọn định danh phù hợp và ghi vai trò dữ liệu','Use suitable identifier names','Identifier objective','DATA_STORAGE:support')
add('9.2',27,P,'Translate input-process-output specifications','Chuyển đặc tả nhập-xử lý-xuất thành thuật toán','Write pseudocode that contains input, process and output','Input/process/output objective','ALGORITHM_TRANSLATE:direct MAIN_FLOW:direct')
add('9.2',28,P,'Refine a task to programmable detail','Tinh chỉnh bài toán tới mức có thể lập trình','Describe and use the process of stepwise refinement','Continued objective 1','MAIN_FLOW:support')
add('9.2',28,P,'Express algorithm conditions with logic statements','Biểu diễn điều kiện thuật toán bằng logic','Use logic statements to define parts of an algorithm solution','Continued objective 2','RULE_COMPUTE:direct VALIDATE_INPUT:direct')
add('10.1',28,P,'Choose suitable scalar data types','Chọn kiểu dữ liệu đơn phù hợp','Select and use appropriate data types for a problem solution','Data types objective','DATA_STORAGE:direct')
add('10.1',28,P,'Define a record with differently typed fields','Định nghĩa bản ghi có các trường khác kiểu','Write pseudocode to define a record structure','Record guidance 1','DATA_RECORD:direct')
add('10.1',28,P,'Read and update record fields','Đọc và cập nhật trường của bản ghi','Write pseudocode to read data from a record structure and save data to a record structure','Record guidance 2','DATA_RECORD:support HASH_INSERT:partial')
add('10.2',28,P,'Use indices and upper/lower bounds','Sử dụng chỉ số và cận trên/dưới của mảng','Including index, upper and lower bound','Array terminology guidance','DATA_STORAGE:direct')
add('10.2',28,P,'Choose and process 1D/2D arrays','Chọn và xử lý mảng một/hai chiều','Select a suitable data structure (1D or 2D array) to use for a given task','Array selection plus processing objectives','DATA_STORAGE:direct OUTPUT_FORMAT:partial')
add('10.3',28,P,'Explain persistent storage and process line-based text files','Giải thích lưu trữ lâu dài và xử lý tệp văn bản theo dòng','Write pseudocode to handle text files that consist of one or more lines','Files objective and why-files bridge','FILE_READ_ARRAY:direct FILE_WRITE:direct')
add('10.4',29,P,'Explain an ADT as data plus permitted operations','Giải thích ADT gồm dữ liệu và thao tác','an ADT is a collection of data and a set of operations on those data','ADT opening objective','STACK_SETUP:support QUEUE_SETUP:support LIST_SETUP:support')
add('10.4',29,P,'Relate stack/queue/list behaviour to array representation','Liên hệ hành vi ngăn xếp/hàng đợi/danh sách với mảng','Describe how a queue, stack and linked list can be implemented using arrays','ADT array objective; AS no-pseudocode note does not remove ALevel implementation','STACK_SETUP:direct QUEUE_SETUP:direct LIST_SETUP:direct')
add('11.1',29,P,'Declare and initialise constants and variables','Khai báo và khởi tạo hằng/biến','the declaration and initialisation of constants','Programming basics declaration bullets','DATA_STORAGE:direct')
add('11.1',29,P,'Assign and evaluate arithmetic/logical expressions','Gán và tính biểu thức số học/logic','the assignment of values to variables','Programming basics assignment and expression bullets','RULE_COMPUTE:direct CHECK_DIGIT:direct')
add('11.1',29,P,'Read keyboard input and produce console output','Nhập từ bàn phím và xuất ra console','input from the keyboard and output to the console','Programming basics expression/I-O bullet','MAIN_FLOW:direct OUTPUT_FORMAT:direct')
add('11.1',29,P,'Use built-in/library functions including strings','Sử dụng hàm có sẵn/thư viện, gồm xử lý chuỗi','Use built-in functions and library routines','Final basics objective and string guidance','STRING_COMPARE:partial STRING_SPLIT:partial STRING_ROUTE:partial')
add('11.2',29,P,'Use selection including nested conditions and CASE equivalents','Sử dụng rẽ nhánh gồm điều kiện lồng và tương đương CASE','an ‘IF’ statement including the ‘ELSE’ clause and nested IF statements','Selection bullets','RULE_COMPUTE:direct')
add('11.2',29,P,'Use count-controlled iteration','Sử dụng vòng lặp đếm','a ‘count-controlled’ loop:','Loop bullet 1','COUNT_OCCURRENCES:direct')
add('11.2',29,P,'Use pre-condition iteration','Sử dụng vòng lặp kiểm tra điều kiện trước','a ‘pre-condition’ loop','Loop bullet 3','VALIDATE_INPUT:partial LIST_TRAVERSE:direct')
add('11.2',29,P,'Use post-condition iteration and choose appropriate loops','Sử dụng vòng lặp kiểm tra điều kiện sau và chọn loại lặp','a ‘post-condition’ loop','Loop bullet 2 plus final choice objective','VALIDATE_INPUT:partial MAIN_FLOW:partial','partial','Implement a task requiring at least one execution using a correct Python equivalent; justify loop choice.')
add('11.3',30,P,'Define and call procedures with clear interfaces','Định nghĩa và gọi thủ tục với giao diện rõ ràng','Define and use a procedure','Procedure objective and purpose guidance','FILE_READ_ARRAY:direct MAIN_FLOW:partial')
add('11.3',30,P,'Use parameters and distinguish value/reference effects','Sử dụng tham số và phân biệt hiệu ứng truyền giá trị/tham chiếu','A parameter can be passed by reference or by value','Parameters objective and guidance','ALGORITHM_TRANSLATE:partial MAIN_FLOW:partial','partial','Predict caller-visible effects for scalar reassignment versus mutable-object change under Python semantics; do not describe Python as having a selectable by-reference parameter mode.')
add('11.3',30,P,'Define functions and use returned values in expressions','Định nghĩa hàm và dùng giá trị trả về trong biểu thức','A function is used in an expression, e.g. the return value replaces the call','Function objective and return-value guidance','RULE_COMPUTE:direct LINEAR_SEARCH:direct')
add('11.3',30,P,'Use header/interface/parameter/argument/return terminology','Dùng đúng thuật ngữ giao diện, tham số, đối số, giá trị trả về','Use the terminology associated with procedures and functions','Terminology objective and examples','MAIN_FLOW:support')
add('11.3',30,P,'Write efficient structured algorithms','Viết thuật toán có cấu trúc và hiệu quả','Write efficient pseudocode','Final structured-programming objective','ALGORITHM_REWRITE:support')
add('12.2',30,P,'Track module decomposition and parameters passed','Theo dõi phân rã mô-đun và tham số truyền giữa mô-đun','Use a structure chart to decompose a problem into sub-tasks','Selected program-design bridge; complete diagram theory is not core P4','MAIN_FLOW:support')
add('12.3',31,P,'Locate syntax errors','Xác định lỗi cú pháp','syntax errors','Fault-identification list, syntax facet','EVIDENCE_RUN:support','support_only','Repair an authored short syntax fault and explain why the program could not execute.')
add('12.3',31,P,'Locate logic errors','Xác định lỗi logic','logic errors','Fault-identification list, logic facet','EVIDENCE_RUN:support','support_only','Use a failing expected-result case to locate an authored logic fault.')
add('12.3',31,P,'Locate runtime errors','Xác định lỗi khi chạy','run-time errors','Fault-identification list, runtime facet','EVIDENCE_RUN:support','support_only','Reproduce an authored runtime error and identify its cause before deciding whether handling is appropriate.')
add('12.3',31,P,'Correct identified faults','Sửa lỗi đã xác định','Correct identified errors','Correction objective','EVIDENCE_RUN:support','support_only','Correct a located fault and rerun a regression case.')
add('12.3',31,P,'Use dry runs and focused testing methods','Chạy tay và dùng phương pháp kiểm thử phù hợp','Including dry run, walkthrough, white-box, black- box, integration, alpha, beta, acceptance, stub','Testing methods guidance; select practical dry-run/black-box/integration subset','EVIDENCE_RUN:partial','partial','Dry-run a short routine, then compare with execution and an expected result; no requirement for a full alpha/beta theory unit.')
add('12.3',31,P,'Build a test plan with expected results','Lập kế hoạch kiểm thử có kết quả mong đợi','Show understanding of the need for a test strategy and test plan and their likely contents','Test strategy/plan objective','EVIDENCE_RUN:partial','partial','Create a compact test table with purpose, input, expected output/state and actual result.')
add('12.3',31,P,'Choose normal, abnormal and boundary test data','Chọn dữ liệu kiểm thử thường, bất thường và biên','Including normal, abnormal and extreme/boundary','Test-data guidance','EVIDENCE_RUN:partial','partial','Choose distinct normal, invalid, empty/full and edge cases appropriate to a stated contract; prescribed exam tests alone do not prove independent test design.')
add('12.3',31,P,'Amend an existing program to enhance behaviour','Sửa chương trình có sẵn để bổ sung chức năng','Analyse an existing program and make amendments to enhance functionality','Final maintenance objective; selected amendment bridge','ALGORITHM_REWRITE:direct')
add('13.2',32,S,'Distinguish serial, sequential and random file organisation','Phân biệt tổ chức tệp nối tiếp, tuần tự và ngẫu nhiên','Including serial, sequential (using a key field), random (using a record key)','File organisation guidance','FILE_READ_ARRAY:support FILE_WRITE:support','support_only','Classify small file layouts by organisation, separating organisation from the method used to access them.')
add('13.2',32,S,'Distinguish sequential and direct access','Phân biệt truy cập tuần tự và trực tiếp','Sequential access for serial and sequential files Direct access for sequential and random files','File access guidance','FILE_READ_ARRAY:support HASH_SEARCH:support','support_only','Compare scanning records with addressing a record location under a specified layout.')
add('13.2',32,S,'Explain a hashing algorithm','Giải thích thuật toán băm','Show understanding of hashing algorithms','Hashing objective','HASH_FUNCTION:direct HASH_INSERT:partial HASH_SEARCH:partial')
add('13.2',32,S,'Use hashing to read/write a random or sequential file','Dùng băm để đọc/ghi tệp ngẫu nhiên hoặc tuần tự','Describe and use different hashing algorithms to read from and write data to a random / sequential file','Hashing guidance; file application facet','HASH_FUNCTION:support HASH_INSERT:support HASH_SEARCH:support','absent','Connect a simple key-to-address function to learner-created persistent record storage. In-memory bucket/overflow-array exam tasks alone do not demonstrate this file operation.')

# Scope register covers every numbered subsection listed in syllabus overview pp9–10.
AS={'1.1':'Data Representation','1.2':'Multimedia – Graphics, Sound','1.3':'Compression','2.1':'Networks including the internet','3.1':'Computers and their components','3.2':'Logic Gates and Logic Circuits','4.1':'Central Processing Unit (CPU) Architecture','4.2':'Assembly Language','4.3':'Bit manipulation','5.1':'Operating Systems','5.2':'Language Translators','6.1':'Data Security','6.2':'Data Integrity','7.1':'Ethics and Ownership','8.1':'Database Concepts','8.2':'Database Management Systems (DBMS)','8.3':'Data Definition Language (DDL) and Data Manipulation Language (DML)'}
ADV={'13.1':'User-defined data types','13.3':'Floating-point numbers, representation and manipulation','14.1':'Protocols','14.2':'Circuit switching, packet switching','15.1':'Processors, Parallel Processing and Virtual Machines','15.2':'Boolean Algebra and Logic Circuits','16.1':'Purposes of an Operating System (OS)','16.2':'Translation Software','17.1':'Encryption, Encryption Protocols and Digital certificates','18.1':'Artificial Intelligence'}
DISPOSITION=[]
for sec,title in sorted((AS|ADV|HEADINGS|{'12.1':'Program Development Life cycle'}).items(),key=lambda t:tuple(map(int,t[0].split('.')))):
    if sec in ['19.1','19.2','20.1','20.2']:status='core_and_support_with_explicit_exclusions';reason='Exhaustive atomic inventory in this file; P4 practical boundary applied.'
    elif sec=='13.2':status='conditional_support';reason='File organisation/access bridge to 20.2; in-memory hash corpus tasks kept distinct from persistent random files.'
    elif sec in HEADINGS:status='selected_prerequisite';reason='Only selected practical dependencies inventoried; not a complete AS course.'
    elif sec=='13.1':status='covered_by_prerequisite_and_oop_bridge';reason='Record and class concepts are linked via 10.1 and 20.1. No independent set/enumerated/pointer-type unit is inferred for P4.'
    elif sec=='12.1':status='outside_core';reason='No standalone development-life-cycle comparison or maintenance-theory module in this practical course.'
    else:status='outside_core';reason='Not inherited into P4 from Paper 1 or Paper 3. Any scenario vocabulary does not expand assessed scope.'
    DISPOSITION.append({'section':sec,'title':title,'disposition':status,'rationale':reason,'source':{'source_id':'syllabus_2026_v2','pdf_page':9 if int(sec.split('.')[0])<=12 else 10,'printed_page':str(9 if int(sec.split('.')[0])<=12 else 10),'heading':'Content overview'},'objective_ids':[o['objective_id'] for o in OBJECTIVES if o['section']==sec]})
CONSTRAINTS=[]
def con(i,page,statement,anchor,kind='assessment'):
 assert anchor in ' '.join(pages[page]['text'].split()),(i,anchor)
 CONSTRAINTS.append({'constraint_id':f'P4-ADM-{i:02d}','type':kind,'statement':statement,'source':{'source_id':'syllabus_2026_v2','pdf_page':page,'printed_page':str(page),'anchor_text':anchor}})
con(1,11,'Paper 4 is 150 minutes, 75 marks and 25% of A Level.','2 hours 30 minutes 75 marks')
con(2,40,'Practical application of sections 19–20 excludes low-level and declarative programming.','except for low-level and declarative programming.')
con(3,13,'AO3 is 100% of Paper 4; design, program and evaluate solutions with reasoned judgements.','Design, program and evaluate computer systems to solve problems, making reasoned judgements about these.')
con(4,11,'Candidates submit complete code and testing evidence.','Candidates will submit complete program code and evidence of testing.')
con(5,11,'Permitted languages are Java, Visual Basic (.NET) or Python, console mode. This course chooses Python by user instruction.','Python (console mode) programming languages.')
con(6,40,'Centre computers have no internet or email access.','these must not have internet access or access to email.')
con(7,11,'Calculators are not permitted.','Calculators must not be used in any paper.')
con(8,40,'Provided source files contain no binary files; random-file processing remains in 20.2.','The source files given will not contain binary files.')
con(9,40,'Save the provided evidence document with centre number, candidate name and candidate number.','should be saved with the centre number, candidate’s name and candidate’s number.')
con(10,40,'Copy requested program listings or result screenshots into the evidence document.','copy program listings or take screenshots of results to paste into the evidence document.')
con(11,40,'Save work regularly; centres are recommended to enable autosave.','Candidates must save their work at regular intervals')
con(12,40,'Work absent from the evidence document receives no marks.','If there is no evidence of work in the evidence document, the work will not receive any marks.')
con(13,39,'Facilities must support direct-access backing-store files and hardcopy.','direct-access file capability on backing store and hardcopy facilities.','teacher_guidance')
con(14,39,'Develop a systematic practical problem-solving approach and use adequate book coverage.','Teachers will need to consult several books to cover the whole syllabus adequately.','teacher_guidance')
# Editorial prerequisite graph: teaching order is not claimed as Cambridge mandated sequencing.
for o in OBJECTIVES:
 sec=o['section'];deps=[]
 if o['scope'] in [C,U]:
  if sec=='19.1':deps=['SYL-10.2-01','SYL-10.2-02','SYL-11.2-01','SYL-11.2-02','SYL-11.3-02']
  if sec=='19.2':deps=['SYL-11.3-02','SYL-11.3-03','SYL-11.2-01']
  if sec=='20.1':deps=['SYL-9.1-02','SYL-11.1-01','SYL-11.3-01','SYL-11.3-03']
  if sec=='20.2':deps=['SYL-10.1-01','SYL-10.3-01','SYL-11.2-03','SYL-11.3-03']
 if sec=='20.2' and 'files' in o['capability_en']:deps+=['SYL-13.2-01','SYL-13.2-02']
 if sec=='19.1' and any(w in o['capability_en'] for w in ['stack','queue','linked list','binary tree','dictionary']):deps+=['SYL-10.4-01','SYL-10.4-02']
 if o['objective_id']=='SYL-19.1-30':deps+=['SYL-19.1-21','SYL-19.1-22']
 o['prerequisite_objective_ids']=deps
# Full manual facet-level evidence audit after A8 findings. No first-tag selection remains.
from a3_semantic_evidence import apply
byid={r['part_id']:r for r in rows}
audit=apply(OBJECTIVES,byid)
(OUT/'A3_SEMANTIC_EVIDENCE_AUDIT.json').write_text(json.dumps({'status':'A3_REWORK_SUBMITTED','reviewed_objectives':len(audit),'policy':'All 111 objective rows semantically reviewed. Exact representative parts are manually selected; support links without specific assessment evidence have empty examples. No matching-by-first-tag evidence survives.','rows':audit},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
ids={o['objective_id'] for o in OBJECTIVES};assert len(ids)==len(OBJECTIVES)
for o in OBJECTIVES:assert set(o['prerequisite_objective_ids'])<=ids
result={'schema_version':'1.0','status':'A3_SUBMITTED_FOR_LEAD_REVIEW','authority':'Objective IDs and atomic decomposition are AlgoCore editorial IDs, not official Cambridge objective codes. Pattern links use frozen Stage 2.','source':{'source_id':syll['source_id'],'path':syll['source_path'],'sha256':syll['sha256'],'page_count':syll['page_count'],'version':'2026 Version 2','version_page':48},'granularity_policy':'Core 19–20 covers every applicable source objective and enumerated capability; umbrella verbs are represented by their atomic facets. AS prerequisites are selected bridges. Scope register covers every content-overview subsection. Supporting-understanding gaps receive checks without becoming theory-heavy P4 modules.','evidence_role_contract':{'candidate_pattern_link_role':'Capability-level relationship of a broad Stage 2 pattern: direct, partial or support. This is not evidence that every occurrence covers the objective.','exact_part_coverage_role':'Direct means the selected part explicitly assesses the stated facet; partial means it assesses only a component or prescribed instance, with the limitation stated in reason.','empty_examples':'No exact assessed corpus evidence is asserted; a candidate link is a teaching context only.','selection_policy':'Manual semantic selection only; no automatic first matching pattern examples.'},'coverage_vocabulary':{'observed':'Representative corpus task assesses this capability, with variant completeness still to review.','partial':'Corpus shows a component, supplied design, or prescribed tests; independent/general capability needs an authored check.','support_only':'Pattern supplies a teaching context; source corpus does not establish assessment of this understanding.','absent':'No standalone assessed example confirmed in frozen corpus; preserve syllabus objective and add authored check.','excluded':'No course practical assessment required.'},'counts':{'objectives':len(OBJECTIVES),'by_scope':dict(Counter(o['scope'] for o in OBJECTIVES)),'by_section':dict(Counter(o['section'] for o in OBJECTIVES)),'whole_syllabus_subsections':len(DISPOSITION),'assessment_constraints':len(CONSTRAINTS)},'objectives':OBJECTIVES,'assessment_constraints':CONSTRAINTS,'whole_syllabus_disposition':DISPOSITION,'limitations':['Representative mappings are not frequency counts, a mark allocation, or a claim every occurrence covers every objective.','Dictionary operations in recommended assessment are an editorial demonstration of the named ADT, not an added official operation list.','Linked-list search remains a standalone gap despite embedded search during removal.','Reading text lines is not proof of sequential key-ordered file organisation; array hashing is not random file access.','No code solutions or later-stage implementations authored here.'],'reviewed_renders':['A3_renders/syllabus_p'+str(p)+'.png' for p in [9,10,11,13,27,28,29,30,31,32,37,38,39,40,48]]}
(OUT/'A3_OBJECTIVE_INVENTORY.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps(result['counts'],ensure_ascii=False))
