import {createRequire} from 'node:module';
import fs from 'node:fs';
const require=createRequire(import.meta.url);
const {chromium}=require('C:/Users/Nguyen/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
fs.mkdirSync('qa',{recursive:true});
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173/',{waitUntil:'networkidle'});
await page.screenshot({path:'qa/entry-desktop.png',fullPage:true});
await page.getByLabel('Class code',{exact:true}).fill('1111');
await page.getByRole('button',{name:'Continue as student'}).click();
await page.getByRole('heading',{name:'Why create a data type?'}).waitFor();
await page.screenshot({path:'qa/lesson-desktop.png',fullPage:true});
await page.getByRole('tab',{name:'Try & check'}).click();
await page.getByRole('button',{name:'Non-composite',exact:true}).click();
await page.getByText('Try again.',{exact:false}).waitFor();
await page.screenshot({path:'qa/lab-desktop.png',fullPage:true});
await page.getByRole('button',{name:'Sign out',exact:true}).click();
await page.getByRole('tab',{name:'Teacher',exact:true}).click();
await page.getByLabel('Class code',{exact:true}).fill('0710');
await page.getByRole('button',{name:'Continue as teacher'}).click();
await page.getByRole('button',{name:'Teaching script'}).click();
await page.getByRole('heading',{name:'01 · Mở bài'}).waitFor();
await page.screenshot({path:'qa/teacher-desktop.png',fullPage:true});
await page.keyboard.press('Escape');
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'qa/lesson-mobile.png',fullPage:true});
const overflow=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));
console.log(JSON.stringify({errors,overflow,webmcp:await page.evaluate(()=>Boolean(document.modelContext))}));
await browser.close();
