from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
def exam(code,title,theory,lab,notice,steps,avoid,example,question,options,answer,why):
 body=f'### Spot the task\n\n{notice}\n\n### A quick method\n\n'+'\n'.join(f'{i+1}. {s}' for i,s in enumerate(steps))+f'\n\n### Keep the marks\n\n{avoid}\n\n### A worked example\n\n{example}\n\n### Use the real paper\n\nOpen the question paper first. Try the linked question before opening its mark scheme. Mark schemes can group several facts into one mark; these steps are not a promise of one mark per line.'
 return {'code':code,'title':title,'goal':'Recognise the task, choose a method and show the steps that earn marks.','theory':theory.split(','),'lab':lab,'body':body,'quiz':{'question':question,'options':options,'answer':answer,'explanation':why}}
E=[
exam('E01','Explain and compare data types','13.1.1','types','Look for define, describe, compare, composite or non-composite.',
['State what each type holds.','Compare both types using the same feature.','Give an example in the correct group.'],
'Do not stop at “it has many variables”. A composite type groups components under one name. A pointer is non-composite in this course. In O/N 2023/32 Q2, the four marks are split across the two sides.',
'“A record groups related fields under one name; its fields may have different types. An enum variable holds one value from a named list.”',
'Which comparison explains a real difference?',['Records are better.','A record groups fields; an enum variable chooses one named value.','Both are always strings.'],1,'Give a feature of each side on the same basis.'),
exam('E02','Define an enum','13.1.2','enum','Look for a new type name and a fixed list of allowed values, or a question about enum order.',
['Write TYPE, the type name, = and the values in parentheses.','Check names, order and repeated values.','If a variable is requested, add a separate DECLARE line.'],
'Do not put enum values in quotes. Do not replace TYPE with DECLARE. The list does not automatically wrap. M/J 2025/31 Q1(a) uses two marks for the declaration and value list.',
'```text\nTYPE TStatus = (Active, Paused, Completed)\nDECLARE Status : TStatus\nStatus ← Paused\n```',
'Which defines a new enum type?',['TYPE TStatus = (Active, Paused)','DECLARE TStatus ← Active','TYPE TStatus = "Active"'],0,'TYPE creates the named list. DECLARE creates a variable.'),
exam('E03','Choose a field for an enum','13.1.2,13.1.3','record','Look for identify a field, give a reason, or change a STRING field to an enum.',
['Choose a field with a small, fixed set of valid choices.','Explain why this list fits the task.','Define the enum and replace the field type when asked.'],
'A few names in a sample table do not make every name an enum choice. Do not define the enum but leave the field as STRING. Answer only the change requested. M/J 2025/33 Q1(b) awards a choice and a reason.',
'Define the enum first:\n\n```text\nTYPE TStatus = (Active, Paused, Completed)\n```\nInside the existing record definition, replace its old STRING field with:\n\n```text\nDECLARE Status : TStatus\n```\nFor a declared record variable Learner, assign `Learner.Status ← Active`. Status suits an enum because only these named study states are valid.',
'Which field is the best enum choice?',['FullName','Phone','StudyStatus'],2,'StudyStatus has a defined list of choices; names and phone numbers do not.'),
exam('E04','Define a record','13.1.3','record','Look for declare a composite data type plus a list of fields or sample data.',
['Write the TYPE/ENDTYPE frame.','Add every requested field with DECLARE.','Check each field type, including any enum from the previous part.'],
'Keep IDs or phone numbers as STRING where their format needs it. Counts use INTEGER, dates DATE and flags BOOLEAN. Follow explicit constraints in the question. In M/J 2025/31 Q1(b), marks cover the frame, DECLARE and groups of fields.',
'```text\nTYPE TLearner\n   DECLARE ID : STRING\n   DECLARE Lessons : INTEGER\n   DECLARE Status : TStatus\nENDTYPE\n```',
'Which field should use INTEGER?',['Phone','LessonsAttended','FullName'],1,'LessonsAttended is a count.'),
exam('E05','Declare a record variable and assign fields','13.1.3','record','The record type is already defined. The question asks for a variable or values in its fields.',
['Use DECLARE Variable : Type when a variable is needed.','Assign each requested value to Variable.Field.','Check quotes, dates, enum values and exact field names.'],
'Do not write Type.Field instead of Variable.Field. Do not rewrite the TYPE definition and forget the requested assignment. M/J 2025/32 Q1(a) checks variable/field use, STRING assignments and the date.',
'```text\nDECLARE Learner : TLearner\nLearner.ID ← "AC027"\nLearner.Lessons ← 8\nLearner.Status ← Active\n```',
'Learner is the variable. Which assignment is correct?',['TLearner.ID ← "AC027"','Learner.ID ← "AC027"','ID.Learner ← "AC027"'],1,'Use the variable name, then a dot, then the field name.'),
exam('E06','Declare and use a pointer','13.1.4','pointer','Look for pointer type, memory location, address, reference or value at an address.',
['Find the target data type.','Use ^TargetType in the pointer type definition.','Separate variable declaration, address assignment and dereference.'],
'Do not place ^ everywhere. A target must be valid before reading through a pointer. O/N 2021/31 Q3(b) checks the pointer declaration and the target type from the previous part.',
'```text\nTYPE TIntPointer = ^INTEGER\nDECLARE P : TIntPointer\nP ← ^Score\nOUTPUT P^\n```\nScore must already be declared and hold a valid INTEGER.',
'What does ^Score mean in P ← ^Score?',['The address of Score','The value of Score','The address of P'],0,'The prefix ^ gets the target address; the suffix ^ dereferences a pointer.'),
exam('E07','Describe and define a set','13.1.5','sets','Look for SET, several items at once, unordered items, union or intersection.',
['Write TYPE Name = SET OF ElementType.','Use DEFINE for the named set when required.','Link the set back to its type and check every item.'],
'Keep SET OF, DEFINE, the set name and the type after the colon. CHAR values need single quotes. A set is not an enum just because both display a list. M/J 2024/32 Q3(b) checks these declaration parts.',
'```text\nTYPE TUnitSet = SET OF INTEGER\nDEFINE Completed (1, 3, 5) : TUnitSet\n```\nAdding 3 again does not change the set.',
'A set already contains 3. Add 3 again. What changes?',['Its size rises by one.','Nothing: items are unique.','All values become strings.'],1,'A set does not contain duplicates.'),
exam('E08','Choose or compare file organisation','13.2.1','organisation','Look for serial, sequential or random organisation, record order, insertion or a use case.',
['Compare storage order.','Explain how a new record is added.','Link that behaviour to the task.'],
'Answer organisation with an organisation, and access with an access method. “Fast” alone does not explain a mechanism. O/N 2021/31 Q5 compares serial and sequential; O/N 2024/32 Q2 asks about serial and a use.',
'“A serial file appends events as they arrive. A sequential file keeps key order, so a new key must be inserted in the correct place.”',
'Which organisation naturally fits an unsorted event log?',['Serial','Sequential by learner ID','Randomly choose a new slot each time'],0,'Appending events preserves their arrival order.'),
exam('E09','Trace a sequential search','13.2.2','search','Look for one record after another or a difference between searching serial and sequential files.',
['Start at the first record.','Read and compare each key.','State the correct stop conditions for the file order.'],
'A sorted ascending file can stop when current key > target. An unsorted file cannot. Reverse the comparison for descending order. M/J 2024/31 Q4 checks the method and the different stopping conditions.',
'Find 20 in 12,18,25,31: read 12 → 18 → 25 → stop. No later key can be 20. In 31,12,25,18, read all four before saying it is absent.',
'When can current key > target prove that the target is absent?',['In every serial file','In an ascending sorted file','Only in an empty file'],1,'The conclusion depends on the order of the file.'),
exam('E10','Explain direct access','13.2.2,13.2.3','hash','Look for locate one record directly, sometimes comparing sequential and random files.',
['For an indexed file: key → index → address → record.','For a hashed file: key → hash → starting slot → compare key.','Explain any extra lookup needed after a collision.'],
'Do not just say “go straight there”. If two organisations are named, explain both mechanisms. Direct access may take more than one read. M/J 2024/32 Q7(b) separates the index and hash cases.',
'An index contains 25 → 0x1040. Read the record at that address. With key MOD7, key25 starts at slot4; check the stored key before using it.',
'What does an index normally link?',['Key to address','Date to rounding mode','Mantissa to exponent'],0,'An index lets a key locate its record address.'),
exam('E11','Calculate a hash and an address','13.2.3','hash','Look for MOD, a key table, a base address or record size.',
['Find the greatest whole multiple of N that does not exceed the key.','Subtract it to get the remainder.','Use Base + Slot × Size only if a byte address is requested and slots start at zero.'],
'MOD is not integer division. Keep 0 ≤ remainder < N and the correct units. Do not invent a new hash when a function is given. M/J 2023/31 Q3(a) uses MOD3.',
'1030 = 343×3 + 1, so the slot is 1. In a separate address example with base4096 and size64, address = 4096+1×64 = 4160 bytes.',
'What is 1030 MOD 3?',['343','1','3'],1,'The remainder is 1; 343 is the quotient.'),
exam('E12','Handle a collision when storing and finding','13.2.4','hash','Different keys have the same starting location, or the hash slot is already occupied.',
['Name the collision: different keys, same hash location.','For storage, follow the rule until a free slot or overflow position is found.','For search, follow the same rule and compare the full key.'],
'Do not overwrite a different key or return the first record only because its hash matches. If asked for storage and retrieval, cover both. Explain the mechanism before any open/closed label; source labels vary. M/J 2023/31 Q3(b) covers both operations.',
'27 and37 both hash to7 under MOD10. Store27 at7 and37 at8. Search37: slot7 has27 → slot8 has37 → found.',
'Why must a search compare the full record key?',['Different keys can have the same hash.','MOD always gives a negative result.','Every record is stored twice.'],0,'A hash location is not a unique identity.'),
exam('E13','Encode denary as floating-point','13.3.1,13.3.3','encode','A denary value and field lengths are given. The question asks for a normalised representation.',
['Write the field lengths and convert the magnitude to binary.','Move the point to a normalised mantissa; record E.','Fill M, apply two’s complement if negative, then check 01/10.','Encode E to the correct width and decode to check.'],
'Keep working. Do not merely flip the first bit, or make E negative just because X is negative. Check the −0.5 boundary after negation. M/J 2025/31 Q2(b) has separate method and final-field marks.',
'−6.5 in M8/E4: 6.5=110.1₂=0.1101₂×2^3. Positive M01101000 → negative M10011000; E0011. Check: (−104/128)×8=−6.5.',
'Which pair is normalised −0.5 in M8/E4?',['11000000/0000','10000000/1111','01000000/0000'],1,'The second pair starts 10 and means −1×2^-1.'),
exam('E14','Decode floating-point to denary','13.3.2','float','A mantissa and exponent bit pattern is given. You need a denary value.',
['Read M as signed integer I.','Compute M=I/2^(m−1) and read signed E.','Use X=M×2^E, keeping intermediate values visible.'],
'The denominator is 2^(m−1), not 2^m. E is signed. A negative E does not add a second minus sign to X. M/J 2025/32 Q2(b) rewards working and the final value.',
'M10110000/E1110: I=−80, M=−80/128, E=−2. X=−80/512=−0.15625.',
'For an eight-bit M, divide its signed integer by what?',['256','128','8'],1,'There are seven fractional positions after the sign bit.'),
exam('E15','Normalise the given value','13.3.4','normalise','The input may be an existing M/E pair or a raw binary number with a point.',
['Identify which input form you have.','For an M/E pair, shift M left k and subtract k from E.','For a raw binary value, derive E from the point movement.','Check bit lengths and that the value is unchanged.'],
'Do not add to E when shifting M left. Do not confuse normalisation with rounding or claim that it restores lost bits. M/J 2025/31 Q2(a) starts with a small raw binary value.',
'0.00011₂ = 0.11₂×2^-3. In M8/E4, M01100000/E1101 gives 3/32. For an existing pair 00011000/0100, shift left2 and reduce E2 to get 01100000/0010; both are3.',
'0.00011₂ = 0.11₂ × 2^E. What is E?',['3','−3','0'],1,'The mantissa is eight times larger, so the scale is one eighth.'),
exam('E16','Find the largest or smallest value','13.3.5','limits','Look for largest positive, smallest positive, most negative or negative nearest zero.',
['Find Emin and Emax from the exponent width.','Choose the correct normalised M pattern.','Combine M and E and write an exact fraction or power of two.'],
'Most negative and negative with the smallest magnitude are different. The largest positive E begins with0, not1. M/J 2025/33 Q2(a) asks for both the pattern and the value.',
'For M8/E8, largest positive M01111111/E01111111 = (127/128)×2^127. In M8/E4, most negative is−128, while negative nearest zero is−65/32768.',
'Which eight-bit exponent is the largest signed value?',['11111111','01111111','10000000'],1,'01111111 is +127. 11111111 is −1.'),
exam('E17','Explain a change in bit allocation','13.3.5','limits','The total word stays fixed while M and E receive different numbers of bits.',
['Write the old split and new split.','Explain M change → significant bits → precision.','Explain E change → exponent limits → range.'],
'Discuss both precision and range when asked. More E bits do not make every fraction exact. If total width is not fixed, do not assume one field must shrink. O/N 2025/33 Q2(a) uses M12 to M10 in a 16-bit word.',
'M12/E4 → M10/E6: fewer significant bits, so lower precision; E grows from four to six bits, so a wider range.',
'With a fixed16-bit word, M changes from12 to10. How many E bits remain?',['4','6','10'],1,'16−10=6.'),
exam('E18','Explain and calculate approximation','13.3.3,13.3.6','rounding','Look for not exact, approximation, too few mantissa bits or two formats storing the same value.',
['Decide whether the binary fraction repeats or merely needs more bits.','Normalise and mark the kept and discarded bits.','Apply the required truncation or rounding rule.','Decode the stored value and find the error if asked.'],
'Not every decimal-point number has an infinite binary fraction. Do not use range errors as a precision explanation. M/J 2023/31 Q1 uses113.75, a finite binary fraction that does not fit M8 exactly; its MS shows truncation.',
'113.75=0.111000111₂×2^7. M8 keeps01110001 and stores113 if truncated. Nearest uses01110010 and stores114. The rule changes the answer.',
'113.75 truncated in M8/E8 becomes what?',['113','114','113.75'],0,'Keep the eight M bits: 01110001 with E7 represents113.'),
exam('E19','Explain overflow or underflow','13.3.5,13.3.7','limits','The question asks when a result becomes too large or too close to zero, sometimes with a consequence.',
['Give a valid calculation.','Compare the non-zero result with the correct format limit.','State that the representation does not fit; describe a handling rule only when known.'],
'Underflow is not simply a negative result. Overflow is not just a carry. Do not assert that every system returns0, or use division by0 as an ordinary finite range example. O/N 2025/33 Q2(b) asks for situation and consequence.',
'M8/E4 normalised:100×2=200>127 is overflow. (1/512)/2=1/1024 is below the smallest positive normalised value, so underflow.',
'Which is an overflow example in normalised M8/E4?',['100×2','−6.5','(1/512)/2'],0,'200 exceeds the maximum positive value127.'),
exam('X01','Crossover: subrange and array fields','13.1.3','record','A record field is restricted to a range, or a record must store several child IDs.',
['Decide: one limited value, or several stored values?','Write the exact replacement/additional field requested.','Use the syntax of that historical question.'],
'M/J 2022/31 Q1(b) asks for subrange and array fields, not SET. Do not call it a set just because there are several accession numbers. This is crossover practice with AS arrays and historical syntax.',
'```text\nDECLARE NumberOfCopies : 1 .. 10\nDECLARE AccessionNumber : ARRAY[1:NumberOfCopies] OF INTEGER\n```\nOne copy count controls the number of array items.',
'Which structure holds several ordered accession numbers?',['An INTEGER array','A single enum value','A pointer address alone'],0,'An array contains multiple indexed items of one type.'),
exam('X02','Crossover: PRIVATE in a class','13.1.6','objects','A record question changes to a class, property, PRIVATE or encapsulation.',
['Identify the property and its type.','Write the requested access keyword and declaration.','Explain outside access through methods, not directly to private state.'],
'PRIVATE does not encrypt the data. If one line is asked for, do not rewrite a whole class. Further inheritance and polymorphism need Unit20. M/J 2022/32 Q1(c) connects a record with class properties.',
'```text\nPRIVATE Name : STRING\n```\nOutside code should use a public method, such as GetName(), rather than reading the private field directly.',
'Why make a property PRIVATE?',['To encrypt it','To control outside access through methods','To make every value zero'],1,'Encapsulation controls direct access; it is not encryption.'),
exam('X03','Crossover: random-file pseudocode','13.1.3,13.2.2,13.2.4','fileio','Look for OPENFILE FOR RANDOM, SEEK, GETRECORD, PUTRECORD, loops or a stored flag.',
['Name the source file, target file and record variable.','SEEK in the correct file before the read or write.','GETRECORD reads into a variable; PUTRECORD writes from it.','Keep loop bounds, position changes, stop flags and CLOSEFILE.'],
'Do not mix up a filename and a record variable, or read from the target file. If looking for an empty slot, preserve the Stored flag and full-table stop. M/J 2025/32 Q13 copies50 records; M/J 2025/33 Q11 finds a free position.',
'```text\nFOR i ← 1 TO 50\n   SEEK SourceFile, i\n   GETRECORD SourceFile, ThisRecord\n   SEEK TargetFile, i\n   PUTRECORD TargetFile, ThisRecord\nNEXT i\n```\nBoth files must be opened in RANDOM mode before the loop and closed after it.',
'Which command reads a record into ThisRecord?',['PUTRECORD File, ThisRecord','GETRECORD File, ThisRecord','SEEK ThisRecord, File'],1,'GETRECORD reads from the file. PUTRECORD writes to it.'),
]
# Readable number spacing in prose; preserve code tokens and identifiers.
for e in E:
 for k in ['body','goal']:
  import re
  e[k]=re.sub(r'(?<=[a-z])(?=\d)', ' ', e[k])
(ROOT/'data/exams.en.json').write_text(json.dumps(E,ensure_ascii=False,indent=2),encoding='utf-8')
print('Wrote 22 exam-pattern lessons')
