"""A8 authored findings register; does not grant the Lead's Stage 2 gate."""
from pathlib import Path
import json,datetime
S=Path(__file__).resolve().parents[1]
findings=[
 dict(id='S2-TAX-01',status='CLOSED_RECHECKED',issue='STRING_SPLIT combined typed field routing with manual delimiter tokenization; record/class boundary depended too strongly on encapsulation.',sources=['9618_s25_41_2(b): QP4/MS21','9618_w25_43_3(b)(ii): QP13/MS35','9618_s25_42_2(a)','9618_w25_41_3(a)'],resolution='Seed now has 58 patterns. STRING_ROUTE covers typed parse/category destination selection; STRING_SPLIT covers tokens. s25_41 row and contexts corrected. DATA_RECORD follows explicit TYPE/record task with class substitute; explicit OOP class/constructor remains OOP_CLASS regardless of public fields or name Record.'),
 dict(id='S2-MAP-01',status='CLOSED_RECHECKED',issue='w25_41 1(d) correctly used MAIN_FLOW with STACK_PUSH context, but lost directly required random generation outside RANDOM_ARRAY.',sources=['9618_w25_41_1(d): QP3/MS11'],resolution='Row now records directly_assessed_additional_skills=[random_generation] and inclusive bounds [0,1000]. MAIN_FLOW primary and STACK_PUSH context preserved. Final normalized skills were independently checked in the aggregate and preserve random_generation.'),
 dict(id='S2-MAP-02',status='CLOSED_RECHECKED',issue='w23_42 2(b)(i) was tagged as assessed ALGORITHM_REWRITE even though the recursive skeleton is already supplied and the candidate completes it.',sources=['9618_w23_42_2(b)(i): QP7-8/MS19-20'],resolution='ALGORITHM_TRANSLATE primary plus RULE_COMPUTE, complete_pseudocode mode; supplied_transformation retained as context variant. Downstream main/evidence contexts now ALGORITHM_TRANSLATE, not ALGORITHM_REWRITE.'),
 dict(id='S2-MODE-01',status='CLOSED_RECHECKED',issue='New PrintArray/structured output routines used implement in one batch and output in another.',sources=['9618_s23_41_1(b)(i): QP2/MS7','9618_w25_42_2(b): QP6/MS19'],resolution='All OUTPUT_FORMAT-primary rows now use output except explicitly mixed integration and amendment/adapt tasks. The final LEAD_DECISIONS mode contract explicitly carries this rule.'),
 dict(id='S2-CO-01',status='CLOSED_RECHECKED',issue='Object-file loader co-tags for explicit storage declaration and instance construction differed by analyst batch.',sources=['9618_s21_41_3(b)','9618_s23_42_3(c): QP11/MS30-33','9618_s24_41_2(b): QP7/MS18-20','9618_w25_41_3(e): QP11/MS31-32'],resolution='s23_42 and s24_41/43 loaders now include DATA_STORAGE and OOP_INSTANTIATE; w25_41 loader includes OOP_INSTANTIATE but not storage already declared earlier. Existing-object hours update does not gain construction tags.')
]
cases=[
 ('operation_vs_name','s23_41 1(c) counts matches despite LinearSearch; s21 search returns presence. GetTotalPay sums; GetPosition/Description format strings; SetTerritorySize updates relative state.'),
 ('invoke_vs_implement','Existing Push/Enqueue/SetPay remain context when a loader/main/override merely invokes them. Screenshot-only rows use EVIDENCE_RUN. Random generation inside w25_41 main is an explicit additional skill.'),
 ('record_vs_class','s25_42 TYPE NewRecord uses DATA_RECORD; w25_41 explicitly OOP Record uses OOP_CLASS and object loader. Public fields do not change this boundary.'),
 ('physical_vs_logical_order','w21 PrintAll and s24_42 OutputTree print physical node storage: OUTPUT_FORMAT. Following linked next fields or left/right children is traversal.'),
 ('rewrite_vs_completion','w23_42 RecursiveValue is supplied incomplete; w22_42 readonly queue sum and s24_42 insertion sort explicitly transform control structure. Direction and readonly/dequeue distinction retained.'),
 ('routing_vs_tokens','s25_41 parses number/colour and routes into six one-dimensional arrays; w25_43 manually constructs four tokens separated by semicolons. Already supplied single-letter stack dispatch is not STRING_ROUTE.'),
 ('queue_variants','Circular versus linear, next-free versus last-live tail, count, reset and sentinel data types remain distinct. w22_42 reduction walks backward without dequeueing; w24_42 ReturnAllData inspects live queue values.'),
 ('compound_assessment','Explicit object-array declaration and construction are co-assessed in loaders; no repeated algorithm credit for calls. Whole-row marks remain primary editorial or non-additive assessed union, never allocated Cambridge submarks.'),
 ('source_specific_rule','s24_41/43 check digit uses floor(weighted sum/10), with 10 mapped to X; no assumed modulo algorithm. s24_42 consumed dictionary answers fit UNIQUE_SELECTION rather than occurrence count.')
]
visuals=['9618_w23_qp_42/p007.png','9618_w22_qp_42/p009.png','9618_s24_qp_41/p012.png','9618_s23_qp_42/p010.png','9618_w25_qp_41/p003.png','9618_w25_ms_41/p011.png']
obj=dict(review_version='A8-stage2-review-v1',reviewer='A8 independent QA',updated_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),status='SUBMISSIONS_RECHECKED_AGGREGATE_PENDING',scope='All 672 row schema/joins; all 140 root 2025 rows semantically read; selected ordinary and ambiguous 2021-2024 rows independently reclassified/read from QP/MS. Not a claim of second full visual inspection of all source pages.',findings=findings,semantic_cases=[dict(boundary=a,evidence=b) for a,b in cases],fresh_stage2_facsimiles=visuals,mechanical_evidence='A8_MECHANICAL_CHECKS.json',pending=['Exact aggregate-to-batch row preservation and Stage 1 joins','Independent per-pattern raw, strict-text and render-corroborated statistics','Catalog/map/normalized skill consistency and method contracts','Final source issue/dependency propagation and release consistency'],authority='Lead alone issues the stage gate after all required findings and pending checks are resolved.')
(S/'evidence/A8_TAXONOMY_REVIEW.json').write_text(json.dumps(obj,ensure_ascii=False,indent=2),encoding='utf-8')
md=['# A8 independent Stage 2 taxonomy review','','**Status: submissions rechecked; aggregate review pending.** No Stage 2 gate is granted by this report. Stage 1 remains immutable.','',obj['scope'],'','## Rework findings','']
for f in findings:
 md += [f"### {f['id']} — {f['status']}",'',f['issue'],'','Evidence: '+ '; '.join(f['sources'])+'.','',f['resolution'],'']
md += ['## Independent evidence and limits','','The A8 mechanical script independently checks all 672 IDs, exact QP/MS locators, pattern and mode vocabulary, primary membership, assessed/context disjointness, and equivalence-family mapping consistency. It reconstructs the 21 strict body-text groups independently and checks all 29 identities in both partitions. Current results: no errors; strict view 21 papers / 63 questions / 487 parts / 1,575 marks, render-corroborated view 23 / 69 / 536 / 1,725. These are sensitivity denominators, not assertions of independent exam questions.','','The A3 REVIEW files and source-reading registers were inspected as provenance; they do not substitute for the A8 semantic checks below. Stage 1 raw-PDF authority, extraction caveats and facsimile rules continue to apply. Source code is not certified executable.','']
for a,b in cases:md += ['- **'+a.replace('_',' ')+':** '+b]
md += ['','Six additional original facsimiles visually inspected in this Stage 2 review: '+', '.join('`'+v+'`' for v in visuals)+'. Stage 1 source reading/images also informed the 2025 review; this report does not claim 672 independent visual page inspections.','','## Checks still pending','']+[ '- '+p for p in obj['pending']]+['','Primary marks will be checked as disjoint editorial allocation. Assessed-pattern marks must be unions within each row and must not be summed across pattern rows. No Cambridge marking-point subdivision or future-exam probability is inferred.','']
(S/'evidence/A8_TAXONOMY_REVIEW.md').write_text('\n'.join(md),encoding='utf-8')
aggregate_path=S/'evidence/A8_AGGREGATE_CHECKS.json'
if aggregate_path.exists():
 aggregate=json.loads(aggregate_path.read_text(encoding='utf-8'))
 if aggregate['status']=='PASS':
  obj['status']='A8_PASS_AFTER_REWORK'
  obj['pending']=[]
  obj['review_version']='A8-stage2-review-v2'
  obj['aggregate_evidence']='A8_AGGREGATE_CHECKS.json'
  obj['independent_statistics_evidence']='A8_INDEPENDENT_STATISTICS.json'
  obj['findings'].append(dict(id='S2-JOIN-01',status='CLOSED_RECHECKED',issue='Aggregate source_issues link targeted nonexistent Stage 1 SOURCE_ISSUES.md.',sources=['QUESTION_PATTERN_MAP.json.source_issues','scripts/build_release.py'],resolution='Lead corrected to ../stage-1/SOURCE_ISSUES.json and rebuilt. A8 independently checked target existence and exact preservation of all source-part, paper and question caveats/context.'))
  obj['fresh_stage2_facsimiles'].append('9618_w25_ms_43/p010.png')
  obj['final_review']={'catalog_metadata':'Read all 58 bilingual names, recognition text, English boundaries and skill/variant metadata. CHECK_DIGIT respects floor division; QUEUE_REDUCE core queue_accumulation permits readonly and destructive forms. Narrow canonical skills cover assessed patterns plus explicit additions; analyst details retained.', 'confusables':'Read all 20 contrasts and variant notes; 40 exact map/source citation joins checked. Four same-pattern implementation variants intentionally preserved.', 'decisions':'Read final LEAD_DECISIONS.md, three batch reviews and A3 cross-batch review. output/adapt/mixed contract explicitly documented; source-part dependencies preserved and parent expansions explained.', 'statistics':'2088 individual per-pattern metric comparisons match independent set-based computation across three views and three roles. Nine actual query-script union cases including repeated pattern input match independent ID sets/marks.', 'limitations':'Not a complete second visual read of all 672 parts; all 140 2025 rows and selected earlier ordinary/ambiguous cases were semantically read. Published code not execution-certified. This is independent QA acceptance, not the Lead stage gate or 2026 syllabus-completeness claim.'}
  text=['# A8 independent Stage 2 review','','**A8 PASS after rework.** No open required finding remains in the reviewed submission and aggregate. Lead retains authority for the final Stage 2 gate.','',obj['scope'],'','## Finding history','']
  for f in obj['findings']:text += [f"### {f['id']} — {f['status']}",'',f['issue'],'','Evidence: '+'; '.join(f['sources'])+'.','',f['resolution'],'']
  text += ['## Final independent checks','','- 672 exact unique IDs; 29 papers, 87 questions and 2,175 original marks. Every source_part is identical to Stage 1, with all paper/question context, caveats, data requirements and source joins preserved.','- Every batch classification field preserved except declared normalized skill/review fields; analyst skills retained verbatim. Canonical skills, co-tags and topic families match the declared catalog contract.','- Dependency references resolve within the same question; no cycles or self-links. The two w24/42 references to parent 1(b) expand to its scored children, retaining original parent references.','- 58 catalog entries have exact assessed-ID membership, task modes, example locators and available facsimiles. Limited-evidence flags agree with the declared threshold.','- 2,088 independent metric comparisons: 58 patterns × 3 views × primary/assessed/context × paper/question/part/marks. All agree. Primary totals are 672/2,175 raw, 487/1,575 strict text, and 536/1,725 render corroborated.','- Nine executed union-query cases across three views and three roles, including repeated pattern arguments, retain each scored ID once.','- 20 confusable pairs, 40 references, 39 distinct part IDs: exact labels and QP/MS locators verified. Four implementation-variant pairs correctly retain the same pattern ID.','']
  text += ['## Semantic review and documentation','']
  for a,b in cases:text += ['- **'+a.replace('_',' ')+':** '+b]
  for key in ['catalog_metadata','confusables','decisions']:text += ['',obj['final_review'][key]]
  text += ['','Seven additional facsimiles directly viewed during this Stage 2 review: '+', '.join('`'+v+'`' for v in obj['fresh_stage2_facsimiles'])+'. Earlier Stage 1 source reading and visuals also informed this review.','',obj['final_review']['limitations'],'','## Reproducible evidence','','- `A8_MECHANICAL_CHECKS.json`: exact source/submission IDs, citations and independently reconstructed equivalence partitions.','- `A8_INDEPENDENT_STATISTICS.json`: independent set-based counts from immutable Stage 1 marks and submitted labels.','- `A8_AGGREGATE_CHECKS.json`: aggregate/catalog/dependency/skill/confusable joins, metric comparisons, query results and reviewed input hashes.','- `A8_REVIEW.json`: finding history and final review record.','','No Stage 1 mutation, Stage 3 mapping, solution authoring or visual production was performed by this review.']
  for name in ['A8_REVIEW','A8_TAXONOMY_REVIEW']:
   (S/f'evidence/{name}.json').write_text(json.dumps(obj,ensure_ascii=False,indent=2),encoding='utf-8')
   (S/f'evidence/{name}.md').write_text('\n'.join(text)+'\n',encoding='utf-8')
print(obj['status'])
