"""Lead-authored semantic boundaries; counts/examples are joined only after mappings are reviewed."""
METADATA = '''
DATA_STORAGE|Khai báo và khởi tạo dữ liệu thông thường|Đề yêu cầu biến, mảng hoặc giá trị ban đầu theo dữ kiện; trạng thái riêng của ADT dùng dạng setup tương ứng.|storage|data_representation,state_initialisation|scope,dimensions,initial_values
DATA_RECORD|Khai báo cấu trúc bản ghi|Khai báo các trường và kiểu dữ liệu theo TYPE/record; class chỉ là phương án thay record nếu ngôn ngữ cần.|storage|data_representation,type_selection|field_types,record_or_class_substitute
ARRAY_APPEND|Thêm phần tử vào mảng còn chỗ|Kiểm sức chứa rồi ghi vào vị trí trống kế tiếp và cập nhật số lượng; chưa yêu cầu duy trì thứ tự sắp xếp.|arrays|capacity_check,index_update|capacity,count_convention,return_contract
ORDERED_INSERT|Chèn vào bảng đã có thứ tự|Đưa phần tử mới vào bảng đang có thứ tự và giữ giới hạn top-N; không tự áp đặt một thuật toán sắp xếp cụ thể nếu đề không yêu cầu.|arrays|ordered_insertion,record_movement|sort_key,direction,ties,retained_capacity
RANDOM_ARRAY|Tạo dữ liệu mảng ngẫu nhiên|Sinh đủ số phần tử trong khoảng quy định; có thể phải loại trùng hoặc khởi tạo mảng nhiều chiều.|arrays|random_generation,uniqueness_control|range_inclusive,dimensions,uniqueness
FILE_READ_ARRAY|Đọc file vào mảng, bản ghi hoặc ADT|Đọc và tách dòng, đưa dữ liệu vào cấu trúc được giao; lời gọi Push/Enqueue/AddNode có sẵn là context.|files|file_iteration,record_parsing,data_conversion|line_count,record_layout,destination,error_handling
FILE_READ_OBJECTS|Đọc file để tạo hoặc cập nhật đối tượng|Mỗi bản ghi xác định đối tượng/loại con, hoặc dùng khóa để tìm và cập nhật đối tượng hiện có.|files|record_parsing,object_construction,object_lookup|fixed_or_variable_record,subclass_dispatch,create_or_update
FILE_WRITE|Ghi hoặc nối dữ liệu vào file|Tạo các dòng đúng định dạng, dùng chế độ ghi phù hợp và xử lý lỗi khi được yêu cầu.|files|file_output,record_formatting,error_handling|append_or_write,provided_or_created_file,physical_or_logical_order
LINEAR_SEARCH|Tìm phần tử bằng duyệt tuần tự|So sánh tuần tự để tìm giá trị, vị trí hoặc tồn tại; nếu phải đếm mọi lần khớp thì dùng dạng đếm.|searching|sequential_comparison,match_detection|matching_rule,case_handling,return_contract
COUNT_OCCURRENCES|Đếm số lần thỏa điều kiện|Đếm mọi phần tử/ký tự khớp trong dữ liệu; cách lặp hay đệ quy là biến thể, không dựa vào tên hàm.|searching|predicate_evaluation,accumulation|iterative_or_recursive,predicate,data_type
FILTER_RECORDS|Lọc tất cả bản ghi thỏa điều kiện|Chọn mọi bản ghi/đối tượng đáp ứng các điều kiện kết hợp, thường có nhiều thuộc tính cần so.|searching|multi_condition_selection,attribute_access|conditions,case_handling,all_matches
GROUP_AGGREGATE|Gom khóa và cập nhật tổng theo nhóm|Tìm nhóm đã tồn tại để tăng tổng, hoặc tạo nhóm mới; không chỉ tính một tổng chung.|arrays|key_matching,group_accumulation|group_key,new_group_rule,total_fields
BUBBLE_SORT|Sắp xếp nổi bọt|Cài đặt so sánh và đổi chỗ các phần tử kề nhau; giữ đúng chiều, khóa và phạm vi của vòng lặp.|sorting|adjacent_comparison,swapping,loop_bounds|direction,dimensions,comparison_key,multiple_keys,comparator
INSERTION_SORT|Sắp xếp chèn|Lấy phần tử kế tiếp, dịch phần đã có thứ tự và chèn đúng chỗ; không nhầm với chèn một mục vào bảng top-N.|sorting|ordered_prefix,shifting,loop_bounds|iterative_or_recursive,record_key,direction
BINARY_SEARCH|Tìm nhị phân trong mảng đã sắp|Tính vị trí giữa, thu hẹp cận và trả vị trí hoặc sentinel; cần phân biệt bản lặp với bản bắt buộc đệ quy.|searching|interval_reduction,termination,comparison|iterative_or_recursive,bounds,midpoint,return_contract
STACK_SETUP|Khởi tạo stack và con trỏ|Khai báo mảng, sức chứa và vị trí top theo đúng quy ước đề cho.|stack|data_representation,state_initialisation|capacity,element_type,top_convention,initial_top
STACK_PUSH|Viết thao tác Push|Kiểm đầy, cập nhật top và lưu giá trị theo đúng thứ tự của quy ước con trỏ.|stack|capacity_check,pointer_update,state_transition|current_top_or_next_free,capacity,return_contract
STACK_POP|Viết thao tác Pop|Kiểm rỗng, lấy giá trị và cập nhật top; kiểu sentinel là một phần của giao diện hàm.|stack|empty_check,pointer_update,state_transition|top_convention,empty_return_type,update_order
STACK_PAIR|Phối hợp hai stack và hoàn trả phần tử|Lấy một cặp phần tử; nếu chỉ một bên có dữ liệu phải khôi phục phần tử chưa ghép được.|stack|transactional_state,paired_operations,restoration|empty_side,restoration_order,pair_output
STACK_REDUCE|Rút dữ liệu từ stack để tính kết quả|Dùng Pop lặp lại để tính biểu thức hoặc tìm cực trị; không chỉ gọi Pop vài lần rồi in.|stack|iterated_consumption,accumulation|arithmetic_or_extrema,operator_order,termination
QUEUE_SETUP|Khởi tạo queue và trạng thái|Khai báo mảng/record, head, tail và count nếu có; phải giữ queue vòng hay tuyến tính theo đề.|queue|data_representation,state_initialisation|linear_or_circular,head_tail_convention,count,capacity
QUEUE_ENQUEUE|Viết thao tác Enqueue|Kiểm đầy, thêm phần tử, xử lý phần tử đầu và cập nhật con trỏ/count; chỉ quay vòng khi đề yêu cầu.|queue|capacity_check,pointer_update,state_transition|linear_or_circular,next_free_or_last_item,wrap,full_condition
QUEUE_DEQUEUE|Viết thao tác Dequeue|Kiểm rỗng, lấy dữ liệu FIFO và cập nhật trạng thái; reset/wrap và việc giữ dữ liệu vật lý phụ thuộc đề.|queue|empty_check,pointer_update,state_transition|sentinel_type,reset_on_empty,wrap,physical_slot_retention
QUEUE_INSPECT|Xem các phần tử queue mà không lấy ra|Duyệt phạm vi dữ liệu đang sống và trả/in nội dung, không thay head/tail hoặc giảm count.|queue|non_destructive_traversal,live_range|live_bounds,format,pointer_convention
QUEUE_REDUCE|Xử lý hoặc cộng dồn dữ liệu queue|Đọc các phần tử của queue để tích lũy; có thể rút qua Dequeue hoặc xử lý bằng đệ quy theo đề.|queue|queue_accumulation,accumulation|destructive_or_readonly,iterative_or_recursive,sentinel
LIST_SETUP|Khởi tạo linked list và free list|Tạo head, các liên kết và vùng trống theo bảng/mô hình; có thể là mảng hoặc object references.|linked_list|data_representation,link_initialisation|array_or_objects,null_value,head,free_list
LIST_TRAVERSE|Duyệt linked list theo liên kết|Đi từ head qua next để đọc/in theo thứ tự logic, không theo chỉ số mảng vật lý.|linked_list|pointer_following,termination|head,null_sentinel,output_format
LIST_INSERT|Chèn node vào linked list|Lấy node trống hoặc tạo object, nối vào vị trí yêu cầu và cập nhật head/link/free list.|linked_list|allocation,link_update,state_transition|front_or_tail,array_or_objects,free_list,full_case
LIST_REMOVE|Xóa node khỏi linked list|Bỏ node khớp yêu cầu, cập nhật link/head và trả node về free list khi cấu trúc yêu cầu.|linked_list|link_update,case_analysis,storage_recycling|head_or_interior,presence_assumption,free_list,return_contract
TREE_SETUP|Khởi tạo cây nhị phân|Thiết lập vùng node, root và free pointer hoặc object gốc; không tự đổi root parameter thành null.|binary_tree|data_representation,root_initialisation|array_or_objects,root_parameter,empty_value,free_pointer
TREE_INSERT|Chèn node vào cây tìm kiếm nhị phân|Theo so sánh để tìm nhánh trống rồi nối node; giữ đúng quy tắc khóa bằng nhau và giới hạn sức chứa.|binary_tree|branch_comparison,link_update,allocation|array_or_objects,equal_key_rule,capacity,root_case
TREE_SEARCH|Tìm giá trị trong cây nhị phân|So giá trị tại node rồi theo con trái/phải; không dùng cận low/high của mảng.|binary_tree|branch_comparison,pointer_following,termination|recursive_or_iterative,missing_case,return_contract
TREE_TRAVERSE|Duyệt cây theo thứ tự yêu cầu|Thứ tự xử lý node và các nhánh xác định inorder/postorder; khác hoàn toàn in các dòng mảng lưu cây.|binary_tree|recursive_traversal,visit_order,null_checks|inorder_or_postorder,array_or_objects,recursion
HASH_SETUP|Khởi tạo hash table và vùng va chạm|Thiết lập bảng chính, spare hoặc bucket và bản ghi rỗng theo biểu diễn được cho.|hashing|data_representation,state_initialisation|spare_or_bucket,dimensions,empty_record
HASH_FUNCTION|Tính địa chỉ hash|Tính chỉ số từ khóa bằng công thức đề cho; chưa bao gồm xử lý va chạm.|hashing|address_calculation,modulo|modulus,key_type
HASH_INSERT|Chèn bản ghi và xử lý va chạm|Tính địa chỉ rồi dùng spare riêng hoặc ô trống trong bucket; không tự thay chiến lược va chạm.|hashing|collision_resolution,capacity_search|separate_spare_or_bucket,empty_key,capacity_assumption
HASH_SEARCH|Tra bản ghi theo hash|Tính địa chỉ và so khóa trong vùng va chạm để trả dữ liệu hoặc thông báo thiếu.|hashing|address_calculation,key_matching|collision_representation,missing_return
OOP_CLASS|Khai báo class và constructor|Tạo thuộc tính, quyền truy cập và constructor; giá trị tham số/default phải theo bảng lớp.|oop|object_modelling,constructor_initialisation|visibility,parameter_mapping,defaults,composition
OOP_SUBCLASS|Khai báo lớp con và constructor|Thể hiện kế thừa, thêm thuộc tính và gọi constructor lớp cha với đúng tham số.|oop|inheritance,parent_initialisation|parent,new_attributes,super_call
OOP_GET|Viết accessor trả dữ liệu đang lưu|Trả thuộc tính hoặc phần tử thành viên được chỉ định; tên Get không đủ nếu hàm phải tính hoặc ghép chuỗi.|oop|encapsulation,member_access|scalar_or_indexed_member,return_type
OOP_SET|Viết setter gán trực tiếp|Gán tham số vào thuộc tính/phần tử; phép tăng tương đối hoặc clamp thuộc OOP_UPDATE.|oop|encapsulation,member_assignment|scalar_or_indexed_member,parameter_order
OOP_UPDATE|Cập nhật trạng thái object theo quy tắc|Thay đổi tương đối, phần trăm, tọa độ hoặc giới hạn; phân biệt phép cộng với thay thế trực tiếp.|oop|state_transition,rule_application|add_or_scale,direction,clamp,multiple_attributes
OOP_OVERRIDE|Ghi đè hành vi kế thừa|Định nghĩa hành vi chuyên biệt cho cùng phương thức; có thể gọi lại phương thức cha.|oop|polymorphism,behaviour_specialisation|parent_call,subclass_rule,return_or_update
OOP_INSTANTIATE|Tạo và lưu các instance|Dùng class đã có với dữ liệu chỉ định hoặc đầu vào; không phải viết lại định nghĩa class.|oop|object_construction,argument_mapping|fixed_or_input_data,single_or_array,composition
OOP_CAPACITY_ADD|Thêm object vào tập hợp có giới hạn|Kiểm giới hạn của object chứa, thêm phần tử con và cập nhật count, như thêm tàu vào ga.|oop|composition,capacity_check,state_transition|capacity_attribute,count,return_contract
RULE_COMPUTE|Tính kết quả từ quy tắc hoặc bảng|Tính điểm, xác suất, tuổi, số năm hoặc kết quả điều kiện theo dữ kiện; không tự thay giả định của đề.|rules|rule_application,selection,arithmetic|table_lookup,bands,units,rounding,assumptions
VALIDATE_INPUT|Kiểm tra và yêu cầu nhập lại|Ràng buộc miền, độ dài, lựa chọn hoặc sự tồn tại; dùng vòng lặp đến khi điều kiện hợp lệ.|input|constraint_check,retry_control|range,length,choice,type,termination
UNIQUE_SELECTION|Chọn hoặc chấp nhận mỗi mục một lần|Theo dõi mục/đáp án đã dùng, từ chối lựa chọn lặp; có thể lưu vị trí hoặc đánh dấu đáp án đã tiêu thụ.|input|availability_tracking,duplicate_rejection|index_or_answer,tracking_structure,consume_marker
CHECK_DIGIT|Kiểm tra dữ liệu bằng check digit|Tính chữ số kiểm tra theo đúng công thức đề cho, kể cả chia và làm tròn xuống; không mặc định công thức modulo. So sánh rồi chấp nhận hoặc loại payload.|validation|weighted_calculation,integrity_check|weights,division_or_modulus,rounding,input_length,payload
STRING_COMPARE|So sánh chuỗi từng ký tự|Tự tìm vị trí ký tự khác đầu tiên theo giả định độ dài/prefix; không dùng hàm so sánh dựng sẵn khi bị cấm.|strings|lexicographic_comparison,index_bounds|prefix_assumption,character_order,built_in_restriction
STRING_SPLIT|Tách chuỗi thành các token|Trả các chuỗi con đã bỏ dấu phân cách; giữ quy định tự cài đặt khi đề cấm built-in. Phân phối giá trị có kiểu vào nhiều mảng thuộc STRING_ROUTE.|strings|tokenisation,delimiter_detection|delimiter,fixed_token_count,built_in_restriction
STRING_ROUTE|Phân tích bản ghi chuỗi và phân phối giá trị|Tách trường có kiểu, dùng trường phân loại để chọn mảng đích rồi lưu giá trị còn lại; không chỉ tạo danh sách token.|strings|record_parsing,data_conversion,typed_routing|field_layout,category_to_array,value_type,destinations
RUN_LENGTH_ENCODE|Mã hóa các đoạn ký tự lặp liên tiếp|Đếm từng run liên tiếp và ghép ký tự/số lượng; không gộp mọi lần xuất hiện rời nhau.|strings|run_detection,accumulation,encoding|max_run,nonempty_input,source_queue,final_run
ALGORITHM_TRANSLATE|Cài đặt thuật toán cho sẵn chưa có dạng riêng|Chuyển đúng thuật toán được mô tả bằng pseudocode; dùng khi chưa phù hợp dạng thao tác cụ thể hơn.|algorithm_forms|pseudocode_translation,control_flow|recursive_or_iterative,division,parameter_updates,side_effects
ALGORITHM_REWRITE|Chuyển đổi giữa đệ quy và vòng lặp|Giữ hành vi khi thay cấu trúc thực hiện; dạng thuật toán cụ thể vẫn được giữ làm nhãn assessed khi có.|algorithm_forms|equivalent_transformation,termination,state_preservation|direction,accumulator,output_order,parameters
MAIN_FLOW|Ghép lời gọi và điều khiển chương trình|Thực hiện trình tự gọi, truyền dữ liệu, lặp lời gọi và xử lý kết quả; thuật toán được gọi thuộc context.|workflow|call_composition,parameter_flow,result_handling|call_order,repetition,input_plumbing,result_branch
OUTPUT_FORMAT|Trình bày hoặc trả dữ liệu đúng định dạng|In mảng/lưới/bảng hoặc ghép chuỗi thông tin; không mặc nhiên là getter hay traversal logic.|output|formatting,iteration,representation|grid_or_line,physical_or_logical,concatenation,labels
EVIDENCE_RUN|Chạy test và ghi minh chứng|Dùng dữ kiện đề chỉ định và ghi đủ input/output/file vào đúng chỗ; không tính là cài thuật toán lần nữa.|evidence|test_execution,evidence_capture|prescribed_inputs,multiple_runs,file_content,filename_visibility
'''

def get_metadata():
    result={}
    for line in METADATA.splitlines():
        if not line.strip():continue
        key,name,desc,topic,skills,axes=line.split('|')
        result[key]={'name_vi':name,'recognition_vi':desc,'topic_family':topic,'skill_ids':skills.split(','),'variant_axes_to_preserve':axes.split(',')}
    return result
