from pathlib import Path
import json
stage=Path(__file__).resolve().parents[1]
seeds=[
('DATA_STORAGE','Declare or initialise general scalar/array storage','General arrays/scalars, fixed supplied data; use specific ADT setup for stack/queue/list/tree/hash.'),
('DATA_RECORD','Declare a record-like field structure','QP asks for TYPE/record fields, allowing a class as a language substitute. If QP explicitly asks for an OOP class and constructor, use OOP_CLASS regardless of visibility or class name.'),
('ARRAY_APPEND','Append a record/value to bounded array storage','Check capacity, write next slot, update count; distinct from ordered insertion and ADT enqueue.'),
('ORDERED_INSERT','Insert into an already ordered table','Shift/position a new score or record in sorted storage; not sorting the whole input.'),
('RANDOM_ARRAY','Generate random array data','Populate array with random values; uniqueness, bounds and dimensionality are variants.'),
('FILE_READ_ARRAY','Read text into arrays/records or an ADT','Read/parse lines, populate a data structure; invoked ADT operations belong to context unless implemented in this row.'),
('FILE_READ_OBJECTS','Read data and construct or update objects','Construct object records, dispatch subclasses or locate/update existing objects from file records.'),
('FILE_WRITE','Write or append data to a text file','Output file records and stated error handling; read/write modes and provided/new file differ.'),
('LINEAR_SEARCH','Find an element by sequential search','Return existence/index/match, possibly retry input; frequency uses COUNT_OCCURRENCES.'),
('COUNT_OCCURRENCES','Count matching data items','Count repeated matches, characters or values; iterative/recursive implementation is a variant.'),
('FILTER_RECORDS','Select all records/objects satisfying conditions','Multiple conditions, case rules and reporting matches; not a single-key search.'),
('GROUP_AGGREGATE','Group repeated keys and update per-key totals','Find existing group or create one and accumulate its count/value.'),
('BUBBLE_SORT','Implement bubble sorting','Sort via adjacent comparisons/swaps; direction, dimensions, key order and comparator are variants.'),
('INSERTION_SORT','Implement insertion sorting','Grow ordered prefix by extracting and shifting; recursive/iterative and record-key variants.'),
('BINARY_SEARCH','Search a sorted array by interval reduction','Iterative/recursive variants, bounds, midpoint and sentinel; tree search is TREE_SEARCH.'),
('STACK_SETUP','Declare or initialise stack state','Array capacity, values and top convention; general record declarations may be separate.'),
('STACK_PUSH','Implement push','Capacity test, pointer/index convention, write and result.'),
('STACK_POP','Implement pop','Empty case, read and pointer update; exact sentinel/type is a variant.'),
('STACK_PAIR','Coordinate two stacks with restoration','Pop paired items and restore the unmatched one when the other stack is empty.'),
('STACK_REDUCE','Consume stack values to compute a result','Repeated pop with arithmetic/min/max; not merely calling Pop twice.'),
('QUEUE_SETUP','Declare or initialise queue state','Linear/circular, array/record wrapper, head/tail/count conventions.'),
('QUEUE_ENQUEUE','Implement enqueue','Full handling and queue pointer/count updates, including wrap when specified.'),
('QUEUE_DEQUEUE','Implement dequeue','Empty handling, read and pointer/count updates, preserving stored slots when required.'),
('QUEUE_INSPECT','Read current queue contents without removing items','Follow live range for concatenation/output; not physical whole-array display or dequeue.'),
('QUEUE_REDUCE','Consume or recursively process queue data','Accumulate/process queue values; group-by and RLE also have their own assessed tags where implemented.'),
('LIST_SETUP','Initialise linked-list and free-list storage','Record/2D array or object linked representation, head/free links and null conventions.'),
('LIST_TRAVERSE','Follow linked-list links to output data','Logical list order, not physical array order.'),
('LIST_INSERT','Insert a linked-list node','Head/tail position, free-list allocation/object creation and link updates are variants.'),
('LIST_REMOVE','Remove a linked-list node','First occurrence, head/middle/tail cases, presence assumptions and free-list recycling.'),
('TREE_SETUP','Initialise binary-tree storage','Array-backed nodes/root/free pointer or object tree wrapper; OOP constructor can be co-assessed.'),
('TREE_INSERT','Insert a node in a binary search tree','Search insertion position and update links/pointers with stated equal-key/full rules.'),
('TREE_SEARCH','Search a binary search tree','Follow child pointers based on comparison; not sorted-array binary search.'),
('TREE_TRAVERSE','Traverse a tree in a specified order','Inorder/postorder and representation/recursion variants; not physical array listing.'),
('HASH_SETUP','Initialise hash-table and collision storage','Bucket or spare-array representation and empty records.'),
('HASH_FUNCTION','Compute hash address','Apply specified key-to-address formula.'),
('HASH_INSERT','Insert a record with collision handling','Separate spare array versus fixed bucket as variants.'),
('HASH_SEARCH','Retrieve a record using hash and collision storage','Compute address then check colliding records for matching key.'),
('OOP_CLASS','Declare class and constructor','Attributes, visibility, constructor parameters/defaults; OOP composition via object arrays is a variant.'),
('OOP_SUBCLASS','Declare subclass and constructor','Inheritance, inherited/new attributes and parent constructor call.'),
('OOP_GET','Implement an accessor','Return stored attribute or indexed member; computed business results are RULE_COMPUTE.'),
('OOP_SET','Implement a direct setter','Replace an attribute with parameter; arithmetic/clamping update uses OOP_UPDATE.'),
('OOP_UPDATE','Update object state according to a rule','Relative/percentage changes, movement, caps and multiple attributes.'),
('OOP_OVERRIDE','Override inherited behaviour','Specialised method behavior and optional parent method call, not merely subclass declaration.'),
('OOP_INSTANTIATE','Construct instances from supplied or input data','Create and store named objects or object arrays; class definition separately assessed.'),
('OOP_CAPACITY_ADD','Add an object to a capacity-limited aggregate','For example station platforms/train array; object-level collection and count update.'),
('RULE_COMPUTE','Compute a result from a stated rule or table','Scoring, probabilities, age, years, arithmetic or condition-based result; preserve stated assumptions.'),
('VALIDATE_INPUT','Validate and repeat user input','Range/length/choice/type/availability conditions and termination; check digit has own tag.'),
('UNIQUE_SELECTION','Accept unused items or answers without replacement','Track selected positions or mark matched answers consumed; reject repeated acceptance. Preserve position-choice versus answer-matching variants.'),
('CHECK_DIGIT','Validate data using a check-digit algorithm','Compute the source-specified weighted arithmetic and comparison, including stated division/rounding or modulus. Never assume a standard modulo formula.'),
('STRING_COMPARE','Compare strings character by character','Manual lexicographic comparison with source length/prefix assumptions.'),
('STRING_SPLIT','Split delimited text into string tokens','Return separate string tokens with delimiters removed; manual-versus-built-in restriction is a variant. Typed parsing and dispatch into destination arrays uses STRING_ROUTE.'),
('STRING_ROUTE','Parse typed string records and route values','Split compound records, interpret typed fields, select destination by a category field and store another field there; not merely tokenisation or a conditional Push of an already supplied character.'),
('RUN_LENGTH_ENCODE','Encode consecutive runs','Digit/character followed by count; max-run and nonempty assumptions are variants.'),
('ALGORITHM_TRANSLATE','Implement a supplied otherwise unnamed algorithm','Use only where no specific operation pattern fits; recursion/iteration, parameters and outputs explicit.'),
('ALGORITHM_REWRITE','Transform between recursive and iterative forms','Preserve algorithm behavior; co-tag specific algorithm when relevant.'),
('MAIN_FLOW','Compose existing calls and control program flow','Top-level or helper-function orchestration: call sequence, input-to-call plumbing, looped calls and simple result handling; invoked algorithms are context.'),
('OUTPUT_FORMAT','Output or return data in a specified format','Grid/array/object messages/concatenation without changing logical data structure.'),
('EVIDENCE_RUN','Run prescribed tests and capture evidence','Required inputs/outputs/screenshots; algorithms under test are context, not newly implemented.'),
]
result={'schema_version':'0.1','status':'LEAD_SEED_PENDING_CORPUS_REVIEW','patterns':[{'pattern_id':key,'working_title':title,'boundary':boundary} for key,title,boundary in seeds],'task_modes':['declare_initialize','implement','complete_pseudocode','translate_pseudocode','adapt','transform','integrate','test_evidence','output','mixed']}
(stage/'PATTERN_SEED.json').write_text(json.dumps(result,indent=2),encoding='utf-8')
print(len(seeds),'seed patterns')
